--Verification  
SELECT ORA_DATABASE_NAME, SYSDATE FROM DUAL;
SELECT 'LED_DEFN_TBL' AS TABLE_NAME, COUNT(1) AS ROW_COUNT FROM PS_LED_DEFN_TBL WHERE SETID = 'SHARE' AND LEDGER = 'UNU_COMMIT';
SELECT 'LED_DEFN_TBL' AS TABLE_NAME, A.* FROM PS_LED_DEFN_TBL A WHERE SETID = 'SHARE' AND LEDGER = 'UNU_COMMIT' ORDER BY 1, 2;
SELECT 'LED_GRP_LED_TBL' AS TABLE_NAME, COUNT(1) AS ROW_COUNT FROM PS_LED_GRP_LED_TBL WHERE SETID = 'SHARE' AND LEDGER_GROUP = 'UNU_COMMIT' AND LEDGER LIKE '%';
SELECT 'LED_GRP_LED_TBL' AS TABLE_NAME, A.* FROM PS_LED_GRP_LED_TBL A WHERE SETID = 'SHARE' AND LEDGER_GROUP = 'UNU_COMMIT' AND LEDGER LIKE '%' ORDER BY 1, 2;
SELECT 'LED_GRP_TBL' AS TABLE_NAME, COUNT(1) AS ROW_COUNT FROM PS_LED_GRP_TBL WHERE SETID = 'SHARE' AND LEDGER_GROUP = 'UNU_COMMIT';
SELECT 'LED_GRP_TBL' AS TABLE_NAME, A.* FROM PS_LED_GRP_TBL A WHERE SETID = 'SHARE' AND LEDGER_GROUP = 'UNU_COMMIT' ORDER BY 1, 2;
SELECT 'LED_GRP_FLD_TBL' AS TABLE_NAME, COUNT(1) AS ROW_COUNT FROM PS_LED_GRP_FLD_TBL WHERE SETID = 'SHARE' AND LEDGER_GROUP = 'UNU_COMMIT' AND FIELD_SEQUENCE LIKE '%' AND CHARTFIELD LIKE '%';
SELECT 'LED_GRP_FLD_TBL' AS TABLE_NAME, A.* FROM PS_LED_GRP_FLD_TBL A WHERE SETID = 'SHARE' AND LEDGER_GROUP = 'UNU_COMMIT' AND FIELD_SEQUENCE LIKE '%' AND CHARTFIELD LIKE '%' ORDER BY 1, 2;
--SELECT 'BUS_UNIT_TBL_GL' AS TABLE_NAME, COUNT(1) AS ROW_COUNT FROM PS_BUS_UNIT_TBL_GL WHERE BUSINESS_UNIT = 'UNUNI';
--SELECT 'BUS_UNIT_TBL_GL' AS TABLE_NAME, A.* FROM PS_BUS_UNIT_TBL_GL A WHERE BUSINESS_UNIT = 'UNUNI' ORDER BY 1, 2;
SELECT 'BU_LED_GRP_TBL' AS TABLE_NAME, COUNT(1) AS ROW_COUNT FROM PS_BU_LED_GRP_TBL WHERE BUSINESS_UNIT = 'UNUNI' AND LEDGER_GROUP = 'UNU_COMMIT' AND LEDGER LIKE '%';
SELECT 'BU_LED_GRP_TBL' AS TABLE_NAME, A.* FROM PS_BU_LED_GRP_TBL A WHERE BUSINESS_UNIT = 'UNUNI' AND LEDGER_GROUP = 'UNU_COMMIT' AND LEDGER LIKE '%' ORDER BY 1, 2;
--SELECT 'BU_LED_COMB_TBL' AS TABLE_NAME, COUNT(1) AS ROW_COUNT FROM PS_BU_LED_COMB_TBL WHERE BUSINESS_UNIT = 'UNUNI';
--SELECT 'BU_LED_COMB_TBL' AS TABLE_NAME, A.* FROM PS_BU_LED_COMB_TBL A WHERE BUSINESS_UNIT = 'UNUNI' ORDER BY 1, 2;
--SELECT 'BUL_CNTL_BUD' AS TABLE_NAME, COUNT(1) AS ROW_COUNT FROM PS_BUL_CNTL_BUD WHERE BUSINESS_UNIT = 'UNUNI' AND LEDGER_GROUP = 'UNU_COMMIT' AND KK_LEDGER_GROUP LIKE '%';
--SELECT 'BUL_CNTL_BUD' AS TABLE_NAME, A.* FROM PS_BUL_CNTL_BUD A WHERE BUSINESS_UNIT = 'UNUNI' AND LEDGER_GROUP = 'UNU_COMMIT' AND KK_LEDGER_GROUP LIKE '%' ORDER BY 1, 2;
SELECT 'LED_FLDS_TBL' AS TABLE_NAME, COUNT(1) AS ROW_COUNT FROM PS_LED_FLDS_TBL WHERE SETID = 'SHARE' AND LEDGER = 'UNU_COMMIT' AND FIELD_SEQUENCE LIKE '%';
SELECT 'LED_FLDS_TBL' AS TABLE_NAME, A.* FROM PS_LED_FLDS_TBL A WHERE SETID = 'SHARE' AND LEDGER = 'UNU_COMMIT' AND FIELD_SEQUENCE LIKE '%' ORDER BY 1, 2;



