--CR001451
--Row Level Security set up for the new UNU BU (623UU)
--Row Level Security for 623UU
INSERT INTO PS_SEC_BU_CLS
SELECT '623UU' , BUSINESS_UNIT  FROM PS_BUS_UNIT_TBL_FS
WHERE NOT EXISTS (SELECT 'X' FROM PS_SEC_BU_CLS WHERE OPRCLASS = '623UU');
--572 rows

INSERT INTO PS_SEC_BU_CLS 
SELECT DISTINCT(OPRCLASS), '623UU' FROM PS_SEC_BU_CLS WHERE OPRCLASS NOT LIKE 'EA%' 
AND OPRCLASS NOT IN (SELECT OPRCLASS FROM PS_SEC_BU_CLS WHERE BUSINESS_UNIT = '623UU');
--278 rows