
--Get all columns of a SQL Table
SELECT :1, LISTAGG(UPPER(:2 || '.' || column_name), ', ') WITHIN GROUP (ORDER BY column_id) column_list
FROM user_tab_columns
WHERE table_name = :1
GROUP BY :1
ORDER BY :1;

SELECT * FROM PSAESECTDEFN WHERE AE_APPLID = 'PC_COMPRESS';
SELECT * FROM PSAESECTDTLDEFN WHERE AE_APPLID = 'PC_COMPRESS';

--Section Details
SELECT SEC.AE_APPLID, SEC.AE_SECTION, SEC.VERSION, SEC.LASTUPDOPRID, SEC.LASTUPDDTTM, SEC.AE_SECTION_TYPE, SEC.AE_PUBLIC_SW, 
       SECDTL.MARKET, SECDTL.DBTYPE, SECDTL.EFFDT, SECDTL.EFF_STATUS, SECDTL.DESCR, SECDTL.AE_AUTO_COMMIT, SECDTL.PTAESECTIONTRACE, SECDTL.DESCRLONG
FROM PSAESECTDEFN SEC, PSAESECTDTLDEFN SECDTL
WHERE SEC.AE_APPLID = SECDTL.AE_APPLID
  AND SEC.AE_SECTION = SECDTL.AE_SECTION
  AND SEC.AE_APPLID = 'PC_COMPRESS'
  AND SECDTL.EFFDT = (SELECT MAX(SECDTL_ED.EFFDT) FROM PSAESECTDTLDEFN SECDTL_ED WHERE SECDTL.AE_APPLID = SECDTL_ED.AE_APPLID AND SECDTL.AE_SECTION = SECDTL_ED.AE_SECTION
                                                   AND SECDTL.MARKET = SECDTL_ED.MARKET AND SECDTL.DBTYPE = SECDTL_ED.DBTYPE)
ORDER BY SEC.AE_APPLID, SEC.AE_SECTION;

--Step Details
SELECT SD1.AE_SECTION, SD1.AE_STEP, SD1.DESCR, SD1.AE_DO_APPL_ID, SD1.AE_DO_SECTION, SD1.AE_ACTIVE_STATUS, SD1.AE_SEQ_NUM,
       CASE 
          WHEN SD1.AE_ABEND_ACTION = 'A' THEN 'Abort'
          WHEN SD1.AE_ABEND_ACTION = 'B' THEN 'Break'
          WHEN SD1.AE_ABEND_ACTION = 'I' THEN 'Ignore Error'
          WHEN SD1.AE_ABEND_ACTION = 'S' THEN 'Suppress Error'
       END "Abend Setting",
       CASE 
          WHEN SD1.AE_COMMIT_AFTER = 'D' THEN 'Default Action' 
          WHEN SD1.AE_COMMIT_AFTER = 'N' THEN 'Later'
          WHEN SD1.AE_COMMIT_AFTER = 'Y' THEN 'After this Step'
       END "Commit Setting", SD1.AE_ON_NOROWS, SD1.MESSAGE_SET_NBR, SD1.MESSAGE_NBR, AE_COMMIT_FREQ
FROM PSAESTEPDEFN SD1 
WHERE SD1.AE_APPLID = 'PC_COMPRESS'
  AND SD1.EFFDT = (SELECT MAX(SD2.EFFDT) FROM PSAESTEPDEFN SD2 WHERE SD1.AE_APPLID = SD2.AE_APPLID AND SD1.AE_SECTION = SD2.AE_SECTION AND SD1.MARKET = SD2.MARKET 
                                                                 AND SD1.DBTYPE = SD2.DBTYPE AND SD1.AE_STEP = SD2.AE_STEP AND SD1.AE_SEQ_NUM = SD2.AE_SEQ_NUM) 
ORDER BY SD1.AE_SEQ_NUM;

--STMT Details
SELECT AE_SECTION, AE_STEP, AE_STMT_TYPE, 
       CASE 
          WHEN AE_STMT_TYPE = 'H' THEN 'DO When'        --DO WHEN 3
          WHEN AE_STMT_TYPE = 'W' THEN 'Do While'       --DO WHILE 9
          WHEN AE_STMT_TYPE = 'D' THEN 'Do Select'      --DO SELECT  5   
          WHEN AE_STMT_TYPE = 'P' THEN 'PeopleCode'     --PEOPLECODE 12
          WHEN AE_STMT_TYPE = 'S' THEN 'SQL'            --SQL 14
          WHEN AE_STMT_TYPE = 'C' THEN 'Call'           --CALL 18
          WHEN AE_STMT_TYPE = 'M' THEN 'Log Message'    --LOG MESSAGE 17
          WHEN AE_STMT_TYPE = 'X' THEN 'XSLT'           --XSLT 0
          WHEN AE_STMT_TYPE = 'N' THEN 'Do Until'       --DO UNTIL 19
       END "Statement Type", AE_REUSE_STMT, AE_DO_SELECT_TYPE, DESCR, SQLID, MARKET, DBTYPE, EFFDT 
FROM PSAESTMTDEFN 
WHERE AE_APPLID  = 'PC_COMPRESS'
ORDER BY AE_SECTION;

SELECT MD1.AE_MESSAGE_PARMS 
FROM PSAESTEPMSGDEFN MD1
 WHERE MD1.AE_APPLID  = 'PS_COMPRESS'
--   AND MD1.AE_SECTION = ?
--   AND MD1.AE_STEP    = ?
--   AND MD1.DBTYPE     = ?
   AND MD1.EFFDT = 
      (SELECT MAX(MD2.EFFDT) FROM PSAESTEPMSGDEFN MD2
        WHERE MD2.AE_APPLID  = MD1.AE_APPLID 
          AND MD2.AE_SECTION = MD1.AE_SECTION
          AND MD2.AE_STEP    = MD1.AE_STEP   
          AND MD2.DBTYPE     = MD1.DBTYPE )  
ORDER BY 1;

----Section + Step
SELECT SEC.AE_APPLID, SEC.AE_SECTION, SECDTL.MARKET, SECDTL.DBTYPE, SECDTL.EFFDT "Section EFFDT", SECDTL.EFF_STATUS, SECDTL.DESCR "Section DESCR",
       (ROW_NUMBER () OVER (PARTITION BY SEC.AE_APPLID ORDER BY SEC.AE_APPLID)) "Section NBR",
       SD1.AE_SEQ_NUM "AE Step SEQ", SD1.AE_STEP, SD1.DESCR "Step DESCR", SD1.AE_DO_APPL_ID, SD1.AE_DO_SECTION, SD1.AE_ACTIVE_STATUS, SD1.EFFDT "Step EFFDT", SD1.AE_DYNAMIC_DO "Dynamic DO", 
       SD1.AE_PC_ON_FALSE "OnFalse PC", SD1.AE_ON_NOROWS "OnNoRows", SD1.MESSAGE_SET_NBR, SD1.MESSAGE_NBR, SD1.AE_MESSAGE_SET_FLD "MsgSet Field", 
       SD1.AE_MESSAGE_NBR_FLD "MsgNbr Field", SD1.AE_COMMIT_FREQ "Commit Freq",
       CASE 
          WHEN SD1.AE_ABEND_ACTION = 'A' THEN 'Abort'
          WHEN SD1.AE_ABEND_ACTION = 'B' THEN 'Break'
          WHEN SD1.AE_ABEND_ACTION = 'I' THEN 'Ignore Error'
          WHEN SD1.AE_ABEND_ACTION = 'S' THEN 'Suppress Error'
       END "On False Return",
       CASE 
          WHEN SD1.AE_COMMIT_AFTER = 'D' THEN 'Default Action' 
          WHEN SD1.AE_COMMIT_AFTER = 'N' THEN 'Later'
          WHEN SD1.AE_COMMIT_AFTER = 'Y' THEN 'After this Step'
       END "Commit After",
       SEC.AE_SECTION_TYPE, SEC.AE_PUBLIC_SW, SECDTL.AE_AUTO_COMMIT, SECDTL.PTAESECTIONTRACE, SEC.VERSION, SEC.LASTUPDOPRID, SEC.LASTUPDDTTM, SECDTL.DESCRLONG
FROM PSAESECTDEFN SEC, PSAESECTDTLDEFN SECDTL, PSAESTEPDEFN SD1 
WHERE SEC.AE_APPLID = SECDTL.AE_APPLID
  AND SEC.AE_SECTION = SECDTL.AE_SECTION
  AND SEC.AE_APPLID = SD1.AE_APPLID
  AND SEC.AE_SECTION = SD1.AE_SECTION
  AND SECDTL.MARKET = SD1.MARKET 
  AND SECDTL.DBTYPE = SD1.DBTYPE
  AND SEC.AE_APPLID = 'PC_COMPRESS'
  AND SECDTL.EFFDT = (SELECT MAX(SECDTL_ED.EFFDT) FROM PSAESECTDTLDEFN SECDTL_ED WHERE SECDTL.AE_APPLID = SECDTL_ED.AE_APPLID AND SECDTL.AE_SECTION = SECDTL_ED.AE_SECTION
                                                   AND SECDTL.MARKET = SECDTL_ED.MARKET AND SECDTL.DBTYPE = SECDTL_ED.DBTYPE)
  --AND SD1.AE_APPLID = 'PC_COMPRESS'
  AND SD1.EFFDT = (SELECT MAX(SD2.EFFDT) FROM PSAESTEPDEFN SD2 WHERE SD1.AE_APPLID = SD2.AE_APPLID AND SD1.AE_SECTION = SD2.AE_SECTION AND SD1.MARKET = SD2.MARKET 
                                                                 AND SD1.DBTYPE = SD2.DBTYPE AND SD1.AE_STEP = SD2.AE_STEP AND SD1.AE_SEQ_NUM = SD2.AE_SEQ_NUM) 
ORDER BY SEC.AE_APPLID, SEC.AE_SECTION, SD1.AE_SEQ_NUM;

--Version 1
SELECT SEC.AE_APPLID, 
       CASE
          WHEN SEC.AE_SECTION = 'MAIN' THEN -1
          --WHEN SEC.AE_SECTION <> 'MAIN' THEN 1
          WHEN SEC.AE_SECTION <> 'MAIN' THEN (1 + ROW_NUMBER () OVER (PARTITION BY SEC.AE_APPLID, SEC.AE_SECTION ORDER BY SEC.AE_APPLID, SEC.AE_SECTION))
       END "SECT_NBR", SEC.AE_SECTION, SECDTL.MARKET, SECDTL.DBTYPE, SECDTL.EFFDT "Section EFFDT", SECDTL.EFF_STATUS, SECDTL.DESCR "Section DESCR",
       SD1.AE_SEQ_NUM "AE Step SEQ", SD1.AE_STEP, SD1.DESCR "Step DESCR", SD1.AE_DO_APPL_ID, SD1.AE_DO_SECTION, 
       CASE 
          WHEN SD1.AE_COMMIT_AFTER = 'D' THEN 'Default Action' 
          WHEN SD1.AE_COMMIT_AFTER = 'N' THEN 'Later'
          WHEN SD1.AE_COMMIT_AFTER = 'Y' THEN 'After this Step'
       END "Commit After", SD1.AE_COMMIT_FREQ "Commit Freq",
       CASE 
          WHEN SD1.AE_ABEND_ACTION = 'A' THEN 'Abort'
          WHEN SD1.AE_ABEND_ACTION = 'B' THEN 'Break'
          WHEN SD1.AE_ABEND_ACTION = 'I' THEN 'Ignore Error'
          WHEN SD1.AE_ABEND_ACTION = 'S' THEN 'Suppress Error'
       END "On Error", SD1.AE_ACTIVE_STATUS, SD1.EFFDT "Step EFFDT", SD1.AE_DYNAMIC_DO "Dynamic DO", SD1.AE_PC_ON_FALSE "OnFalse PC", SD1.AE_ON_NOROWS "OnNoRows", 
       CASE 
          WHEN AE_STMT_TYPE = 'H' THEN 'DO When'        --DO WHEN 3
          WHEN AE_STMT_TYPE = 'W' THEN 'Do While'       --DO WHILE 9
          WHEN AE_STMT_TYPE = 'D' THEN 'Do Select'      --DO SELECT  5   
          WHEN AE_STMT_TYPE = 'P' THEN 'PeopleCode'     --PEOPLECODE 12
          WHEN AE_STMT_TYPE = 'S' THEN 'SQL'            --SQL 14
          WHEN AE_STMT_TYPE = 'C' THEN 'Call'           --CALL 18
          WHEN AE_STMT_TYPE = 'M' THEN 'Log Message'    --LOG MESSAGE 17
          WHEN AE_STMT_TYPE = 'X' THEN 'XSLT'           --XSLT 0
          WHEN AE_STMT_TYPE = 'N' THEN 'Do Until'       --DO UNTIL 19
       END "Statement Type", 
       CASE 
          WHEN AE_REUSE_STMT = 'N' THEN 'No'          --DO WHEN 3
          WHEN AE_REUSE_STMT = 'Y' THEN 'Yes'         --DO WHILE 9
          WHEN AE_REUSE_STMT = 'B' THEN 'Bulk Insert' --DO SELECT  5
       END "ReUse Statement", 
       CASE
          WHEN AE_DO_SELECT_TYPE = 'F' AND AE_STMT_TYPE = 'D' THEN 'Select/Fetch'
          WHEN AE_DO_SELECT_TYPE = 'R' THEN 'Reselect'
          WHEN AE_DO_SELECT_TYPE = 'Y' THEN 'Restartable'
       END "Do Select Type", STMT.DESCR "Action DESCR", --STMT.SQLID, SQTXT.SEQNUM, SQTXT.SQLTEXT,
       SD1.MESSAGE_SET_NBR, SD1.MESSAGE_NBR, SD1.AE_MESSAGE_SET_FLD "MsgSet Field", SD1.AE_MESSAGE_NBR_FLD "MsgNbr Field", 
       SEC.AE_SECTION_TYPE, SEC.AE_PUBLIC_SW, SECDTL.AE_AUTO_COMMIT, SECDTL.PTAESECTIONTRACE, SEC.VERSION, SEC.LASTUPDOPRID, SEC.LASTUPDDTTM, SECDTL.DESCRLONG
FROM PSAESECTDEFN SEC, PSAESECTDTLDEFN SECDTL, PSAESTEPDEFN SD1, PSAESTMTDEFN STMT
WHERE SEC.AE_APPLID = SECDTL.AE_APPLID
  AND SEC.AE_SECTION = SECDTL.AE_SECTION
  AND SEC.AE_APPLID = SD1.AE_APPLID
  AND SEC.AE_SECTION = SD1.AE_SECTION
  AND SECDTL.MARKET = SD1.MARKET 
  AND SECDTL.DBTYPE = SD1.DBTYPE
  AND SEC.AE_APPLID = STMT.AE_APPLID
  AND SEC.AE_SECTION = STMT.AE_SECTION
  AND SECDTL.MARKET = STMT.MARKET 
  AND SECDTL.DBTYPE = STMT.DBTYPE
  AND SD1.AE_STEP = STMT.AE_STEP
  AND SEC.AE_APPLID = 'PC_COMPRESS'
  AND SECDTL.EFFDT = (SELECT MAX(SECDTL_ED.EFFDT) FROM PSAESECTDTLDEFN SECDTL_ED WHERE SECDTL.AE_APPLID = SECDTL_ED.AE_APPLID AND SECDTL.AE_SECTION = SECDTL_ED.AE_SECTION
                                                                                   AND SECDTL.MARKET = SECDTL_ED.MARKET AND SECDTL.DBTYPE = SECDTL_ED.DBTYPE)
  AND SD1.EFFDT = (SELECT MAX(SD2.EFFDT) FROM PSAESTEPDEFN SD2 WHERE SD1.AE_APPLID = SD2.AE_APPLID AND SD1.AE_SECTION = SD2.AE_SECTION AND SD1.MARKET = SD2.MARKET 
                                                                 AND SD1.DBTYPE = SD2.DBTYPE AND SD1.AE_STEP = SD2.AE_STEP AND SD1.AE_SEQ_NUM = SD2.AE_SEQ_NUM)
  AND STMT.EFFDT = (SELECT MAX(STMT_ED.EFFDT) FROM PSAESTMTDEFN STMT_ED WHERE STMT.AE_APPLID = STMT_ED.AE_APPLID AND STMT.AE_SECTION = STMT_ED.AE_SECTION AND STMT.MARKET = STMT_ED.MARKET 
                                                                          AND STMT.DBTYPE = STMT_ED.DBTYPE AND STMT.AE_STEP = STMT_ED.AE_STEP AND STMT.AE_STMT_TYPE = STMT_ED.AE_STMT_TYPE)
ORDER BY SEC.AE_APPLID, SECT_NBR, SEC.AE_SECTION, SD1.AE_SEQ_NUM;

--Version 2
SELECT SEC.AE_APPLID, 
       CASE
          WHEN SEC.AE_SECTION = 'MAIN' THEN -1
          WHEN SEC.AE_SECTION <> 'MAIN' THEN 1
          --WHEN SEC.AE_SECTION <> 'MAIN' THEN (1 + ROW_NUMBER () OVER (PARTITION BY 1,2 ORDER BY 1,2))
       END "SECT_NBR", SEC.AE_SECTION, SECDTL.MARKET, SECDTL.DBTYPE, SECDTL.EFFDT "Section EFFDT", SECDTL.EFF_STATUS, SECDTL.DESCR "Section DESCR",
       SD1.AE_SEQ_NUM "AE Step SEQ", SD1.AE_STEP, SD1.DESCR "Step DESCR",  
       CASE 
          WHEN SD1.AE_COMMIT_AFTER = 'D' THEN 'Default Action' 
          WHEN SD1.AE_COMMIT_AFTER = 'N' THEN 'Later'
          WHEN SD1.AE_COMMIT_AFTER = 'Y' THEN 'After this Step'
       END "Commit After", SD1.AE_COMMIT_FREQ "Commit Freq",
       CASE 
          WHEN SD1.AE_ABEND_ACTION = 'A' THEN 'Abort'
          WHEN SD1.AE_ABEND_ACTION = 'B' THEN 'Break'
          WHEN SD1.AE_ABEND_ACTION = 'I' THEN 'Ignore Error'
          WHEN SD1.AE_ABEND_ACTION = 'S' THEN 'Suppress Error'
       END "On Error", SD1.AE_ACTIVE_STATUS, SD1.EFFDT "Step EFFDT", SD1.AE_DYNAMIC_DO "Dynamic DO", SD1.AE_PC_ON_FALSE "OnFalse PC", SD1.AE_ON_NOROWS "OnNoRows", SD1.AE_DO_APPL_ID, SD1.AE_DO_SECTION,
       CASE 
          WHEN AE_STMT_TYPE = 'H' THEN 'DO When'        --DO WHEN 3
          WHEN AE_STMT_TYPE = 'W' THEN 'Do While'       --DO WHILE 9
          WHEN AE_STMT_TYPE = 'D' THEN 'Do Select'      --DO SELECT  5   
          WHEN AE_STMT_TYPE = 'P' THEN 'PeopleCode'     --PEOPLECODE 12
          WHEN AE_STMT_TYPE = 'S' THEN 'SQL'            --SQL 14
          WHEN AE_STMT_TYPE = 'C' THEN 'Call Section'   --CALL SECTION 18
          WHEN AE_STMT_TYPE = 'M' THEN 'Log Message'    --LOG MESSAGE 17
          WHEN AE_STMT_TYPE = 'X' THEN 'XSLT'           --XSLT 0
          WHEN AE_STMT_TYPE = 'N' THEN 'Do Until'       --DO UNTIL 19
       END "AE Statement Type", 
       CASE 
          WHEN AE_REUSE_STMT = 'N' THEN 'No'          --DO WHEN 3
          WHEN AE_REUSE_STMT = 'Y' THEN 'Yes'         --DO WHILE 9
          WHEN AE_REUSE_STMT = 'B' THEN 'Bulk Insert' --DO SELECT  5
       END "ReUse Statement", 
       CASE
          WHEN AE_DO_SELECT_TYPE = 'F' AND AE_STMT_TYPE = 'D' THEN 'Select/Fetch'
          WHEN AE_DO_SELECT_TYPE = 'R' THEN 'Reselect'
          WHEN AE_DO_SELECT_TYPE = 'Y' THEN 'Restartable'
       END "Do Select Type", STMT.DESCR "Action DESCR", STMT.SQLID, SQTXT.SEQNUM, SQTXT.SQLTEXT,
       SD1.MESSAGE_SET_NBR, SD1.MESSAGE_NBR, SD1.AE_MESSAGE_SET_FLD "MsgSet Field", SD1.AE_MESSAGE_NBR_FLD "MsgNbr Field", 
       SEC.AE_SECTION_TYPE, SEC.AE_PUBLIC_SW, SECDTL.AE_AUTO_COMMIT, SECDTL.PTAESECTIONTRACE, SEC.VERSION, SEC.LASTUPDOPRID, SEC.LASTUPDDTTM, SECDTL.DESCRLONG
FROM PSAESECTDEFN SEC, PSAESECTDTLDEFN SECDTL, PSAESTEPDEFN SD1, (PSAESTMTDEFN STMT LEFT OUTER JOIN PSSQLTEXTDEFN SQTXT ON SQTXT.SQLID = STMT.SQLID AND SQTXT.MARKET = STMT.MARKET 
                                                                                                                       AND SQTXT.DBTYPE = STMT.DBTYPE)
WHERE SEC.AE_APPLID = SECDTL.AE_APPLID
  AND SEC.AE_SECTION = SECDTL.AE_SECTION
  AND SEC.AE_APPLID = SD1.AE_APPLID
  AND SEC.AE_SECTION = SD1.AE_SECTION
  AND SECDTL.MARKET = SD1.MARKET 
  AND SECDTL.DBTYPE = SD1.DBTYPE
  AND SEC.AE_APPLID = STMT.AE_APPLID
  AND SEC.AE_SECTION = STMT.AE_SECTION
  AND SECDTL.MARKET = STMT.MARKET 
  AND SECDTL.DBTYPE = STMT.DBTYPE
  AND SD1.AE_STEP = STMT.AE_STEP
  AND SEC.AE_APPLID = 'PC_COMPRESS'
  AND SECDTL.EFFDT = (SELECT MAX(SECDTL_ED.EFFDT) FROM PSAESECTDTLDEFN SECDTL_ED WHERE SECDTL.AE_APPLID = SECDTL_ED.AE_APPLID AND SECDTL.AE_SECTION = SECDTL_ED.AE_SECTION
                                                                                   AND SECDTL.MARKET = SECDTL_ED.MARKET AND SECDTL.DBTYPE = SECDTL_ED.DBTYPE)
  AND SD1.EFFDT = (SELECT MAX(SD2.EFFDT) FROM PSAESTEPDEFN SD2 WHERE SD1.AE_APPLID = SD2.AE_APPLID AND SD1.AE_SECTION = SD2.AE_SECTION AND SD1.MARKET = SD2.MARKET 
                                                                 AND SD1.DBTYPE = SD2.DBTYPE AND SD1.AE_STEP = SD2.AE_STEP AND SD1.AE_SEQ_NUM = SD2.AE_SEQ_NUM)
  AND STMT.EFFDT = (SELECT MAX(STMT_ED.EFFDT) FROM PSAESTMTDEFN STMT_ED WHERE STMT.AE_APPLID = STMT_ED.AE_APPLID AND STMT.AE_SECTION = STMT_ED.AE_SECTION AND STMT.MARKET = STMT_ED.MARKET 
                                                                          AND STMT.DBTYPE = STMT_ED.DBTYPE AND STMT.AE_STEP = STMT_ED.AE_STEP AND STMT.AE_STMT_TYPE = STMT_ED.AE_STMT_TYPE)
  AND (SQTXT.EFFDT IS NULL OR SQTXT.EFFDT = (SELECT MAX(EFFDT) FROM PSSQLTEXTDEFN SQTXT_ED WHERE SQTXT.SQLID = SQTXT_ED.SQLID AND SQTXT.SQLTYPE = SQTXT_ED.SQLTYPE 
                                                                                             AND SQTXT.MARKET = SQTXT_ED.MARKET AND SQTXT.DBTYPE = SQTXT_ED.DBTYPE 
                                                                                             AND SQTXT.SEQNUM = SQTXT_ED.SEQNUM))
ORDER BY SEC.AE_APPLID, SECT_NBR, SEC.AE_SECTION, SD1.AE_SEQ_NUM, (CASE AE_STMT_TYPE WHEN 'H' THEN 1 WHEN 'W' THEN 2 WHEN 'D' THEN 3 WHEN 'P' THEN 4 WHEN 'S' THEN 5 WHEN 'C' THEN 5 WHEN 'M' THEN 6 WHEN 'X' THEN 8 WHEN 'N' THEN 7 ELSE 9 END);

SELECT * FROM PSSQLTEXTDEFN WHERE SQLID = 'PC_COMPRESS MAIN    PROCESS D';
