--UNU AM Retirement Report
--Trimmed Version based on 9.2 SQR AMRT2100
--Version 2
--Added XLAT
--Added CoA
--Added PROFILE_ID based on HM's email - 13July2015
SELECT DISTINCT R.BUSINESS_UNIT, R.BOOK, B.FINANCIAL_ASSET_SW "Capitalized Asset", R.ASSET_ID, B.DESCR, B.PROFILE_ID,
       TO_CHAR(CAST((R.DTTM_STAMP) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') AS DTTM_STAMP, 
       TO_CHAR(R.RETIREMENT_DT, 'YYYY-MM-DD') AS RETIREMENT_DT, TO_DATE('1901-01-01','YYYY-MM-DD') AS TRANS_DT, R.ACCOUNTING_DT, R.CONVENTION, TO_CHAR(R.END_DEPR_DT, 'YYYY-MM-DD') AS END_DEPR_DT, 
       R.DISPOSAL_CODE, X1.XLATLONGNAME AS DISPOSAL_CD_DESCR, R.RETIREMENT_TYPE, X2.XLATLONGNAME AS RETIREMENT_TYPE_DESCR, R.RETIREMENT_STATUS, X3.XLATLONGNAME AS RETIREMENT_STS_DESCR,
       R.REFERENCE, R.QUANTITY, R.RETIREMENT_AMT, R.RETIREMENT_RSV, R.GAIN_LOSS, ACQ.CURRENCY_CD AS ACQ_CURR_CD, ACQ.AMOUNT AS ACQ_AMT, ACQ.TXN_CURRENCY_CD AS ACQ_TXN_CURR_CD, ACQ.TXN_AMOUNT AS ACQ_TXN_AMT,
       R.TXN_CURRENCY_CD, R.FROM_CUR, R.RETIREMENT_PCT, R.FULLY_DEPR_SW, R.IN_SERVICE_PDS,
       DECODE(C.OPERATING_UNIT, '',  ACQ.OPERATING_UNIT,  C.OPERATING_UNIT) OPERATING_UNIT,
       DECODE(C.FUND_CODE,'', ACQ.FUND_CODE, C.FUND_CODE) FUND_CODE,
       DECODE(C.DEPTID, '',  ACQ.DEPTID,  C.DEPTID) DEPTID,
       DECODE(C.CHARTFIELD2, '',  ACQ.CHARTFIELD2,  C.CHARTFIELD2) CHARTFIELD2,
       DECODE(C.PROJECT_ID, '',  ACQ.PROJECT_ID,  C.PROJECT_ID) PROJECT_ID,
       ASD.CUSTODIAN, ASD.OPERATING_UNIT AS CUST_OP_UNIT, ASD.FUND_CODE AS CUST_FUND_CODE, ASD.DEPTID AS CUST_DEPTID, ASD.CHARTFIELD2 AS CUST_DONOR, ASD.PROJECT_ID AS CUST_PROJECT_ID
FROM (((((((PS_RETIREMENT R LEFT OUTER JOIN PS_COST C ON R.BUSINESS_UNIT = C.BUSINESS_UNIT AND R.ASSET_ID = C.ASSET_ID AND R.BOOK = C.BOOK AND R.DTTM_STAMP = C.DTTM_STAMP)
      LEFT OUTER JOIN PS_ASSET_ACQ_DET ACQ ON R.BUSINESS_UNIT = ACQ.BUSINESS_UNIT AND R.ASSET_ID = ACQ.ASSET_ID)
      LEFT OUTER JOIN PS_UN_OAPR_COST_CF C ON R.BUSINESS_UNIT =  C.BUSINESS_UNIT AND R.ASSET_ID =  C.ASSET_ID)
      LEFT OUTER JOIN PS_ASSET_CUSTODIAN ASD ON R.BUSINESS_UNIT =  ASD.BUSINESS_UNIT AND R.ASSET_ID =  ASD.ASSET_ID)
      LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'DISPOSAL_CODE' AND X1.FIELDVALUE = R.DISPOSAL_CODE AND X1.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'RETIREMENT_TYPE' AND X2.FIELDVALUE = R.RETIREMENT_TYPE AND X2.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'RETIREMENT_STATUS' AND X3.FIELDVALUE = R.RETIREMENT_STATUS AND X3.EFF_STATUS = 'A'), PS_ASSET B
WHERE R.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND R.ASSET_ID = B.ASSET_ID 
  AND (ASD.EFFDT = (SELECT MAX(EFFDT) FROM PS_ASSET_CUSTODIAN A_ASD WHERE ASD.BUSINESS_UNIT = A_ASD.BUSINESS_UNIT AND ASD.ASSET_ID = A_ASD.ASSET_ID AND A_ASD.EFFDT <= SYSDATE)
    OR ASD.EFFDT IS NULL)
  AND (ASD.EFFSEQ = (SELECT MAX(ASD_ED.EFFSEQ) FROM PS_ASSET_CUSTODIAN ASD_ED WHERE ASD.BUSINESS_UNIT = ASD_ED.BUSINESS_UNIT AND ASD.ASSET_ID = ASD_ED.ASSET_ID AND ASD.EFFDT = ASD_ED.EFFDT)
    OR ASD.EFFSEQ IS NULL)
  AND R.BUSINESS_UNIT = 'UNUNI' 
  --AND C.AM_PHY_TXN_SW <> 'Y'
UNION
SELECT DISTINCT R.BUSINESS_UNIT, R.BOOK, B.FINANCIAL_ASSET_SW, R.ASSET_ID, B.DESCR, B.PROFILE_ID,
       TO_CHAR(CAST((R.DTTM_STAMP) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') AS DTTM_STAMP, TO_CHAR(R.RETIREMENT_DT, 'YYYY-MM-DD') AS RETIREMENT_DT, 
       R.TRANS_DT, TO_DATE('1901-01-01','YYYY-MM-DD') AS ACCOUNTING_DT, R.CONVENTION, TO_CHAR(R.END_DEPR_DT, 'YYYY-MM-DD') AS END_DEPR_DT, 
       R.DISPOSAL_CODE, X1.XLATLONGNAME AS DISPOSAL_CD_DESCR, R.RETIREMENT_TYPE, X2.XLATLONGNAME AS RETIREMENT_TYPE_DESCR, R.RETIREMENT_STATUS, X3.XLATLONGNAME AS RETIREMENT_STS_DESCR,
       R.REFERENCE, R.QUANTITY, R.RETIREMENT_AMT, R.RETIREMENT_RSV, R.GAIN_LOSS, ACQ.CURRENCY_CD AS ACQ_CURR_CD, ACQ.AMOUNT AS ACQ_AMT, ACQ.TXN_CURRENCY_CD AS ACQ_TXN_CURR_CD, ACQ.TXN_AMOUNT AS ACQ_TXN_AMT, 
       ' ', R.FROM_CUR, R.RETIREMENT_PCT, R.FULLY_DEPR_SW, 0.00,
       ACQ.OPERATING_UNIT, ACQ.FUND_CODE, ACQ.DEPTID, ACQ.CHARTFIELD2, ACQ.PROJECT_ID,
       ASD.CUSTODIAN, ASD.OPERATING_UNIT AS CUST_OP_UNIT, ASD.FUND_CODE AS CUST_FUND_CODE, ASD.DEPTID AS CUST_DEPTID, ASD.CHARTFIELD2 AS CUST_DONOR, ASD.PROJECT_ID AS CUST_PROJECT_ID
FROM (((((PS_RETIREMENT_NF R LEFT OUTER JOIN PS_ASSET_ACQ_DET ACQ ON R.BUSINESS_UNIT = ACQ.BUSINESS_UNIT AND R.ASSET_ID = ACQ.ASSET_ID)
      LEFT OUTER JOIN PS_ASSET_CUSTODIAN ASD ON R.BUSINESS_UNIT =  ASD.BUSINESS_UNIT AND R.ASSET_ID =  ASD.ASSET_ID)
      LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'DISPOSAL_CODE' AND X1.FIELDVALUE = R.DISPOSAL_CODE AND X1.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'RETIREMENT_TYPE' AND X2.FIELDVALUE = R.RETIREMENT_TYPE AND X2.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'RETIREMENT_STATUS' AND X3.FIELDVALUE = R.RETIREMENT_STATUS AND X3.EFF_STATUS = 'A'), PS_ASSET B
WHERE R.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND R.ASSET_ID = B.ASSET_ID
  AND (ASD.EFFDT = (SELECT MAX(EFFDT) FROM PS_ASSET_CUSTODIAN A_ASD WHERE ASD.BUSINESS_UNIT = A_ASD.BUSINESS_UNIT AND ASD.ASSET_ID = A_ASD.ASSET_ID AND A_ASD.EFFDT <= SYSDATE)
    OR ASD.EFFDT IS NULL)
  AND (ASD.EFFSEQ = (SELECT MAX(ASD_ED.EFFSEQ) FROM PS_ASSET_CUSTODIAN ASD_ED WHERE ASD.BUSINESS_UNIT = ASD_ED.BUSINESS_UNIT AND ASD.ASSET_ID = ASD_ED.ASSET_ID AND ASD.EFFDT = ASD_ED.EFFDT)
    OR ASD.EFFSEQ IS NULL)
  AND R.BUSINESS_UNIT = 'UNUNI'
ORDER BY DTTM_STAMP DESC, BUSINESS_UNIT, ASSET_ID, BOOK, RETIREMENT_DT;
