-----------------PO
--UNU_PO_SOURCING_STATUS 
SELECT A.PROCESS_INSTANCE, A.STAGE_STATUS, A.BUSINESS_UNIT, A.PO_STG_TYPE, A.PO_STG_ID, A.LINE_NBR, A.SCHED_NBR, A.BUYER_ID, A.CNTRCT_ID, 
            A.CNTRCT_LINE_NBR, A.CNTRCT_SETID, A.CURRENCY_CD, A.CURRENCY_CD_BASE, 
            TO_CHAR(CAST((A.DATETIME_MODIFIED) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF'), TO_CHAR(A.DUE_DT,'YYYY-MM-DD'), 
            A.ITM_ID_VNDR, A.ITM_SETID, A.OPRID, A.PO_ID, A.PO_LINE_NBR, A.PO_PROCESS_ID, A.VENDOR_ID, A.VENDOR_SETID, 
            A.MERCHANDISE_AMT, A.MESSAGE_SET_NBR, A.MESSAGE_NBR, B.MESSAGE_TEXT, B.DESCRLONG
FROM PS_PO_ITM_STG A, PSMSGCATDEFN B
WHERE A.BUSINESS_UNIT LIKE '6%'
    AND A.MESSAGE_SET_NBR = B.MESSAGE_SET_NBR (+)
    AND A.MESSAGE_NBR = B.MESSAGE_NBR (+)
    --AND A.STAGE_STATUS IN ('B','E','I','N','P','S','V')
    AND A.STAGE_STATUS <> 'C'
ORDER BY 1 DESC;
--X C POs needing Bud Check
SELECT 'X_C_POs_needing_Bud_Check', A.BUSINESS_UNIT, A.PO_ID, A.PO_STATUS, A.BUDGET_HDR_STATUS, TO_CHAR(PO_DT,'YYYY'), B.LINE_NBR, B.SCHED_NBR, B.DISTRIB_LINE_NUM, B.BUDGET_LINE_STATUS, 
            B.ACCOUNT, B.OPERATING_UNIT, B.DEPTID, B.FUND_CODE, B.CHARTFIELD2, B.PROJECT_ID, A.HOLD_STATUS, 
            TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD') AS ACCTG_DT, B.MERCH_AMT_BSE, B.DISTRIB_LN_STATUS, TO_CHAR(B.BUDGET_DT,'YYYY-MM-DD') AS BUDGET_DT
FROM PS_PO_HDR A, PS_PO_LINE_DISTRIB B
WHERE A.BUSINESS_UNIT LIKE '6%'     
    AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
    AND A.PO_ID = B.PO_ID
    AND A.PO_STATUS NOT IN ('I','O','PA')
    AND B.BUDGET_DT > TO_DATE('2008-12-31','YYYY-MM-DD')
    AND ( B.BUDGET_LINE_STATUS IN ('E','N') AND A.BUDGET_HDR_STATUS <> 'V')
    AND B.DISTRIB_LN_STATUS IN ('C','X')
ORDER BY 1, 2, 6, 7, 8;
--UNU PO's not fully processed
SELECT 'UNU_PO_not_fully_processed', A.BUSINESS_UNIT, A.PO_ID, A.BUYER_ID, TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD') AS ACCTG_DT, A.PO_STATUS, A.BUDGET_HDR_STATUS, 
            A.CHNG_ORD_BATCH, A.PO_REF, A.VENDOR_ID, 
            E.ACCOUNT, E.DEPTID, E.OPERATING_UNIT, E.FUND_CODE, E.BUSINESS_UNIT_PC, E.PROJECT_ID, E.ACTIVITY_ID            
FROM PS_PO_HDR A, PS_PO_LINE C, PS_PO_LINE_SHIP D, PS_PO_LINE_DISTRIB E
  WHERE A.BUSINESS_UNIT = C.BUSINESS_UNIT
      AND A.PO_ID = C.PO_ID
      AND C.BUSINESS_UNIT = D.BUSINESS_UNIT
      AND C.PO_ID = D.PO_ID
      AND C.LINE_NBR = D.LINE_NBR
      AND D.BUSINESS_UNIT = E.BUSINESS_UNIT
      AND D.PO_ID = E.PO_ID
      AND D.LINE_NBR = E.LINE_NBR
      AND D.SCHED_NBR = E.SCHED_NBR
      AND A.BUSINESS_UNIT LIKE '6%'
      AND E.BUDGET_DT BETWEEN TO_DATE('2012-01-01','YYYY-MM-DD') AND TO_DATE('2015-12-31','YYYY-MM-DD')
      AND ( A.PO_STATUS IN ('I','O','PA') OR A.BUDGET_HDR_STATUS <> 'V' OR ( A.PO_STATUS = 'A' AND NOT EXISTS (SELECT 'X' FROM PS_CNTRCT_RPO_XREF B WHERE B.BUSINESS_UNIT = A.BUSINESS_UNIT AND B.PO_ID = A.PO_ID)))
ORDER BY 1, 2;
--PO's not fully matched or closed
SELECT DISTINCT B.BUSINESS_UNIT, B.PO_ID, TO_CHAR(B.ACCOUNTING_DT,'YYYY') AS ACCTNG, TO_CHAR(B.PO_DT,'YYYY') PODATE, 
       B.VENDOR_ID, B.PO_STATUS, B.RECV_STATUS, B.MATCH_STATUS_PO
FROM PS_PO_LINE A, PS_PO_HDR B, PS_PO_LINE_DISTRIB C
WHERE A.BUSINESS_UNIT LIKE '6%'
  AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND A.PO_ID = B.PO_ID
  AND B.PO_STATUS NOT IN ('C','X')
  AND B.MATCH_STATUS_PO NOT IN ('M','N')
  AND A.CANCEL_STATUS <> 'X'
  AND A.BUSINESS_UNIT = C.BUSINESS_UNIT
  AND A.PO_ID = C.PO_ID
  AND A.LINE_NBR = C.LINE_NBR
  AND C.KK_CLOSE_FLAG = 'N'
  AND TO_CHAR(B.ACCOUNTING_DT,'YYYY') IN ('2011', '2012', '2013', '2014', '2015')
ORDER BY 1, 2;
--Open PO Lines
SELECT DISTINCT B.BUSINESS_UNIT, B.PO_ID, TO_CHAR(B.PO_DT,'YYYY-MM-DD') AS PO_DT, B.VENDOR_ID, B.PO_STATUS, B.BUDGET_HDR_STATUS, B.RECV_STATUS, 
       B.MATCH_STATUS_PO, C.LINE_NBR, C.REQ_ID, D.REQUESTOR_ID, TO_CHAR(C.BUDGET_DT,'YYYY-MM-DD') AS BD_DT, B.PO_REF, C.MERCH_AMT_BSE, 
       TO_CHAR(B.ACCOUNTING_DT,'YYYY-MM-DD') AS ACCTG_DT, B.BUYER_ID, C.DEPTID, C.KK_CLOSE_FLAG
FROM PS_PO_LINE A, PS_PO_HDR B, PS_PO_LINE_DISTRIB C, PS_REQ_HDR D
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND A.PO_ID = B.PO_ID
  AND A.BUSINESS_UNIT = C.BUSINESS_UNIT
  AND A.PO_ID = C.PO_ID
  AND A.LINE_NBR = C.LINE_NBR
  AND C.BUSINESS_UNIT = D.BUSINESS_UNIT(+)
  AND D.REQ_ID(+) = C.REQ_ID
  AND B.BUSINESS_UNIT LIKE '6%'
  AND B.PO_STATUS NOT IN ('C','X')
  AND A.CANCEL_STATUS IN ('A','H')
  AND B.ACCOUNTING_DT BETWEEN TO_DATE('2012-01-01','YYYY-MM-DD') AND TO_DATE('2015-12-31','YYYY-MM-DD')
ORDER BY 1, 2;
--Check for PO's which are Pending Cancellation
SELECT 'PX', BUSINESS_UNIT, DISP_METHOD, PO_STATUS, COUNT(1) 
FROM PS_PO_HDR 
WHERE BUSINESS_UNIT LIKE '6%' 
    AND PO_STATUS = 'PX'
GROUP BY BUSINESS_UNIT, DISP_METHOD, PO_STATUS
ORDER BY 1,2;
--UNU_PO_OPEN_LINES_CLOSED
--Open POs all lines closed
SELECT A.BUSINESS_UNIT, A.PO_ID, A.BUDGET_HDR_STATUS
FROM PS_PO_HDR A
WHERE A.BUSINESS_UNIT LIKE '6%'
     AND A.PO_STATUS = 'D'
     AND NOT EXISTS (SELECT B.PO_ID FROM PS_PO_LINE B WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT AND A.PO_ID = B.PO_ID AND B.CANCEL_STATUS = 'A')
ORDER BY 1, 2;
