--Requisitions
--Requisitions Ready for Approval
SELECT 'Ready4Approval', A.BUSINESS_UNIT, A.REQ_ID, X2.XLATLONGNAME AS REQ_STATUS, B.REQ_DT, B.REQUESTOR_ID, B.CHNG_ORD_BATCH,
       X1.XLATLONGNAME AS APPROVAL_STATUS
FROM PS_REQ_APPROVAL A, PS_REQ_HDR B, PSXLATITEM X1, PSXLATITEM X2
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT 
    AND A.REQ_ID = B.REQ_ID 
    AND A.APPROVAL_TYPE = 'AMT' 
    AND A.APPROVAL_STATUS <> 'A' 
    AND B.REQ_STATUS = 'P' 
    AND B.HOLD_STATUS = 'N'
    --XLAT X1
    AND X1.FIELDNAME = 'APPROVAL_STATUS'
    AND X1.FIELDVALUE = APPROVAL_STATUS
     --XLAT X2
    AND X2.FIELDNAME = 'REQ_STATUS'
    AND X2.FIELDVALUE = REQ_STATUS    
    AND A.BUSINESS_UNIT LIKE '6%'
    AND TO_CHAR(B.REQ_DT, 'YYYY') < 2016
ORDER BY 1,2,4;
--Requisition Approval Problem
SELECT 'APPR_PROBLEM', H.BUSINESS_UNIT, H.REQ_ID, X1.XLATLONGNAME AS REQ_STATUS, H.REQ_DT, H.REQUESTOR_ID, H.OPRID_ENTERED_BY, H.OPRID_APPROVED_BY, H.BUDGET_HDR_STATUS,
            L.LINE_NBR, L.IN_PROCESS_FLG, X2.XLATLONGNAME AS CURR_STATUS, L.CATEGORY_ID, L.MERCHANDISE_AMT,  L.SOURCE_STATUS
FROM PS_REQ_HDR H, PS_REQ_LINE L, PSXLATITEM X1, PSXLATITEM X2
WHERE H.BUSINESS_UNIT = L.BUSINESS_UNIT 
    AND H.REQ_ID = L.REQ_ID
     --XLAT X1
    AND X1.FIELDNAME = 'REQ_STATUS'
    AND X1.FIELDVALUE = H.REQ_STATUS
     --XLAT X2
    AND X2.FIELDNAME = 'CURR_STATUS'
    AND X2.FIELDVALUE = L.CURR_STATUS
    AND H.BUSINESS_UNIT LIKE '6%' 
    AND H.REQ_STATUS = 'A'
    AND L.CURR_STATUS IN ('H', 'O', 'P')
ORDER BY H.BUSINESS_UNIT, H.REQ_ID, L.LINE_NBR;
--X C Reqs needing Bud Check
SELECT '--X_C_Reqs_needing_Bud_Check', A.BUSINESS_UNIT, A.REQ_ID, A.REQ_STATUS, A.BUDGET_HDR_STATUS, TO_CHAR(REQ_DT,'YYYY'), B.LINE_NBR, B.CURR_STATUS, C.DISTRIB_LINE_NUM, C.BUDGET_LINE_STATUS, 
            C.ACCOUNT, C.OPERATING_UNIT, C.FUND_CODE, C.DEPTID, C.PROJECT_ID, C.ACTIVITY_ID, C.CHARTFIELD2, C.MERCH_AMT_BSE, A.HOLD_STATUS, TO_CHAR(C.BUDGET_DT,'YYYY-MM-DD')            
FROM PS_REQ_HDR A, PS_REQ_LINE B, PS_REQ_LN_DISTRIB C
WHERE A.BUSINESS_UNIT LIKE '6%'
    AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
    AND A.REQ_ID = B.REQ_ID
    AND B.CURR_STATUS IN ('C','X')
    AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
    AND B.REQ_ID = C.REQ_ID
    AND B.LINE_NBR = C.LINE_NBR
    AND ( C.BUDGET_LINE_STATUS IN ('E','N') AND A.BUDGET_HDR_STATUS <> 'V')
    AND A.REQ_STATUS NOT IN ('O','P','I')
    AND C.BUDGET_DT > TO_DATE('2009-12-31','YYYY-MM-DD')
ORDER BY 1, 2, 6, 8;
--UNU_REQ_OPEN_BY_BU - 2012
--List of Unsourced Requisitions
SELECT 'UNSOURCED_2012', A.BUSINESS_UNIT, A.REQ_ID, A.REQ_STATUS, A.REQ_DT, A.REQUESTOR_ID, A.BUDGET_HDR_STATUS, B.LINE_NBR, B.VENDOR_ID, B.CATEGORY_ID, C.SCHED_NBR, D.DISTRIB_LINE_NUM, 
            C.SHIPTO_ID, D.DEPTID, B.BUYER_ID, D.BUDGET_LINE_STATUS, B.DESCR254_MIXED
FROM PS_REQ_HDR A, PS_REQ_LINE B, PS_REQ_LINE_SHIP C, PS_REQ_LN_DISTRIB D
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND A.REQ_ID = B.REQ_ID
  AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
  AND B.REQ_ID = C.REQ_ID
  AND B.LINE_NBR = C.LINE_NBR
  AND C.BUSINESS_UNIT = D.BUSINESS_UNIT
  AND C.REQ_ID = D.REQ_ID
  AND C.LINE_NBR = D.LINE_NBR
  AND C.SCHED_NBR = D.SCHED_NBR
  AND A.REQ_STATUS NOT IN ('X','C')
  AND D.KK_CLOSE_FLAG = 'N'
  AND B.SOURCE_STATUS = 'A'
  AND B.CURR_STATUS NOT IN ('C','X')
  AND A.BUSINESS_UNIT LIKE '6%'  
  AND A.ACCOUNTING_DT BETWEEN TO_DATE('2012-01-01','YYYY-MM-DD') AND TO_DATE('2012-12-31','YYYY-MM-DD')
ORDER BY 1, 2, 7, 8, 9;
--UNU_REQ_OPEN_BY_BU - 2013
--List of Unsourced Requisitions
SELECT 'UNSOURCED_2013', A.BUSINESS_UNIT, A.REQ_ID, A.REQ_STATUS, A.REQ_DT, A.REQUESTOR_ID, A.BUDGET_HDR_STATUS, B.LINE_NBR, B.VENDOR_ID, B.CATEGORY_ID, C.SCHED_NBR, D.DISTRIB_LINE_NUM, 
            C.SHIPTO_ID, D.DEPTID, B.BUYER_ID, D.BUDGET_LINE_STATUS, B.DESCR254_MIXED
FROM PS_REQ_HDR A, PS_REQ_LINE B, PS_REQ_LINE_SHIP C, PS_REQ_LN_DISTRIB D
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND A.REQ_ID = B.REQ_ID
  AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
  AND B.REQ_ID = C.REQ_ID
  AND B.LINE_NBR = C.LINE_NBR
  AND C.BUSINESS_UNIT = D.BUSINESS_UNIT
  AND C.REQ_ID = D.REQ_ID
  AND C.LINE_NBR = D.LINE_NBR
  AND C.SCHED_NBR = D.SCHED_NBR
  AND A.REQ_STATUS NOT IN ('X','C')
  AND D.KK_CLOSE_FLAG = 'N'
  AND B.SOURCE_STATUS = 'A'
  AND B.CURR_STATUS NOT IN ('C','X')
  AND A.BUSINESS_UNIT LIKE '6%'  
  AND A.ACCOUNTING_DT BETWEEN TO_DATE('2013-01-01','YYYY-MM-DD') AND TO_DATE('2013-12-31','YYYY-MM-DD')
ORDER BY 1, 2, 7, 8, 9;
--UNU_REQ_OPEN_BY_BU - 2014
--List of Unsourced Requisitions
SELECT 'UNSOURCED_2014', A.BUSINESS_UNIT, A.REQ_ID, A.REQ_STATUS, A.REQ_DT, A.REQUESTOR_ID, A.BUDGET_HDR_STATUS, B.LINE_NBR, B.VENDOR_ID, B.CATEGORY_ID, C.SCHED_NBR, D.DISTRIB_LINE_NUM, 
            C.SHIPTO_ID, D.DEPTID, B.BUYER_ID, D.BUDGET_LINE_STATUS, B.DESCR254_MIXED
FROM PS_REQ_HDR A, PS_REQ_LINE B, PS_REQ_LINE_SHIP C, PS_REQ_LN_DISTRIB D
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND A.REQ_ID = B.REQ_ID
  AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
  AND B.REQ_ID = C.REQ_ID
  AND B.LINE_NBR = C.LINE_NBR
  AND C.BUSINESS_UNIT = D.BUSINESS_UNIT
  AND C.REQ_ID = D.REQ_ID
  AND C.LINE_NBR = D.LINE_NBR
  AND C.SCHED_NBR = D.SCHED_NBR
  AND A.REQ_STATUS NOT IN ('X','C')
  AND D.KK_CLOSE_FLAG = 'N'
  AND B.SOURCE_STATUS = 'A'
  AND B.CURR_STATUS NOT IN ('C','X')
  AND A.BUSINESS_UNIT LIKE '6%'  
  AND A.ACCOUNTING_DT BETWEEN TO_DATE('2014-01-01','YYYY-MM-DD') AND TO_DATE('2014-12-31','YYYY-MM-DD')
ORDER BY 1, 2, 7, 8, 9;
--UNU_REQS_NOT_APPRVD
SELECT 'REQS_NOT_APPRVD', A.BUSINESS_UNIT, A.REQ_ID, B.REQ_STATUS, A.LINE_NBR, A.VENDOR_SETID, A.VENDOR_ID, A.QTY_REQ, A.CATEGORY_ID, C.CATEGORY_CD, C.DESCR, A.PRICE_REQ, 
            A.CURRENCY_CD, A.MERCHANDISE_AMT, A.MERCH_AMT_BSE, A.AMT_ONLY_FLG,
            A.BUYER_ID, A.INV_ITEM_ID, A.SOURCE_STATUS, D.SHIPTO_ID, D.SCHED_NBR, B.REQ_DT, B.REQUESTOR_ID, B.ENTERED_DT, B.OPRID_ENTERED_BY, B.ACCOUNTING_DT,
            A.DESCR254_MIXED 
FROM PS_REQ_LINE A, PS_REQ_HDR B, PS_ITM_CAT_TBL C, PS_REQ_LINE_SHIP D, PS_SET_CNTRL_REC F
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
     AND A.REQ_ID = B.REQ_ID
     AND B.REQ_STATUS IN ('I','O','P')
     AND A.BUSINESS_UNIT LIKE '6%'
     AND F.SETCNTRLVALUE = A.BUSINESS_UNIT
     AND C.SETID = F.SETID
     AND F.RECNAME = 'ITM_CAT_TBL'
     AND C.CATEGORY_ID = A.CATEGORY_ID
     AND C.EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_ITM_CAT_TBL C_ED WHERE C.SETID = C_ED.SETID AND C.CATEGORY_TYPE = C_ED.CATEGORY_TYPE 
                                                                                                                       AND C.CATEGORY_CD = C_ED.CATEGORY_CD AND C.CATEGORY_ID = C_ED.CATEGORY_ID AND C_ED.EFFDT <= SYSDATE)
     AND A.BUSINESS_UNIT = D.BUSINESS_UNIT
     AND A.REQ_ID = D.REQ_ID
     AND A.LINE_NBR = D.LINE_NBR
ORDER BY 1, 2, 4;
--Requisition with Approval issues
SELECT * FROM PS_REQ_HDR H 
WHERE H.BUSINESS_UNIT LIKE '6%' 
    AND REQ_STATUS = 'A' 
    AND EXISTS (SELECT 'X' FROM PS_REQ_LINE L WHERE H.BUSINESS_UNIT = L.BUSINESS_UNIT AND H.REQ_ID = L.REQ_ID AND L.CURR_STATUS IN ('H', 'O', 'P') );
--Find all req lines raised after go-live that do not have an Item ID
SELECT 'NO_ITEMS', H.BUSINESS_UNIT, H.REQ_ID, L.LINE_NBR, H.REQ_STATUS, H.REQ_DT, H.REQUESTOR_ID, H.OPRID_ENTERED_BY, H.OPRID_MODIFIED_BY, H.OPRID_APPROVED_BY, H.ENTERED_DT, H.APPROVAL_DT, H.ACCOUNTING_DT, 
       H.CHNG_ORD_BATCH, L.INV_ITEM_ID, L.QTY_REQ, L.BUYER_ID, L.CATEGORY_ID, CAT.CATEGORY_CD, CAT.DESCR, CAT.EFF_STATUS, CAT.ACCOUNT,
       L.UNIT_OF_MEASURE, L.PRICE_REQ, L.SOURCE_STATUS, L.SOURCE_DATE, L.DESCR254_MIXED, L.PHYSICAL_NATURE, H.LAST_DTTM_UPDATE, L.CURR_STATUS
FROM PS_REQ_HDR H, PS_REQ_LINE L, PS_ITM_CAT_TBL CAT
WHERE H.BUSINESS_UNIT = L.BUSINESS_UNIT 
  AND H.REQ_ID = L.REQ_ID 
  AND L.INV_ITEM_ID = ' '
  AND H.BUSINESS_UNIT LIKE '6%'
  AND TO_CHAR(((H.LAST_DTTM_UPDATE ) + (0)),'YYYY-MM-DD') >= '2013-10-07'
  AND TO_CHAR(((H.LAST_DTTM_UPDATE ) + (-1)),'YYYY-MM-DD') <= TO_CHAR(SYSDATE, 'YYYY-MM-DD')
  AND CAT.SETID = 'UNUNI'
  AND CAT.CATEGORY_ID = L.CATEGORY_ID
  AND CAT.EFFDT = (SELECT MAX(CAT_ED.EFFDT) FROM PS_ITM_CAT_TBL CAT_ED WHERE CAT.SETID = CAT_ED.SETID AND CAT.CATEGORY_TYPE = CAT_ED.CATEGORY_TYPE AND CAT.CATEGORY_CD = CAT_ED.CATEGORY_CD 
                                                                         AND CAT.CATEGORY_ID = CAT_ED.CATEGORY_ID AND CAT_ED.EFFDT <= SYSDATE)
ORDER BY 1,2,3;
--Requisitions with a blank account code
SELECT * FROM PS_REQ_LN_DISTRIB 
WHERE BUSINESS_UNIT LIKE '6%'
  AND DISTRIB_LN_STATUS NOT IN ('C', 'X') 
  AND ACCOUNT = ' ' 
  AND TO_CHAR(BUDGET_DT, 'YYYY') >= '2013'
ORDER BY 1,2,3,4;
