--Review Commitment Control - PC Exceptions
SELECT A.BUSINESS_UNIT, A.PROJECT_ID, A.RESOURCE_ID, A.PC_BUDGET_ID, B.PC_BUD_TYPE, B.DESCR, B.START_DT, B.CALENDAR_ID, B.NUM_PERIODS, 
       B.PC_BUDGET_STATUS, B.ANALYSIS_TYPE, B.PC_FUND_FINALIZED, B.FINALIZE_SW, B.PROJECT_ID_TO, B.POST_OPTION, B.PC_SEND_TO_KK, B.LAST_DTTIME, 
       B.FMS_DTTM_STAMP, B.FMS_OPRID, B.FMS_LASTUPDDTTM, B.FMS_LASTUPDOPRID, B.BUDGET_ADJUST,
       A.ANALYSIS_TYPE, A.INTFC_ID, A.PROCESS_INSTANCE, A.KK_DISTRIB_STATUS, A.PC_BUDGET_ITEM, KK_BUDG_LN_TYPE, BD_HDR_STATUS, GM_DISTRIB_STATUS, LOAD_STATUS,
       A.JOURNAL_ID, ACCOUNT, A.OPERATING_UNIT, A.FUND_CODE, A.DEPTID, A.CHARTFIELD2,
       A.MESSAGE_SET_NBR, A.MESSAGE_NBR, C.MESSAGE_TEXT
FROM PS_INTFC_PROJ_RES A, PS_PC_BUD_PLAN B, PSMSGCATDEFN C
WHERE A.KK_DISTRIB_STATUS IN ('E', 'S', 'B', 'C', 'N', ' ') 
    AND A.BUSINESS_UNIT = B.BUSINESS_UNIT 
    AND A.PROJECT_ID = B.PROJECT_ID 
    AND (A.PC_BUDGET_ID = B.PC_BUDGET_ID OR A.PC_BUDGET_ID = 0)
    AND A.MESSAGE_SET_NBR = C.MESSAGE_SET_NBR (+)
    AND A.MESSAGE_NBR = C.MESSAGE_NBR (+)
    AND A.BUSINESS_UNIT = 'UNUNI'
ORDER BY B.FMS_LASTUPDDTTM DESC;
--FURTHER DRILL DOWN ON CF's for ATLAS
SELECT X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2,
       SUM(BUD) AS Budget, SUM(ACT) AS Actuals, SUM(ENC) AS Encumbered, SUM(PRE) AS PreEncumbered
FROM(
SELECT A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2,
CASE B.ANALYSIS_GROUP WHEN 'BUD' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS BUD,
CASE B.ANALYSIS_GROUP WHEN 'GMACT' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS ACT,
CASE B.ANALYSIS_GROUP WHEN 'COM' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS ENC,
CASE B.ANALYSIS_GROUP WHEN 'REQ' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS PRE
FROM PS_PROJ_RESOURCE A, PS_PROJ_AN_GRP_MAP B, PS_PROJ_AN_GRP_TBL C 
WHERE C.SETID=(SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = A.BUSINESS_UNIT AND G.RECNAME = 'PROJ_AN_GRP_TBL') 
  AND C.ANALYSIS_GROUP IN ('BUD', 'COM', 'REQ', 'GMACT')
  --AND C.ANALYSIS_GROUP IN ('BUD', 'COM', 'REQ', 'GMACT', 'UNACT')  
  AND B.SETID = C.SETID 
  AND B.ANALYSIS_GROUP = C.ANALYSIS_GROUP 
  AND B.ANALYSIS_TYPE = A.ANALYSIS_TYPE
  AND A.BUSINESS_UNIT = 'UNUNI' 
  AND A.PROJECT_ID = '00064159'
  AND A.ACCOUNTING_DT BETWEEN TO_DATE('2014-01-01','YYYY-MM-DD') AND TO_DATE('2015-12-31','YYYY-MM-DD')
GROUP BY A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2, B.ANALYSIS_GROUP
) X
GROUP BY X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2
ORDER BY 1,3;
--FURTHER DRILL DOWN ON CF's for C3
SELECT X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2,
       SUM(BUD) AS Budget, SUM(ACT) AS Actuals, SUM(ENC) AS Encumbered, SUM(PRE) AS PreEncumbered
FROM(
SELECT A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2,
CASE B.ANALYSIS_GROUP WHEN 'BUD' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS BUD,
CASE B.ANALYSIS_GROUP WHEN 'GMACT' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS ACT,
CASE B.ANALYSIS_GROUP WHEN 'COM' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS ENC,
CASE B.ANALYSIS_GROUP WHEN 'REQ' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS PRE
FROM PS_PROJ_RESOURCE A, PS_PROJ_AN_GRP_MAP B, PS_PROJ_AN_GRP_TBL C 
WHERE C.SETID=(SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = A.BUSINESS_UNIT AND G.RECNAME = 'PROJ_AN_GRP_TBL') 
  AND C.ANALYSIS_GROUP IN ('BUD', 'COM', 'REQ', 'GMACT')
  --AND C.ANALYSIS_GROUP IN ('BUD', 'COM', 'REQ', 'GMACT', 'UNACT')  
  AND B.SETID = C.SETID 
  AND B.ANALYSIS_GROUP = C.ANALYSIS_GROUP 
  AND B.ANALYSIS_TYPE = A.ANALYSIS_TYPE
  AND A.BUSINESS_UNIT = 'UNUNI' 
  AND A.PROJECT_ID = '00064153'
  AND A.ACCOUNTING_DT BETWEEN TO_DATE('2014-01-01','YYYY-MM-DD') AND TO_DATE('2015-12-31','YYYY-MM-DD')
GROUP BY A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2, B.ANALYSIS_GROUP
) X
GROUP BY X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2
ORDER BY 1,3;
--FURTHER DRILL DOWN ON CF's for ADMIN
SELECT X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2,
       SUM(BUD) AS Budget, SUM(ACT) AS Actuals, SUM(ENC) AS Encumbered, SUM(PRE) AS PreEncumbered
FROM(
SELECT A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2,
CASE B.ANALYSIS_GROUP WHEN 'BUD' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS BUD,
CASE B.ANALYSIS_GROUP WHEN 'GMACT' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS ACT,
CASE B.ANALYSIS_GROUP WHEN 'COM' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS ENC,
CASE B.ANALYSIS_GROUP WHEN 'REQ' THEN SUM(A.RESOURCE_AMOUNT) ELSE 0 END AS PRE
FROM PS_PROJ_RESOURCE A, PS_PROJ_AN_GRP_MAP B, PS_PROJ_AN_GRP_TBL C 
WHERE C.SETID=(SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = A.BUSINESS_UNIT AND G.RECNAME = 'PROJ_AN_GRP_TBL') 
  AND C.ANALYSIS_GROUP IN ('BUD', 'COM', 'REQ', 'GMACT')
  --AND C.ANALYSIS_GROUP IN ('BUD', 'COM', 'REQ', 'GMACT', 'UNACT')  
  AND B.SETID = C.SETID 
  AND B.ANALYSIS_GROUP = C.ANALYSIS_GROUP 
  AND B.ANALYSIS_TYPE = A.ANALYSIS_TYPE
  AND A.BUSINESS_UNIT = 'UNUNI' 
  AND A.PROJECT_ID = '00064158'
  AND A.ACCOUNTING_DT BETWEEN TO_DATE('2014-01-01','YYYY-MM-DD') AND TO_DATE('2015-12-31','YYYY-MM-DD')
GROUP BY A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2, B.ANALYSIS_GROUP
) X
GROUP BY X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2
ORDER BY 1,3;
