-----------------AP
--Find vouchers that need to be matched
SELECT 'VOUCHERS_TO_BE_MATCHED', A.MATCH_STATUS_VCHR, A.* FROM PS_VCHR_MM_VW A
WHERE A.BUSINESS_UNIT LIKE '6%' 
  AND A.MATCH_STATUS_VCHR <> 'M'
ORDER BY 2,3,4;
--UN_AP_PENDING_VOUCHERS     
SELECT 'VCHRS_2_B_APPROVED', A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_ID, A.INVOICE_DT, A.VENDOR_SETID, A.VENDOR_ID, B.NAME1, 
       A.OPRID, A.GROSS_AMT, A.TXN_CURRENCY_CD, A.GROSS_AMT_BSE,  A.DUE_DT
FROM (PS_VOUCHER A LEFT OUTER JOIN PS_VENDOR B ON B.SETID = A.VENDOR_SETID AND B.VENDOR_ID = A.VENDOR_ID)
WHERE A.APPR_STATUS = 'P'
    AND A.CLOSE_STATUS <> 'C'
    AND A.BUSINESS_UNIT LIKE '6%'
    AND A.ENTRY_STATUS <> 'X'
ORDER BY A.INVOICE_DT DESC, A.BUSINESS_UNIT, A.VOUCHER_ID, A.DUE_DT;
--Liability Exposure by Supplier
--In Transaction Currency ONLY
SELECT A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_DT, C.SETID, C.VENDOR_ID, C.NAME1, C.VENDOR_NAME_SHORT, A.VNDR_LOC, A.TXN_CURRENCY_CD, SUM(B.PYMNT_GROSS_AMT) AS GROSS_AMT, 0 AS PREPAID_AMT 
FROM PS_VOUCHER A, PS_PYMNT_VCHR_XREF B, PS_VENDOR C 
WHERE A.VOUCHER_STYLE NOT IN ('PPAY', 'TMPL') 
  AND (A.PROCESS_MAN_CLOSE = 'N' OR A.CLOSE_STATUS <> 'C') 
  AND A.ENTRY_STATUS <> 'X' 
  AND A.VENDOR_SETID = C.SETID 
  AND A.VENDOR_ID = C.VENDOR_ID 
  AND A.VOUCHER_ID = B.VOUCHER_ID 
  AND A.BUSINESS_UNIT = B.BUSINESS_UNIT 
  AND B.PYMNT_SELCT_STATUS NOT IN ('P', 'X', 'S') 
  AND (B.NET_SELCT_STATUS <> 'S' OR B.NET_TXN_STATUS <> 'N') 
  AND B.DUE_DT IS NOT NULL 
  AND A.BUSINESS_UNIT LIKE '6%'
  AND C.SETID = 'UNUNI'
  --AND C.VENDOR_ID = '0000005935'
GROUP BY C.SETID, C.VENDOR_ID ,C.NAME1, C.VENDOR_NAME_SHORT, A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_DT, A.VNDR_LOC, A.TXN_CURRENCY_CD 
UNION ALL 
SELECT A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_DT, C.SETID, C.VENDOR_ID, C.NAME1, C.VENDOR_NAME_SHORT, A.VNDR_LOC, A.TXN_CURRENCY_CD, 0, SUM (B.AVAILABLE_AMT) 
FROM PS_VOUCHER A, PS_VCHR_PPAY_XREF B, PS_VENDOR C, PS_PYMNT_VCHR_XREF D 
WHERE A.VOUCHER_STYLE = 'PPAY' 
  AND (A.PROCESS_MAN_CLOSE = 'N' OR A.CLOSE_STATUS <> 'C') 
  AND A.ENTRY_STATUS <> 'X' 
  AND A.VENDOR_SETID = C.SETID 
  AND A.VENDOR_ID = C.VENDOR_ID 
  AND A.VOUCHER_ID = B.VOUCHER_ID 
  AND A.BUSINESS_UNIT = B.BUSINESS_UNIT 
  AND B.PREPAID_STATUS = 'P' 
  AND A.BUSINESS_UNIT = D.BUSINESS_UNIT 
  AND A.VOUCHER_ID = D.VOUCHER_ID 
  AND D.PYMNT_TYPE = 'R' 
  AND D.PYMNT_SELCT_STATUS = 'P'
  AND A.BUSINESS_UNIT LIKE '6%'
  AND C.SETID = 'UNUNI'
  --AND C.VENDOR_ID = '0000005935'
GROUP BY C.SETID, C.VENDOR_ID , C.NAME1, C.VENDOR_NAME_SHORT, A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_DT, A.VNDR_LOC, A.TXN_CURRENCY_CD
ORDER BY 3 DESC, 1,2;
--UNU Match Exceptions Detail
--UNU_AP_DTL_MATCH_EXCEPTIONS
SELECT 'UNU_AP_DTL_MATCH_EXCEPTIONS', A.BUSINESS_UNIT, A.VOUCHER_ID, D.VOUCHER_LINE_NUM, D.INV_ITEM_ID, A.VOUCHER_STYLE, A.INVOICE_ID, TO_CHAR(A.INVOICE_DT,'YYYY-MM-DD') AS INV_DT, 
            TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD') AS ACCTG_DT, A.VENDOR_ID, C.NAME1, B.MATCH_RULE_ID, E.DESCR50, B.MTCH_EXCPTN_TYPE, 
            B.VCHR_FLDVALUE, B.PO_FLDVALUE, B.RECV_FLDVALUE, D.BUSINESS_UNIT_PO, D.PO_ID, D.LINE_NBR, D.SCHED_NBR, D.DESCR, D.DESCR254_MIXED, D.MERCHANDISE_AMT, D.TXN_CURRENCY_CD, D.MERCH_AMT_BSE,
			D.BUSINESS_UNIT_RECV, D.RECEIVER_ID, D.RECV_LN_NBR, D.RECV_SHIP_SEQ_NBR
FROM PS_VOUCHER A, PS_AP_MTCH_EXCPTN B, PS_VENDOR C, PS_VOUCHER_LINE D, PS_AP_MTCH_RULES E
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
    AND A.VOUCHER_ID = B.VOUCHER_ID
    AND A.BUSINESS_UNIT LIKE '6%'
    AND A.ENTRY_STATUS NOT IN ('X','C')
    AND A.VOUCHER_STYLE <> 'TMPL'
    AND A.MATCH_STATUS_VCHR = 'E'
    AND C.SETID = A.VENDOR_SETID
    AND C.VENDOR_ID = A.VENDOR_ID
    AND A.BUSINESS_UNIT = D.BUSINESS_UNIT
    AND A.VOUCHER_ID = D.VOUCHER_ID
    AND B.VOUCHER_LINE_NUM = D.VOUCHER_LINE_NUM
    AND B.MATCH_RULE_ID = E.MATCH_RULE_ID
ORDER BY 1, 2, 9;
--FINQA_AP_MATCH_EXCEPTIONS
SELECT A.PROCESS_INSTANCE, A.BUSINESS_UNIT, A.VOUCHER_ID, A.VOUCHER_LINE_NUM, C.BUSINESS_UNIT_PO, C.PO_ID, C.LINE_NBR, C.SCHED_NBR, C.BUSINESS_UNIT_RECV, 
       C.RECEIVER_ID, C.RECV_LN_NBR, C.RECV_SHIP_SEQ_NBR, B.MATCH_RULE_ID, A.SETID, A.MATCH_CNTRL_ID, C.BUYER_ID, B.DESCR254, C.QTY_VCHR_CNVT, 
       C.QTY_ACCEPTED_CNVT, C.PRICE_PO, C.QTY_PO, C.UNIT_PRICE_CNVT, C.ASSTN_NAME, C.ALGTHM_BEHAVIOR
FROM PS_AP_MTCH_EXCPTN A, PS_AP_MTCH_RULES B, PS_VCHR_LOG_LN_VW C
WHERE A.MATCH_RULE_ID = B.MATCH_RULE_ID
     AND A.BUSINESS_UNIT = C.BUSINESS_UNIT
     AND A.VOUCHER_ID = C.VOUCHER_ID
     AND A.VOUCHER_LINE_NUM = C.VOUCHER_LINE_NUM
     AND A.BUSINESS_UNIT LIKE '6%'
     --AND A.VOUCHER_ID LIKE :2
ORDER BY 2, 3, 4, 13;
--Match Exceptions Analysis
SELECT A.VENDOR_SETID, A.VENDOR_ID, C.VENDOR_NAME_SHORT, B.MATCH_RULE_ID, COUNT(B.MATCH_RULE_ID) AS "Total Exceptions"
FROM PS_VCHR_MTCH_DETLS A, PS_AP_MTCH_EXCPTN B, PS_VENDOR C, PS_VOUCHER D, PS_AP_MTCH_RULES E, PSMSGCATDEFN F 
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT 
  AND A.VOUCHER_ID = B.VOUCHER_ID 
  AND A.VOUCHER_LINE_NUM = B.VOUCHER_LINE_NUM 
  AND A.VENDOR_SETID = C.SETID 
  AND A.VENDOR_ID = C.VENDOR_ID 
  AND A.BUSINESS_UNIT = D.BUSINESS_UNIT 
  AND A.VOUCHER_ID = D.VOUCHER_ID 
  AND B.MATCH_RULE_ID = E.MATCH_RULE_ID 
  AND D.MATCH_STATUS_VCHR <> 'M'
  AND E.MESSAGE_SET_NBR = F.MESSAGE_SET_NBR
  AND E.MESSAGE_NBR = F.MESSAGE_NBR
  AND A.BUSINESS_UNIT LIKE '6%'
GROUP BY A.VENDOR_SETID, A.VENDOR_ID, C.VENDOR_NAME_SHORT, B.MATCH_RULE_ID
ORDER BY A.VENDOR_SETID, A.VENDOR_ID, C.VENDOR_NAME_SHORT, B.MATCH_RULE_ID;
--UNU_MATCH_OVERRIDES since 7th Oct 2013
--Added Voucher, Voucher Line, Vendor and Item tables
SELECT 'MTCH_OVRDS', A.BUSINESS_UNIT, A.VOUCHER_ID, B.VOUCHER_LINE_NUM, B.INV_ITEM_ID, NVL(M.DESCR, 'NO_ITEM') AS ITEM_DESCR, A.MATCH_STATUS_VCHR, 
       A.INVOICE_DT, A.ACCOUNTING_DT, B.QTY_VCHR, B.UNIT_OF_MEASURE, B.UNIT_PRICE, A.VENDOR_ID, D.NAME1,  
       B.BUSINESS_UNIT_PO, B.PO_ID, B.LINE_NBR, B.SCHED_NBR, B.DESCR, B.MERCHANDISE_AMT, 
       B.TXN_CURRENCY_CD, B.MERCH_AMT_BSE,
       B.BUSINESS_UNIT_RECV, B.RECEIVER_ID, B.RECV_LN_NBR, B.RECV_SHIP_SEQ_NBR,
       C.MATCH_CNTRL_ID, C.MATCH_RULE_ID, R.DESCR50,  R.MTCH_RULE_LEVEL, R.DESCR254,
       C.OPRID, NVL(TO_CHAR(C.DATETIME_STAMP, 'DD-MON-YYYY'), '01-JAN-1901') AS DATE_STAMP, C.OVRD_REASON, C.REASONDESCR
FROM  PS_VOUCHER A, PS_VOUCHER_LINE B, PS_MTCH_RULE_OVRD C, PS_VENDOR D, PS_AP_MTCH_RULES R, PS_MASTER_ITEM_TBL M
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
    AND A.VOUCHER_ID = B.VOUCHER_ID
    AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
    AND B.VOUCHER_ID = C.VOUCHER_ID
    AND B.VOUCHER_LINE_NUM = C.VOUCHER_LINE_NUM
    AND D.SETID = A.VENDOR_SETID
    AND D.VENDOR_ID = A.VENDOR_ID
    AND C.MATCH_RULE_ID = R.MATCH_RULE_ID
    AND B.ITM_SETID = M.SETID (+)
    AND B.INV_ITEM_ID = M.INV_ITEM_ID (+) 
    AND A.BUSINESS_UNIT LIKE '6%'
    AND TO_CHAR(((C.DATETIME_STAMP ) + (0)),'YYYY-MM-DD') >= '2013-10-07' 
    AND TO_CHAR(((C.DATETIME_STAMP ) + (-1)),'YYYY-MM-DD') <= TO_CHAR(SYSDATE, 'YYYY-MM-DD')
ORDER BY C.DATETIME_STAMP DESC, 2,3;
--Calculates matching exceptions
SELECT 'CALC_MTCH_EXCPTN', V.BUSINESS_UNIT, V.VOUCHER_ID, V.VOUCHER_LINE_NUM, VCHR.INVOICE_DT, VCHR.ENTERED_DT, VCHR.ACCOUNTING_DT, V.QTY_VCHR, V.ITM_SETID, V.INV_ITEM_ID, 
            V.BUSINESS_UNIT_PO, V.PO_ID, V.LINE_NBR, V.SCHED_NBR, V.BUSINESS_UNIT_RECV, V.RECEIVER_ID, V.RECV_LN_NBR, V.RECV_SHIP_SEQ_NBR,
            V.MERCHANDISE_AMT, V.MERCH_AMT_BSE,
            X.MATCH_RULE_ID, X.MTCH_EXCPTN_TYPE, X.VCHR_FLDVALUE, X.PO_FLDVALUE, X.RECV_FLDVALUE
FROM PS_VOUCHER_LINE V, PS_AP_MTCH_EXCPTN X, PS_VOUCHER VCHR
WHERE VCHR.BUSINESS_UNIT = V.BUSINESS_UNIT
    AND VCHR.VOUCHER_ID = V.VOUCHER_ID 
    AND X.BUSINESS_UNIT = V.BUSINESS_UNIT
    AND X.VOUCHER_ID = V.VOUCHER_ID
    AND X.VOUCHER_LINE_NUM = V.VOUCHER_LINE_NUM
    AND V.BUSINESS_UNIT_PO LIKE '6%'
ORDER BY 1,2,3,4;
--UNU_VOUCHERS_WITH_BUDG_ERROR     
SELECT 'UNU_VOUCHERS_WITH_BUDG_ERROR', A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_ID, A.VENDOR_ID, A.VOUCHER_STYLE, A.APPR_STATUS, A.BUDGET_HDR_STATUS, A.MATCH_STATUS_VCHR, 
       TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD') AS ACCTG_DT, TO_CHAR(A.ENTERED_DT,'YYYY-MM-DD') AS ENTERED_DT, TO_CHAR(A.LAST_UPDATE_DT,'YYYY-MM-DD') AS LAST_UPD_DT, 
       A.OPRID_LAST_UPDT, A.OPRID, B.ACCOUNT, B.OPERATING_UNIT, B.FUND_CODE, B.DEPTID, B.CHARTFIELD2, B.PROJECT_ID, B.ACTIVITY_ID, B.BUSINESS_UNIT_PO, B.PO_ID, A.TXN_CURRENCY_CD, 
       SUM(B.FOREIGN_AMOUNT), SUM(B.MONETARY_AMOUNT), D.BUYER_ID
FROM PS_VOUCHER A, PS_DISTRIB_LINE B, PS_VOUCHER_LINE C, PS_PO_HDR D
WHERE A.BUSINESS_UNIT = C.BUSINESS_UNIT
    AND A.VOUCHER_ID = C.VOUCHER_ID
    AND B.BUSINESS_UNIT_GL = 'UNUNI'
    AND A.ENTRY_STATUS <> 'X'
    AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
    AND B.VOUCHER_ID = C.VOUCHER_ID
    AND B.VOUCHER_LINE_NUM = C.VOUCHER_LINE_NUM
    AND A.BUSINESS_UNIT LIKE '6%'
    --AND A.OPRID LIKE :2
    AND A.BUDGET_HDR_STATUS = 'E'
    AND B.PO_ID =  D.PO_ID (+)
    AND B.BUSINESS_UNIT_PO =  D.BUSINESS_UNIT (+)
    --AND TO_CHAR( A.ACCOUNTING_DT,'YYYY') = :4
GROUP BY  A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_ID, A.VENDOR_ID, A.VOUCHER_STYLE, A.APPR_STATUS, A.BUDGET_HDR_STATUS, A.MATCH_STATUS_VCHR, TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD'),  
                 TO_CHAR(A.ENTERED_DT,'YYYY-MM-DD'), TO_CHAR(A.LAST_UPDATE_DT,'YYYY-MM-DD'), A.OPRID_LAST_UPDT, A.OPRID, B.ACCOUNT, B.OPERATING_UNIT, B.FUND_CODE, B.DEPTID, B.CHARTFIELD2, B.PROJECT_ID, B.ACTIVITY_ID,
                 B.BUSINESS_UNIT_PO, B.PO_ID, A.TXN_CURRENCY_CD, D.BUYER_ID
ORDER BY 1, 2, 3;
--UNU_POSTED_VCHRS_NOT_JRNL_GEN     
SELECT DISTINCT A.BUSINESS_UNIT, A.VOUCHER_ID, B.ENTRY_STATUS, B.POST_STATUS_AP, A.BUSINESS_UNIT_GL, A.JOURNAL_ID, A.BUSINESS_UNIT_PO, A.PO_ID, 
            TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD') AS ACCTG_DT, A.ACCOUNTING_PERIOD, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.PROJECT_ID, A.CHARTFIELD2, A.MERCH_AMT_BSE
FROM PS_VCHR_ACCTG_LINE A, PS_VOUCHER B
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
    AND A.VOUCHER_ID = B.VOUCHER_ID
    AND A.GL_DISTRIB_STATUS <> 'D'
    AND A.APPL_JRNL_ID = 'ACCRUAL'
    AND A.BUSINESS_UNIT LIKE '6%'
    AND A.ACCOUNT NOT LIKE '21%'
ORDER BY 1, 2, 9;
--UNU Vouchers with PAYMENT entries not DISTRIBUTED
--Header Level
SELECT DISTINCT A.BUSINESS_UNIT, A.VOUCHER_ID,
            TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD') AS A_ACCTG_DT, A.BUSINESS_UNIT_GL, A.JOURNAL_ID, A.JOURNAL_DATE,  
            TO_CHAR(B.ACCOUNTING_DT,'YYYY-MM-DD') AS B_ACCTG_DT,  B.BUSINESS_UNIT_GL, B.JOURNAL_ID, B.JOURNAL_DATE
FROM PS_VCHR_ACCTG_LINE A, PS_VCHR_ACCTG_LINE B
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
      AND A.VOUCHER_ID = B.VOUCHER_ID
      AND A.UNPOST_SEQ = B.UNPOST_SEQ
      AND A.BUSINESS_UNIT LIKE '6%'
      --AND A.VOUCHER_ID = '00018853'  
     --AND A.VOUCHER_ID = '00018783'
     AND A.APPL_JRNL_ID = 'ACCRUAL' 
     AND A.POSTING_PROCESS = 'ACCR'
     AND A.GL_DISTRIB_STATUS = 'D'
     AND B.APPL_JRNL_ID = 'PAYMENT'
     AND B.POSTING_PROCESS  = 'PYMN'
     AND B.GL_DISTRIB_STATUS <> 'D'
ORDER BY 1,2;
--UNU_VHCR_PD_NOT_BUDCHKD     
SELECT 'UNU_VHCR_PD_NOT_BUDCHKD', A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_ID, A.VENDOR_ID, TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD') AS ACCTG_DT, A.POST_STATUS_AP, 
            TO_CHAR(A.ENTERED_DT,'YYYY-MM-DD') AS ENTERED_DT, TO_CHAR(A.LAST_UPDATE_DT,'YYYY-MM-DD') AS LAST_UPD_DT, A.OPRID_LAST_UPDT, A.BUDGET_HDR_STATUS, B.PYMNT_CNT, B.PYMNT_ID, 
            TO_CHAR(B.SCHEDULED_PAY_DT,'YYYY-MM-DD') AS SCH_PAY_DT, B.POST_STATUS_AP, C.UNPOST_SEQ, C.APPL_JRNL_ID, C.POSTING_PROCESS, C.PYMNT_CNT, C.VOUCHER_LINE_NUM, 
            C.DISTRIB_LINE_NUM, C.DST_ACCT_TYPE, C.CF_BAL_LINE_NUM, C.LEDGER, C.ACCOUNT, C.DEPTID, C.OPERATING_UNIT, C.FUND_CODE, C.CHARTFIELD1, C.CHARTFIELD2, 
            C.PROJECT_ID, C.JOURNAL_ID, TO_CHAR(C.JOURNAL_DATE,'YYYY-MM-DD') AS JRNL_DT, C.BUDGET_HDR_STATUS, TO_CHAR(C.BUDGET_DT,'YYYY-MM-DD') AS BUDGET_DT, C.BUDGET_LINE_STATUS, 
            C.FOREIGN_AMOUNT, C.FOREIGN_CURRENCY, C.MONETARY_AMOUNT
FROM PS_VOUCHER A, PS_PYMNT_VCHR_XREF B, PS_VCHR_ACCTG_LINE C
WHERE A.BUSINESS_UNIT LIKE '6%'
     AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
     AND A.VOUCHER_ID = B.VOUCHER_ID
     AND B.PYMNT_SELCT_STATUS = 'P'
     AND A.BUSINESS_UNIT = C.BUSINESS_UNIT
     AND A.VOUCHER_ID = C.VOUCHER_ID
     AND C.BUDGET_LINE_STATUS NOT IN ('V', 'W')
     AND A.ACCOUNTING_DT >= TO_DATE('2012-01-01','YYYY-MM-DD')
     AND A.ACCOUNTING_DT <= TO_DATE('2015-12-31','YYYY-MM-DD')
     --AND C.OPERATING_UNIT LIKE :3
     --AND C.DEPTID LIKE :4
ORDER BY 1, 2, 3;
--VCHR_PSTBL_VW
--Added Accounting Date to keep track of Vouchers as it has been observed that 
--Vouchers have Payment entries distributed to GL before Accrual entries are created
SELECT 'VCHR_POSTABLE', A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_ID, A.ACCOUNTING_DT, A.BUSINESS_UNIT_PO AS BU_PO, A.PO_ID, B.VENDOR_NAME_SHORT, B.NAME1, 
        A.INVOICE_DT, A.TXN_CURRENCY_CD, A.GROSS_AMT, A.GROSS_AMT_BSE, A.BASE_CURRENCY, A.RATE_MULT, A.RATE_DIV, A.OPRID_LAST_UPDT
FROM PS_VOUCHER A, PS_VENDOR B, PS_BUS_UNIT_TBL_AP C 
WHERE A.VENDOR_SETID = B.SETID 
    AND A.VENDOR_ID = B.VENDOR_ID 
    AND A.BUSINESS_UNIT = C.BUSINESS_UNIT
    AND A.BUSINESS_UNIT LIKE '6%'
    AND A.ENTRY_STATUS = 'P' 
    AND A.IN_PROCESS_FLG = 'N' 
    AND A.BUDGET_HDR_STATUS = 'V' 
    AND A.BUDGET_MISC_STATUS = 'V' 
    AND A.DOC_TOL_HDR_STATUS = 'V' 
    AND (A.PROCESS_MAN_CLOSE = 'Y' OR A.POST_STATUS_AP = 'U') 
    AND A.VCHR_LINE_APPR IN ('0', '1') 
    AND A.POST_VOUCHER IN ('D', 'P') 
    AND (A.APPR_STATUS = 'A' OR (A.APPR_STATUS <> 'A' AND C.POST_UNAPPRV_FLG = 'Y')) 
    AND ((C.POST_UNMATCH_FLG = 'Y') OR (C.POST_UNMATCH_FLG = 'N' AND (A.MATCH_STATUS_VCHR = 'N' OR A.MATCH_STATUS_VCHR = 'M') ))
ORDER BY 1,2;
--VCHR_SRCH_CLOSE
SELECT 'VCHR_CLOSE', A.BUSINESS_UNIT, A.VOUCHER_ID, A.VOUCHER_STYLE, A.INVOICE_ID, A.VENDOR_SETID, B.VENDOR_NAME_SHORT, B.VENDOR_ID, B.NAME1, A.CLOSE_STATUS 
FROM PS_VOUCHER A, PS_VENDOR B 
WHERE A.VENDOR_SETID = B.SETID 
    AND A.VENDOR_ID = B.VENDOR_ID
    AND A.PROCESS_MAN_CLOSE IN ('Y','N') 
    AND A.POST_STATUS_AP = 'P' 
    AND A.IN_PROCESS_FLG = 'N'
    AND A.BUSINESS_UNIT LIKE '6%' --AND A.VOUCHER_ID = '00013943'
    AND EXISTS (SELECT 'x' FROM PS_PYMNT_VCHR_XREF C WHERE A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.VOUCHER_ID = C.VOUCHER_ID AND (( C.PYMNT_SELCT_STATUS = 'N' AND C.PYMNT_TYPE <> 'W') 
                                                                                        OR (C.PYMNT_SELCT_STATUS = 'X' AND A.VOUCHER_STYLE = 'CLBK'))) 
    AND NOT EXISTS (SELECT 'X' FROM PS_VCHR_PPAY_XREF D WHERE A.BUSINESS_UNIT = D.BUSINESS_UNIT AND A.VOUCHER_ID = D.VOUCHER_ID AND D.PREPAID_STATUS IN ('A','F')) 
    AND NOT EXISTS (SELECT 'X' FROM PS_PYMNT_VCHR_XREF G WHERE A.BUSINESS_UNIT = G.BUSINESS_UNIT AND A.VOUCHER_ID = G.VOUCHER_ID AND G.PYMNT_TYPE = 'W' 
                                                                                                    AND G.PYMNT_SELCT_STATUS <> 'X')
ORDER BY 1,2,3;
--Non UNU Paycycles which have UNU AP BUs
--Using LISTAGG
SELECT PAY_CYCLE AS "Non UNU Paycycles", 
       LISTAGG(BUSINESS_UNIT, '--') WITHIN GROUP (ORDER BY PAY_CYCLE, BUSINESS_UNIT) AS "UNU AP BUs"
FROM PS_PYCYCL_BU WHERE BUSINESS_UNIT LIKE '6%' AND PROCESS_FLG = 'Y' AND PAY_CYCLE NOT LIKE '6%'
GROUP BY PAY_CYCLE
ORDER BY 1,2;
--Monitor Paycycle Statuses for UNU
SELECT PY.PAY_CYCLE, PY.PAY_RUN_AP_STATUS, X1.XLATLONGNAME AS PAY_RUN_AP_STATUS_DESC, PY.PAY_THRU_DT, PY.PYMNT_DT, PY.OPRID, PY.PAY_RUN_DT, PY.ACCOUNTING_DT, COUNT(1)
FROM PS_PYCYCL_STAT PY, PSXLATITEM X1 
WHERE PY.PAY_CYCLE LIKE '6%' 
    AND TO_CHAR(PY.ACCOUNTING_DT, 'YYYY') IN ('2014', '2015')
    AND X1.FIELDNAME = 'PAY_RUN_AP_STATUS'
    AND X1.FIELDVALUE = PY.PAY_RUN_AP_STATUS
GROUP BY PY.PAY_CYCLE, PY.PAY_RUN_AP_STATUS, X1.XLATLONGNAME, PY.PAY_THRU_DT, PY.PYMNT_DT, PY.OPRID, PY.PAY_RUN_DT, PY.ACCOUNTING_DT
ORDER BY PY.PAY_RUN_DT DESC, PY.PAY_CYCLE;
--UNU AP Pending Payments
SELECT A.BUSINESS_UNIT, A.VOUCHER_ID, A.VOUCHER_STYLE, A.VOUCHER_ID_RELATED, A.INVOICE_ID, A.ACCOUNTING_DT, A.OPRID AS "User Id Entered By", A.APPR_STATUS, A.BUDGET_HDR_STATUS, 
       A.BUDGET_MISC_STATUS, A.MATCH_STATUS_VCHR, DECODE(A.POST_VOUCHER,'N','No','Yes') AS POST_VCHR, A.POST_STATUS_AP, A.GROSS_AMT AS "Voucher Gross Amt (Txn)", 
       A.TXN_CURRENCY_CD, A.GROSS_AMT_BSE AS "Voucher Gross Amt (Base)", A.BASE_CURRENCY, D.PYMNT_CNT, D.BANK_SETID, D.BANK_CD, D.BANK_ACCT_KEY, D.PYMNT_METHOD, 
       D.REMIT_VENDOR, B.NAME1, D.VNDR_LOC, D.BANK_ACCT_SEQ_NBR, D.REMIT_ADDR_SEQ_NUM, D.PYMNT_HOLD, D.PYMNT_HOLD_REASON, D.VNDR_PYMNT_HLD_FLG, D.PYMNT_HANDLING_CD, 
       D.PYMNT_GROSS_AMT AS "Payment Gross Amt (Txn)", D.CURRENCY_PYMNT, D.GROSS_AMT_BSE AS "Payment Gross Amt (Base)", D.BASE_CURRENCY AS "Base Currency", D.PYMNT_SEPARATE, 
       D.SCHEDULED_PAY_DT, D.PYMNT_SELCT_STATUS, D.PAY_CYCLE, D.POST_STATUS_AP AS "Payment Post Status"
FROM PS_VOUCHER A, PS_PYMNT_VCHR_XREF D, PS_VENDOR B
WHERE (A.ENTRY_STATUS <> 'X'
     AND A.CLOSE_STATUS = 'O'
     AND A.VOUCHER_STYLE NOT IN ('TMPL','JRNL')
     AND A.APPR_STATUS = 'A'
     AND A.BUDGET_HDR_STATUS = 'V'
     AND A.BUDGET_MISC_STATUS = 'V'
     AND A.MATCH_STATUS_VCHR IN ('M','N')
     AND A.BUSINESS_UNIT LIKE '6%'
     AND A.ACCOUNTING_DT >= TO_DATE('2014-01-01','YYYY-MM-DD')
     AND A.ACCOUNTING_DT <= TO_DATE('2014-12-31','YYYY-MM-DD')
     AND A.BUSINESS_UNIT = D.BUSINESS_UNIT
     AND A.VOUCHER_ID = D.VOUCHER_ID
     AND D.PYMNT_SELCT_STATUS NOT IN ('P','X','S')
     AND D.BANK_SETID = 'SHARE'
     AND D.BANK_CD LIKE '6%'
     --AND D.BANK_ACCT_KEY LIKE :6
     AND D.PYMNT_GROSS_AMT <> 0
     AND B.SETID = D.REMIT_SETID
     AND B.VENDOR_ID = D.REMIT_VENDOR
     AND D.PYMNT_ACTION NOT IN ('P'))
ORDER BY 1, 2, 18;
--Experimental Version 1
--AP_MATCH run by UNU
SELECT 'AP_MATCH_STATS', PL.PROCESS_INSTANCE, PL.MESSAGE_SEQ, PR.RUNCNTLID, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, ML.MESSAGE_SET_NBR, ML.MESSAGE_NBR, 
       CAT.MESSAGE_TEXT, LISTAGG(PL.MESSAGE_PARM, '|') WITHIN GROUP (ORDER BY PARM_SEQ) MESSAGE_PARM, PR.RUNDTTM 
FROM PS_MESSAGE_LOGPARM PL, PS_MESSAGE_LOG ML, PSPRCSRQST PR, PSMSGCATDEFN CAT
WHERE PL.PROCESS_INSTANCE = ML.PROCESS_INSTANCE
    AND PL.MESSAGE_SEQ = ML.MESSAGE_SEQ
    AND PL.PROCESS_INSTANCE = PR.PRCSINSTANCE
    AND ML.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR
    AND ML.MESSAGE_NBR = CAT.MESSAGE_NBR
    --AND PR.PRCSJOBNAME = 'PO_POREP'
    --AND PR.PRCSNAME = 'PO_PORECON'
    AND ML.MESSAGE_SET_NBR IN (7500)
    AND ML.MESSAGE_NBR IN (1, 2, 3, 8, 21, 22, 119, 128, 136, 320, 324, 333, 400, 396, 397, 398, 399, 403, 404, 405, 406, 137, 407)
    --Only for reporting exceptions
    --AND ML.MESSAGE_NBR = 406
    AND PR.OPRID = 'prakash.prashant'
    AND PR.PRCSINSTANCE >= (SELECT MIN(PR_ED.PRCSINSTANCE) FROM PSPRCSRQST PR_ED WHERE PR_ED.OPRID = 'prakash.prashant' AND PR_ED.PRCSNAME = 'AP_MATCH' 
                                                                                                                                                 AND TO_CHAR(PR_ED.RUNDTTM, 'YYYY-MM-DD') = TO_CHAR(SYSDATE, 'YYYY-MM-DD'))
    --AND PR.RUNCNTLID = 'UNU_PO_CLOSE_31DEC'
GROUP BY PL.PROCESS_INSTANCE, PL.MESSAGE_SEQ, PR.RUNCNTLID, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, ML.MESSAGE_SET_NBR, 
               ML.MESSAGE_NBR, CAT.MESSAGE_TEXT, PR.RUNDTTM;
--Payables Voucher Error Logging
--AP TSE Records
SELECT 'TSE_VCHR', A.* FROM PS_TSE_VCHR A WHERE BUSINESS_UNIT LIKE '6%' ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID;
SELECT 'TSE_VCHR_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_VCHR_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR) 
WHERE BUSINESS_UNIT LIKE '6%'
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID;
SELECT 'TSE_VCHRLN_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_VCHRLN_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR)
WHERE BUSINESS_UNIT LIKE '6%' 
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID, VOUCHER_LINE_NUM;
SELECT 'TSE_ACCTLN_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_ACCTLN_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR) 
WHERE BUSINESS_UNIT LIKE '6%' 
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID, VOUCHER_LINE_NUM;
SELECT 'TSE_PYMNT_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_PYMNT_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR)
WHERE BUSINESS_UNIT LIKE '6%' 
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID;
SELECT 'TSE_MISC_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_MISC_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR) 
WHERE BUSINESS_UNIT LIKE '6%' 
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID;
--AP_WC_PMTPST_VW
--PaymentsReadyforPosting
--As per FSCM 9.2.004/8.53.10
--Modified it for UNU
SELECT 'UNU_PYMNTS_RDY_4_POSTING', A.BANK_SETID, A.BANK_CD, A.BANK_ACCT_KEY, A.PYMNT_METHOD, A.PYMNT_ID_REF, A.REMIT_SETID, A.REMIT_VENDOR, B.VENDOR_NAME_SHORT, 
       A.NAME1, A.PYMNT_DT, A.PYMNT_AMT, A.CURRENCY_PYMNT 
FROM PS_PAYMENT_TBL A, PS_VENDOR B 
WHERE A.IN_PROCESS_FLG = 'N' 
    AND (A.POST_STATUS_AP = 'U' 
             AND (A.PYMNT_METHOD NOT IN ('BOO', 'DFT', 'BEF')
                     OR (A.PYMNT_METHOD IN ('BOO', 'DFT', 'BEF') AND A.DFT_STATUS IN ('A', 'C') AND A.DFT_APPROVE_FLAG = 'N' AND A.CREATION_DT <= SYSDATE) 
                     OR (A.PYMNT_METHOD IN ('BOO', 'DFT', 'BEF') AND A.DFT_STATUS = 'A' AND A.DFT_APPROVE_FLAG = 'Y' AND A.CREATION_DT <= SYSDATE)
                    ) 
              OR (A.POST_STATUS_AP = 'P' 
                     AND ((A.CANCEL_POST_STATUS = 'W') OR (A.DFT_STATUS = 'W' AND A.DFT_WO_DT <= SYSDATE) 
                                                                               OR (A.PYMNT_DT <= SYSDATE AND A.DFT_STATUS = 'A' AND A.CANCEL_POST_STATUS <> 'P'))
                    )
            ) 
   AND A.SOURCE_TXN = 'VCHR' 
   AND A.REMIT_SETID = B.SETID 
   AND A.REMIT_VENDOR = B.VENDOR_ID
   AND B.SETID = 'UNUNI'
   AND A.BANK_SETID = 'SHARE'
   AND A.BANK_CD LIKE '6%'
ORDER BY PYMNT_DT DESC, 1,2,3,4;
--Vouchers marked as DO NOT POST on Voucher Attributes Page
SELECT 'VCHR_DO_NOT_POST', BUSINESS_UNIT, ENTRY_STATUS, COUNT(1) 
FROM PS_VOUCHER 
WHERE BUSINESS_UNIT LIKE '6%'
    AND POST_VOUCHER = 'N' --Do Not Post
GROUP BY BUSINESS_UNIT, ENTRY_STATUS
ORDER BY BUSINESS_UNIT, ENTRY_STATUS;
--VCHR_UNBAL_VW
--Unbalanced Accounting Entries
SELECT DISTINCT A.BUSINESS_UNIT, A.VOUCHER_ID, A.INVOICE_ID, A.INVOICE_DT, A.VENDOR_SETID, B.VENDOR_NAME_SHORT, A.VENDOR_ID, B.NAME1, A.BASE_CURRENCY, C.PROCESS_INSTANCE 
FROM PS_VOUCHER A, PS_VENDOR B, PS_PST_UNBALANCED C 
WHERE A.VENDOR_SETID = B.SETID 
    AND A.VENDOR_ID = B.VENDOR_ID 
    AND A.ENTRY_STATUS IN ('P','R') 
    AND A.BUSINESS_UNIT = C.BUSINESS_UNIT 
    AND A.VOUCHER_ID = C.VOUCHER_ID
    AND A.BUSINESS_UNIT LIKE '6%'
ORDER BY 1,2;
--Pay Cycle Error Table
--Keep Tab on S06 as that is related to FG Staging
SELECT A.PAY_CYCLE, A.ERR_TYPE, X1.XLATLONGNAME AS ERR_DESCR, A.BUSINESS_UNIT, A.BANK_CD, A.PYMNT_METHOD, A.SOURCE_TXN, COUNT(1)
FROM (PS_PYCYCL_ERR_TMP A LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'ERR_TYPE' AND X1.FIELDVALUE = A.ERR_TYPE)
GROUP BY A.PAY_CYCLE, A.ERR_TYPE, X1.XLATLONGNAME, A.BUSINESS_UNIT, A.BANK_CD, A.PYMNT_METHOD, A.SOURCE_TXN
ORDER BY 1,2;
--Pay Cycles to be completed
SELECT 'PAY_CYCLE_2B_COMPLETED', A.PAY_CYCLE, A.PAY_THRU_DT, A.PYMNT_DT, A.PAY_RUN_DT, A.ACCOUNTING_DT, A.PAY_RUN_AP_STATUS, X1.XLATLONGNAME AS DESCR
FROM (PS_PYCYCL_STAT A LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'PAY_RUN_AP_STATUS' AND X1.FIELDVALUE = A.PAY_RUN_AP_STATUS)
WHERE (A.PAY_RUN_AP_STATUS NOT IN ('2','C','D','N') 
   AND A.PAY_CYCLE_SEQ_NUM = (SELECT MAX( B.PAY_CYCLE_SEQ_NUM) FROM PS_PYCYCL_STAT B WHERE B.PAY_CYCLE =  A.PAY_CYCLE))
   AND A.PAY_CYCLE LIKE '6%' 
ORDER BY A.PAY_CYCLE, A.PAY_THRU_DT, A.PYMNT_DT, A.PAY_RUN_DT, A.ACCOUNTING_DT;
--Establish direct download link for the DAT file(s)
SELECT 'https://finance.partneragencies.org/psreports/UNDPP1FS/' || A.CONTENTID || '/' || A.FILENAME AS REPORT_FILENAME_URL, A.*, PRCS.*
FROM PS_CDM_FILE_LIST A INNER JOIN PSPRCSRQST PRCS ON PRCS.PRCSINSTANCE = A.PRCSINSTANCE
WHERE PRCS.OPRID IN (SELECT DISTINCT B.OPRID FROM PSUSEREMAIL A, PSOPRDEFN B WHERE A.OPRID = B.OPRID AND A.EMAILID LIKE '%unu.edu' AND B.ACCTLOCK = 0) 
    AND PRCS.PRCSNAME = 'UN_F2025' 
    --AND TO_CHAR(PRCS.RUNDTTM, 'YYYY-MM-DD') = TO_CHAR(SYSDATE, 'YYYY-MM-DD') 
    --AND A.CDM_FILE_TYPE = 'PDF'
ORDER BY DTTM_CREATED DESC;
--Pay Cycle STATS UNU--For UNU
SELECT * FROM PS_PYCYCL_DATA WHERE REMIT_SETID = 'UNUNI' 
ORDER BY PYMNT_DT DESC, PAY_CYCLE, PAY_CYCLE_SEQ_NUM, BUSINESS_UNIT, PAY_DOC_ID;
--Find all Voucher Distrib lines which make use of an Open Item Account but do not have an EMPLID
SELECT A.ACCOUNT, A.OPEN_ITEM_KEY, A.OPEN_ITEM_STATUS, A.BUDGET_LINE_STATUS, A.* 
FROM PS_DISTRIB_LINE A, PS_GL_ACCOUNT_TBL D, PS_SET_CNTRL_REC B4
WHERE (A.BUSINESS_UNIT LIKE '6%' OR A.BUSINESS_UNIT_GL = 'UNUNI')
   AND B4.SETCNTRLVALUE = A.BUSINESS_UNIT
   AND B4.RECNAME = 'GL_ACCOUNT_TBL'
   AND B4.SETID = D.SETID
   AND A.ACCOUNT = D.ACCOUNT
   AND D.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = D.SETID AND CJ.ACCOUNT = D.ACCOUNT AND CJ.EFFDT <= SYSDATE)
   AND A.OPEN_ITEM_KEY = ' '
   AND D.OPEN_ITEM = 'Y'
ORDER BY BUSINESS_UNIT, VOUCHER_ID, VOUCHER_LINE_NUM, DISTRIB_LINE_NUM;

--New 21 Oct 2021 AE Monitoring
SELECT PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, PR.SERVERNAMERUN, PR.RUNDTTM, PR.OPRID, PR.RUNCNTLID, PR.CONTENTID,
       (SELECT RTRIM(XMLAGG(XMLELEMENT(E, PL.PROCESS_INSTANCE || ' - '|| ML.DTTM_STAMP_SEC || ' - '|| PL.MESSAGE_SEQ || ' - '|| MSG.MESSAGE_TEXT || ' - '|| PL.MESSAGE_PARM, 
                                          ' ; ' || chr(13)).EXTRACT('//text()')ORDER BY ML.DTTM_STAMP_SEC, PL.PARM_SEQ, PL.MESSAGE_SEQ).getclobval(),',') AS "A0"
        FROM ((PS_MESSAGE_LOGPARM PL LEFT OUTER JOIN PS_MESSAGE_LOG ML ON PL.PROCESS_INSTANCE = ML.PROCESS_INSTANCE AND PL.MESSAGE_SEQ = ML.MESSAGE_SEQ)
               LEFT OUTER JOIN PSMSGCATDEFN MSG ON ML.MESSAGE_SET_NBR = MSG.MESSAGE_SET_NBR AND ML.MESSAGE_NBR = MSG.MESSAGE_NBR)
        WHERE PL.PROCESS_INSTANCE = PR.PRCSINSTANCE) AS "MESSAGE_PARM"       
FROM PSPRCSRQST PR
WHERE 1 = 1
--  AND PR.PRCSNAME IN ('PMT_DISPATCH', 'PMT_DISP_BT')
  AND PR.PRCSINSTANCE = 71706726
ORDER BY PR.PRCSINSTANCE DESC;
