set pages 50000 lines 32767;
--set verify off
set trimspool on;
set trimout on;
--set termout off;
set sqlformat default;
def s = 'EMDBO.';
def x = 4;
def ProcessInstance = 160535;
def BU = 'US004';
def ProjectID = 'PP17AUG18';

--PROJ_RESOURCE BEFORE RUN
SELECT 'PS_PROJ_RESOURCE', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PROJ_RESOURCE A 
WHERE BUSINESS_UNIT = '&BU' AND PROJECT_ID = '&ProjectID' ORDER BY A.DTTM_STAMP DESC;
--Temp Table Data Export
SELECT 'PS_PC_RES_PA_TA0&x', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_RES_PA_TA0&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_RES_PA_TA1&x', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_RES_PA_TA1&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_TRAN_BAL_TAO', PROCESS_INSTANCE, DTTM_STAMP, AMOUNT_FLG, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, T.* FROM &s.PS_PC_TRAN_BAL_TAO T 
WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_ORIG_BAL_TAO', PROCESS_INSTANCE, DTTM_STAMP, AMT_ONLY_FLG, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, O.* FROM &s.PS_PC_ORIG_BAL_TAO O 
WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_RES_PA_TA3&x' PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_RES_PA_TA3&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_RES_PA_TA4&x' PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_RES_PA_TA4&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
--SEL_BAL BACK_REV -- PC_PO_PO_TAO --Q/A
SELECT 'PS_PC_PO_PO_TAO', PROCESS_INSTANCE, PR.BUSINESS_UNIT_PO, PR.PO_ID, PR.LINE_NBR, PR.SCHED_NBR, PR.DST_ACCT_TYPE, PR.DISTRIB_LINE_NUM, 
--       SUM(((PR.RESOURCE_QUANTITY) * (AGM.QUANTITY_MULTIPLY))), SUM(((PR.RESOURCE_AMOUNT) * (AGM.SIGNED_VALUE))), PR.CURRENCY_CD,
       PR.RESOURCE_QUANTITY, AGM.QUANTITY_MULTIPLY, PR.RESOURCE_AMOUNT, AGM.SIGNED_VALUE, PR.CURRENCY_CD, PR.ANALYSIS_TYPE
FROM &s.PS_PC_RES_PA_TA0&x PR , &s.PS_PROJ_AN_GRP_MAP AGM 
WHERE PR.PROCESS_INSTANCE = &ProcessInstance 
-- AND PR.ANALYSIS_TYPE IN ('COM', 'CRV', 'CCO', 'CCR')
 AND (PR.ANALYSIS_TYPE IN ('COM', 'CRV', 'CCO', 'CCR') OR PR.ANALYSIS_TYPE IN ('CCA', 'CAJ'))
 AND PR.BUSINESS_UNIT = '&BU'
 AND PR.PROJECT_ID = '&ProjectID'
 AND AGM.ANALYSIS_GROUP = 'POADJ' 
 AND PR.ANALYSIS_TYPE = AGM.ANALYSIS_TYPE 
 AND AGM.SETID = ( SELECT SETID FROM &s.PS_SET_CNTRL_REC WHERE RECNAME = 'PROJ_AN_GRP_MAP' AND SETCNTRLVALUE = PR.BUSINESS_UNIT) 
 AND BUSINESS_UNIT_PO <> ' ' AND PO_ID <> ' ' AND LINE_NBR <> 0 AND SCHED_NBR <> 0 AND DST_ACCT_TYPE <> ' ' AND DISTRIB_LINE_NUM <> 0;
--GROUP BY PR.BUSINESS_UNIT, PR.PROJECT_ID, PR.ACTIVITY_ID, PR.BUSINESS_UNIT_PO, PR.PO_ID, PR.LINE_NBR, PR.SCHED_NBR, PR.DST_ACCT_TYPE, PR.DISTRIB_LINE_NUM, PR.CURRENCY_CD 
--HAVING SUM(((PR.RESOURCE_AMOUNT) * (AGM.SIGNED_VALUE))) < 0;
--SEL_BAL ADD_REV -- PC_PO_PO_TAO --Q/A
SELECT 'PS_PC_PO_PO_TAO', PROCESS_INSTANCE, PR.BUSINESS_UNIT_PO, PR.PO_ID, PR.LINE_NBR, PR.SCHED_NBR, PR.DST_ACCT_TYPE, PR.DISTRIB_LINE_NUM, 
--       SUM(((PR.RESOURCE_QUANTITY) * (AGM.QUANTITY_MULTIPLY))), SUM(((PR.RESOURCE_AMOUNT) * (AGM.SIGNED_VALUE))), MAX(PR.CURRENCY_CD) 
       PR.RESOURCE_QUANTITY, AGM.QUANTITY_MULTIPLY, PR.RESOURCE_AMOUNT, AGM.SIGNED_VALUE, PR.CURRENCY_CD, PR.ANALYSIS_TYPE
FROM &s.PS_PC_RES_PA_TA0&x PR, &s.PS_PROJ_AN_GRP_MAP AGM 
WHERE PR.PROCESS_INSTANCE = &ProcessInstance 
 AND (PR.ANALYSIS_TYPE IN ('ACT', 'ACT', 'TLX', 'CAC', 'VIN') OR PR.ANALYSIS_TYPE IN ('CRV', 'CCR')) 
 AND PR.BUSINESS_UNIT = '&BU'
 AND PR.PROJECT_ID = '&ProjectID'
 AND AGM.ANALYSIS_GROUP = 'POADJ' 
 AND PR.ANALYSIS_TYPE = AGM.ANALYSIS_TYPE 
 AND AGM.SETID = ( SELECT SETID FROM PS_SET_CNTRL_REC WHERE RECNAME = 'PROJ_AN_GRP_MAP' AND SETCNTRLVALUE = PR.BUSINESS_UNIT) 
 AND BUSINESS_UNIT_PO <> ' ' AND PO_ID <> ' ' AND LINE_NBR <> 0 AND SCHED_NBR <> 0 AND DST_ACCT_TYPE <> ' ' AND DISTRIB_LINE_NUM <> 0;
-- AND NOT EXISTS ( SELECT 'X' FROM &s.PS_PC_PO_PO_TAO WHERE PS_PC_PO_PO_TAO.PROCESS_INSTANCE = &ProcessInstance AND PR.BUSINESS_UNIT_PO = PS_PC_PO_PO_TAO.BUSINESS_UNIT_PO 
--                                                    AND PR.PO_ID = PS_PC_PO_PO_TAO.PO_ID AND PR.LINE_NBR = PS_PC_PO_PO_TAO.LINE_NBR 
--                                                    AND PR.SCHED_NBR = PS_PC_PO_PO_TAO.SCHED_NBR AND PR.DISTRIB_LINE_NUM = PS_PC_PO_PO_TAO.DISTRIB_LINE_NUM 
--                                                    AND PR.DST_ACCT_TYPE = PS_PC_PO_PO_TAO.DST_ACCT_TYPE ) 
--GROUP BY PR.BUSINESS_UNIT_PO, PR.PO_ID, PR.LINE_NBR, PR.SCHED_NBR, PR.DST_ACCT_TYPE, PR.DISTRIB_LINE_NUM 
--HAVING SUM(((PR.RESOURCE_AMOUNT) * (AGM.SIGNED_VALUE))) <> 0;
SELECT 'PS_PC_RES_PA_TA5&x', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_RES_PA_TA5&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_RES_PA_TA6&x', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_RES_PA_TA6&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_RES_PA_TA7&x', PROCESS_INSTANCE, RESOURCE_AMOUNT2, RESOURCE_QUANTITY2, A.* FROM &s.PS_PC_RES_PA_TA7&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_RES_PA_TA8&x', PROCESS_INSTANCE, RESOURCE_AMOUNT2, RESOURCE_QUANTITY2, A.* FROM &s.PS_PC_RES_PA_TA8&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_CPY_PA_TA0&x', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_CPY_PA_TA0&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_CPY_PA_TA1&x', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_CPY_PA_TA0&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_PA_DTL_TAO&x', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_PA_DTL_TAO&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
SELECT 'PS_PC_PA_RES_TMP&x', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PC_PA_RES_TMP&x A WHERE PROCESS_INSTANCE = &ProcessInstance;
--PROJ_RESOURCE AFTER RUN
SELECT 'PS_PROJ_RESOURCE', PROCESS_INSTANCE, DTTM_STAMP, ANALYSIS_TYPE, RESOURCE_AMOUNT, RESOURCE_QUANTITY, A.* FROM &s.PS_PROJ_RESOURCE A 
WHERE BUSINESS_UNIT = '&BU' AND PROJECT_ID = '&ProjectID' ORDER BY A.DTTM_STAMP DESC;
