--Version 2
--Added PAYMENT_TBL, PYMNT_VCHR_XREF, PYMNT_ADVICE Tables
SELECT PD.PMT_ID, PD.PMT_SOURCE, PD.BUSINESS_UNIT, PD.SRC_REF_ID, PD.AMOUNT, PD.AMOUNT_CURRENCY_CD, PD.PYMNT_DT, PD.VALUE_DT, PD.ESTIMATED_DUE_DATE, PD.PMT_STATUS, X1.XLATLONGNAME AS PMT_STS_DESCR, 
       PD.PMT_LAST_STATUS, X2.XLATLONGNAME AS PMT_LAST_STS_DESCR, PD.PMT_TYPE, X9.XLATLONGNAME AS PMT_TYPE_DESCR, PD.BANK_SETID, 
       PD.BANK_CD, PD.BANK_ACCT_KEY, PD.ACCT_BUS_UNIT_GL, PD.FROM_BNK_ID_NBR, PD.FROM_BNK_ACCT_NUM, PD.FROM_DFI_ID_NUM, PD.FROM_DFI_ID_QUAL, PD.PYMNT_METHOD, PD.FORMAT_ID, PD.PRENOTE_FLAG, X4.XLATLONGNAME AS PRE_NOTE_DESCR,
       PD.PAY_IMMEDIATELY, PD.COUNTRY, PD.BANK_ID_QUAL, PD.BNK_ID_NBR, PD.BRANCH_ID, PD.BANK_ACCT_TYPE, X5.XLATLONGNAME AS BANK_ACCT_TYPE_DECSR, 
       PD.BANK_ACCOUNT_NUM, PD.CHECK_DIGIT, PD.DFI_ID_QUAL, X3.XLATLONGNAME AS DFI_ID_QUAL_DESCR, PD.DFI_ID_NUM, 
       PD.BANK_NAME, PD.BANK_NAME_AC, PD.BRANCH_DESCR, PD.BRANCH_NAME_AC, PD.IBAN_CHECK_DIGIT, PD.IBAN_ID, PD.PARTY_ID_TYPE, PD.PARTY_SETID, PD.PARTY_ID, PD.NAME1, PD.NAME1_AC, PD.NAME2, 
       PD.STD_ID_NUM, PD.STD_ID_NUM_QUAL, PD.EFT_PYMNT_FMT_CD, X6.XLATLONGNAME AS EFT_PMT_FMT_CD_DESCR, PD.EFT_RTNG_FLG, PD.EFT_RTNG_STATUS, 
       PD.EFT_TRANS_HANDLING, X7.XLATLONGNAME AS EFT_TRANS_HANDLING_DESCR, PD.EFT_DOM_COSTS_CD, X8.XLATLONGNAME AS EFT_DOMESTIC_COSTS, 
       PD.EFT_CORR_COSTS_CD, X13.XLATLONGNAME AS EFT_CORRESPONDENTS_COSTS, PD.EFT_CROSSED_CHECK, PD.EFT_CHECK_FWRD_CD, PD.EFT_CHECK_DRAW_CD, PD.EFT_PAY_INST_CD1, PD.EFT_PAY_INST_CD2, PD.EFT_PAY_INST_CD3,
       PD.EFT_PAY_INST_CD4, PD.EFT_PAY_INST_REF1, PD.EFT_PAY_INST_REF2, PD.ADDENDA_VALUE, PD.REPETITVE_TRNFR_CD, PD.DRAWDOWN_FLG, PD.CREATED_BY_USER, PD.PMT_FIELD1, PD.PMT_FIELD2, PD.PMT_FIELD3, PD.PAY_CYCLE, 
       PD.PAY_CYCLE_SEQ_NUM, PD.BATCH_NAME, PD.PMT_FILE_ID, PD.BANK_REF_ID, PD.EVENT_TRACKING_ID, PD.PMT_MSG_ID, PD.PMTRUNINSTANCE, PD.IN_PROCESS_FLG, PD.PAYEE_VIOLATION,
       PI.PMT_ID AS INV_PMT_ID, PI.INVOICE_ID, PI.BUSINESS_UNIT AS INV_BU, PI.INVOICE_DT, PI.GROSS_AMT, PI.TXN_CURRENCY_CD, PI.PAID_AMT, PI.PAID_AMT_CURRENCY, PI.DISCOUNT_TAKEN, PI.DESCR254_MIXED, 
       PI.PAY_DOC_ID, PI.PAY_DOC_SEQ, PI.AR_NUM, PI.EMPLID, 
       PF.PMT_FILE_ID, PF.PMTRUNINSTANCE, PF.FILE_STATUS, X12.XLATLONGNAME AS FILE_STS_DESCR, PF.BANK_SETID, PF.BANK_CD, PF.FORMAT_ID, PF.TOTAL_PMT_COUNT, PF.OUTPUT_TYPE, PF.PMT_FILE_PATH, PF.FILENAME, 
       PF.CREATE_DTTM, PF.CREATED_BY_USER, PF.PMT_CRYPTO_ID, PF.PUBNODE, PF.MSGNAME, PF.APMSGVER, PF.CHNLNAME, PF.PUBID, PF.IBPUBTRANSACTID, PF.EVENT_TRACKING_ID, PF.EXT_FILE_ID, PF.PMT_FIELD1,
       XREF.VOUCHER_ID, XREF.PYMNT_ID, XREF.PYMNT_SELCT_STATUS, X10.XLATLONGNAME AS PYMNT_SELECT_STS, 
       PT.PYMNT_ID_REF, PT.PYMNT_STATUS, X11.XLATLONGNAME AS PYMNT_STS_DESCR, PT.COUNTRY, PT.ADDRESS1, PT.ADDRESS2, PT.ADDRESS3, PT.ADDRESS4,
       PT.CITY, PT.STATE, PT.POSTAL, PT.OPRID, PT.PYMNT_RECONCILE_DT, PT.RECONCILE_OPRID, PT.RECON_STATUS, PT.MICR_LINE,
       PA.PAY_DOC_SEQ, PA.SOURCE_TXN, PA.BUSINESS_UNIT, PA.PAY_DOC_ID, PA.CURRENCY_PYMNT, PA.VENDOR_ID, PA.EMPLID, PA.INVOICE_ID, 
       PA.PAY_DOC_DT, PA.PAID_AMT, PA.PAID_AMT_GROSS, PT.EFT_LAYOUT_CD, PT.PMT_PYMNT_STATUS
FROM ((((((((((((((((((PS_PMT_DETAIL_TBL PD LEFT OUTER JOIN PS_PMT_INVOICE_TBL PI ON PD.PMT_ID = PI.PMT_ID)
      LEFT OUTER JOIN PS_PMT_FILE_DEFN PF ON PD.PMT_FILE_ID = PF.PMT_FILE_ID)
      LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'PMT_STATUS' AND X1.FIELDVALUE = PD.PMT_STATUS AND X1.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'PMT_LAST_STATUS' AND X2.FIELDVALUE = PD.PMT_LAST_STATUS AND X2.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'DFI_ID_QUAL' AND X3.FIELDVALUE = PD.DFI_ID_QUAL AND X3.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'PRENOTE_FLAG' AND X4.FIELDVALUE = PD.PRENOTE_FLAG AND X4.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X5 ON X5.FIELDNAME = 'BANK_ACCT_TYPE' AND X5.FIELDVALUE = PD.BANK_ACCT_TYPE AND X5.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X6 ON X6.FIELDNAME = 'EFT_PYMNT_FMT_CD' AND X6.FIELDVALUE = PD.EFT_PYMNT_FMT_CD AND X6.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X7 ON X7.FIELDNAME = 'EFT_TRANS_HANDLING' AND X7.FIELDVALUE = PD.EFT_TRANS_HANDLING AND X7.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X8 ON X8.FIELDNAME = 'EFT_DOM_COSTS_CD' AND X8.FIELDVALUE = PD.EFT_DOM_COSTS_CD AND X8.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X13 ON X13.FIELDNAME = 'EFT_CORR_COSTS_CD' AND X13.FIELDVALUE = PD.EFT_CORR_COSTS_CD AND X13.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X9 ON X9.FIELDNAME = 'PMT_TYPE' AND X9.FIELDVALUE = PD.PMT_TYPE AND X9.EFF_STATUS = 'A')
      --LEFT OUTER JOIN PS_PYMNT_VCHR_XREF XREF ON PD.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND PI.PAY_DOC_ID = XREF.VOUCHER_ID)
      LEFT OUTER JOIN PS_PAYMENT_TBL PT ON PD.BANK_SETID = PT.BANK_SETID AND PD.BANK_CD = PT.BANK_CD AND PD.BANK_ACCT_KEY = PT.BANK_ACCT_KEY AND PD.PMT_ID = PT.PMT_ID) --AND XREF.PYMNT_ID = PT.PYMNT_ID)
      LEFT OUTER JOIN PS_PYMNT_VCHR_XREF XREF ON PI.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND PI.PAY_DOC_ID = XREF.VOUCHER_ID)
      LEFT OUTER JOIN PSXLATITEM X10 ON X10.FIELDNAME = 'PYMNT_SELCT_STATUS' AND X10.FIELDVALUE = XREF.PYMNT_SELCT_STATUS AND X10.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X11 ON X11.FIELDNAME = 'PYMNT_STATUS' AND X11.FIELDVALUE = PT.PYMNT_STATUS AND X11.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X12 ON X12.FIELDNAME = 'FILE_STATUS' AND X12.FIELDVALUE = PF.FILE_STATUS AND X12.EFF_STATUS = 'A')
      LEFT OUTER JOIN PS_PYMNT_ADVICE PA ON PT.PAY_CYCLE = PA.PAY_CYCLE AND PT.PAY_CYCLE_SEQ_NUM = PA.PAY_CYCLE_SEQ_NUM AND PT.BANK_SETID = PA.BANK_SETID AND PT.BANK_CD = PA.BANK_CD AND PT.BANK_ACCT_KEY = PA.BANK_ACCT_KEY
                                        AND PT.PYMNT_METHOD = PA.PYMNT_METHOD AND PA.REMIT_LINE_TYPE = 'A' AND PT.PYMNT_ID_REF = PA.PYMNT_ID_REF)
WHERE PD.BANK_SETID = 'SHARE' 
--  AND PD.BANK_CD LIKE '6%'
AND PD.PMT_FILE_ID = '00062501'
ORDER BY PD.PYMNT_DT DESC, PD.VALUE_DT DESC, PD.PMT_SOURCE, PD.PMT_ID DESC;

--Payments in Error
--Added XLAT for PMT_ADDRESS_TYPE as there are 2 rows for each txn
SELECT PD.PMT_ID, PD.PMT_SOURCE, PD.BUSINESS_UNIT, PD.SRC_REF_ID, PD.AMOUNT, PD.AMOUNT_CURRENCY_CD, PD.PYMNT_DT, PD.VALUE_DT, PD.ESTIMATED_DUE_DATE, 
       PD.PMT_STATUS || ' - ' || X1.XLATLONGNAME AS PMT_STS_DESCR, PD.PMT_LAST_STATUS || ' - ' || X2.XLATLONGNAME AS PMT_LAST_STS_DESCR, 
       PD.PMT_TYPE || ' - ' || X9.XLATLONGNAME AS PMT_TYPE_DESCR, PD.BANK_SETID, PD.BANK_CD, PD.BANK_ACCT_KEY, PD.ACCT_BUS_UNIT_GL, PD.FROM_BNK_ID_NBR, 
       PD.FROM_BNK_ACCT_NUM, PD.FROM_DFI_ID_NUM, PD.FROM_DFI_ID_QUAL, PD.PYMNT_METHOD, PD.FORMAT_ID, PD.PRENOTE_FLAG || ' - ' || X4.XLATLONGNAME AS PRE_NOTE_DESCR,
       PD.PAY_IMMEDIATELY, PD.COUNTRY, PD.BANK_ID_QUAL, PD.BNK_ID_NBR, PD.BRANCH_ID, PD.BANK_ACCT_TYPE || ' - ' || X5.XLATLONGNAME AS BANK_ACCT_TYPE_DECSR, 
       PD.BANK_ACCOUNT_NUM, PD.CHECK_DIGIT, PD.DFI_ID_QUAL || ' - ' || X3.XLATLONGNAME AS DFI_ID_QUAL_DESCR, PD.DFI_ID_NUM, 
       PD.BANK_NAME, PD.BANK_NAME_AC, PD.BRANCH_DESCR, PD.BRANCH_NAME_AC, PD.IBAN_CHECK_DIGIT, PD.IBAN_ID, PD.PARTY_ID_TYPE, PD.PARTY_SETID, PD.PARTY_ID, PD.NAME1, 
       PD.NAME1_AC, PD.NAME2, PD.STD_ID_NUM, PD.STD_ID_NUM_QUAL, PD.EFT_PYMNT_FMT_CD || ' - ' || X6.XLATLONGNAME AS EFT_PMT_FMT_CD_DESCR, PD.EFT_RTNG_FLG, PD.EFT_RTNG_STATUS, 
       PD.EFT_TRANS_HANDLING || ' - ' || X7.XLATLONGNAME AS EFT_TRANS_HANDLING_DESCR, PD.EFT_DOM_COSTS_CD || ' - ' || X8.XLATLONGNAME AS EFT_DOMESTIC_COSTS, 
       PD.EFT_CORR_COSTS_CD || ' - ' || X13.XLATLONGNAME AS EFT_CORRESPONDENTS_COSTS, PD.EFT_CROSSED_CHECK, PD.EFT_CHECK_FWRD_CD, PD.EFT_CHECK_DRAW_CD, PD.EFT_PAY_INST_CD1, 
       PD.EFT_PAY_INST_CD2, PD.EFT_PAY_INST_CD3, PD.EFT_PAY_INST_CD4, PD.EFT_PAY_INST_REF1, PD.EFT_PAY_INST_REF2, PD.ADDENDA_VALUE, PD.REPETITVE_TRNFR_CD, PD.DRAWDOWN_FLG, 
       PD.CREATED_BY_USER, PD.PMT_FIELD1, PD.PMT_FIELD2, PD.PMT_FIELD3, PD.PAY_CYCLE, PD.PAY_CYCLE_SEQ_NUM, PD.BATCH_NAME, PD.PMT_FILE_ID, PD.BANK_REF_ID, PD.EVENT_TRACKING_ID, 
       PD.PMT_MSG_ID, PD.PMTRUNINSTANCE, PD.IN_PROCESS_FLG, PD.PAYEE_VIOLATION, PI.PMT_ID AS INV_PMT_ID, PI.INVOICE_ID, PI.BUSINESS_UNIT AS INV_BU, PI.INVOICE_DT, 
       PI.GROSS_AMT, PI.TXN_CURRENCY_CD, PI.PAID_AMT, PI.PAID_AMT_CURRENCY, PI.DISCOUNT_TAKEN, PI.DESCR254_MIXED, PI.PAY_DOC_ID, PI.PAY_DOC_SEQ, PI.AR_NUM, PI.EMPLID, 
       PF.PMT_FILE_ID, PF.PMTRUNINSTANCE, PF.FILE_STATUS || ' - ' || X12.XLATLONGNAME AS FILE_STS_DESCR, PF.BANK_SETID, PF.BANK_CD, PF.FORMAT_ID, PF.TOTAL_PMT_COUNT, 
       PF.OUTPUT_TYPE, PF.PMT_FILE_PATH, PF.FILENAME, PF.CREATE_DTTM, PF.CREATED_BY_USER, PF.PMT_CRYPTO_ID, PF.PUBNODE, PF.MSGNAME, PF.APMSGVER, PF.CHNLNAME, PF.PUBID, 
       PF.IBPUBTRANSACTID, PF.EVENT_TRACKING_ID, PF.EXT_FILE_ID, PF.PMT_FIELD1, XREF.VOUCHER_ID, XREF.PYMNT_ID, 
       XREF.PYMNT_SELCT_STATUS || ' - ' || X10.XLATLONGNAME AS PYMNT_SELECT_STS, PT.PYMNT_ID_REF, PT.PYMNT_STATUS || ' - ' || X11.XLATLONGNAME AS PYMNT_STS_DESCR, 
       PT.COUNTRY, PT.ADDRESS1, PT.ADDRESS2, PT.ADDRESS3, PT.ADDRESS4, PT.CITY, PT.STATE, PT.POSTAL, PT.OPRID, PT.PYMNT_RECONCILE_DT, PT.RECONCILE_OPRID, PT.RECON_STATUS, 
       PT.MICR_LINE, PA.PAY_DOC_SEQ, PA.SOURCE_TXN, PA.BUSINESS_UNIT, PA.PAY_DOC_ID, PA.CURRENCY_PYMNT, PA.VENDOR_ID, PA.EMPLID, PA.INVOICE_ID, 
       PA.PAY_DOC_DT, PA.PAID_AMT, PA.PAID_AMT_GROSS, PT.EFT_LAYOUT_CD, PT.PMT_PYMNT_STATUS,
       PR.KEY_CHAR_40_01, PR.KEY_CHAR_40_02, PR.KEY_CHAR_40_03, PR.KEY_CHAR_40_04, PR.KEY_CHAR_40_05, PR.KEY_CHAR_40_06, PR.KEY_CHAR_40_07, PR.KEY_CHAR_40_08, 
       PR.KEY_CHAR_40_09, PR.KEY_CHAR_40_10, PR.KEY_CHAR_40_11, PR.KEY_CHAR_40_12, PR.KEY_CHAR_40_13, PR.KEY_CHAR_40_14, PR.KEY_CHAR_40_15, PR.KEY_DATE_01, 
       PR.KEY_DATE_02, PR.KEY_DATE_03, PR.KEY_DATE_04, PR.KEY_DATE_05, PR.KEY_DTTM_01, PR.KEY_DTTM_02, PR.KEY_DTTM_03, PR.KEY_DTTM_04, PR.KEY_DTTM_05, 
       PR.KEY_SIGN_01, PR.KEY_SIGN_02, PR.KEY_SIGN_03, PR.KEY_SIGN_04, PR.KEY_SIGN_05, CTR.ERROR_MESSAGE,
       PAD.PMT_ADDRESS_TYPE || ' - ' || X17.XLATLONGNAME AS "PMT Address Type", PAD.COUNTRY, PAD.ADDRESS1, PAD.ADDRESS2, PAD.ADDRESS3, PAD.ADDRESS4,
       PAD.CITY, PAD.STATE, PAD.POSTAL,
       CFTR.TR_SOURCE_CD, CFTR.SOURCE_BUS_UNIT, CFTR.TR_SOURCE_ID, CFTR.BUSINESS_DATE, CFTR.PMT_ID, CFTR.PMT_STATUS AS "PMT STS", CFTR.CASH_FLOW_LINE, 
       CFTR.CASH_FLOW_LEG, CFTR.PAY_DOC_SEQ, CFTR.CASH_TYPE AS "Cash Type", 
       CFTR.AMOUNT AS "CF Amount", CFTR.CURRENCY_CD AS "CF Curr", CFTR.BANK_SETID AS "CF Bank SetID", CFTR.BANK_CD_CUST AS "CF Bank Cust", CFTR.BANK_CD "CF Bank CD", 
       CFTR.BANK_ACCT_KEY AS "CF Bank Acct Key", CFTR.ACCT_BUS_UNIT_GL, CFTR.BNK_ID_NBR, 
       CFTR.BANK_ACCOUNT_NUM AS "CF Bank Acct#", CFTR.TRANSACTION_LINE, CFTR.RECONCILE_DT, CFTR.RECONCILE_OPRID, CFTR.RECON_TYPE, CFTR.RECON_STATUS, CFTR.RECON_CYCLE_NBR, 
       CFTR.STTLMNT_DT_ACTUAL, CFTR.NET_STATUS, CFTR.APPROVAL_OPRID, CFTR.CPTY_REFERENCE, CFTR.NET_REF_ID, CFTR.CF_SOURCE_REF_ID, CFTR.CP_NETTOR, 
       CFTR.PYMNT_METHOD AS "CF Pymnt Mthd", CFTR.SETTLEMENT_ID AS "CF Settlement ID", CFTR.PYMNT_SELCT_STATUS, CFTR.APPROVAL_FLG_TR, CFTR.APPROV_SUBMITTED, CFTR.PYMNT_ID, 
       CFTR.CURRENCY_CD_BASE, CFTR.BASE_AMT, CFTR.BASE_CURRENCY_BNK, 
       CFTR.BNK_RATE_DIV, CFTR.BNK_RATE_MULT, CFTR.CUR_RT_TYPE_BNK, CFTR.CURRENCY_PYMNT, CFTR.PAID_AMT, CFTR.PAID_AMT_BNK_BSE, CFTR.PAID_AMT_BSE, CFTR.PYMNT_RATE_DIV, 
       CFTR.PYMNT_RATE_MULT, CFTR.PAY_CYCLE, CFTR.PAY_CYCLE_SEQ_NUM, CFTR.BANK_STMT_DT, CFTR.RECORD_SEQ_NUMBER, CFTR.SELECTED_OPRID, CFTR.SELECTED_DTTM, CFTR.APPROVAL_DTTM, 
       CFTR.RECON_RUN_ID, CFTR.BANK_ACCT_RVL_AMT, CFTR.STL_THROUGH, CFTR.EVENT_TRACKING_ID, CFTR.REPETITVE_TRNFR_CD AS "CF Repetitive TRF CD", 
       CFTR.DRAWDOWN_FLG AS "CF Drawdown Flag", CFTR.FORMAT_ID AS "CF Foormat ID", CFTR.TRP_BUSINESS_UNIT, CFTR.POOL_ID,
       (SELECT RTRIM(XMLAGG(XMLELEMENT(E, PACK.PMT_ACK_FILE_ID || ' - '|| PACK.HEADER_ID || ' - '|| PACK.FILE_ACK_STATUS || ' - ' || X14.XLATLONGNAME || ' - '|| 
                                   PHDR.ACK_FILE_STATUS || ' - ' || X15.XLATLONGNAME || ' - '|| PHDR.BANK_FILE_ID || ' - '|| PHDR.BANK_SEND_DTTM || ' - '||
                                   PHDR.FORMAT_ID || ' - '|| PHDR.FILENAME || ' - '|| PHDR.CREATE_DTTM || ' - '|| PHDR.EVENT_TRACKING_ID || ' - '|| 
                                   PHDR.BANK_SETID || ' - '|| PHDR.BANK_CD || ' - '|| PMACK.PMT_ACK_FILE_ID || ' - '|| PMACK.PYMNT_REF_ID || ' - '|| 
                                   PMACK.PMT_STATUS || ' - ' || X16.XLATLONGNAME || ' - '|| PERR.PMT_ACK_FILE_ID  || ' - '|| PERR.PYMNT_REF_ID || ' - '|| 
                                   PERR.SEQ_NUM || ' - '|| PERR.ERROR_CODE || ' - '|| PERR.ERROR_MESSAGE, ' ; ' || chr(13))
                                   .EXTRACT('//text()')ORDER BY PACK.HEADER_ID, PHDR.BANK_SEND_DTTM desc).getclobval(),',') AS "A3"
        FROM ((((((PS_PMT_FILE_ACK PACK LEFT OUTER JOIN PS_PMT_ACK_HEADER PHDR ON PHDR.PMT_ACK_FILE_ID = PACK.PMT_ACK_FILE_ID)      
        LEFT OUTER JOIN PS_PMT_ACK PMACK ON PMACK.PMT_ACK_FILE_ID = PACK.PMT_ACK_FILE_ID)
        LEFT OUTER JOIN PS_PMT_ACK_ERR PERR ON PERR.PMT_ACK_FILE_ID = PACK.PMT_ACK_FILE_ID AND PMACK.PYMNT_REF_ID = PERR.PYMNT_REF_ID)
        LEFT OUTER JOIN PSXLATITEM X14 ON X14.FIELDNAME = 'FILE_ACK_STATUS' AND X14.FIELDVALUE = PACK.FILE_ACK_STATUS AND X14.EFF_STATUS = 'A')
        LEFT OUTER JOIN PSXLATITEM X15 ON X15.FIELDNAME = 'ACK_FILE_STATUS' AND X15.FIELDVALUE = PHDR.ACK_FILE_STATUS AND X15.EFF_STATUS = 'A')
        LEFT OUTER JOIN PSXLATITEM X16 ON X16.FIELDNAME = 'PMT_STATUS' AND X16.FIELDVALUE = PMACK.PMT_STATUS AND X16.EFF_STATUS = 'A')
        WHERE PACK.HEADER_ID = PD.PMT_FILE_ID AND (PMACK.PYMNT_REF_ID = PD.SRC_REF_ID OR PERR.PYMNT_REF_ID = PD.SRC_REF_ID)) AS "Acknowledgement - PMT_FILE_ACK"
FROM (((((((((((((((((((((((PS_PMT_DETAIL_TBL PD LEFT OUTER JOIN PS_PMT_INVOICE_TBL PI ON PD.PMT_ID = PI.PMT_ID)
      LEFT OUTER JOIN PS_PMT_FILE_DEFN PF ON PD.PMT_FILE_ID = PF.PMT_FILE_ID)
      LEFT OUTER JOIN PS_PMT_REF_TBL PR ON PD.PMT_ID = PR.PMT_ID)
      LEFT OUTER JOIN PS_PMT_ADDRESS_TBL PAD ON PD.PMT_ID = PAD.PMT_ID)
      LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'PMT_STATUS' AND X1.FIELDVALUE = PD.PMT_STATUS AND X1.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'PMT_LAST_STATUS' AND X2.FIELDVALUE = PD.PMT_LAST_STATUS AND X2.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'DFI_ID_QUAL' AND X3.FIELDVALUE = PD.DFI_ID_QUAL AND X3.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'PRENOTE_FLAG' AND X4.FIELDVALUE = PD.PRENOTE_FLAG AND X4.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X5 ON X5.FIELDNAME = 'BANK_ACCT_TYPE' AND X5.FIELDVALUE = PD.BANK_ACCT_TYPE AND X5.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X6 ON X6.FIELDNAME = 'EFT_PYMNT_FMT_CD' AND X6.FIELDVALUE = PD.EFT_PYMNT_FMT_CD AND X6.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X7 ON X7.FIELDNAME = 'EFT_TRANS_HANDLING' AND X7.FIELDVALUE = PD.EFT_TRANS_HANDLING AND X7.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X8 ON X8.FIELDNAME = 'EFT_DOM_COSTS_CD' AND X8.FIELDVALUE = PD.EFT_DOM_COSTS_CD AND X8.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X13 ON X13.FIELDNAME = 'EFT_CORR_COSTS_CD' AND X13.FIELDVALUE = PD.EFT_CORR_COSTS_CD AND X13.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X17 ON X17.FIELDNAME = 'PMT_ADDRESS_TYPE' AND X17.FIELDVALUE = PAD.PMT_ADDRESS_TYPE AND X17.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X9 ON X9.FIELDNAME = 'PMT_TYPE' AND X9.FIELDVALUE = PD.PMT_TYPE AND X9.EFF_STATUS = 'A')
      --LEFT OUTER JOIN PS_PYMNT_VCHR_XREF XREF ON PD.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND PI.PAY_DOC_ID = XREF.VOUCHER_ID)
      LEFT OUTER JOIN PS_PAYMENT_TBL PT ON PD.BANK_SETID = PT.BANK_SETID AND PD.BANK_CD = PT.BANK_CD AND PD.BANK_ACCT_KEY = PT.BANK_ACCT_KEY AND PD.PMT_ID = PT.PMT_ID) --AND XREF.PYMNT_ID = PT.PYMNT_ID)
      LEFT OUTER JOIN PS_PYMNT_VCHR_XREF XREF ON PI.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND PI.PAY_DOC_ID = XREF.VOUCHER_ID)
      LEFT OUTER JOIN PSXLATITEM X10 ON X10.FIELDNAME = 'PYMNT_SELCT_STATUS' AND X10.FIELDVALUE = XREF.PYMNT_SELCT_STATUS AND X10.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X11 ON X11.FIELDNAME = 'PYMNT_STATUS' AND X11.FIELDVALUE = PT.PYMNT_STATUS AND X11.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X12 ON X12.FIELDNAME = 'FILE_STATUS' AND X12.FIELDVALUE = PF.FILE_STATUS AND X12.EFF_STATUS = 'A')
      LEFT OUTER JOIN PS_PYMNT_ADVICE PA ON PT.PAY_CYCLE = PA.PAY_CYCLE AND PT.PAY_CYCLE_SEQ_NUM = PA.PAY_CYCLE_SEQ_NUM AND PT.BANK_SETID = PA.BANK_SETID AND PT.BANK_CD = PA.BANK_CD AND PT.BANK_ACCT_KEY = PA.BANK_ACCT_KEY
                                        AND PT.PYMNT_METHOD = PA.PYMNT_METHOD AND PA.REMIT_LINE_TYPE = 'A' AND PT.PYMNT_ID_REF = PA.PYMNT_ID_REF)
      LEFT OUTER JOIN UNDPFS.PS_UN_TR_FG_IN_ERR CTR ON PD.PMT_ID = CTR.PMT_ID AND PD.SRC_REF_ID = CTR.SRC_REF_ID)
      LEFT OUTER JOIN PS_CASH_FLOW_TR CFTR ON CFTR.PMT_ID = PD.PMT_ID AND PD.BUSINESS_UNIT = CFTR.SOURCE_BUS_UNIT AND PD.SRC_REF_ID = CFTR.TR_SOURCE_ID AND CFTR.AMOUNT < 0)
WHERE PD.BANK_SETID = 'SHARE' 
--  AND PD.BANK_CD LIKE '6%'
--AND PD.PMT_FILE_ID = '00062460'
AND PD.PYMNT_DT BETWEEN TO_DATE('2021-11-19','YYYY-MM-DD') AND TO_DATE('2021-11-25','YYYY-MM-DD')
--AND PD.BANK_CD = '00055'
--AND UPPER(PD.NAME1) LIKE '%ATMAN%'
--AND PD.PMT_STATUS IN ('L', 'H', 'E', 'SC')
--AND PD.COUNTRY = 'PAK'
--AND PD.PMT_TYPE IN ('BAX')
--AND PD.SRC_REF_ID IN ('BT00082334', 'DL00107205', 'BT00085232', 'DL00105210')
--AND PD.PMT_ID = 'CM0000017258'
--  AND PF.FILENAME = 'UNDP_CIT_002871001_pain002_20211028_060019.xml'
--  AND PD.PMT_FILE_ID = '00073540'
--  AND (PD.PARTY_ID = '71001933' OR PA.EMPLID = '71001933')
  AND PD.PMT_STATUS = 'E'
ORDER BY PD.PYMNT_DT DESC, PD.VALUE_DT DESC, PD.PMT_SOURCE, PD.PMT_ID DESC;

--Payment File Acknowledgent
--Version 1
--PMT_FILE_ID from above query is HEADER_ID in here
SELECT PACK.PMT_ACK_FILE_ID, PACK.HEADER_ID, PACK.FILE_ACK_STATUS || ' - ' || X1.XLATLONGNAME AS "File Ack Status", PACK.NUM_PMTS_ACCEPTED, PACK.NUM_PMTS_IN_ERROR,
       PHDR.ACK_FILE_STATUS || ' - ' || X2.XLATLONGNAME AS "ACK Status", PHDR.BANK_FILE_ID, PHDR.BANK_SEND_DTTM, PHDR.FORMAT_ID, PHDR.OUTPUT_TYPE, PHDR.PMT_FILE_PATH, 
       PHDR.FILENAME, PHDR.CREATE_DTTM, PHDR.CREATED_BY_USER, PHDR.PMT_CRYPTO_ID, PHDR.PUBNODE, PHDR.MSGNAME, PHDR.APMSGVER, PHDR.CHNLNAME, PHDR.PUBID, PHDR.EVENT_TRACKING_ID, 
       PHDR.BANK_SETID, PHDR.BANK_CD, PHDR.BANK_ID_QUAL, PHDR.BNK_ID_NBR, PHDR.DFI_ID_NUM, PHDR.DFI_ID_QUAL,
       PMACK.PMT_ACK_FILE_ID AS "ACK_PMT_ACK_FILE_ID", PMACK.PYMNT_REF_ID AS "ACK_PYMNT_REF_ID", PMACK.PMT_STATUS || ' - ' || X3.XLATLONGNAME AS "PMT Status", PMACK.BANK_REF_ID, 
       PERR.PMT_ACK_FILE_ID AS "ERR_PMT_ACK_FILE_ID", PERR.PYMNT_REF_ID AS "ERR_PYMNT_REF_ID", PERR.SEQ_NUM, PERR.ERROR_CODE, PERR.ERROR_MESSAGE
FROM ((((((PS_PMT_FILE_ACK PACK LEFT OUTER JOIN PS_PMT_ACK_HEADER PHDR ON PHDR.PMT_ACK_FILE_ID = PACK.PMT_ACK_FILE_ID)      
      LEFT OUTER JOIN PS_PMT_ACK PMACK ON PMACK.PMT_ACK_FILE_ID = PACK.PMT_ACK_FILE_ID)
      LEFT OUTER JOIN PS_PMT_ACK_ERR PERR ON PERR.PMT_ACK_FILE_ID = PACK.PMT_ACK_FILE_ID AND PMACK.PYMNT_REF_ID = PERR.PYMNT_REF_ID)
      LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'FILE_ACK_STATUS' AND X1.FIELDVALUE = PACK.FILE_ACK_STATUS AND X1.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'ACK_FILE_STATUS' AND X2.FIELDVALUE = PHDR.ACK_FILE_STATUS AND X2.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'PMT_STATUS' AND X3.FIELDVALUE = PMACK.PMT_STATUS AND X3.EFF_STATUS = 'A')
WHERE 1 = 1
  AND PACK.HEADER_ID = '00073540'
ORDER BY PACK.HEADER_ID, PHDR.BANK_SEND_DTTM desc;

--Queries for FG to check Process Monitor for specific Message Catalogs
--Version 1
--Using LISTAGG
SELECT PL.PROCESS_INSTANCE, PL.MESSAGE_SEQ, PR.OPRID, PR.RUNCNTLID, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, ML.MESSAGE_SET_NBR, ML.MESSAGE_NBR, 
       CAT.MESSAGE_TEXT, LISTAGG(PL.MESSAGE_PARM, '|') WITHIN GROUP (ORDER BY PARM_SEQ) MESSAGE_PARM, PR.RUNDTTM 
FROM PS_MESSAGE_LOGPARM PL, PS_MESSAGE_LOG ML, PSPRCSRQST PR, PSMSGCATDEFN CAT
WHERE PL.PROCESS_INSTANCE = ML.PROCESS_INSTANCE
    AND PL.MESSAGE_SEQ = ML.MESSAGE_SEQ
    AND PL.PROCESS_INSTANCE = PR.PRCSINSTANCE
    AND ML.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR
    AND ML.MESSAGE_NBR = CAT.MESSAGE_NBR
    AND ML.MESSAGE_SET_NBR IN (10511, 13950)
    --AND ML.MESSAGE_NBR IN (1, 2, 3, 8, 21, 22, 119, 128, 136, 320, 324, 333, 400, 396, 397, 398, 399, 403, 404, 405, 406, 137, 407)
    --Only for reporting exceptions
    --AND ML.MESSAGE_NBR = 406
    --AND PR.OPRID = 'prakash.prashant'
    AND TO_CHAR(((RUNDTTM ) + (0)),'YYYY-MM-DD') >= TO_CHAR(TRUNC(TRUNC(SYSDATE, 'DD') -1, 'DD'), 'YYYY-MM-DD')
    AND TO_CHAR(((RUNDTTM ) + (-1)),'YYYY-MM-DD') <= TO_CHAR(SYSDATE, 'YYYY-MM-DD')
GROUP BY PL.PROCESS_INSTANCE, PL.MESSAGE_SEQ, PR.OPRID, PR.RUNCNTLID, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, ML.MESSAGE_SET_NBR, 
         ML.MESSAGE_NBR, CAT.MESSAGE_TEXT, PR.RUNDTTM
ORDER BY PL.PROCESS_INSTANCE DESC, PL.MESSAGE_SEQ;

--Version 2
--Using XMLAGG
SELECT PL.PROCESS_INSTANCE, PR.OPRID, PL.MESSAGE_SEQ, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, 
       ML.DTTM_STAMP_SEC, MSG.MESSAGE_TEXT, MSG.MESSAGE_SET_NBR, MSG.MESSAGE_NBR, 
       RTRIM(XMLAGG(XMLELEMENT(E, PL.MESSAGE_PARM, '|').EXTRACT('//text()') ORDER BY PL.PARM_SEQ).GETCLOBVAL(),',') AS MESSAGE_PARM
FROM PS_MESSAGE_LOGPARM PL, PS_MESSAGE_LOG ML, PSPRCSRQST PR, PSMSGCATDEFN MSG
WHERE PL.PROCESS_INSTANCE = ML.PROCESS_INSTANCE
    AND PL.MESSAGE_SEQ = ML.MESSAGE_SEQ
    AND PL.PROCESS_INSTANCE = PR.PRCSINSTANCE
    AND ML.MESSAGE_SET_NBR = MSG.MESSAGE_SET_NBR
    AND ML.MESSAGE_NBR = MSG.MESSAGE_NBR
    AND ML.MESSAGE_SET_NBR IN (10511, 13950)
    AND TO_CHAR(((RUNDTTM ) + (0)),'YYYY-MM-DD') >= TO_CHAR(TRUNC(TRUNC(SYSDATE, 'DD') -1, 'DD'), 'YYYY-MM-DD')
    AND TO_CHAR(((RUNDTTM ) + (-1)),'YYYY-MM-DD') <= TO_CHAR(SYSDATE, 'YYYY-MM-DD')
GROUP BY PL.PROCESS_INSTANCE, PR.OPRID, PL.MESSAGE_SEQ, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, 
         ML.DTTM_STAMP_SEC, MSG.MESSAGE_TEXT, MSG.MESSAGE_SET_NBR, MSG.MESSAGE_NBR
ORDER BY PL.PROCESS_INSTANCE DESC, PL.MESSAGE_SEQ;
