--Version 2
--Added PAYMENT_TBL, PYMNT_VCHR_XREF, PYMNT_ADVICE Tables
SELECT PD.PMT_ID, PD.PMT_SOURCE, PD.BUSINESS_UNIT, PD.SRC_REF_ID, PD.AMOUNT, PD.AMOUNT_CURRENCY_CD, PD.PYMNT_DT, PD.VALUE_DT, PD.ESTIMATED_DUE_DATE, PD.PMT_STATUS, X1.XLATLONGNAME AS PMT_STS_DESCR, 
       PD.PMT_LAST_STATUS, X2.XLATLONGNAME AS PMT_LAST_STS_DESCR, PD.PMT_TYPE, X9.XLATLONGNAME AS PMT_TYPE_DESCR, PD.BANK_SETID, 
       PD.BANK_CD, PD.BANK_ACCT_KEY, PD.ACCT_BUS_UNIT_GL, PD.FROM_BNK_ID_NBR, PD.FROM_BNK_ACCT_NUM, PD.FROM_DFI_ID_NUM, PD.FROM_DFI_ID_QUAL, PD.PYMNT_METHOD, PD.FORMAT_ID, PD.PRENOTE_FLAG, X4.XLATLONGNAME AS PRE_NOTE_DESCR,
       PD.PAY_IMMEDIATELY, PD.COUNTRY, PD.BANK_ID_QUAL, PD.BNK_ID_NBR, PD.BRANCH_ID, PD.BANK_ACCT_TYPE, X5.XLATLONGNAME AS BANK_ACCT_TYPE_DECSR, 
       PD.BANK_ACCOUNT_NUM, PD.CHECK_DIGIT, PD.DFI_ID_QUAL, X3.XLATLONGNAME AS DFI_ID_QUAL_DESCR, PD.DFI_ID_NUM, 
       PD.BANK_NAME, PD.BANK_NAME_AC, PD.BRANCH_DESCR, PD.BRANCH_NAME_AC, PD.IBAN_CHECK_DIGIT, PD.IBAN_ID, PD.PARTY_ID_TYPE, PD.PARTY_SETID, PD.PARTY_ID, PD.NAME1, PD.NAME1_AC, PD.NAME2, 
       PD.STD_ID_NUM, PD.STD_ID_NUM_QUAL, PD.EFT_PYMNT_FMT_CD, X6.XLATLONGNAME AS EFT_PMT_FMT_CD_DESCR, PD.EFT_RTNG_FLG, PD.EFT_RTNG_STATUS, 
       PD.EFT_TRANS_HANDLING, X7.XLATLONGNAME AS EFT_TRANS_HANDLING_DESCR, PD.EFT_DOM_COSTS_CD, X8.XLATLONGNAME AS EFT_DOMESTIC_COSTS, 
       PD.EFT_CORR_COSTS_CD, X13.XLATLONGNAME AS EFT_CORRESPONDENTS_COSTS, PD.EFT_CROSSED_CHECK, PD.EFT_CHECK_FWRD_CD, PD.EFT_CHECK_DRAW_CD, PD.EFT_PAY_INST_CD1, PD.EFT_PAY_INST_CD2, PD.EFT_PAY_INST_CD3,
       PD.EFT_PAY_INST_CD4, PD.EFT_PAY_INST_REF1, PD.EFT_PAY_INST_REF2, PD.ADDENDA_VALUE, PD.REPETITVE_TRNFR_CD, PD.DRAWDOWN_FLG, PD.CREATED_BY_USER, PD.PMT_FIELD1, PD.PMT_FIELD2, PD.PMT_FIELD3, PD.PAY_CYCLE, 
       PD.PAY_CYCLE_SEQ_NUM, PD.BATCH_NAME, PD.PMT_FILE_ID, PD.BANK_REF_ID, PD.EVENT_TRACKING_ID, PD.PMT_MSG_ID, PD.PMTRUNINSTANCE, PD.IN_PROCESS_FLG, PD.PAYEE_VIOLATION,
       PI.PMT_ID AS INV_PMT_ID, PI.INVOICE_ID, PI.BUSINESS_UNIT AS INV_BU, PI.INVOICE_DT, PI.GROSS_AMT, PI.TXN_CURRENCY_CD, PI.PAID_AMT, PI.PAID_AMT_CURRENCY, PI.DISCOUNT_TAKEN, PI.DESCR254_MIXED, 
       PI.PAY_DOC_ID, PI.PAY_DOC_SEQ, PI.AR_NUM, PI.EMPLID, 
       PF.PMT_FILE_ID, PF.PMTRUNINSTANCE, PF.FILE_STATUS, X12.XLATLONGNAME AS FILE_STS_DESCR, PF.BANK_SETID, PF.BANK_CD, PF.FORMAT_ID, PF.TOTAL_PMT_COUNT, PF.OUTPUT_TYPE, PF.PMT_FILE_PATH, PF.FILENAME, 
       PF.CREATE_DTTM, PF.CREATED_BY_USER, PF.PMT_CRYPTO_ID, PF.PUBNODE, PF.MSGNAME, PF.APMSGVER, PF.CHNLNAME, PF.PUBID, PF.IBPUBTRANSACTID, PF.EVENT_TRACKING_ID, PF.EXT_FILE_ID, PF.PMT_FIELD1,
       XREF.VOUCHER_ID, XREF.PYMNT_ID, XREF.PYMNT_SELCT_STATUS, X10.XLATLONGNAME AS PYMNT_SELECT_STS, 
       PT.PYMNT_ID_REF, PT.PYMNT_STATUS, X11.XLATLONGNAME AS PYMNT_STS_DESCR, PT.COUNTRY, PT.ADDRESS1, PT.ADDRESS2, PT.ADDRESS3, PT.ADDRESS4,
       PT.CITY, PT.STATE, PT.POSTAL, PT.OPRID, PT.PYMNT_RECONCILE_DT, PT.RECONCILE_OPRID, PT.RECON_STATUS, PT.MICR_LINE,
       PA.PAY_DOC_SEQ, PA.SOURCE_TXN, PA.BUSINESS_UNIT, PA.PAY_DOC_ID, PA.CURRENCY_PYMNT, PA.VENDOR_ID, PA.EMPLID, PA.INVOICE_ID, 
       PA.PAY_DOC_DT, PA.PAID_AMT, PA.PAID_AMT_GROSS, PT.EFT_LAYOUT_CD, PT.PMT_PYMNT_STATUS
FROM ((((((((((((((((((PS_PMT_DETAIL_TBL PD LEFT OUTER JOIN PS_PMT_INVOICE_TBL PI ON PD.PMT_ID = PI.PMT_ID)
      LEFT OUTER JOIN PS_PMT_FILE_DEFN PF ON PD.PMT_FILE_ID = PF.PMT_FILE_ID)
      LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'PMT_STATUS' AND X1.FIELDVALUE = PD.PMT_STATUS AND X1.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'PMT_LAST_STATUS' AND X2.FIELDVALUE = PD.PMT_LAST_STATUS AND X2.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'DFI_ID_QUAL' AND X3.FIELDVALUE = PD.DFI_ID_QUAL AND X3.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'PRENOTE_FLAG' AND X4.FIELDVALUE = PD.PRENOTE_FLAG AND X4.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X5 ON X5.FIELDNAME = 'BANK_ACCT_TYPE' AND X5.FIELDVALUE = PD.BANK_ACCT_TYPE AND X5.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X6 ON X6.FIELDNAME = 'EFT_PYMNT_FMT_CD' AND X6.FIELDVALUE = PD.EFT_PYMNT_FMT_CD AND X6.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X7 ON X7.FIELDNAME = 'EFT_TRANS_HANDLING' AND X7.FIELDVALUE = PD.EFT_TRANS_HANDLING AND X7.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X8 ON X8.FIELDNAME = 'EFT_DOM_COSTS_CD' AND X8.FIELDVALUE = PD.EFT_DOM_COSTS_CD AND X8.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X13 ON X13.FIELDNAME = 'EFT_CORR_COSTS_CD' AND X13.FIELDVALUE = PD.EFT_CORR_COSTS_CD AND X13.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X9 ON X9.FIELDNAME = 'PMT_TYPE' AND X9.FIELDVALUE = PD.PMT_TYPE AND X9.EFF_STATUS = 'A')
      --LEFT OUTER JOIN PS_PYMNT_VCHR_XREF XREF ON PD.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND PI.PAY_DOC_ID = XREF.VOUCHER_ID)
      LEFT OUTER JOIN PS_PAYMENT_TBL PT ON PD.BANK_SETID = PT.BANK_SETID AND PD.BANK_CD = PT.BANK_CD AND PD.BANK_ACCT_KEY = PT.BANK_ACCT_KEY AND PD.PMT_ID = PT.PMT_ID) --AND XREF.PYMNT_ID = PT.PYMNT_ID)
      LEFT OUTER JOIN PS_PYMNT_VCHR_XREF XREF ON PI.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND PI.PAY_DOC_ID = XREF.VOUCHER_ID)
      LEFT OUTER JOIN PSXLATITEM X10 ON X10.FIELDNAME = 'PYMNT_SELCT_STATUS' AND X10.FIELDVALUE = XREF.PYMNT_SELCT_STATUS AND X10.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X11 ON X11.FIELDNAME = 'PYMNT_STATUS' AND X11.FIELDVALUE = PT.PYMNT_STATUS AND X11.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X12 ON X12.FIELDNAME = 'FILE_STATUS' AND X12.FIELDVALUE = PF.FILE_STATUS AND X12.EFF_STATUS = 'A')
      LEFT OUTER JOIN PS_PYMNT_ADVICE PA ON PT.PAY_CYCLE = PA.PAY_CYCLE AND PT.PAY_CYCLE_SEQ_NUM = PA.PAY_CYCLE_SEQ_NUM AND PT.BANK_SETID = PA.BANK_SETID AND PT.BANK_CD = PA.BANK_CD AND PT.BANK_ACCT_KEY = PA.BANK_ACCT_KEY
                                        AND PT.PYMNT_METHOD = PA.PYMNT_METHOD AND PA.REMIT_LINE_TYPE = 'A' AND PT.PYMNT_ID_REF = PA.PYMNT_ID_REF)
WHERE PD.BANK_SETID = 'SHARE' 
--  AND PD.BANK_CD LIKE '6%'
AND PD.PMT_FILE_ID = '00062501'
ORDER BY PD.PYMNT_DT DESC, PD.VALUE_DT DESC, PD.PMT_SOURCE, PD.PMT_ID DESC;

--Queries for FG to check Process Monitor for specific Message Catalogs
--Version 1
--Using LISTAGG
SELECT PL.PROCESS_INSTANCE, PL.MESSAGE_SEQ, PR.OPRID, PR.RUNCNTLID, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, ML.MESSAGE_SET_NBR, ML.MESSAGE_NBR, 
       CAT.MESSAGE_TEXT, LISTAGG(PL.MESSAGE_PARM, '|') WITHIN GROUP (ORDER BY PARM_SEQ) MESSAGE_PARM, PR.RUNDTTM 
FROM PS_MESSAGE_LOGPARM PL, PS_MESSAGE_LOG ML, PSPRCSRQST PR, PSMSGCATDEFN CAT
WHERE PL.PROCESS_INSTANCE = ML.PROCESS_INSTANCE
    AND PL.MESSAGE_SEQ = ML.MESSAGE_SEQ
    AND PL.PROCESS_INSTANCE = PR.PRCSINSTANCE
    AND ML.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR
    AND ML.MESSAGE_NBR = CAT.MESSAGE_NBR
    AND ML.MESSAGE_SET_NBR IN (10511, 13950)
    --AND ML.MESSAGE_NBR IN (1, 2, 3, 8, 21, 22, 119, 128, 136, 320, 324, 333, 400, 396, 397, 398, 399, 403, 404, 405, 406, 137, 407)
    --Only for reporting exceptions
    --AND ML.MESSAGE_NBR = 406
    --AND PR.OPRID = 'prakash.prashant'
    AND TO_CHAR(((RUNDTTM ) + (0)),'YYYY-MM-DD') >= TO_CHAR(TRUNC(TRUNC(SYSDATE, 'DD') -1, 'DD'), 'YYYY-MM-DD')
    AND TO_CHAR(((RUNDTTM ) + (-1)),'YYYY-MM-DD') <= TO_CHAR(SYSDATE, 'YYYY-MM-DD')
GROUP BY PL.PROCESS_INSTANCE, PL.MESSAGE_SEQ, PR.OPRID, PR.RUNCNTLID, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, ML.MESSAGE_SET_NBR, 
         ML.MESSAGE_NBR, CAT.MESSAGE_TEXT, PR.RUNDTTM
ORDER BY PL.PROCESS_INSTANCE DESC, PL.MESSAGE_SEQ;

--Version 2
--Using XMLAGG
SELECT PL.PROCESS_INSTANCE, PR.OPRID, PL.MESSAGE_SEQ, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, 
       ML.DTTM_STAMP_SEC, MSG.MESSAGE_TEXT, MSG.MESSAGE_SET_NBR, MSG.MESSAGE_NBR, 
       RTRIM(XMLAGG(XMLELEMENT(E, PL.MESSAGE_PARM, '|').EXTRACT('//text()') ORDER BY PL.PARM_SEQ).GETCLOBVAL(),',') AS MESSAGE_PARM
FROM PS_MESSAGE_LOGPARM PL, PS_MESSAGE_LOG ML, PSPRCSRQST PR, PSMSGCATDEFN MSG
WHERE PL.PROCESS_INSTANCE = ML.PROCESS_INSTANCE
    AND PL.MESSAGE_SEQ = ML.MESSAGE_SEQ
    AND PL.PROCESS_INSTANCE = PR.PRCSINSTANCE
    AND ML.MESSAGE_SET_NBR = MSG.MESSAGE_SET_NBR
    AND ML.MESSAGE_NBR = MSG.MESSAGE_NBR
    AND ML.MESSAGE_SET_NBR IN (10511, 13950)
    AND TO_CHAR(((RUNDTTM ) + (0)),'YYYY-MM-DD') >= TO_CHAR(TRUNC(TRUNC(SYSDATE, 'DD') -1, 'DD'), 'YYYY-MM-DD')
    AND TO_CHAR(((RUNDTTM ) + (-1)),'YYYY-MM-DD') <= TO_CHAR(SYSDATE, 'YYYY-MM-DD')
GROUP BY PL.PROCESS_INSTANCE, PR.OPRID, PL.MESSAGE_SEQ, PR.PRCSNAME, PR.PRCSJOBNAME, PR.MAINJOBNAME, PR.RUNSTATUS, 
         ML.DTTM_STAMP_SEC, MSG.MESSAGE_TEXT, MSG.MESSAGE_SET_NBR, MSG.MESSAGE_NBR
ORDER BY PL.PROCESS_INSTANCE DESC, PL.MESSAGE_SEQ;
