--Version 8
--Anchor on PSDBFIELD
--Be careful while using DISTINCT, check for LONG columns
--Is CREF/Page Hidden or Visible
--Conditional Navigation
SELECT DBF.FIELDNAME, RECFLD.RECNAME "RecField Record", RECD.RECNAME "RecDefn Record",
       CASE(NVL(RECD.RECTYPE, 99))
          WHEN 0 THEN '0 - SQL Table' WHEN 1 THEN '1 - SQL View' WHEN 2 THEN '2 - Work Record' WHEN 3 THEN '3 - Sub Record' WHEN 5 THEN '5 - Dynamic View' WHEN 6 THEN '6 - Query View'
          WHEN 7 THEN '7 - Temporary Table'
       ELSE 'Excluded Record or Deleted' END AS "Record Type",
       RECFLD.RECNAME_PARENT, RECFLD.DEFRECNAME, RECFLD.EDITTABLE, RECFLD.LABEL_ID,
       CASE DBF.FIELDTYPE
         WHEN 0 THEN '0 - Char' WHEN 1 THEN '1 - Long Char' WHEN 2 THEN '2 - NBR' WHEN 3 THEN '3 - Sign NBR' WHEN 4 THEN '4 - Date' WHEN 5 THEN '5 - Time' WHEN 6 THEN '6 - Dttm'
         WHEN 7 THEN '7 - Img' WHEN 8 THEN '8 - Img/Attch' WHEN 9 THEN '9 - Img/Ref'
       ELSE 'Unknown' END "DB Field Type", DBF.LENGTH, DBF.OBJECTOWNERID || ' - ' || X1.XLATLONGNAME AS "DBField Object Ident",
       RECD.OBJECTOWNERID || ' - ' || X2.XLATLONGNAME AS "Record Object Ident", PNLD.OBJECTOWNERID || ' - ' || X3.XLATLONGNAME AS "Page Object Ident",
       CASE DBF.FORMAT
         WHEN 0 THEN CASE WHEN DBF.FIELDTYPE = 0 THEN '0 - Char(UpperCase)' WHEN DBF.FIELDTYPE = 6 THEN '6 - HH:MM' END
         WHEN 1 THEN '1 - Name' WHEN 2 THEN '2 - Phone Number North American (mandatory length 12 characters)'
         WHEN 3 THEN '3 - Zip/Postal Code North American (mandatory length 10 characters)' WHEN 4 THEN '4 - US Social Security Number (mandatory length 9 characters)'
         WHEN 5 THEN '5 - BLANK' WHEN 6 THEN '6 - Mixed Case' WHEN 7 THEN '7 - Raw/Binary'  WHEN 8 THEN '8 - Numbers Only' WHEN 9 THEN '9 - SIN (mandatory length 9 characters)'
         WHEN 10 THEN '10 - International Phone Number' WHEN 11 THEN '11 - Zip/Postal Code International' WHEN 12 THEN '12 - Time HH:MM:SS' WHEN 13 THEN '13 - Time HH:MM:SS.999999'
         WHEN 14 THEN '14 - Custom'
       ELSE 'Unknown' END "DB Field Format",
--       DBF.FLDNOTUSED, DBF.AUXFLAGMASK,
       CASE WHEN BITAND(RECFLD.USEEDIT, 256) > 0 THEN 'YES' ELSE 'NO' END AS "REQ (Y/N)",
       CASE WHEN BITAND(RECFLD.USEEDIT, 1) > 0 THEN 'KEY' WHEN BITAND(RECFLD.USEEDIT, 2) > 0 THEN 'DUP' WHEN BITAND(RECFLD.USEEDIT, 16) > 0 THEN 'ALT' ELSE NULL END AS KEY_TYPE,
       CASE WHEN BITAND(RECFLD.USEEDIT, 64) > 0 THEN 'DESC' WHEN (BITAND(RECFLD.USEEDIT, 1) > 0 OR BITAND(RECFLD.USEEDIT, 2) > 0 OR BITAND(RECFLD.USEEDIT, 16) > 0 )
                                                                                                                                AND BITAND(RECFLD.USEEDIT, 64) = 0 THEN 'ASC' ELSE NULL END AS DIR,
       CASE WHEN BITAND(RECFLD.USEEDIT, 2048) > 0 THEN 'YES' ELSE 'NO' END AS SRCH_KEY,
       CASE WHEN BITAND(RECFLD.USEEDIT, 32) > 0 THEN 'YES' ELSE 'NO' END AS LIST_BOX,
       CASE WHEN BITAND(RECFLD.USEEDIT, 4) > 0 THEN 'YES' ELSE 'NO' END AS SYS_MAINT,
       CASE WHEN BITAND(RECFLD.USEEDIT, 8) > 0 AND BITAND(RECFLD.USEEDIT, 128) = 0 AND BITAND(RECFLD.USEEDIT, 1024) = 0 THEN 'A'
            WHEN BITAND(RECFLD.USEEDIT, 8) > 0 AND BITAND(RECFLD.USEEDIT, 128) > 0 AND BITAND(RECFLD.USEEDIT, 1024) = 0 THEN 'AC'
            WHEN BITAND(RECFLD.USEEDIT, 8) > 0 AND BITAND(RECFLD.USEEDIT, 128) > 0 AND BITAND(RECFLD.USEEDIT, 1024) > 0 THEN 'ACD'
            WHEN BITAND(RECFLD.USEEDIT, 8) = 0 AND BITAND(RECFLD.USEEDIT, 128) > 0 AND BITAND(RECFLD.USEEDIT, 1024) = 0 THEN 'C'
            WHEN BITAND(RECFLD.USEEDIT, 8) = 0 AND BITAND(RECFLD.USEEDIT, 128) > 0 AND BITAND(RECFLD.USEEDIT, 1024) > 0 THEN 'CD'
            WHEN BITAND(RECFLD.USEEDIT, 8) = 0 AND BITAND(RECFLD.USEEDIT, 128) = 0 AND BITAND(RECFLD.USEEDIT, 1024) > 0 THEN 'D' ELSE NULL END AS AUDT,
       CASE WHEN BITAND(RECFLD.USEEDIT, 16384) > 0 THEN 'PROMPT' WHEN BITAND(RECFLD.USEEDIT, 512) > 0 THEN 'XLAT' WHEN BITAND(RECFLD.USEEDIT, 8192) > 0 THEN 'Y/N' ELSE NULL END AS EDIT_TYPE,
       CASE WHEN BITAND(RECFLD.USEEDIT, 4096) > 0 THEN 'YES' ELSE 'NO' END AS REASONABLE_DT,
       CASE WHEN BITAND(RECFLD.USEEDIT, 32768) > 0 THEN 'YES' ELSE 'NO' END AS AUTO_UPDT,
       CASE WHEN BITAND(RECFLD.USEEDIT, 262144) > 0 THEN 'FROM' WHEN BITAND(RECFLD.USEEDIT, 524288) > 0 THEN 'THROUGH' ELSE NULL END AS SEARCH_FIELD, RECFLD.FIELDNUM "Rec Field#",
       CASE WHEN PNLF.PNLNAME IS NOT NULL THEN CASE WHEN BITAND(PNLF.FIELDUSE, 1) = 1 THEN 'Display Only' WHEN BITAND(PNLF.FIELDUSE, 1) <> 1 THEN 'XXXX' END ELSE 'Unknown' END AS "Display Only",           
       CASE WHEN PNLF.PNLNAME IS NOT NULL THEN CASE WHEN BITAND(PNLF.FIELDUSE, 2) = 2 THEN 'Invisible' WHEN BITAND(PNLF.FIELDUSE, 2) <> 2 THEN 'Visible' END ELSE 'Unknown' END AS "Visible Y/N",           
--       CASE WHEN BITAND(PNLF.FIELDUSE, 2) = 2 THEN CASE WHEN PNLF.PNLNAME IS NOT NULL THEN 'Invisible' WHEN PNLF.PNLNAME IS NULL THEN 'Unknown' END ELSE 'PPPP' END AS "Visible Y/N",      
       PNLF.PNLNAME "Page Name",
       CASE PNLD.PNLTYPE WHEN 0 THEN 'Page' WHEN 1 THEN 'Sub Page' WHEN 2 THEN 'Secondary Page' WHEN 3 THEN 'Popup Page' WHEN 4 THEN 'NUI Header Page' WHEN 5 THEN 'NUI Side Page 1'
                         WHEN 6 THEN 'NUI Footer Page' WHEN 7 THEN 'NUI Layout Page' WHEN 8 THEN 'NUI Search Page' WHEN 9 THEN 'NUI Prompt Page' WHEN 10 THEN 'NUI Master Detail Target Page'
                         WHEN 11 THEN 'NUI Side Page 2'
       ELSE 'Unknown' END "Page Type",
       PNLF.PNLFIELDNAME "Page Field Name", PNLF.LABEL_ID "Label ID", PNLF.LBLTEXT "Label Text", PNLF.PNLFLDID, PNLF.FIELDNUM "Page Field#", PNLF.DSPLFORMAT, PNLF.ASSOCFIELDNUM,       
       PNLGRP.PNLGRPNAME "Component Name", PNLGRP.MARKET "Comp MKT", PRS.PORTAL_NAME "Portal Name",
       P3.PORTAL_LABEL || ' > ' || P2.PORTAL_LABEL || ' > ' || P1.PORTAL_LABEL || ' > ' || PRS.PORTAL_LABEL "Navigation", PRS.PORTAL_OBJNAME "Portal Object Name",
       PRS.PORTAL_PRODUCT "CREF Product", PRS.OBJECTOWNERID "Portal Object Ident", PRS.PORTAL_URI_SEG1 "Menu Name", PRS.PORTAL_URLTEXT "PSP URL",
       CASE WHEN PRS.PORTAL_OBJNAME IS NOT NULL THEN
         CASE WHEN dbms_lob.instr(PRSATTR.PORTAL_ATTR_VAL, 'TRUE') > 0 THEN 'Hidden' ELSE 'Visible' END ELSE 'Unknown' END "IsCREFHidden",
       PNLGRP.SUBITEMNUM "Page Tab#", CASE PNLGRP.HIDDEN WHEN 0 THEN '0 - Visible' WHEN 1 THEN '1 - Hidden' ELSE 'Unkown' END "IsPageHidden",
       MNU.MENUNAME, MNU.BARNAME "Menu Bar Name", MNU.ITEMNAME "Item Name", MNU.ITEMLABEL "Item Label", PRSATTR1.PORTAL_ATTR_VAL "Conditional Nav Attr Value"
--       CASE WHEN dbms_lob.instr(PRSATTR.PORTAL_ATTR_VAL, 'TRUE') > 0 THEN 'Hidden' ELSE 'Visible' END "IsCREFHidden"
FROM (((((((((((((((PSDBFIELD DBF LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'OBJECTOWNERID' AND X1.FIELDVALUE = DBF.OBJECTOWNERID AND X1.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSRECFIELDDB RECFLD ON DBF.FIELDNAME = RECFLD.FIELDNAME)
      LEFT OUTER JOIN PSRECDEFN RECD ON RECFLD.RECNAME = RECD.RECNAME
--                                   AND (RECD.RECNAME NOT LIKE '%_AET%' AND RECD.RECNAME NOT LIKE '%_TMP%' AND RECD.RECNAME NOT LIKE '%_RUN%' AND RECD.RECNAME NOT LIKE '%RQST%'
--                                   AND RECD.RECNAME NOT LIKE '%_TAO%' AND RECD.RECNAME NOT LIKE '%_TEO%')
                                   AND RECD.OBJECTOWNERID NOT IN ('PPT', 'CCF', 'CCU', 'CEO', 'CEI', 'CEW', 'CLT', 'CPP', 'CTP', 'TTS'))
                                   --http://www.go-faster.co.uk/peopletools/objectownerid.htm
      LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'OBJECTOWNERID' AND X2.FIELDVALUE = RECD.OBJECTOWNERID AND X2.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSPNLFIELD PNLF ON RECD.RECNAME = PNLF.RECNAME AND RECFLD.FIELDNAME = PNLF.FIELDNAME) --AND BITAND(PNLF.FIELDUSE, 2) <> 2) -- not Invisible Fields
      LEFT OUTER JOIN PSPNLDEFN PNLD ON PNLF.PNLNAME = PNLD.PNLNAME) --  AND PNLD.PNLNAME NOT LIKE '%!_WRK%' ESCAPE '!'
      LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'OBJECTOWNERID' AND X3.FIELDVALUE = PNLD.OBJECTOWNERID AND X3.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSPNLGROUP PNLGRP ON PNLF.PNLNAME = PNLGRP.PNLNAME) --AND PNLGRP.SUBITEMNUM = (SELECT MIN(PNL2.SUBITEMNUM) FROM PSPNLGROUP PNL2 WHERE PNL2.PNLGRPNAME = PNLGRP.PNLGRPNAME
                                                                                                                                                             --AND PNL2.HIDDEN = 0))
      LEFT OUTER JOIN PSMENUITEM MNU ON PNLGRP.PNLGRPNAME = MNU.PNLGRPNAME)
      LEFT OUTER JOIN PSPRSMDEFN PRS ON PRS.PORTAL_URI_SEG1 = MNU.MENUNAME AND PRS.PORTAL_URI_SEG2 = PNLGRP.PNLGRPNAME AND PRS.PORTAL_URI_SEG3 = PNLGRP.MARKET AND PRS.PORTAL_CREF_USGT = 'TARG')
      LEFT OUTER JOIN PSPRSMDEFN P1 ON PRS.PORTAL_PRNTOBJNAME = P1.PORTAL_OBJNAME AND PRS.PORTAL_NAME = P1.PORTAL_NAME)
      LEFT OUTER JOIN PSPRSMDEFN P2 ON P1.PORTAL_PRNTOBJNAME = P2.PORTAL_OBJNAME AND P1.PORTAL_NAME = P2.PORTAL_NAME)
      LEFT OUTER JOIN PSPRSMDEFN P3 ON P2.PORTAL_PRNTOBJNAME = P3.PORTAL_OBJNAME AND P2.PORTAL_NAME = P3.PORTAL_NAME)
      LEFT OUTER JOIN PSPRSMSYSATTRVL PRSATTR ON PRSATTR.PORTAL_NAME = PRS.PORTAL_NAME AND PRSATTR.PORTAL_OBJNAME = PRS.PORTAL_OBJNAME AND PRSATTR.PORTAL_ATTR_NAM = 'PORTAL_HIDE_FROM_NAV')
      LEFT OUTER JOIN PSPRSMSYSATTRVL PRSATTR1 ON PRSATTR1.PORTAL_NAME = PRS.PORTAL_NAME AND PRSATTR1.PORTAL_OBJNAME = PRS.PORTAL_OBJNAME AND PRSATTR1.PORTAL_ATTR_NAM LIKE 'CN_DISPLAYMODE_%')
WHERE 1 = 1
--  AND DBF.LENGTH > 4
--  AND DBF.FIELDTYPE IN (0, 1, 2, 3)
--  AND DBF.FORMAT = 4
--  AND DBF.OBJECTOWNERID NOT IN ('PPT', 'CCF', 'CCU', 'CEO', 'CEI', 'CEW', 'CLT', 'CPP', 'CTP', 'TTS')
  AND ((DBF.FIELDNAME LIKE '%EMPL%ID' OR DBF.FIELDNAME LIKE '%EMPL%' OR DBF.FIELDNAME LIKE '%PERSON%' OR DBF.FIELDNAME LIKE '%PERS%' OR DBF.FIELDNAME LIKE '%APPLICANT%'
     OR DBF.FIELDNAME LIKE '%TEAM%MEMBER%' OR DBF.FIELDNAME LIKE '%MEMBER%' OR DBF.FIELDNAME LIKE '%MANAGER%' OR DBF.FIELDNAME LIKE '%APPLID%' OR DBF.FIELDNAME LIKE '%EMP%ID%'
     OR DBF.FIELDNAME LIKE '%CRDMEM%' OR DBF.FIELDNAME LIKE '%APPROVER%' OR DBF.FIELDNAME LIKE '%CSTDN%' OR DBF.FIELDNAME LIKE '%MGR%' OR DBF.FIELDNAME LIKE '%STDNT%'
     OR DBF.FIELDNAME LIKE '%TEAM%MBR%' OR DBF.FIELDNAME LIKE '%TEAM%MBR%' OR DBF.FIELDNAME LIKE '%SUPERVISOR%' OR DBF.FIELDNAME LIKE '%CM_NAME%' OR DBF.FIELDNAME LIKE '%APP_IDNT%'
     OR DBF.FIELDNAME LIKE '%BIDDER%' OR DBF.FIELDNAME LIKE '%BIRTHDATE%' OR DBF.FIELDNAME LIKE '%ATTN_TO%' OR DBF.FIELDNAME LIKE '%MNGR%' OR DBF.FIELDNAME LIKE '%EMP%'
     OR DBF.FIELDNAME LIKE '%CONTACT%' OR DBF.FIELDNAME LIKE '%CORD_ID%')
    AND DBF.FIELDNAME NOT LIKE '%TEMPLATE%' AND DBF.FIELDNAME <> 'AE_APPLID' AND DBF.FIELDNAME <> 'AE_DO_APPLID')
--  AND DBF.FIELDNAME = 'EMPLID'
ORDER BY DBF.FIELDNAME, RECFLD.RECNAME, RECFLD.FIELDNUM;
