--Find Record Definition References
set pages 50000 lines 32767;
set verify off
set trimspool on;
set trimout on;
set sqlformat csv;
--set sqlformat ansiconsole;
--set termout off;
def RECNAME = ('HCR_HANDLE_WK', 'HCR_JOB_WK', 'HCR_ACK_WK', 'HCR_ERROR_WK', 'HCR_CAN_JOB_WK', 'HRS_CAND_UPD_WK', 'SAC_CANDIDATE', 'SP_EXT_TIME_HDR', 'AR_DEDUCTNS_RSP',
               'AR_DISPUTES_RSP', 'PA_SP_MSG', 'EX_AIRLINE_TKT', 'CC_CARD_DATA_EX', 'EX_EMC_CA_APR_H', 'EX_EMC_ER_APR_H', 'EX_EMC_TR_APR_H', 'PAY_ACKNOWLEDGE',
               'PAY_ISSUED', 'PAY_REQUEST', 'WRK_PROJ_TAO', 'PROJ_ACT_TEAM', 'PROJECT_TEAM', 'ACCOMPLISHMENTS', 'PERSONAL_DATA', 'EMAIL_ADDRESSES', 'PERSONAL_PHONE', 'PERS_DATA_EFFDT',
               'PERS_NID', 'RS_EVALUATIONS', 'COMPETENCIES', 'CITIZENSHIP', 'CITIZEN_PSSPRT', 'VISA_PMT_DATA', 'VISA_PMT_SUPPRT', 'RS_SCHED_TASK', 'RS_POOL_MEMBER', 'RS_SO_LINE_REC',
               'EMPL_PHOTO', 'EMPLOYMENT', 'JOB', 'BEN_PROG_PARTIC', 'COMPENSATION', 'JOB_JR', 'DIVERSITY', 'PRIORWORK_EXPER', 'DIRECT_DEPOSIT', 'DIR_DEP_DISTRIB', 'FO_ASGN_XREF',
               'TL_EMPL_DATA', 'FO_MC_ART_SEL', 'FO_RATE_ELEMENT');
  
SELECT DISTINCT 'Used_in_Activity', ACTIVITYNAME FROM PSMSGAGTDEFN WHERE SEARCHRECNAME IN &RECNAME ORDER BY ACTIVITYNAME;
SELECT DISTINCT 'Used_as_AUDIT_Rec', D.RECNAME FROM PSRECDEFN D WHERE D.AUDITRECNAME IN &RECNAME ORDER BY D.RECNAME;
SELECT DISTINCT 'Used_as_PARENT_Rec', D.RECNAME FROM PSRECDEFN D WHERE D.PARENTRECNAME IN &RECNAME ORDER BY D.RECNAME;
SELECT DISTINCT 'Used_as_Qry_Sec_Rec', D.RECNAME FROM PSRECDEFN D WHERE D.QRYSECRECNAME IN &RECNAME ORDER BY D.RECNAME;
SELECT DISTINCT 'Used_as_RLR_Rec', D.RECNAME FROM PSRECDEFN D WHERE D.RELLANGRECNAME IN &RECNAME ORDER BY D.RECNAME;
SELECT DISTINCT 'Used_in_Routing_Event_Workflow', E.RECNAME, E.ACTIVITYNAME, E.EVENTNAME FROM PSEVENTDEFN E WHERE E.RECNAME IN &RECNAME ORDER BY E.ACTIVITYNAME, E.EVENTNAME;
SELECT DISTINCT 'Used_in_FileLayout_Segments', FLDSEGNAME, FLDDEFNNAME FROM PSFLDSEGDEFN WHERE FLDSEGNAME IN &RECNAME ORDER BY FLDDEFNNAME;
SELECT DISTINCT 'Used_as_ADD_SearchRec', G.ADDSRCHRECNAME, G.PNLGRPNAME FROM PSPNLGRPDEFN G WHERE G.ADDSRCHRECNAME IN &RECNAME ORDER BY G.PNLGRPNAME;
SELECT DISTINCT 'Used_as_SearchRec', G.SEARCHRECNAME, G.PNLGRPNAME FROM PSPNLGRPDEFN G WHERE G.SEARCHRECNAME IN &RECNAME ORDER BY G.PNLGRPNAME;
SELECT DISTINCT 'Used_in_CI', I.BCNAME, I.RECNAME, I.FIELDNAME FROM PSBCITEM I WHERE I.RECNAME IN &RECNAME AND I.BCTYPE NOT IN (3, 6, 7) ORDER BY I.BCNAME;
SELECT DISTINCT 'Used_as_SearchRec_MENU', I.SEARCHRECNAME, I.MENUNAME FROM PSMENUITEM I WHERE I.SEARCHRECNAME IN &RECNAME ORDER BY I.MENUNAME;
SELECT DISTINCT 'Used_in_(Records)_in_Projects', I.OBJECTVALUE1, I.PROJECTNAME FROM PSPROJECTITEM I WHERE I.OBJECTTYPE = 0 AND I.OBJECTVALUE1 IN &RECNAME ORDER BY I.PROJECTNAME;
SELECT DISTINCT 'Used_in_BPA_MAP_Level', L.RECNAME, L.ACTIVITYNAME, L.EVENTNAME, L.MAPNAME FROM PSMAPLEVEL L WHERE L.RECNAME IN &RECNAME ORDER BY L.ACTIVITYNAME, L.EVENTNAME, L.MAPNAME;
SELECT DISTINCT 'Used_in_BPA_MAPRec', M.RECNAME, M.ACTIVITYNAME, M.EVENTNAME, M.MAPNAME FROM PSMAPRECFIELD M WHERE M.RECNAME IN &RECNAME ORDER BY M.ACTIVITYNAME, M.EVENTNAME, M.MAPNAME;
SELECT DISTINCT 'Used_in_BPA_MAP_Role', M.RECNAME, M.ACTIVITYNAME, M.EVENTNAME, M.MAPNAME FROM PSMAPROLEBIND M WHERE M.RECNAME IN &RECNAME ORDER BY M.ACTIVITYNAME, M.EVENTNAME, M.MAPNAME;
SELECT DISTINCT 'Used_as_IB_MessageRec', RECNAME, MSGNAME FROM PSMSGREC WHERE RECNAME IN &RECNAME ORDER BY MSGNAME;
SELECT DISTINCT 'Used_in_PeopleCode_Rec_REFNAME_PC', REFNAME, OBJECTID1, OBJECTVALUE1, OBJECTID2, OBJECTVALUE2, OBJECTID3, OBJECTVALUE3, OBJECTID4, OBJECTVALUE4, OBJECTID5, OBJECTVALUE5,
OBJECTID6, OBJECTVALUE6, OBJECTID7, OBJECTVALUE7, RECNAME FROM PSPCMNAME WHERE RECNAME = 'RECORD' AND REFNAME IN &RECNAME;
SELECT DISTINCT 'Used_in_PeopleCode_Rec_PC_References', RECNAME, OBJECTID1, OBJECTVALUE1, OBJECTID2, OBJECTVALUE2, OBJECTID3, OBJECTVALUE3, OBJECTID4, OBJECTVALUE4, OBJECTID5,
OBJECTVALUE5, OBJECTID6, OBJECTVALUE6, OBJECTID7, OBJECTVALUE7, REFNAME FROM PSPCMNAME WHERE RECNAME IN &RECNAME;
SELECT DISTINCT 'Used_as_PNL_Field', P.RECNAME, P.PNLNAME, P.FIELDNAME FROM PSPNLFIELD P WHERE P.RECNAME IN &RECNAME ORDER BY P.PNLNAME;
SELECT DISTINCT 'Used_in_PTF', RECNAME, PTTST_NAME FROM PSPTTSTCOMMAND WHERE RECNAME IN &RECNAME ORDER BY PTTST_NAME;
SELECT DISTINCT 'Used_in_Query_View_QRYRec', Q.RECNAME, Q.QRYNAME FROM PSQRYRECORD Q WHERE Q.RECNAME IN &RECNAME ORDER BY Q.QRYNAME;
SELECT DISTINCT 'Used_in_BPA_MAP_Event_Route', R.WLRECNAME, R.ACTIVITYNAME, R.EVENTNAME, R.ROUTENAME FROM PSEVENTROUTE R WHERE R.WLRECNAME IN &RECNAME
ORDER BY R.ACTIVITYNAME, R.EVENTNAME, R.ROUTENAME;
SELECT DISTINCT 'Used_in_BusPrcs_Name', R.RECNAME_CUR, R.BUSPROCNAME FROM PS_APPR_RULE_HDR R WHERE R.RECNAME_CUR IN &RECNAME ORDER BY R.BUSPROCNAME;
SELECT DISTINCT 'Used_in_OPT_Appl_Rec', R.RECNAME, R.PROBTYPE FROM PSOPTREC R WHERE R.RECNAME IN &RECNAME ORDER BY R.PROBTYPE;
SELECT DISTINCT 'Used_as_RecField_DEFRECNAME', R.RECNAME, R.FIELDNAME FROM PSRECFIELD R WHERE R.DEFRECNAME IN &RECNAME ORDER BY R.RECNAME;
SELECT DISTINCT 'Used_as_RecField_EDITTABLE', R.RECNAME, R.FIELDNAME FROM PSRECFIELD R WHERE R.EDITTABLE IN &RECNAME ORDER BY R.RECNAME;
SELECT DISTINCT 'Used_as_RecField_SUBREC', R.RECNAME, R.FIELDNAME FROM PSRECFIELD R WHERE R.FIELDNAME IN &RECNAME AND R.SUBRECORD = 'Y' ORDER BY R.RECNAME;
SELECT DISTINCT 'Used_in_Rec_Group_REC', RECNAME, REC_GROUP_ID FROM PS_REC_GROUP_REC WHERE RECNAME IN &RECNAME ORDER BY REC_GROUP_ID;
SELECT DISTINCT 'Used_as_AE_State_Rec', S.AE_STATE_RECNAME, S.AE_APPLID FROM PSAEAPPLSTATE S WHERE S.AE_STATE_RECNAME IN &RECNAME ORDER BY S.AE_APPLID;
SELECT DISTINCT 'Used_as_QRY_SecurityRec', S.QRYSECRECNAME, S.RECNAME FROM PSRECQRYSECRECS S WHERE S.QRYSECRECNAME IN &RECNAME ORDER BY S.RECNAME;
SELECT DISTINCT 'Used_as_AE_TempTable', T.RECNAME, T.AE_APPLID FROM PSAEAPPLTEMPTBL T WHERE T.RECNAME IN &RECNAME ORDER BY T.AE_APPLID;
SELECT DISTINCT 'Used_as_Panel_Tree_Cntrl_Rec', T.RECNAME, T.PNLNAME FROM PSPNLTREECTRL T WHERE T.RECNAME IN &RECNAME ORDER BY T.PNLNAME;
SELECT DISTINCT 'Used_as_TREE_DTL_Rec', B.DTL_RECNAME, TREE_NAME FROM PSTREEDEFN A, PSTREESTRCT B WHERE B.DTL_RECNAME IN &RECNAME AND A.TREE_STRCT_ID = B.TREE_STRCT_ID  ORDER BY TREE_NAME;
SELECT DISTINCT 'Used_as_TREE_LVL_Rec', B.LEVEL_RECNAME, TREE_NAME FROM PSTREEDEFN A, PSTREESTRCT B WHERE B.LEVEL_RECNAME IN &RECNAME AND A.TREE_STRCT_ID = B.TREE_STRCT_ID  ORDER BY TREE_NAME;
SELECT DISTINCT 'Used_as_TREE_NODE_Rec', B.NODE_RECNAME, TREE_NAME FROM PSTREEDEFN A, PSTREESTRCT B WHERE B.NODE_RECNAME IN &RECNAME AND A.TREE_STRCT_ID = B.TREE_STRCT_ID  ORDER BY TREE_NAME;
