--Find In SQL
--Replace PERSONAL_DATA with your record
SELECT SQLTEXT.SQLID, SQLD.OBJECTOWNERID, CASE SQLTEXT.SQLTYPE WHEN '0' THEN '0 - SQL Object' WHEN '2' THEN '2 - SQL View' ELSE 'Unknown' END AS "SQL Type", SQLTEXT.MARKET,
       CASE SQLTEXT.DBTYPE WHEN '1' THEN '1 - DB2/MVS' WHEN '2' THEN '2 - Oracle' WHEN '3' THEN '3 - Informix' WHEN '4' THEN '4 - DB2/UNIX' WHEN '6' THEN '6 - Sybase'
                           WHEN '7' THEN '7 - Microsoft' WHEN ' ' THEN 'default'
       ELSE 'Unknown' END "DB Type", SQLTEXT.EFFDT, SQLTEXT.SEQNUM, SQLTEXT.SQLTEXT
FROM (PSSQLTEXTDEFN SQLTEXT LEFT OUTER JOIN PSSQLDEFN SQLD ON SQLD.SQLID = SQLTEXT.SQLID AND SQLD.SQLTYPE = SQLTEXT.SQLTYPE)
WHERE SQLTEXT.SQLTYPE IN('0', '2') AND UPPER(SQLTEXT.SQLTEXT) LIKE UPPER('%PERSONAL_DATA%') ORDER BY SQLTEXT.SQLID, SQLTEXT.SQLTYPE;
