set pages 50000 lines 32767;
set verify off
set trimspool on;
set trimout on;
set sqlformat csv;
--set sqlformat ansiconsole;
--set termout off;
def FIELDNAME = ('EMPLID')
 
SELECT DISTINCT 'Used_in_CUBES', ACEMODELID FROM PSACECUBECOLMAP WHERE FIELDNAME IN &FIELDNAME OR ACEAGGRFIELDNAME IN &FIELDNAME ORDER BY ACEMODELID;
SELECT DISTINCT 'Used_in_Queue', CHNLNAME FROM PSSUBCHNL WHERE FIELDNAME IN &FIELDNAME ORDER BY CHNLNAME;
SELECT DISTINCT 'Used_as_SetCntrlFld_Rec', D.RECNAME FROM PSRECDEFN D WHERE D.SETCNTRLFLD IN &FIELDNAME ORDER BY D.RECNAME;
SELECT DISTINCT 'Uses_in_Analytic_Type', F.PROBTYPE, F.RECNAME FROM PSOPTFIELD F WHERE F.FIELDNAME IN &FIELDNAME ORDER BY F.PROBTYPE;
SELECT DISTINCT 'Used_in_FileLayout', FLDDEFNNAME FROM PSFLDFIELDDEFN WHERE FLDFIELDNAME IN &FIELDNAME ORDER BY FLDDEFNNAME;
SELECT DISTINCT 'Used_in_Projects', I.PROJECTNAME FROM PSPROJECTITEM I WHERE I.OBJECTTYPE = 2 AND I.OBJECTVALUE1 IN &FIELDNAME ORDER BY I.PROJECTNAME;
SELECT DISTINCT 'Used_as_MsgRecFldOverride', MSGNAME FROM PSMSGFLDOVR WHERE FIELDNAME IN &FIELDNAME ORDER BY MSGNAME;
SELECT DISTINCT 'Used_in_PeopleCode_Field_REFNAME_PC', OBJECTID1, OBJECTVALUE1, OBJECTID2, OBJECTVALUE2, OBJECTID3, OBJECTVALUE3, OBJECTID4, OBJECTVALUE4, OBJECTID5, OBJECTVALUE5, OBJECTID6,
       OBJECTVALUE6, OBJECTID7, OBJECTVALUE7, RECNAME FROM PSPCMNAME WHERE REFNAME IN &FIELDNAME AND
       RECNAME NOT IN ('PANEL','RECORD','MENUNAME','BARNAME','ITEMNAME','PANELGROUP','BUSPROCESS','BUSACTIVITY','BUSEVENT','SCROLL','SQL','MESSAGE','FILELAYOUT','COMPONENT','INTERLINK','IMAGE');
SELECT DISTINCT 'Used_in_PTF', PTTST_NAME FROM PSPTTSTCOMMAND WHERE FIELDNAME IN &FIELDNAME ORDER BY PTTST_NAME;
SELECT DISTINCT 'Used_as_QryField', Q.QRYNAME FROM PSQRYFIELD Q WHERE Q.FIELDNAME IN &FIELDNAME ORDER BY Q.QRYNAME;
SELECT DISTINCT 'Used_in_Records', R.RECNAME, R.FIELDNAME FROM PSRECFIELD R WHERE R.FIELDNAME IN &FIELDNAME ORDER BY R.RECNAME;
SELECT DISTINCT 'Used_as_SetCntrlFld_Field', R.RECNAME, R.FIELDNAME FROM PSRECFIELD R WHERE R.SETCNTRLFLD IN &FIELDNAME ORDER BY R.RECNAME;
SELECT 'Used_in_CI', I.BCNAME FROM PSBCITEM I WHERE I.FIELDNAME IN &FIELDNAME ORDER BY I.BCNAME;
SELECT 'Used_on_Page', P.PNLNAME, P.FIELDNAME FROM PSPNLFIELD P WHERE P.FIELDNAME IN &FIELDNAME ORDER BY P.PNLNAME;
