--Find In Record
SELECT P.OBJECTID1, P.OBJECTVALUE1, P.OBJECTID2, P.OBJECTVALUE2, P.OBJECTID3, P.OBJECTVALUE3, P.OBJECTID4, P.OBJECTVALUE4, P.OBJECTID5, P.OBJECTVALUE5, P.OBJECTID6, P.OBJECTVALUE6,
       P.OBJECTID7, P.OBJECTVALUE7, D.RECNAME, D.FIELDCOUNT, D.INDEXCOUNT, D.RECTYPE, D.RELLANGRECNAME, D.RECDESCR, D.PARENTRECNAME, D.SQLTABLENAME, D.BUILDSEQNO, D.OBJECTOWNERID
FROM PSPCMTXT P, PSRECDEFN D
WHERE P.OBJECTID1 IN (1,3,9,10,60,66,74,104,65)
  AND P.OBJECTVALUE1 = D.RECNAME
  AND D.RECTYPE IN (0,1,2,3,5,6,7)
  AND UPPER(P.PCTEXT) LIKE UPPER('%PERSONAL_DATA%');
