CREATE TABLE PS_FSCM_811FIELDS_TBL
AS
SELECT RECFLD.RECNAME "Record Name",
       CASE(NVL(RECD.RECTYPE, 99)) WHEN 0 THEN '0 - SQL Table' WHEN 1 THEN '1 - SQL View' WHEN 2 THEN '2 - Work Record' WHEN 3 THEN '3 - Sub Record' WHEN 5 THEN '5 - Dynamic View'
                                   WHEN 6 THEN '6 - Query View' WHEN 7 THEN '7 - Temporary Table'
       ELSE 'Excluded Record or Deleted' END AS "Record Type", RECFLD.FIELDNAME "Record Field Name",
       CASE DBF.FIELDTYPE
         WHEN 0 THEN '0 - Char' WHEN 1 THEN '1 - Long Char' WHEN 2 THEN '2 - NBR' WHEN 3 THEN '3 - Sign NBR' WHEN 4 THEN '4 - Date' WHEN 5 THEN '5 - Time' WHEN 6 THEN '6 - Dttm'
         WHEN 7 THEN '7 - Img' WHEN 8 THEN '8 - Img/Attch' WHEN 9 THEN '9 - Img/Ref'
       ELSE 'Unknown' END "DB Field Type", DBF.LENGTH, RECFLD.RECNAME_PARENT, RECFLD.DEFRECNAME, RECFLD.EDITTABLE,
       RECD.OBJECTOWNERID || ' - ' || X1.XLATLONGNAME AS "Record Object Ident", PNLD.OBJECTOWNERID || ' - ' || X2.XLATLONGNAME AS "Page Object Ident", PNLF.PNLNAME "Page Name",
       PNLD.DESCR "Page Description",
       CASE PNLD.PNLTYPE WHEN 0 THEN 'Page' WHEN 1 THEN 'Subpage' WHEN 2 THEN 'Secondary Page' WHEN 3 THEN 'Popup Page' WHEN 4 THEN 'NUI Header Page' WHEN 5 THEN 'NUI Side Page 1'
                         WHEN 6 THEN 'NUI Footer Page' WHEN 7 THEN 'NUI Layout Page' WHEN 8 THEN 'NUI Search Page' WHEN 9 THEN 'NUI Prompt Page' WHEN 10 THEN 'NUI Master Detail Target Page'
                         WHEN 11 THEN 'NUI Side Page 2'
       ELSE 'Unknown' END "Page Type", PNLF.PNLFIELDNAME "Page Field Name",
       CASE PNLF.FIELDTYPE
         WHEN 0 THEN 'Text' WHEN 1 THEN 'Frame' WHEN 2 THEN 'Group Box' WHEN 3 THEN 'Static Image' WHEN 4 THEN 'Edit Box' WHEN 5 THEN 'Drop Down List' WHEN 6 THEN 'Long Edit Box'
         WHEN 7 THEN 'Check Box' WHEN 8 THEN 'Radio Button' WHEN 9 THEN 'Image' WHEN 10 THEN 'Scroll Bar' WHEN 11 THEN 'Subpage' WHEN 12 THEN 'Push Button/Link - PeopleCode'
         WHEN 13 THEN 'Push Button/Link - Scroll Action' WHEN 14 THEN 'Push Button/Link - Toolbar Action' WHEN 15 THEN 'Push Button/Link - External Link'
         WHEN 16 THEN 'Push Button/Link - Internal Link' WHEN 17 THEN 'Push Button/Link - Process' WHEN 18 THEN 'SecPage' WHEN 19 THEN 'Grid' WHEN 20 THEN 'Tree'
         WHEN 21 THEN 'Push Button/Link - Secondary Page' WHEN 23 THEN 'Horizontal Rule' WHEN 24 THEN 'Tab Separator' WHEN 25 THEN 'HTML Area' WHEN 26 THEN 'Push Button/Link - Prompt Action'
         WHEN 27 THEN 'Scroll Area' WHEN 29 THEN 'Push Button/Link - Page Anchor' WHEN 30 THEN 'Chart' WHEN 31 THEN 'Push Button/Link - Instant Message Action' WHEN 32 THEN 'Analytic Grid'
       ELSE 'Unknown' END "PNL Field Type",
       CASE WHEN PNLF.PNLNAME IS NOT NULL THEN CASE WHEN BITAND(PNLF.FIELDUSE, 1) = 1 THEN 'Display Only' WHEN BITAND(PNLF.FIELDUSE, 1) <> 1 THEN 'XXXX' END ELSE 'Unknown' END
       AS "Display Only",          
       CASE WHEN PNLF.PNLNAME IS NOT NULL THEN CASE WHEN BITAND(PNLF.FIELDUSE, 2) = 2 THEN 'Invisible' WHEN BITAND(PNLF.FIELDUSE, 2) <> 2 THEN 'Visible' END ELSE 'Unknown' END
       AS "Visible Y/N",
       PNLF.LABEL_ID "Label ID", PNLF.LBLTEXT "Label Text",
       CAST(' ' AS VARCHAR2(100)) "Category", CAST(' ' AS VARCHAR2(100)) "Classification", CAST(' ' AS VARCHAR2(3)) "Personally Identifiable", CAST(' ' AS VARCHAR2(3)) "Sensitive",
       PNLF.PNLFLDID, PNLF.FIELDNUM, PNLF.DSPLFORMAT, PNLF.ASSOCFIELDNUM,
       PNLGRP.PNLGRPNAME "Component Name", PNLGRP.MARKET "Comp MKT", PRS.PORTAL_NAME "Portal Name",
       P3.PORTAL_LABEL || ' > ' || P2.PORTAL_LABEL || ' > ' || P1.PORTAL_LABEL || ' > ' || PRS.PORTAL_LABEL "Navigation", PRS.PORTAL_OBJNAME "Portal Object Name",
       PRS.PORTAL_PRODUCT "CREF Product", PRS.OBJECTOWNERID "Portal Object Ident", PRS.PORTAL_URI_SEG1 "Portal Registry Menu Name", PRS.PORTAL_URLTEXT "PSP URL",
       CASE WHEN PRS.PORTAL_OBJNAME IS NOT NULL THEN
         CASE WHEN dbms_lob.instr(PRSATTR.PORTAL_ATTR_VAL, 'TRUE') > 0 THEN 'Hidden' ELSE 'Visible' END ELSE 'Unknown' END "IsCREFHidden",
       PNLGRP.SUBITEMNUM "Page Tab#", CASE PNLGRP.HIDDEN WHEN 0 THEN '0 - Visible' WHEN 1 THEN '1 - Hidden' ELSE 'Unkown' END "IsPageHidden",
       MNU.MENUNAME "MENUITEM Menu Name", MNU.BARNAME "Menu Bar Name", MNU.ITEMNAME "Item Name", MNU.ITEMLABEL "Item Label", PRSATTR1.PORTAL_ATTR_VAL "Conditional Nav Attr Value"
FROM PSRECFIELDDB RECFLD, PSDBFIELD DBF, (PSRECDEFN RECD LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'OBJECTOWNERID' AND X1.FIELDVALUE = RECD.OBJECTOWNERID AND X1.EFF_STATUS = 'A'),
     ((((((((PSPNLFIELD PNLF LEFT OUTER JOIN PSPNLGROUP PNLGRP ON PNLF.PNLNAME = PNLGRP.PNLNAME)
        LEFT OUTER JOIN PSMENUITEM MNU ON PNLGRP.PNLGRPNAME = MNU.PNLGRPNAME)
        LEFT OUTER JOIN PSPRSMDEFN PRS ON PRS.PORTAL_URI_SEG2 = PNLGRP.PNLGRPNAME AND PRS.PORTAL_CREF_USGT = 'TARG')
      LEFT OUTER JOIN PSPRSMDEFN P1 ON PRS.PORTAL_PRNTOBJNAME = P1.PORTAL_OBJNAME AND PRS.PORTAL_NAME = P1.PORTAL_NAME)
      LEFT OUTER JOIN PSPRSMDEFN P2 ON P1.PORTAL_PRNTOBJNAME = P2.PORTAL_OBJNAME AND P1.PORTAL_NAME = P2.PORTAL_NAME)
      LEFT OUTER JOIN PSPRSMDEFN P3 ON P2.PORTAL_PRNTOBJNAME = P3.PORTAL_OBJNAME AND P2.PORTAL_NAME = P3.PORTAL_NAME)
      LEFT OUTER JOIN PSPRSMSYSATTRVL PRSATTR ON PRSATTR.PORTAL_NAME = PRS.PORTAL_NAME AND PRSATTR.PORTAL_OBJNAME = PRS.PORTAL_OBJNAME AND PRSATTR.PORTAL_ATTR_NAM = 'PORTAL_HIDE_FROM_NAV')
      LEFT OUTER JOIN PSPRSMSYSATTRVL PRSATTR1 ON PRSATTR1.PORTAL_NAME = PRS.PORTAL_NAME AND PRSATTR1.PORTAL_OBJNAME = PRS.PORTAL_OBJNAME AND PRSATTR1.PORTAL_ATTR_NAM LIKE 'CN_DISPLAYMODE_%'),
      (PSPNLDEFN PNLD LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'OBJECTOWNERID' AND X2.FIELDVALUE = PNLD.OBJECTOWNERID AND X2.EFF_STATUS = 'A')
WHERE 1 = 1
  AND RECFLD.FIELDNAME = DBF.FIELDNAME
  AND RECFLD.RECNAME = RECD.RECNAME
  AND RECD.OBJECTOWNERID NOT IN ('PPT', 'CCF', 'CCU', 'CEO', 'CEI', 'CEW', 'CLT', 'CPP', 'CTP', 'TTS')
  AND RECFLD.RECNAME = PNLF.RECNAME
  AND RECFLD.FIELDNAME = PNLF.FIELDNAME
  AND PNLF.PNLNAME = PNLD.PNLNAME
  AND (RECFLD.RECNAME, RECFLD.FIELDNAME) IN (SELECT DISTINCT X.RECNM_D, X.FIELDNAME
                                         FROM (SELECT DISTINCT RECFLD.RECNAME, RECFLD.FIELDNAME, RECD.RECNAME RECNM_D FROM PSRECFIELDDB RECFLD, PSRECDEFN RECD
                          WHERE RECFLD.RECNAME = RECD.RECNAME AND RECD.RECTYPE <> 7 AND RECD.OBJECTOWNERID NOT IN ('PPT', 'CCF', 'CCU', 'CEO', 'CEI', 'CEW', 'CLT', 'CPP', 'CTP', 'TTS')
                           AND (RECFLD.FIELDNAME IN (SELECT XX.FIELDNAME FROM PS_PP_FLD_LIST_TBL XX))
                           AND EXISTS (SELECT 'X' FROM PSPNLFIELD PNLF WHERE PNLF.RECNAME = RECFLD.RECNAME AND PNLF.FIELDNAME = RECFLD.FIELDNAME))X)
  AND RECFLD.RECNAME NOT IN ('PC_COMPRESS_TPL', 'PC_PM_SUMM_TMPL', 'PC_ICLIENT_WRK', 'RUN_CNTL_PC')
  AND RECFLD.RECNAME NOT LIKE 'INSTALLATION%'
  AND DBF.FIELDTYPE IN (0, 2, 4)
  AND DBF.LENGTH > 4
--  AND (RECFLD.FIELDNAME NOT LIKE 'BUSINESS_UNIT%' AND RECFLD.FIELDNAME NOT LIKE '%SETID%' AND RECFLD.FIELDNAME NOT LIKE '%CURRENCY_CD%')
  AND RECFLD.FIELDNAME NOT IN (SELECT FIELDNAME FROM PS_FS_CF_TEMPLATE)
ORDER BY RECFLD.RECNAME, RECFLD.FIELDNUM;
 
 
--List of fields
SELECT * FROM PS_PP_FLD_LIST_TBL ORDER BY 1;
