--Modified Version as per the PDF output
SELECT A.BASE_CURRENCY, A.PROJECT_ID, A.BUDGET_PERIOD, B.KK_TRAN_DT, B.KK_SOURCE_TRAN, B.BUSINESS_UNIT, B.JOURNAL_ID, B.JOURNAL_DATE,
            B.UNPOST_SEQ, C.JOURNAL_LINE, A.LEDGER, C.LEDGER, B.CUST_ID, B.ITEM, B.ITEM_LINE, B.DEPOSIT_ID, B.PAYMENT_SEQ_NUM, B.VOUCHER_ID, C.VOUCHER_LINE_NUM, B.PO_ID, B.REQ_ID, 
            C.LINE_NBR, C.DISTRIB_LINE_NUM, B.ACCOUNTING_DT, C.ACCTG_LINE_NO, B.INVOICE, C.LINE_SEQ_NUM, B.ACTIVITY_ID, B.RESOURCE_ID, B.EMPLID, B.TRANS_NBR,
            A.MONETARY_AMOUNT, C.PROJECT_ID, A.KK_TRAN_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2, E.LEDGER_TYPE_KK, J.LEDGER_GROUP_TYPE,            
            CASE WHEN (E.LEDGER_TYPE_KK = 1 AND J.LEDGER_GROUP_TYPE = 'R') THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Total Recognized Amount",
            CASE WHEN E.LEDGER_TYPE_KK = 4 THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Total Collected Amount",
            CASE WHEN E.LEDGER_TYPE_KK = 3 THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Pre Encumbered Amount",
            CASE WHEN E.LEDGER_TYPE_KK = 2 THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Encumbered Amount",
            CASE WHEN (E.LEDGER_TYPE_KK = 1 AND J.LEDGER_GROUP_TYPE = 'E') THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Expended Amount"
FROM PS_KK_ACTIVITY_LOG A, PS_KK_SOURCE_HDR B, PS_KK_SOURCE_LN C, PS_LED_GRP_LED_TBL E, PS_KK_BUDGET_TYPE H, PS_SET_CNTRL_REC I, PS_LED_GRP_TBL J
WHERE A.KK_TRAN_ID = B.KK_TRAN_ID
    AND A.KK_TRAN_DT = B.KK_TRAN_DT
    AND B.KK_TRAN_ID = C.KK_TRAN_ID
    AND B.KK_TRAN_DT = C.KK_TRAN_DT
    AND A.KK_TRAN_LN = C.KK_TRAN_LN
    AND A.LEDGER = E.LEDGER
    AND E.SETID = I.SETID
    AND H.EFFDT = (SELECT MAX(H_ED.EFFDT) FROM PS_KK_BUDGET_TYPE H_ED WHERE H.SETID1 = H_ED.SETID1 AND H.LEDGER_GROUP = H_ED.LEDGER_GROUP AND H_ED.EFFDT <= SYSDATE) 
    AND H.LEDGER_GROUP = E.LEDGER_GROUP
    AND H.SETID1 = E.SETID
    AND E.SETID = J.SETID
    AND E.LEDGER_GROUP = J.LEDGER_GROUP
    AND I.SETCNTRLVALUE = A.BUSINESS_UNIT    
    AND I.RECNAME = 'LED_GRP_LED_TBL'
    AND A.BALANCING_LINE <> 'Y'
    AND (A.BUSINESS_UNIT = 'UNUNI' OR A.BUSINESS_UNIT LIKE '6%')    
    AND A.BUDGET_PERIOD IN ('2012', '2013')
    AND A.PROJECT_ID IN ('00064159')
    --AND A.ACCOUNT IN ('B7000', 'B7100')
    --AND A.DEPTID = 'B0112'
    --AND B.KK_SOURCE_TRAN = 'AP_ACCT_LN'
    AND A.LEDGER_GROUP = 'DET_UU'    
ORDER BY 2,4;
