--Record View for list of PSJob accessible by user based on component security
SELECT * FROM PS_PTRCJOBSEC_VW WHERE USERID = 'david.birkett' ORDER BY 1,2,3;
--Expanded PTRCJOBSEC_VW
SELECT A.OPRID, A.PNLGRPNAME, B.PRCSJOBNAME 
FROM PS_PTRCUSERPAGESEC A, PS_PRCSJOBPNL B 
WHERE A.PNLGRPNAME = B.PNLGRPNAME
    AND A.OPRID = 'prakash.prashant'
ORDER BY 1,2,3;

--list of processes accessible by user based on component security
SELECT DISTINCT A.OPRID, A.PNLGRPNAME, B.PRCSNAME
FROM PS_PTRCUSERPAGESEC A, PS_PRCSDEFNPNL B
WHERE A.PNLGRPNAME = B.PNLGRPNAME
    AND A.OPRID = 'prakash.prashant'
    --AND B.PRCSNAME = 'FS_BP'
ORDER BY 1,2,3;

--User's Component Security
SELECT * FROM PS_PTRCJOBSEC_VW WHERE USERID = 'prakash.prashant' ORDER BY 1,2,3;

--Modified and expanded PTRCJOBSEC_VW
SELECT DISTINCT A.OPRID, A.OPRDEFNDESC, B.CLASSID, C.ROLENAME, D.MENUNAME, G.BARNAME, G.ITEMNAME, G.ITEMLABEL, G.PNLGRPNAME,
CASE E.AUTHORIZEDACTIONS
    WHEN 1 THEN 'Add'
    WHEN 2 THEN 'Update/Display'
    WHEN 3 THEN 'Add, Update/Display'
    WHEN 4 THEN 'Update/Display All'
    WHEN 5 THEN 'Add, Update/Display All'
    WHEN 6 THEN 'Update/Display, Update/Display All'
    WHEN 7 THEN 'Add, Update/Display, Update/Display All'
    WHEN 8 THEN 'Correction'
    WHEN 9 THEN 'Add, Correction'
    WHEN 10 THEN 'Update/Display, Correction'
    WHEN 11 THEN 'Add, Update/Display, Correction'
    WHEN 12 THEN 'Update/Display All, Correction'
    WHEN 13 THEN 'Add, Update/Display All, Correction'
    WHEN 14 THEN 'Update/Display, Update/Display All, Correction'
    WHEN 15 THEN 'Add, Update/Display, Update/Display All, Correction'
    ELSE 'SPECIAL' END AS "Authorized Actions", E.AUTHORIZEDACTIONS
FROM PSOPRDEFN A, PSROLECLASS B, PSROLEUSER C, PSAUTHITEM D, PSPGEACCESSDESC E, PSPNLGROUP F, PSMENUITEM G 
WHERE B.ROLENAME = C.ROLENAME 
    AND D.MENUNAME = G.MENUNAME 
    AND D.BARNAME = G.BARNAME 
    AND D.BARITEMNAME = G.ITEMNAME 
    AND F.PNLGRPNAME = G.PNLGRPNAME 
    AND A.OPRID = C.ROLEUSER 
    AND B.CLASSID = D.CLASSID 
    AND D.MENUNAME NOT IN ('APPLICATION_DESIGNER','CLIENTPROCESS','DATA_MOVER','IMPORT_MANAGER','OBJECT_SECURITY','QUERY') 
    AND D.MENUNAME NOT LIKE 'WEBLIB%' 
    AND D.AUTHORIZEDACTIONS = E.AUTHORIZEDACTIONS
    AND A.OPRID = 'prakash.prashant'
    AND B.ROLENAME = 'UN_AM_CONFIG_ADMIN'
ORDER BY 1,2,3,4,5,6,7,9,10;

--Processes (includes PSJobs as well) accessible by User
SELECT * FROM PS_PTRCPRCSLST WHERE OPRID = 'prakash.prashant';
SELECT DISTINCT PRCSNAME, PRCSJOBNAME FROM PS_PTRCPRCSLST WHERE PRCSNAME LIKE 'APS8001%';
SELECT * FROM PS_PTRCPRCSLST WHERE OPRID = 'david.birkett';
SELECT * FROM PS_PTRCPRCSLST WHERE OPRID = 'jack.noordhuizen';
SELECT * FROM PS_PTRCPRCSLST WHERE OPRID = 'huey-miin.lim';

--View 1 for Processes
SELECT DISTINCT A.OPRID, A.OPRDEFNDESC, B.CLASSID, C.ROLENAME, D.MENUNAME, G.BARNAME, G.ITEMNAME, G.ITEMLABEL, G.PNLGRPNAME, PR.PRCSNAME,
CASE E.AUTHORIZEDACTIONS
    WHEN 1 THEN 'Add'
    WHEN 2 THEN 'Update/Display'
    WHEN 3 THEN 'Add, Update/Display'
    WHEN 4 THEN 'Update/Display All'
    WHEN 5 THEN 'Add, Update/Display All'
    WHEN 6 THEN 'Update/Display, Update/Display All'
    WHEN 7 THEN 'Add, Update/Display, Update/Display All'
    WHEN 8 THEN 'Correction'
    WHEN 9 THEN 'Add, Correction'
    WHEN 10 THEN 'Update/Display, Correction'
    WHEN 11 THEN 'Add, Update/Display, Correction'
    WHEN 12 THEN 'Update/Display All, Correction'
    WHEN 13 THEN 'Add, Update/Display All, Correction'
    WHEN 14 THEN 'Update/Display, Update/Display All, Correction'
    WHEN 15 THEN 'Add, Update/Display, Update/Display All, Correction'
    ELSE 'SPECIAL' END AS "Authorized Actions", E.AUTHORIZEDACTIONS
FROM PSOPRDEFN A, PSROLECLASS B, PSROLEUSER C, PSAUTHITEM D, PSPGEACCESSDESC E, PSPNLGROUP F, PSMENUITEM G, PS_PRCSDEFNPNL PR
WHERE B.ROLENAME = C.ROLENAME 
    AND D.MENUNAME = G.MENUNAME 
    AND D.BARNAME = G.BARNAME 
    AND D.BARITEMNAME = G.ITEMNAME 
    AND F.PNLGRPNAME = G.PNLGRPNAME 
    AND A.OPRID = C.ROLEUSER 
    AND B.CLASSID = D.CLASSID 
    AND D.MENUNAME NOT IN ('APPLICATION_DESIGNER','CLIENTPROCESS','DATA_MOVER','IMPORT_MANAGER','OBJECT_SECURITY','QUERY') 
    AND D.MENUNAME NOT LIKE 'WEBLIB%' 
    AND D.AUTHORIZEDACTIONS = E.AUTHORIZEDACTIONS
    AND F.PNLGRPNAME = PR.PNLGRPNAME
    AND A.OPRID = 'prakash.prashant'
    --AND PR.PRCSNAME = 'AP_MATCH'
ORDER BY 1,2,3,4,5,6,7,9,10;

--View 1 without the Case statement
SELECT DISTINCT A.OPRID, A.OPRDEFNDESC, B.CLASSID, C.ROLENAME, D.MENUNAME, G.BARNAME, G.ITEMNAME, G.ITEMLABEL, G.PNLGRPNAME, PR.PRCSNAME
FROM PSOPRDEFN A, PSROLECLASS B, PSROLEUSER C, PSAUTHITEM D, PSPGEACCESSDESC E, PSPNLGROUP F, PSMENUITEM G, PS_PRCSDEFNPNL PR
WHERE B.ROLENAME = C.ROLENAME 
    AND D.MENUNAME = G.MENUNAME 
    AND D.BARNAME = G.BARNAME 
    AND D.BARITEMNAME = G.ITEMNAME 
    AND F.PNLGRPNAME = G.PNLGRPNAME 
    AND A.OPRID = C.ROLEUSER 
    AND B.CLASSID = D.CLASSID 
    AND D.MENUNAME NOT IN ('APPLICATION_DESIGNER','CLIENTPROCESS','DATA_MOVER','IMPORT_MANAGER','OBJECT_SECURITY','QUERY') 
    AND D.MENUNAME NOT LIKE 'WEBLIB%' 
    AND D.AUTHORIZEDACTIONS = E.AUTHORIZEDACTIONS
    AND F.PNLGRPNAME = PR.PNLGRPNAME
    AND A.OPRID = 'jack.noordhuizen'
    --AND PR.PRCSNAME = 'AP_MATCH'
ORDER BY 1,2,3,4,5,6,7,9,10;

--View 2 for PSJobs
SELECT DISTINCT A.OPRID, A.OPRDEFNDESC, B.CLASSID, C.ROLENAME, D.MENUNAME, G.BARNAME, G.ITEMNAME, G.ITEMLABEL, G.PNLGRPNAME, PR.PRCSJOBNAME,
CASE E.AUTHORIZEDACTIONS
    WHEN 1 THEN 'Add'
    WHEN 2 THEN 'Update/Display'
    WHEN 3 THEN 'Add, Update/Display'
    WHEN 4 THEN 'Update/Display All'
    WHEN 5 THEN 'Add, Update/Display All'
    WHEN 6 THEN 'Update/Display, Update/Display All'
    WHEN 7 THEN 'Add, Update/Display, Update/Display All'
    WHEN 8 THEN 'Correction'
    WHEN 9 THEN 'Add, Correction'
    WHEN 10 THEN 'Update/Display, Correction'
    WHEN 11 THEN 'Add, Update/Display, Correction'
    WHEN 12 THEN 'Update/Display All, Correction'
    WHEN 13 THEN 'Add, Update/Display All, Correction'
    WHEN 14 THEN 'Update/Display, Update/Display All, Correction'
    WHEN 15 THEN 'Add, Update/Display, Update/Display All, Correction'
    ELSE 'SPECIAL' END AS "Authorized Actions", E.AUTHORIZEDACTIONS
FROM PSOPRDEFN A, PSROLECLASS B, PSROLEUSER C, PSAUTHITEM D, PSPGEACCESSDESC E, PSPNLGROUP F, PSMENUITEM G, PS_PRCSJOBPNL PR
WHERE B.ROLENAME = C.ROLENAME 
    AND D.MENUNAME = G.MENUNAME 
    AND D.BARNAME = G.BARNAME 
    AND D.BARITEMNAME = G.ITEMNAME 
    AND F.PNLGRPNAME = G.PNLGRPNAME 
    AND A.OPRID = C.ROLEUSER 
    AND B.CLASSID = D.CLASSID 
    AND D.MENUNAME NOT IN ('APPLICATION_DESIGNER','CLIENTPROCESS','DATA_MOVER','IMPORT_MANAGER','OBJECT_SECURITY','QUERY') 
    AND D.MENUNAME NOT LIKE 'WEBLIB%' 
    AND D.AUTHORIZEDACTIONS = E.AUTHORIZEDACTIONS
    AND F.PNLGRPNAME = PR.PNLGRPNAME
    AND A.OPRID = 'prakash.prashant'
ORDER BY 1,2,3,4,5,6,7,9,10;
