--Project Details from KK
---------------------------------------------
--STEP 1
--Run this SQL and verify against Budget Overview Page
--This Query is run for AX1_UU and REV_UU aka Associated Budgets
--To find Associated Expense Budget Ledger, query PS_KK_BUDGET_TYPE
SELECT X.LEDGER_GROUP, X.BUDGET_PERIOD, X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2, X.ACTIVITY_ID,
       SUM(X.REV_BUD) "Total Revenue Budgeted Amount", SUM(X.RECOG) "Total Recognized Amount", SUM(X.COLL) "Total Collected Amount",
       SUM(X.EXP_BUD) "Total Expense Budgeted Amount", SUM(X.EXP) "Expended Amount", SUM(X.ENC) "Encumbered Amount", SUM(X.PRE_ENC) "Pre Encumbered Amount",
       SUM((X.EXP_BUD + X.COLL) - (X.EXP + X.ENC)) AS "Available Budget"
FROM
(SELECT E.LEDGER_GROUP, A.BUDGET_PERIOD, A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2, A.ACTIVITY_ID, 
        --E.LEDGER_TYPE_KK, J.LEDGER_GROUP_TYPE,
        --CASE WHEN E.LEDGER_TYPE_KK = 0 THEN (1 * SUM(A.POSTED_TOTAL_AMT)) ELSE 0 END AS BUD,
        CASE WHEN (E.LEDGER_TYPE_KK = 0 AND H.BUDG_TYPE = 'E') THEN (-1 * SUM(A.POSTED_TOTAL_AMT)) ELSE 0 END AS EXP_BUD,
        CASE WHEN (E.LEDGER_TYPE_KK = 0 AND H.BUDG_TYPE = 'R') THEN (1 * SUM(A.POSTED_TOTAL_AMT)) ELSE 0 END AS REV_BUD,
        CASE WHEN (E.LEDGER_TYPE_KK = 1 AND J.LEDGER_GROUP_TYPE = 'R') THEN (1 * SUM(A.POSTED_TOTAL_AMT)) ELSE 0 END AS RECOG,
        CASE WHEN E.LEDGER_TYPE_KK = 4 THEN (-1 * SUM(A.POSTED_TOTAL_AMT)) ELSE 0 END AS COLL,
        CASE WHEN E.LEDGER_TYPE_KK = 3 THEN (1 * SUM(A.POSTED_TOTAL_AMT)) ELSE 0 END AS PRE_ENC,
        CASE WHEN E.LEDGER_TYPE_KK = 2 THEN (1 * SUM(A.POSTED_TOTAL_AMT)) ELSE 0 END AS ENC,
        CASE WHEN (E.LEDGER_TYPE_KK = 1 AND J.LEDGER_GROUP_TYPE = 'E') THEN (1 * SUM(A.POSTED_TOTAL_AMT)) ELSE 0 END AS EXP
FROM PS_LEDGER_KK A, PS_LED_GRP_LED_TBL E, PS_KK_BUDGET_TYPE H, PS_SET_CNTRL_REC I, PS_LED_GRP_TBL J
WHERE A.LEDGER = E.LEDGER
    AND A.CURRENCY_CD = A.BASE_CURRENCY
    AND E.SETID = I.SETID
    AND H.EFFDT = (SELECT MAX(H_ED.EFFDT) FROM PS_KK_BUDGET_TYPE H_ED WHERE H.SETID1 = H_ED.SETID1 AND H.LEDGER_GROUP = H_ED.LEDGER_GROUP AND H_ED.EFFDT <= SYSDATE) 
    AND H.LEDGER_GROUP = E.LEDGER_GROUP
    AND H.SETID1 = E.SETID
    AND E.SETID = J.SETID
    AND E.LEDGER_GROUP = J.LEDGER_GROUP
    AND I.SETCNTRLVALUE = A.BUSINESS_UNIT
    AND I.RECNAME = 'LED_GRP_LED_TBL'
    AND A.BUSINESS_UNIT = 'UNUNI'
    --AND E.LEDGER_GROUP NOT IN ('CHD_UU', 'DET_UU', 'PAR_UU')
	AND E.LEDGER_GROUP NOT IN ('CHD_UU', 'DET_UU')
GROUP BY E.LEDGER_GROUP, A.BUDGET_PERIOD, A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2, A.ACTIVITY_ID, 
               E.LEDGER_TYPE_KK, J.LEDGER_GROUP_TYPE, H.BUDG_TYPE)X
WHERE X.PROJECT_ID = '00064262'
 --AND(X.BUDGET_PERIOD IN ('2012', '2013') OR X.BUDGET_PERIOD = ' ')        
 --AND X.FUND_CODE = '11000'
GROUP BY X.LEDGER_GROUP, X.BUDGET_PERIOD, X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2, X.ACTIVITY_ID
ORDER BY X.LEDGER_GROUP, X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2, X.ACTIVITY_ID;
--STEP 2
--Run this SQL to verify LEDGER_KK numbers for AX1_UU & REV_UU ledger groups
--SELECT * FROM PS_KK_INQ_BDLD_VW2 WHERE BUSINESS_UNIT = 'UNUNI'
--AND PROJECT_ID = '00064262'
--AND LEDGER_GROUP IN ('AX1_UU', 'REV_UU')
--ORDER BY 1;
--STEP 3
--Get other KK details
SELECT X.LEDGER_GROUP, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2, X.PROJECT_ID, X.ACTIVITY_ID, X.BUDGET_PERIOD, X.CURRENCY_CD,  
SUM(BUD) AS BUD, SUM(EXP) AS EXP, SUM(ENC) AS ENC, SUM(PRE) AS PRE, SUM((-1*BUD) - (EXP + (ENC))) AS AVAILABLE, SUM(REC_REV) AS REC_REV, SUM(REC_COL) AS REC_COL
FROM (
SELECT LEDGER_GROUP, ACCOUNT, DEPTID, OPERATING_UNIT, FUND_CODE, CHARTFIELD2, PROJECT_ID, ACTIVITY_ID, BUDGET_PERIOD, CURRENCY_CD, 
CASE WHEN LEDGER LIKE '%_UU_BUD' THEN (1 * SUM(POSTED_TOTAL_AMT)) ELSE 0 END AS BUD,
CASE WHEN LEDGER LIKE '%_UU_EXP' THEN (1 * SUM(POSTED_TOTAL_AMT)) ELSE 0 END AS EXP,
CASE WHEN LEDGER LIKE '%_UU_ENC' THEN (1 * SUM(POSTED_TOTAL_AMT)) ELSE 0 END AS ENC,
CASE WHEN LEDGER LIKE '%_UU_PRE' THEN (1 * SUM(POSTED_TOTAL_AMT)) ELSE 0 END AS PRE,
CASE WHEN LEDGER LIKE '%_UU_REC' THEN (1 * SUM(POSTED_TOTAL_AMT)) ELSE 0 END AS REC_REV,
CASE WHEN LEDGER LIKE '%_UU_COL' THEN (1 * SUM(POSTED_TOTAL_AMT)) ELSE 0 END AS REC_COL
FROM PS_KK_INQ_BDLD_VW2
WHERE BUSINESS_UNIT = 'UNUNI'
  --AND LEDGER_GROUP NOT IN ('CHD_UU', 'DET_UU', 'PAR_UU')
  AND LEDGER_GROUP NOT IN ('CHD_UU', 'DET_UU')
GROUP BY LEDGER_GROUP, ACCOUNT, DEPTID, OPERATING_UNIT, FUND_CODE, CHARTFIELD2, PROJECT_ID, ACTIVITY_ID, BUDGET_PERIOD, CURRENCY_CD, LEDGER
) X
WHERE X.PROJECT_ID = '00064262'
--AND X.BUDGET_PERIOD IN ('2012', '2013')
--AND X.FUND_CODE = '11000'
GROUP BY X.LEDGER_GROUP, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2, X.PROJECT_ID, X.ACTIVITY_ID, X.BUDGET_PERIOD, X.CURRENCY_CD
ORDER BY X.LEDGER_GROUP, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2, X.PROJECT_ID;
--STEP 4
--Run this SQL to bring details for that CF combination for ledger groups AX1_UU and REV_UU from PS_KK_ACTIVITY_LOG
--SELECT * FROM PS_KK_ACTIVITY_LOG 
--WHERE BUSINESS_UNIT = 'UNUNI' 
--AND PROJECT_ID = '00064262' 
--AND CHARTFIELD2 = '10359'
--AND LEDGER_GROUP IN ('AX1_UU', 'REV_UU')
--ORDER BY 1;
--STEP 5
--Run this SQL to bring aggregated details from PS_KK_ACTIVITY_LOG
SELECT X.LEDGER_GROUP, X.BUDGET_PERIOD, X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2, X.ACTIVITY_ID,
       SUM(X.REV_BUD) "Total Revenue Budgeted Amount", SUM(X.RECOG) "Total Recognized Amount", SUM(X.COLL) "Total Collected Amount",
       SUM(X.EXP_BUD) "Total Expense Budgeted Amount", SUM(X.EXP) "Expended Amount", SUM(X.ENC) "Encumbered Amount", SUM(X.PRE_ENC) "Pre Encumbered Amount",
       SUM((X.EXP_BUD + X.COLL) - (X.EXP + X.ENC)) AS "Available Budget"             
FROM
(SELECT E.LEDGER_GROUP, A.BUDGET_PERIOD, A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2, A.ACTIVITY_ID, 
        --E.LEDGER_TYPE_KK, J.LEDGER_GROUP_TYPE,
        CASE WHEN (E.LEDGER_TYPE_KK = 0 AND H.BUDG_TYPE = 'E') THEN (-1 * SUM(A.MONETARY_AMOUNT)) ELSE 0 END AS EXP_BUD,
        CASE WHEN (E.LEDGER_TYPE_KK = 0 AND H.BUDG_TYPE = 'R') THEN (1 * SUM(A.MONETARY_AMOUNT)) ELSE 0 END AS REV_BUD,            
        CASE WHEN (E.LEDGER_TYPE_KK = 1 AND J.LEDGER_GROUP_TYPE = 'R') THEN (1 * SUM(A.MONETARY_AMOUNT)) ELSE 0 END AS RECOG,
        CASE WHEN E.LEDGER_TYPE_KK = 4 THEN (1 * SUM(A.MONETARY_AMOUNT)) ELSE 0 END AS COLL,
        CASE WHEN E.LEDGER_TYPE_KK = 3 THEN (1 * SUM(A.MONETARY_AMOUNT)) ELSE 0 END AS PRE_ENC,
        CASE WHEN E.LEDGER_TYPE_KK = 2 THEN (1 * SUM(A.MONETARY_AMOUNT)) ELSE 0 END AS ENC,
        CASE WHEN (E.LEDGER_TYPE_KK = 1 AND J.LEDGER_GROUP_TYPE = 'E') THEN (1 * SUM(A.MONETARY_AMOUNT)) ELSE 0 END AS EXP
FROM PS_KK_ACTIVITY_LOG A, PS_LED_GRP_LED_TBL E, PS_KK_BUDGET_TYPE H, PS_SET_CNTRL_REC I, PS_LED_GRP_TBL J
WHERE A.LEDGER = E.LEDGER
    AND A.BASE_CURRENCY = 'USD'
    AND E.SETID = I.SETID
    AND H.EFFDT = (SELECT MAX(H_ED.EFFDT) FROM PS_KK_BUDGET_TYPE H_ED WHERE H.SETID1 = H_ED.SETID1 AND H.LEDGER_GROUP = H_ED.LEDGER_GROUP AND H_ED.EFFDT <= SYSDATE) 
    AND H.LEDGER_GROUP = E.LEDGER_GROUP
    AND H.SETID1 = E.SETID
    AND E.SETID = J.SETID
    AND E.LEDGER_GROUP = J.LEDGER_GROUP
    AND I.SETCNTRLVALUE = A.BUSINESS_UNIT
    AND I.RECNAME = 'LED_GRP_LED_TBL'
    AND A.BUSINESS_UNIT = 'UNUNI'
    --AND E.LEDGER_GROUP NOT IN ('CHD_UU', 'DET_UU', 'PAR_UU')
	AND E.LEDGER_GROUP NOT IN ('CHD_UU', 'DET_UU')
GROUP BY E.LEDGER_GROUP, A.BUDGET_PERIOD, A.PROJECT_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2, A.ACTIVITY_ID, 
         E.LEDGER_TYPE_KK, J.LEDGER_GROUP_TYPE, H.BUDG_TYPE)X
WHERE X.PROJECT_ID = '00064262'
--AND X.FUND_CODE = '11000'
--AND X.BUDGET_PERIOD IN ('2013') OR X.BUDGET_PERIOD = ' ')
GROUP BY X.LEDGER_GROUP, X.BUDGET_PERIOD, X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2, X.ACTIVITY_ID
ORDER BY X.LEDGER_GROUP, X.PROJECT_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.CHARTFIELD2, X.ACTIVITY_ID;
--STEP 6
--KK Associated Budgets
SELECT C.BUSINESS_UNIT, B.ASSOC_EXP_BD, C.ACCOUNT AS EX_ACCT, C.DEPTID AS EX_DEPT, C.OPERATING_UNIT AS EX_OU, C.FUND_CODE AS EX_FUND_CODE, 
       C.CHARTFIELD2 AS EX_DONOR, C.PROJECT_ID AS EX_PROJECT, C.ACTIVITY_ID AS EX_ACTIVITY, C.BUDGET_PERIOD, 
       D.ACCOUNT AS REV_ACCOUNT, D.DEPTID AS REV_DEPTID, D.OPERATING_UNIT AS REV_OU, D.FUND_CODE AS REV_FUND_CODE, 
       D.CHARTFIELD2 AS REV_DONOR, D.PROJECT_ID AS REV_PROJECT, D.ACTIVITY_ID AS REV_ACTIVITY,            
       D.LEDGER_GROUP, D.SEQ_NBR, - SUM(A.POSTED_TOTAL_AMT) AS POSTED_TOTAL_AMT, A.LEDGER, E.LEDGER_TYPE_KK, D.CAP, D.PERCENTAGE 
FROM PS_LEDGER_KK A, PS_KK_BUDGET_TYPE B, PS_KK_EX_XREF C, PS_KK_REV_XREF D, PS_LED_GRP_LED_TBL E, PS_SET_CNTRL_REC F, PS_SET_CNTRL_REC G, 
     PS_BUS_UNIT_TBL_GL H
WHERE A.BUSINESS_UNIT = C.BUSINESS_UNIT 
  AND A.BUSINESS_UNIT = D.BUSINESS_UNIT 
  AND A.BUSINESS_UNIT = H.BUSINESS_UNIT 
  AND A.CURRENCY_CD = H.BASE_CURRENCY 
  AND A.LEDGER = E.LEDGER 
  AND E.SETID = F.SETID 
  AND F.SETCNTRLVALUE = A.BUSINESS_UNIT 
  AND F.RECNAME = 'LED_GRP_LED_TBL' 
  AND E.LEDGER_GROUP = D.LEDGER_GROUP 
  AND E.LEDGER_GROUP = B.LEDGER_GROUP 
  AND E.LEDGER_TYPE_KK = D.REV_METHOD 
  AND B.SETID1 = G.SETID 
  AND A.BUDGET_PERIOD = D.BUDGET_PERIOD 
  AND G.SETCNTRLVALUE = A.BUSINESS_UNIT 
  AND G.RECNAME = 'KK_BD_TYPE_VW' 
  AND B.EFFDT = (SELECT MAX(H.EFFDT) FROM PS_KK_BUDGET_TYPE H WHERE H.SETID1 = B.SETID1 AND H.LEDGER_GROUP = B.LEDGER_GROUP AND H.EFFDT <= SYSDATE 
                                                                                                                AND H.EFF_STATUS = 'A')
  AND C.SEQ_NBR = D.SEQ_NBR 
  AND B.ASSOC_EXP_BD = C.LEDGER_GROUP 
  AND B.LEDGER_GROUP = D.LEDGER_GROUP 
  AND (A.ACCOUNT = D.ACCOUNT 
    OR A.ACCOUNT = (SELECT I.ACCOUNT FROM PS_KK_BD_DFLT_ACCT I, PS_SET_CNTRL_REC J 
                                   WHERE I.SETID1 = B.SETID1 AND I.LEDGER_GROUP = B.LEDGER_GROUP AND I.EFFDT = B.EFFDT AND I.SETID = J.SETID 
                                                                             AND J.SETCNTRLVALUE = A.BUSINESS_UNIT AND J.RECNAME = 'KK_BD_TYPE_VW')) 
  AND A.DEPTID = D.DEPTID
  AND A.OPERATING_UNIT = D.OPERATING_UNIT
  AND A.PRODUCT = D.PRODUCT  
  AND A.FUND_CODE = D.FUND_CODE  
  AND A.CLASS_FLD = D.CLASS_FLD  
  AND A.PROGRAM_CODE = D.PROGRAM_CODE  
  AND A.BUDGET_REF = D.BUDGET_REF  
  AND A.AFFILIATE = D.AFFILIATE  
  AND A.AFFILIATE_INTRA1 = D.AFFILIATE_INTRA1  
  AND A.AFFILIATE_INTRA2 = D.AFFILIATE_INTRA2  
  AND A.CHARTFIELD1 = D.CHARTFIELD1  
  AND A.CHARTFIELD2 = D.CHARTFIELD2  
  AND A.CHARTFIELD3 = D.CHARTFIELD3  
  AND A.BUSINESS_UNIT_PC = D.BUSINESS_UNIT_PC  
  AND A.PROJECT_ID = D.PROJECT_ID  
  AND A.ACTIVITY_ID = D.ACTIVITY_ID  
  AND A.RESOURCE_TYPE = D.RESOURCE_TYPE
  AND A.BUSINESS_UNIT = 'UNUNI'
  AND A.PROJECT_ID = '00064262'
GROUP BY C.BUSINESS_UNIT, B.ASSOC_EXP_BD, C.ACCOUNT, C.DEPTID, C.OPERATING_UNIT, C.FUND_CODE, C.CHARTFIELD2, C.BUSINESS_UNIT_PC, C.PROJECT_ID, C.ACTIVITY_ID, 
         C.BUDGET_PERIOD, D.ACCOUNT, D.DEPTID, D.OPERATING_UNIT, D.FUND_CODE, D.CHARTFIELD2, D.BUSINESS_UNIT_PC, D.PROJECT_ID, D.ACTIVITY_ID, 
         D.LEDGER_GROUP, A.LEDGER, E.LEDGER_TYPE_KK, D.SEQ_NBR, D.CAP, D.PERCENTAGE
ORDER BY C.BUSINESS_UNIT, B.ASSOC_EXP_BD, C.ACCOUNT;
--STEP 7
--DRILLDOWN Number 1 on PS_KK_ACTIVITY_LOG
--SELECT ACT.KK_TRAN_ID, ACT.LEDGER, ACT.ACCOUNT, ACT.DEPTID, ACT.OPERATING_UNIT, ACT.FUND_CODE, ACT.PROJECT_ID, ACT.ACTIVITY_ID, CHARTFIELD2, 
--       ACT.FOREIGN_AMOUNT, ACT.FOREIGN_CURRENCY, ACT.MONETARY_AMOUNT, ACT.BASE_CURRENCY,
--       HDR.KK_SOURCE_TRAN, KEYLIST
--FROM PS_KK_ACTIVITY_LOG ACT, PS_KK_SOURCE_HDR HDR 
--WHERE ACT.KK_TRAN_ID = HDR.KK_TRAN_ID 
--  AND ACT.KK_TRAN_DT = HDR.KK_TRAN_DT 
--  AND ACT.KK_TRAN_LN  = HDR.KK_TRAN_LN
--  AND ACT.BUSINESS_UNIT = 'UNUNI' 
--  AND ACT.FUND_CODE = '11000'
--  AND ACT.PROJECT_ID = '00064262' 
--  AND CHARTFIELD2 = '10359'
--  AND ACT.LEDGER_GROUP IN ('AX1_UU', 'REV_UU')
--ORDER BY 1;
--STEP 8
--DRILLDOWN Number 2 on PS_KK_ACTIVITY_LOG
SELECT X.KK_TRAN_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.PROJECT_ID, X.ACTIVITY_ID, X.CHARTFIELD2, 
       X.BASE_CURRENCY, X.KEYLIST, SUM(EXP) AS EXP, SUM(REC_REV) AS REC_REV, SUM(REC_COL) AS REC_COL
FROM
(SELECT ACT.KK_TRAN_ID, ACT.LEDGER, ACT.ACCOUNT, ACT.DEPTID, ACT.OPERATING_UNIT, ACT.FUND_CODE, ACT.PROJECT_ID, ACT.ACTIVITY_ID, ACT.CHARTFIELD2, 
        ACT.BASE_CURRENCY, KEYLIST,
        CASE WHEN LEDGER LIKE '%_UU_EXP' THEN (1 * SUM( ACT.MONETARY_AMOUNT)) ELSE 0 END AS EXP,
        CASE WHEN LEDGER LIKE '%_UU_REC' THEN (1 * SUM( ACT.MONETARY_AMOUNT)) ELSE 0 END AS REC_REV,
        CASE WHEN LEDGER LIKE '%_UU_COL' THEN (1 * SUM( ACT.MONETARY_AMOUNT)) ELSE 0 END AS REC_COL
FROM PS_KK_ACTIVITY_LOG ACT, PS_KK_SOURCE_HDR HDR 
WHERE ACT.KK_TRAN_ID = HDR.KK_TRAN_ID 
    AND ACT.KK_TRAN_DT = HDR.KK_TRAN_DT 
  --AND ACT.KK_TRAN_LN  = HDR.KK_TRAN_LN
    AND ACT.BUSINESS_UNIT = 'UNUNI'
    AND ACT.LEDGER_GROUP IN ('AX1_UU', 'REV_UU')
GROUP BY ACT.KK_TRAN_ID, ACT.LEDGER, ACT.ACCOUNT, ACT.DEPTID, ACT.OPERATING_UNIT, ACT.FUND_CODE, ACT.PROJECT_ID, ACT.ACTIVITY_ID, CHARTFIELD2, 
         ACT.BASE_CURRENCY, HDR.KEYLIST) X
WHERE X.PROJECT_ID = '00064262'
--AND X.FUND_CODE = '11000'
--AND X.CHARTFIELD2 = '10359'
GROUP BY X.KK_TRAN_ID, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.PROJECT_ID, X.ACTIVITY_ID, X.CHARTFIELD2, 
         X.BASE_CURRENCY, X.KEYLIST
ORDER BY 1;
--STEP 9
--GLS8005 - Budget Transaction Detail Rep
SELECT A.BASE_CURRENCY, A.PROJECT_ID, A.BUDGET_PERIOD, B.KK_TRAN_DT, B.KK_SOURCE_TRAN, B.BUSINESS_UNIT, B.JOURNAL_ID, B.JOURNAL_DATE,
       B.UNPOST_SEQ, C.JOURNAL_LINE, A.LEDGER, C.LEDGER, B.CUST_ID, B.ITEM, B.ITEM_LINE, B.DEPOSIT_ID, B.PAYMENT_SEQ_NUM, B.VOUCHER_ID, C.VOUCHER_LINE_NUM, B.PO_ID, B.REQ_ID, 
       C.LINE_NBR, C.DISTRIB_LINE_NUM, B.ACCOUNTING_DT, C.ACCTG_LINE_NO, B.INVOICE, C.LINE_SEQ_NUM, B.ACTIVITY_ID, B.RESOURCE_ID, B.EMPLID, B.TRANS_NBR,
       A.MONETARY_AMOUNT, C.PROJECT_ID, A.KK_TRAN_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, A.CHARTFIELD2, E.LEDGER_TYPE_KK, J.LEDGER_GROUP_TYPE,
       CASE WHEN (E.LEDGER_TYPE_KK = 0 AND H.BUDG_TYPE = 'E') THEN (-1 * A.MONETARY_AMOUNT) ELSE 0 END AS  "Total Expense Budgeted Amount",
       CASE WHEN (E.LEDGER_TYPE_KK = 0 AND H.BUDG_TYPE = 'R') THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS  "Total Revenue Budgeted Amount",
       CASE WHEN (E.LEDGER_TYPE_KK = 1 AND J.LEDGER_GROUP_TYPE = 'R') THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Total Recognized Amount",
       CASE WHEN E.LEDGER_TYPE_KK = 4 THEN (-1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Total Collected Amount",
       CASE WHEN E.LEDGER_TYPE_KK = 3 THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Pre Encumbered Amount",
       CASE WHEN E.LEDGER_TYPE_KK = 2 THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Encumbered Amount",
       CASE WHEN (E.LEDGER_TYPE_KK = 1 AND J.LEDGER_GROUP_TYPE = 'E') THEN (1 * A.MONETARY_AMOUNT) ELSE 0 END AS "Expended Amount"       
FROM PS_KK_ACTIVITY_LOG A, PS_KK_SOURCE_HDR B, PS_KK_SOURCE_LN C, PS_LED_GRP_LED_TBL E, PS_KK_BUDGET_TYPE H, PS_SET_CNTRL_REC I, PS_LED_GRP_TBL J
WHERE A.KK_TRAN_ID = B.KK_TRAN_ID
  AND A.KK_TRAN_DT = B.KK_TRAN_DT
  AND B.KK_TRAN_ID = C.KK_TRAN_ID
  AND B.KK_TRAN_DT = C.KK_TRAN_DT
  AND A.KK_TRAN_LN = C.KK_TRAN_LN
  AND A.LEDGER = E.LEDGER
  AND E.SETID = I.SETID
  AND H.EFFDT = (SELECT MAX(H_ED.EFFDT) FROM PS_KK_BUDGET_TYPE H_ED WHERE H.SETID1 = H_ED.SETID1 AND H.LEDGER_GROUP = H_ED.LEDGER_GROUP AND H_ED.EFFDT <= SYSDATE) 
  AND H.LEDGER_GROUP = E.LEDGER_GROUP
  AND H.SETID1 = E.SETID
  AND E.SETID = J.SETID
  AND E.LEDGER_GROUP = J.LEDGER_GROUP
  AND I.SETCNTRLVALUE = A.BUSINESS_UNIT
  AND I.RECNAME = 'LED_GRP_LED_TBL'
  AND A.BALANCING_LINE <> 'Y'
  AND (A.BUSINESS_UNIT = 'UNUNI' OR A.BUSINESS_UNIT LIKE '6%')    
  AND (A.BUDGET_PERIOD IN ('2014', '2015') OR A.BUDGET_PERIOD = ' ')
  AND A.PROJECT_ID IN ('00064262')
  --AND A.FUND_CODE = '11000'
  --AND A.LEDGER_GROUP IN ('AX1_UU', 'REV_UU')
ORDER BY 2,4;
