--Version 7
--Added PSPRSMDEFN
--Retrieve Page for Secondary and Sub Pages and their Component(s)
SELECT IBOP.IB_OPERATIONNAME "Service Operation", IBOP.VERSION "SvOp Ver", IBOP.DEFAULTVER "SvOp DFLT Ver", OPVER.VERSIONNAME "SvOp Ver Name",
       IBOP.OBJECTOWNERID || ' - ' || X2.XLATLONGNAME AS "SvOp Object Ident", IBOP.RTNGTYPE || ' - ' || X1.XLATLONGNAME AS "Routing Type", OPVERDFN.PARAMETERNAME,
       OPVERDFN.MSGNAME "SvOp Msg Name", OPVERDFN.IB_MSGVERSION "SvOp Msg Ver", IBOP.IB_SERVICENAME "Service", IB_ALIASNAME "Service Alias", IBOP.DESCR "Operation Descr",
       SERV.IB_SERVICENAME, MSGD.MSGNAME "MSG Name", MSGD.VERSION "MSG Ver", MSGD.DEFAULTVER "MSG DFLT V",
       CASE MSGV.IB_MSGTYPE
         WHEN 0 THEN '0 - MSGTYPE_DOCUMENT' WHEN 1 THEN '1 - MSGTYPE_ROWSET_BASED' WHEN 2 THEN '2 - MSGTYPE_CONTAINER' WHEN 3 THEN '3 - MSGTYPE_PART_ROWSET_BASED'
         WHEN 4 THEN '4 - MSGTYPE_PART_NON_ROWSET_BASED' WHEN 5 THEN '5 - MSGTYPE_NON_ROWSET_BASED'
       ELSE 'Unknown' END AS "Msg Type",
       MSGR.RECNAME "MSG Record", RECFLD.FIELDNAME,
       CASE WHEN BITAND(RECFLD.USEEDIT, 256) > 0 THEN 'YES' ELSE 'NO' END AS "REQ (Y/N)",
       CASE WHEN BITAND(RECFLD.USEEDIT, 1) > 0 THEN 'KEY' WHEN BITAND(RECFLD.USEEDIT, 2) > 0 THEN 'DUP' WHEN BITAND(RECFLD.USEEDIT, 16) > 0 THEN 'ALT' ELSE NULL END AS KEY_TYPE,
       CASE WHEN BITAND(RECFLD.USEEDIT, 64) > 0 THEN 'DESC' WHEN (BITAND(RECFLD.USEEDIT, 1) > 0 OR BITAND(RECFLD.USEEDIT, 2) > 0 OR BITAND(RECFLD.USEEDIT, 16) > 0 )
                                                                                                                                AND BITAND(RECFLD.USEEDIT, 64) = 0 THEN 'ASC' ELSE NULL END AS DIR,
       CASE WHEN BITAND(RECFLD.USEEDIT, 2048) > 0 THEN 'YES' ELSE 'NO' END AS SRCH_KEY,
       CASE WHEN BITAND(RECFLD.USEEDIT, 32) > 0 THEN 'YES' ELSE 'NO' END AS LIST_BOX,
       CASE WHEN BITAND(RECFLD.USEEDIT, 4) > 0 THEN 'YES' ELSE 'NO' END AS SYS_MAINT,
       CASE WHEN BITAND(RECFLD.USEEDIT, 8) > 0 AND BITAND(RECFLD.USEEDIT, 128) = 0 AND BITAND(RECFLD.USEEDIT, 1024) = 0 THEN 'A'
            WHEN BITAND(RECFLD.USEEDIT, 8) > 0 AND BITAND(RECFLD.USEEDIT, 128) > 0 AND BITAND(RECFLD.USEEDIT, 1024) = 0 THEN 'AC'
            WHEN BITAND(RECFLD.USEEDIT, 8) > 0 AND BITAND(RECFLD.USEEDIT, 128) > 0 AND BITAND(RECFLD.USEEDIT, 1024) > 0 THEN 'ACD'
            WHEN BITAND(RECFLD.USEEDIT, 8) = 0 AND BITAND(RECFLD.USEEDIT, 128) > 0 AND BITAND(RECFLD.USEEDIT, 1024) = 0 THEN 'C'
            WHEN BITAND(RECFLD.USEEDIT, 8) = 0 AND BITAND(RECFLD.USEEDIT, 128) > 0 AND BITAND(RECFLD.USEEDIT, 1024) > 0 THEN 'CD'
            WHEN BITAND(RECFLD.USEEDIT, 8) = 0 AND BITAND(RECFLD.USEEDIT, 128) = 0 AND BITAND(RECFLD.USEEDIT, 1024) > 0 THEN 'D' ELSE NULL END AS AUDT,
       CASE WHEN BITAND(RECFLD.USEEDIT, 16384) > 0 THEN 'PROMPT' WHEN BITAND(RECFLD.USEEDIT, 512) > 0 THEN 'XLAT' WHEN BITAND(RECFLD.USEEDIT, 8192) > 0 THEN 'Y/N' ELSE NULL END AS EDIT_TYPE,
       CASE WHEN BITAND(RECFLD.USEEDIT, 4096) > 0 THEN 'YES' ELSE 'NO' END AS REASONABLE_DT,
       CASE WHEN BITAND(RECFLD.USEEDIT, 32768) > 0 THEN 'YES' ELSE 'NO' END AS AUTO_UPDT,
       CASE WHEN BITAND(RECFLD.USEEDIT, 262144) > 0 THEN 'FROM' WHEN BITAND(RECFLD.USEEDIT, 524288) > 0 THEN 'THROUGH' ELSE NULL END AS SEARCH_FIELD,
       CASE DBF.FIELDTYPE
         WHEN 0 THEN 'Char' WHEN 1 THEN 'Long Char' WHEN 2 THEN 'NBR' WHEN 3 THEN 'Sign NBR' WHEN 4 THEN 'Date' WHEN 5 THEN 'Time' WHEN 6 THEN 'Dttm' WHEN 7 THEN 'Img' WHEN 8 THEN 'Img/Attch'
         WHEN 9 THEN 'Img/Ref'
       ELSE 'Unknown' END "DB Field Type", DENSE_RANK() OVER (PARTITION BY MSGD.MSGNAME, MSGR.RECNAME ORDER BY MSGD.MSGNAME, MSGR.RECNAME, RECFLD.FIELDNUM ASC) AS "Fld#", RECFLD.FIELDNUM,
       CASE PNLF.FIELDTYPE
         WHEN 0 THEN 'Text' WHEN 1 THEN 'Frame' WHEN 2 THEN 'Group Box' WHEN 3 THEN 'Static Image' WHEN 4 THEN 'Edit Box' WHEN 5 THEN 'Drop Down List' WHEN 6 THEN 'Long Edit Box'
         WHEN 7 THEN 'Check Box' WHEN 8 THEN 'Radio Button' WHEN 9 THEN 'Image' WHEN 10 THEN 'Scroll Bar' WHEN 11 THEN 'Subpage' WHEN 12 THEN 'Push Button/Link - PeopleCode'
         WHEN 13 THEN 'Push Button/Link - Scroll Action' WHEN 14 THEN 'Push Button/Link - Toolbar Action' WHEN 15 THEN 'Push Button/Link - External Link'
         WHEN 16 THEN 'Push Button/Link - Internal Link' WHEN 17 THEN 'Push Button/Link - Process' WHEN 18 THEN 'SecPage' WHEN 19 THEN 'Grid' WHEN 20 THEN 'Tree'
         WHEN 21 THEN 'Push Button/Link - Secondary Page' WHEN 23 THEN 'Horizontal Rule' WHEN 24 THEN 'Tab Separator' WHEN 25 THEN 'HTML Area' WHEN 26 THEN 'Push Button/Link - Prompt Action'
         WHEN 27 THEN 'Scroll Area' WHEN 29 THEN 'Push Button/Link - Page Anchor' WHEN 30 THEN 'Chart' WHEN 31 THEN 'Push Button/Link - Instant Message Action' WHEN 32 THEN 'Analytic Grid'
       ELSE 'Unknown' END "PNL Field Type",
       MSGR.PRNTRECNAME "MSG Parent Rec", MSGR.SEQNO, RECD.OBJECTOWNERID || ' - ' || X3.XLATLONGNAME AS "REC Object Ident", PNLD.PNLNAME,
       CASE PNLD.PNLTYPE WHEN 0 THEN 'Page' WHEN 1 THEN 'Sub Page' WHEN 2 THEN 'Secondary Page' WHEN 3 THEN 'Popup Page' WHEN 4 THEN 'NUI Header Page' WHEN 5 THEN 'NUI Side Page 1'
                         WHEN 6 THEN 'NUI Footer Page' WHEN 7 THEN 'NUI Layout Page' WHEN 8 THEN 'NUI Search Page' WHEN 9 THEN 'NUI Prompt Page' WHEN 10 THEN 'NUI Master Detail Target Page'
                         WHEN 11 THEN 'NUI Side Page 2'
       ELSE 'Unknown' END "Page Type",
       PNLF.PNLFIELDNAME, PNLF.LABEL_ID, PNLF.LBLTEXT, PNLF1.PNLNAME "ORIG PNL Name", PNLGRP1.PNLGRPNAME "S/S Page Comp",
       PNLGRP.PNLGRPNAME "Page Comp", PNLGRP.MARKET, PRS.PORTAL_LABEL "L0", PRS1.PORTAL_LABEL "L01", MSGP.IB_MSGVERSION "MSG Part Msg", MSGP.IB_MSGVERSION "MSG Part Ver",
       CASE(NVL(RECD.RECTYPE, 99))
          WHEN 0 THEN '0 - SQL Table' WHEN 1 THEN '1 - SQL View' WHEN 2 THEN '2 - Work Record' WHEN 3 THEN '3 - Sub Record' WHEN 5 THEN '5 - Dynamic View' WHEN 6 THEN '6 - Query View'
          WHEN 7 THEN '7 - Temporary Table'
       ELSE 'Other Record or Deleted' END AS RECTYPE,
       IBOPHND.HANDLERNAME, IBOPHND.VERSION "Handler Ver", IBOPHND.IB_HANDLERALIAS "Handler Alias", IBOPHND.SEQNO "Handler Seq#",
       IBOPHND.HANDLERID || ' - ' || X4.XLATLONGNAME AS "Handler Type", IBOPHND.HANDLERTYPE "Implementation",  OPVER.VERSION "SvOp Version", OPVER.ACTIVE_FLAG "SvOp Flag",
       OPVER.DESCR "SvOp Descr", OPVERDFN.QUEUENAME, IBOPHND.ACTIVE_FLAG "Handler Flag", IBOPHND.DESCR "Handler Descr", IBOPHND.OBJECTOWNERID "Handler Owner ID",
       OPAC.PACKAGEID, OPAC.PACKAGEROOT, OPAC.QUALIFYPATH, OPAC.APPCLASSID, OPAC.APPCLASSMETHOD, OPCI.BCNAME, OPCI.IB_ACTION, IBOP.MSGNAME, IBOP.IB_MSGVERSION, IBOPHND.DESCRLONG, PNLF.PNLFLDID
       --, PNLF.*, PNLGRP.*, IBOPHND.*, --IBOP.*
FROM ((((((((((((((((((((((((PSOPERATION IBOP LEFT OUTER JOIN PSOPRHDLR IBOPHND ON IBOP.IB_OPERATIONNAME = IBOPHND.IB_OPERATIONNAME AND IBOPHND.HANDLERTYPE <> 'Deprecated')
       LEFT OUTER JOIN PSOPRVERDFN OPVER ON IBOP.IB_OPERATIONNAME = OPVER.IB_OPERATIONNAME AND IBOP.DEFAULTVER = OPVER.VERSIONNAME)
       LEFT OUTER JOIN PSOPRVERDFNPARM OPVERDFN ON IBOP.IB_OPERATIONNAME = OPVERDFN.IB_OPERATIONNAME AND OPVER.VERSIONNAME = OPVERDFN.VERSIONNAME)      
       LEFT OUTER JOIN PSOPERATIONAC OPAC ON IBOPHND.IB_OPERATIONNAME = OPAC.IB_OPERATIONNAME AND IBOPHND.HANDLERNAME = OPAC.HANDLERNAME)
       LEFT OUTER JOIN PSOPERATIONCI OPCI ON IBOPHND.IB_OPERATIONNAME = OPCI.IB_OPERATIONNAME AND IBOPHND.HANDLERNAME = OPCI.HANDLERNAME)
       LEFT OUTER JOIN PSSERVICEOPR SERV ON IBOP.IB_OPERATIONNAME = SERV.IB_OPERATIONNAME)
       LEFT OUTER JOIN PSMSGDEFN MSGD ON OPVERDFN.MSGNAME = MSGD.MSGNAME)
       LEFT OUTER JOIN PSMSGVER MSGV ON (MSGV.MSGNAME = MSGD.MSGNAME AND MSGV.APMSGVER = OPVERDFN.IB_MSGVERSION AND MSGV.IB_PARTS = 0))
                                     --OR (MSGV.MSGNAME LIKE MSGD.MSGNAME || '%' AND MSGV.APMSGVER = OPVERDFN.IB_MSGVERSION AND MSGV.IB_PARTS = 1))
       LEFT OUTER JOIN PSMSGREC MSGR ON MSGR.MSGNAME = MSGD.MSGNAME AND MSGR.APMSGVER = MSGV.APMSGVER)
       LEFT OUTER JOIN PSMSGPARTS MSGP ON MSGR.MSGNAME = MSGP.MSGNAME AND MSGR.APMSGVER = MSGP.APMSGVER)
       LEFT OUTER JOIN PSRECDEFN RECD ON MSGR.RECNAME = RECD.RECNAME)
       LEFT OUTER JOIN PSRECFIELDDB RECFLD ON RECFLD.RECNAME = RECD.RECNAME)
       LEFT OUTER JOIN PSDBFIELD DBF ON RECFLD.FIELDNAME = DBF.FIELDNAME)      
       LEFT OUTER JOIN PSPNLFIELD PNLF ON RECD.RECNAME = PNLF.RECNAME AND RECFLD.FIELDNAME = PNLF.FIELDNAME)
       LEFT OUTER JOIN PSPNLFIELD PNLF1 ON PNLF.PNLNAME = PNLF1.SUBPNLNAME)
       LEFT OUTER JOIN PSPNLDEFN PNLD ON PNLF.PNLNAME = PNLD.PNLNAME)      
       LEFT OUTER JOIN PSPNLGROUP PNLGRP ON PNLF.PNLNAME = PNLGRP.PNLNAME)
       LEFT OUTER JOIN PSPNLGROUP PNLGRP1 ON PNLF1.PNLNAME = PNLGRP1.PNLNAME)
       LEFT OUTER JOIN PSPRSMDEFN PRS ON PRS.PORTAL_URI_SEG2 = PNLGRP.PNLGRPNAME AND PRS.PORTAL_CREF_USGT = 'TARG')
       LEFT OUTER JOIN PSPRSMDEFN PRS1 ON PRS1.PORTAL_URI_SEG2 = PNLGRP1.PNLGRPNAME AND PRS1.PORTAL_CREF_USGT = 'TARG')
       LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'RTNGTYPE' AND X1.FIELDVALUE = IBOP.RTNGTYPE AND X1.EFF_STATUS = 'A')
       LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'OBJECTOWNERID' AND X2.FIELDVALUE = IBOP.OBJECTOWNERID AND X2.EFF_STATUS = 'A')
       LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'OBJECTOWNERID' AND X3.FIELDVALUE = RECD.OBJECTOWNERID AND X3.EFF_STATUS = 'A')
       LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'HANDLERID' AND X4.FIELDVALUE = IBOPHND.HANDLERID AND X4.EFF_STATUS = 'A')
WHERE 1 = 1
--  AND IBOP.IB_OPERATIONNAME = 'WM_ASSET_GET'
--  AND IBOP.IB_OPERATIONNAME = 'ADVANCED_SHIPPING_RECEIPT'
--  AND RECFLD.FIELDNAME LIKE '%EMPLID%'
--  AND RECFLD.FIELDNAME LIKE '%BIRTHDATE%'
  AND ((RECFLD.FIELDNAME LIKE '%EMPL%ID' OR RECFLD.FIELDNAME LIKE '%EMPL%' OR RECFLD.FIELDNAME LIKE '%PERSON%' OR RECFLD.FIELDNAME LIKE '%APPLICANT%' OR RECFLD.FIELDNAME = 'TEAM_MEMBER'
     OR RECFLD.FIELDNAME = 'TEAM_MEMBER') AND RECFLD.FIELDNAME NOT LIKE '%TEMPLATE%' AND RECFLD.FIELDNAME <> 'AE_APPLID' AND RECFLD.FIELDNAME <> 'AE_DO_APPLID')
ORDER BY IBOP.IB_OPERATIONNAME, MSGR.PRNTRECNAME, MSGR.SEQNO;
