--Version 3
--Combined PPs PO Register with Version 1
--It does work but difficult to interpret
SELECT A.BUSINESS_UNIT, A.PO_ID, A.PO_STATUS, X1.XLATLONGNAME AS PO_STATUS_DESCR, A.VENDOR_ID, E.NAME1, E.VENDOR_CLASS, X10.XLATLONGNAME AS VENDOR_CLASS_DESCR, 
            B.INV_ITEM_ID, ITM.DESCR AS ITM_DESCR, P.ACCOUNT AS ITM_ACCT, B.LINE_NBR AS PO_LINE_NBR, C.SCHED_NBR AS PO_SCHED_NBR, D.DISTRIB_LINE_NUM AS PO_DISTRIB_LINE_NUM, 
            A.BUDGET_HDR_STATUS, A.BUDGET_CHECK, B.UNIT_OF_MEASURE, B.RECV_REQ, X2.XLATLONGNAME AS RECV_REQ_PO, B.AMT_ONLY_FLG, 
            B.CATEGORY_ID, CAT.CATEGORY_CD, CAT.ACCOUNT AS CAT_ACCT, B.CNTRCT_SETID, B.CNTRCT_ID, 
            B.CNTRCT_LINE_NBR, B.RELEASE_NBR, A.BUYER_ID, A.OPRID_ENTERED_BY, A.OPRID_APPROVED_BY, A.MATCH_STATUS_PO, X3.XLATLONGNAME AS MTCH_STATUS_PO, A.PO_DT, 
            A.ACCOUNTING_DT AS PO_ACCT_DT, D.BUDGET_DT AS PO_BUD_DT, B.CANCEL_STATUS AS POL_CANCEL_STATUS, D.DISTRIB_LN_STATUS, D.KK_CLOSE_FLAG, D.KK_PROCESS_PRIOR, 
            D.KK_CLOSE_PRIOR, D.QTY_PO AS POD_QTY_PO, D.MERCH_AMT_BSE AS PO_USD_AMT, C.DISTRIB_MTHD_FLG, C.MATCH_STATUS_LN_PO, C.PRICE_PO AS PO_LS_PRICE, 
            C.PRICE_PO_BSE AS PO_LS_PRICE_BSE, C.QTY_PO AS PO_LS_QTY, C.MERCHANDISE_AMT AS PO_LS_MERCH_AMT, C.CURRENCY_CD AS PO_LS_M_AMT_CURR, 
            C.MERCH_AMT_BSE AS PO_LS_MERCH_AMT_BSE, C.FREIGHT_TERMS, C.MATCH_LINE_OPT, 
            D.MERCHANDISE_AMT AS PO_FOREIGN_AMT, D.CURRENCY_CD, A.CURRENCY_CD AS PO_HDR_CURR, 
            --NVL(ROUND((A.RATE_MULT/A.RATE_DIV), 7), 0) AS PO_HDR_RATE, NVL(ROUND((D.RATE_MULT/D.RATE_DIV), 7), 0) AS PO_DIST_RATE, 
            A.RATE_MULT AS PO_HDR_RATE_MULT, A.RATE_DIV AS PO_HDR_RATE_DIV, D.RATE_MULT AS PO_DIST_RATE_MULT, D.RATE_DIV AS PO_DIST_RATE_DIV, 
            C.DUE_DT, C.SHIPTO_ID, 
            D.ACCOUNT AS PO_ACCT, D.OPERATING_UNIT AS PO_OP_UNIT, D.FUND_CODE AS PO_FUND, D.DEPTID AS PO_DEPT, D.PROJECT_ID AS PO_PRJ, D.ACTIVITY_ID AS PO_ACT, 
            D.CHARTFIELD2 AS PO_DONOR, 
            D.BUSINESS_UNIT_REQ, D.REQ_ID, REQ_LINE_NBR, REQ_SCHED_NBR, REQ_DISTRIB_NBR, REQD.BUSINESS_UNIT_AM AS REQ_BU_AM, REQD.PROFILE_ID AS REQ_PROFILE_ID, 
            REQH.REQUESTOR_ID AS REQ_REQUESTOR, REQH.OPRID_APPROVED_BY AS REQ_APPR, REQH.APPROVAL_DT AS REQ_APPR_DT, REQH.OPRID_ENTERED_BY AS REQ_ENTERED_BY, 
            REQH.ENTERED_DT AS REQ_ENTERED_DT, NVL(D.QTY_REQ, 0) "QTY Req on PO Distrib", NVL(REQD.QTY_OPEN, 0) "QTY Open on REQ Distrib", NVL(REQD.AMT_OPEN, 0) "AMT Open on Req Distrib",
            REQD.ACCOUNT AS REQ_ACCT, REQD.OPERATING_UNIT AS REQ_OP_UNIT, REQD.FUND_CODE AS REQ_FUND, REQD.DEPTID AS REQ_DEPT, REQD.PROJECT_ID AS REQ_PRJ, 
            REQD.ACTIVITY_ID AS REQ_ACT, REQD.CHARTFIELD2 AS REQ_DONOR, 
            --NVL(ROUND((REQH.RATE_MULT/REQH.RATE_DIV), 7), 0) AS REQ_HDR_RATE, NVL(ROUND((REQD.RATE_MULT/REQD.RATE_DIV), 7), 0) AS REQ_DIST_RATE,
            REQH.RATE_MULT AS REQ_HDR_RATE_MULT, REQH.RATE_DIV AS REQ_HDR_RATE_DIV, REQD.RATE_MULT AS REQ_DIST_RATE_MULT, REQD.RATE_DIV AS REQ_DIST_RATE_DIV,
            RLD.BUSINESS_UNIT AS RECV_BU, RLD.RECEIVER_ID, RH.RECV_STATUS, X4.XLATLONGNAME AS RECV_STATUS_DESC, G.RECEIVER_ID AS VCHR_RECV_ID,
            RH.MATCH_STATUS_RECV, X5.XLATLONGNAME AS MTCH_STATUS_RECV, RLD.RECV_LN_NBR, RLD.RECV_SHIP_SEQ_NBR, RLD.DISTRIB_LINE_NUM AS RECV_DIST_LINE_NUM, RH.RECEIPT_DT, 
            RLA.DISTRIB_SEQ_NUM, RH.OPRID AS RECV_OPRID, RH.INTFC_ASSET, RLD.BUSINESS_UNIT_AM AS RLD_BU_AM, RLD.PROFILE_ID AS RLD_PROFILE_ID, 
            RLS.RECV_SHIP_STATUS, X6.XLATLONGNAME AS RECV_SHIP_DESCR, 
            RLS.MOVE_STAT_AM, X7.XLATLONGNAME AS MOVE_STATUS_DESCR, RLD.QTY_DS_ACCPT_VUOM, RLS.QTY_SH_REJCT_VUOM, RLS.QTY_SH_ACCPT_VUOM, RLS.QTY_SH_RECVD_VUOM, 
            RLD.QTY_PO, RLA.ACTUAL_COST, RLA.COST, --NVL(ROUND((RLD.RATE_MULT/RLD.RATE_DIV), 7), 0) AS RECV_DIST_RATE,
            RLD.RATE_MULT AS RECV_DIST_RATE_MULT, RLD.RATE_DIV AS RECV_DIST_RATE_DIV,
            RLA.CUSTODIAN, RLA.DESCR AS RLA_DESCR, RLA.DTTM_STAMP, RLA.FINANCIAL_ASSET_SW, RLA.LOCATION, RLA.MODEL, RLA.SERIAL_ID, 
            RLA.TAG_NUMBER, RLA.PRE_INTFC_ID, RLA.PRE_INTFC_LINE_NUM, RLA.PRICE_PO_BSE, RLA.RECV_AM_STATUS, X8.XLATLONGNAME AS RECV_AM_STS,
            PRE.INTFC_ID, PRE.INTFC_LINE_NUM, PRE.LOAD_STATUS AS PRE_AM_LOAD_STATUS, PRE.TRANS_DT, PRE.ACCOUNTING_DT, PRE.TXN_COST, PRE.TXN_CURRENCY_CD,
            FIN.BUSINESS_UNIT AS AM_BU_FIN, FIN.ASSET_ID, FIN.DTTM_STAMP AS FIN_DTTM_STAMP, FIN.INTFC_TYPE, FIN.INTFC_STATUS, FIN.LOAD_STATUS, FIN.IN_SERVICE_DT, FIN.OPEN_TRANS_ID, 
            --PHYA.BUSINESS_UNIT AS AM_BU_PHYA, PHYA.ASSET_ID AS PHYA_ASSET, 
            PHYA.ACQUISITION_DT, PHYA.DESCR AS ASSET_DESCR, 
            G.BUSINESS_UNIT AS DIST_AP_BU, G.VOUCHER_ID AS DIST_VCHR_ID, VC.APPR_STATUS, X16.XLATLONGNAME AS VCHR_APPR_STS,
            RVP.BUSINESS_UNIT_AP AS RVP_AP_BU, RVP.VOUCHER_ID AS RVP_VCHR_ID, RVP.VOUCHER_LINE_NUM AS RVP_VCHR_LINE_NUM, RVP.RECEIVER_ID AS RVP_RECV_ID, 
            RVP.RECV_LN_NBR AS RVP_RECV_LN_NBR, VC.ENTRY_STATUS, X15.XLATLONGNAME AS VCHR_ENTRY_STATUS, G.VOUCHER_LINE_NUM, G.DISTRIB_LINE_NUM, VL.DESCR AS VCHR_LINE_DESCR, 
            VL.VNDR_LOC, VL.MERCHANDISE_AMT AS VL_MERCH_AMT, VL.TXN_CURRENCY_CD AS VL_TXN_CURR, VL.MERCH_AMT_BSE AS VL_BASE_AMT, 
            --NVL(ROUND((VC.RATE_MULT/VC.RATE_DIV), 7), 0) AS VCHR_HDR_RATE, NVL(ROUND((G.RATE_MULT/G.RATE_DIV), 7), 0) AS VCHR_DIST_RATE,
            VC.RATE_MULT AS VCHR_HDR_RATE_MULT, VC.RATE_DIV AS VCHR_HDR_RATE_DIV, G.RATE_MULT AS VCHR_DIST_RATE_MULT, G.RATE_DIV AS VCHR_DIST_RATE_DIV, 
            G.FOREIGN_AMOUNT AS VCHR_DIST_FOREIGN_AMT, G.TXN_CURRENCY_CD AS VCHR_DIST_TXN_CURR, G.MONETARY_AMOUNT AS VCHR_DIST_BASE_AMT, G.QTY_VCHR AS VCHR_DIST_QTY, 
            G.QTY_VCHR, VC.INVOICE_ID, VC.MATCH_STATUS_VCHR, X9.XLATLONGNAME AS MATCH_STS_VCHR, VC.MATCH_OVERRIDE, VC.MATCHED_DT, VC.OPRID AS AP_OPRID, VC.ENTERED_DT, 
            VC.LAST_UPDATE_DT, VC.OPRID_LAST_UPDT, XREF.PYMNT_ID, XREF.PYMNT_HOLD, XREF.PYMNT_SELCT_STATUS, X11.XLATLONGNAME AS PYMNT_SELCT_STS, 
            --XREF.PAID_AMT, XREF.PYMNT_GROSS_AMT, 
            XREF.GROSS_AMT_BSE AS XREF_GROSS_AMT_BSE, XREF.PAID_AMT_BSE AS XREF_PAID_AMT_BSE,
            --NVL(ROUND((XREF.RATE_MULT/XREF.RATE_DIV), 7), 0) AS XREF_XCHNG_RATE, 
            --NVL(ROUND((XREF.PYMNT_RATE_MULT/XREF.PYMNT_RATE_DIV), 7), 0) AS PYMNT_XCHNG_RATE, NVL(ROUND((XREF.BNK_RATE_MULT/XREF.BNK_RATE_DIV), 7), 0) AS BNK_XCHNG_RATE,
            XREF.RATE_MULT, XREF.RATE_DIV, XREF.PYMNT_RATE_MULT, XREF.PYMNT_RATE_DIV, XREF.BNK_RATE_MULT, XREF.BNK_RATE_DIV, 
            XREF.BANK_SETID, XREF.BANK_CD, XREF.BANK_ACCT_KEY, PYMNT.PYMNT_ID, PYMNT.PYMNT_ID_REF, PYMNT.PAY_CYCLE, 
            PYMNT.PYMNT_STATUS, X12.XLATLONGNAME AS PYMNT_STS_DESCR, 
            PYMNT.POST_STATUS_AP, X13.XLATLONGNAME AS PYMNT_POST_STS, PYMNT.RECON_STATUS, PYMNT.CANCEL_POST_STATUS, X14.XLATLONGNAME AS PYMNT_CANCEL_STS,
            PYMNT.PYMNT_DT, PYMNT.CREATION_DT, PYMNT.OPRID AS PYMNT_CREATOR, PYMNT.PYMNT_METHOD, PYMNT.BRANCH_NAME, 
            PYMNT.PYMNT_AMT AS PYMNT_PAID_AMT, PYMNT.CURRENCY_PYMNT, A.DST_CNTRL_ID, A.MATCH_ACTION, A.MATCH_CNTRL_ID, B.DESCR254_MIXED, A.PO_REF,
            G.KK_TRAN_LN, G.KK_POSTED_AMT AS TOTAL, G.KK_FRN_POSTED_AMT, G.MONETARY_AMOUNT AS USD_Bal_Amt_ENC, G.FOREIGN_AMOUNT AS Foreign_Bal_Amt, G.FOREIGN_CURRENCY, 
            G.ACTIVITY, G.LEDGER_GROUP, G.PC_DISTRIB_STATUS, G.LIQUIDATE_METHOD, A.DST_CNTRL_ID, A.MATCH_ACTION, A.MATCH_CNTRL_ID
FROM PS_PO_HDR A, PS_PO_LINE_SHIP C, PS_VENDOR E, PSXLATITEM X1, PSXLATITEM X2, PSXLATITEM X3, PSXLATITEM X10,
         (((PS_PO_LINE B LEFT OUTER JOIN PS_MASTER_ITEM_TBL ITM ON B.ITM_SETID = ITM.SETID AND B.INV_ITEM_ID = ITM.INV_ITEM_ID)
                                 LEFT OUTER JOIN PS_PURCH_ITEM_ATTR P ON ITM.SETID = P.SETID AND ITM.INV_ITEM_ID = P.INV_ITEM_ID)
                                 LEFT OUTER JOIN PS_ITM_CAT_TBL CAT ON CAT.SETID = 'UNUNI' AND CAT.CATEGORY_ID = B.CATEGORY_ID),
          ((((((((((((((((((((((((((((((PS_PO_LINE_DISTRIB D
          LEFT OUTER JOIN PS_KK_SOURCE_HDR E ON D.BUSINESS_UNIT = E.BUSINESS_UNIT AND D.PO_ID = E.PO_ID) 
          LEFT OUTER JOIN PS_KK_SOURCE_LN F ON E.KK_TRAN_DT = F.KK_TRAN_DT AND E.KK_TRAN_ID = F.KK_TRAN_ID AND D.LINE_NBR = F.LINE_NBR 
                                                                   AND D.SCHED_NBR = F.SCHED_NBR AND D.DISTRIB_LINE_NUM = F.DISTRIB_LINE_NUM) 
          LEFT OUTER JOIN PS_KK_LIQUIDATION G ON F.KK_TRAN_ID = G.KK_TRAN_ID AND F.KK_TRAN_DT = G.KK_TRAN_DT AND F.KK_TRAN_LN = G.KK_TRAN_LN) 
          LEFT OUTER JOIN PS_REQ_LN_DISTRIB REQD ON REQD.BUSINESS_UNIT = D.BUSINESS_UNIT_REQ AND REQD.REQ_ID = D.REQ_ID AND REQD.LINE_NBR = D.REQ_LINE_NBR 
                                                                           AND REQD.SCHED_NBR = D.REQ_SCHED_NBR AND REQD.DISTRIB_LINE_NUM = D.REQ_DISTRIB_NBR)
          LEFT OUTER JOIN PS_REQ_HDR REQH ON REQD.BUSINESS_UNIT = REQH.BUSINESS_UNIT AND REQD.REQ_ID = REQH.REQ_ID)         
          LEFT OUTER JOIN PS_RECV_LN_DISTRIB RLD ON RLD.BUSINESS_UNIT_PO = D.BUSINESS_UNIT AND RLD.PO_ID = D.PO_ID AND RLD.LINE_NBR = D.LINE_NBR 
                                                               AND RLD.SCHED_NBR = D.SCHED_NBR AND RLD.PO_DIST_LINE_NUM = D.DISTRIB_LINE_NUM)
          LEFT OUTER JOIN PS_RECV_LN_ASSET RLA ON RLD.BUSINESS_UNIT = RLA.BUSINESS_UNIT AND RLD.RECEIVER_ID = RLA.RECEIVER_ID 
                                                                        AND RLD.RECV_LN_NBR = RLA.RECV_LN_NBR AND RLD.RECV_SHIP_SEQ_NBR = RLA.RECV_SHIP_SEQ_NBR 
                                                                        AND RLD.DISTRIB_LINE_NUM = RLA.DISTRIB_LINE_NUM)
          LEFT OUTER JOIN PS_RECV_LN_SHIP RLS ON RLD.BUSINESS_UNIT = RLS.BUSINESS_UNIT AND RLD.RECEIVER_ID = RLS.RECEIVER_ID AND RLD.RECV_LN_NBR = RLS.RECV_LN_NBR
                                         AND RLD.RECV_SHIP_SEQ_NBR = RLS.RECV_SHIP_SEQ_NBR)
          LEFT OUTER JOIN PS_RECV_HDR RH ON RLD.BUSINESS_UNIT = RH.BUSINESS_UNIT AND RLD.RECEIVER_ID = RH.RECEIVER_ID)
          LEFT OUTER JOIN PS_INTFC_PRE_AM PRE ON RLA.PRE_INTFC_ID = PRE.PRE_INTFC_ID AND RLA.PRE_INTFC_LINE_NUM = PRE.PRE_INTFC_LINE_NUM)
          LEFT OUTER JOIN PS_INTFC_FIN FIN ON PRE.INTFC_ID = FIN.INTFC_ID AND PRE.INTFC_LINE_NUM = FIN.INTFC_LINE_NUM)
          LEFT OUTER JOIN PS_INTFC_PHY_A PHYA ON PRE.INTFC_ID = PHYA.INTFC_ID AND PRE.INTFC_LINE_NUM = PHYA.INTFC_LINE_NUM)
          LEFT OUTER JOIN PS_DISTRIB_LINE G ON (((RLD.BUSINESS_UNIT IS NOT NULL OR RLD.BUSINESS_UNIT <> ' ') --Vouchers with receipt
                AND D.BUSINESS_UNIT = G.BUSINESS_UNIT_PO AND D.PO_ID = G.PO_ID AND D.LINE_NBR = G.LINE_NBR AND D.SCHED_NBR = G.SCHED_NBR AND D.DISTRIB_LINE_NUM = G.PO_DIST_LINE_NUM
                AND (G.BUSINESS_UNIT_RECV = RLD.BUSINESS_UNIT AND G.RECEIVER_ID = RLD.RECEIVER_ID AND G.RECV_LN_NBR = RLD.RECV_LN_NBR 
                 AND G.RECV_SHIP_SEQ_NBR = RLD.RECV_SHIP_SEQ_NBR AND G.RECV_DIST_LINE_NUM = RLD.DISTRIB_LINE_NUM))
                  OR ((RLD.BUSINESS_UNIT IS NULL OR RLD.BUSINESS_UNIT = ' ') --Vouchers with no receipt
                AND D.BUSINESS_UNIT = G.BUSINESS_UNIT_PO AND D.PO_ID = G.PO_ID AND D.LINE_NBR = G.LINE_NBR AND D.SCHED_NBR = G.SCHED_NBR AND D.DISTRIB_LINE_NUM = G.PO_DIST_LINE_NUM))
                         --G.BUSINESS_UNIT_PO = D.BUSINESS_UNIT AND G.PO_ID = D.PO_ID AND G.LINE_NBR = D.LINE_NBR AND G.SCHED_NBR = D.SCHED_NBR 
                         --AND G.PO_DIST_LINE_NUM = D.DISTRIB_LINE_NUM
                         --AND (G.BUSINESS_UNIT_RECV = RLD.BUSINESS_UNIT OR RLD.BUSINESS_UNIT IS NULL)
                         --AND (G.RECEIVER_ID = RLD.RECEIVER_ID OR RLD.RECEIVER_ID IS NULL)
                         --AND (G.RECV_LN_NBR = RLD.RECV_LN_NBR OR RLD.RECV_LN_NBR IS NULL)
                         --AND (G.RECV_SHIP_SEQ_NBR = RLD.RECV_SHIP_SEQ_NBR OR RLD.RECV_SHIP_SEQ_NBR IS NULL)
                         --AND (G.RECV_DIST_LINE_NUM = RLD.DISTRIB_LINE_NUM OR RLD.DISTRIB_LINE_NUM IS NULL)
                         )
          LEFT OUTER JOIN PS_VOUCHER VC ON G.BUSINESS_UNIT = VC.BUSINESS_UNIT AND G.VOUCHER_ID = VC.VOUCHER_ID)
          LEFT OUTER JOIN PS_VOUCHER_LINE VL ON VC.BUSINESS_UNIT = VL.BUSINESS_UNIT AND VC.VOUCHER_ID = VL.VOUCHER_ID AND G.VOUCHER_LINE_NUM = VL.VOUCHER_LINE_NUM)
          LEFT OUTER JOIN PS_RECV_VCHR_MTCH RVP ON RVP.BUSINESS_UNIT = RLD.BUSINESS_UNIT AND RVP.RECEIVER_ID = RLD.RECEIVER_ID AND RVP.RECV_LN_NBR = RLD.RECV_LN_NBR 
                         AND RVP.RECV_SHIP_SEQ_NBR = RLD.RECV_SHIP_SEQ_NBR 
                         AND (RVP.BUSINESS_UNIT_AP = VC.BUSINESS_UNIT OR VC.BUSINESS_UNIT IS NULL) AND (RVP.VOUCHER_ID = VC.VOUCHER_ID OR VC.VOUCHER_ID IS NULL) 
                         AND (RVP.VOUCHER_LINE_NUM = VL.VOUCHER_LINE_NUM OR VL.VOUCHER_LINE_NUM IS NULL)
                         AND RVP.BUSINESS_UNIT_PO = D.BUSINESS_UNIT AND RVP.PO_ID = D.PO_ID AND RVP.LINE_NBR = D.LINE_NBR AND RVP.SCHED_NBR = D.SCHED_NBR
                         )
          LEFT OUTER JOIN PS_PYMNT_VCHR_XREF XREF ON (VC.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND VC.VOUCHER_ID = XREF.VOUCHER_ID)
                                              OR (RVP.BUSINESS_UNIT_AP = XREF.BUSINESS_UNIT AND RVP.VOUCHER_ID = XREF.VOUCHER_ID))
          LEFT OUTER JOIN PS_PAYMENT_TBL PYMNT ON XREF.BANK_SETID = PYMNT.BANK_SETID AND XREF.BANK_CD= PYMNT.BANK_CD AND XREF.BANK_ACCT_KEY = PYMNT.BANK_ACCT_KEY 
                                                                         AND XREF.PYMNT_ID = PYMNT.PYMNT_ID)
          LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'RECV_STATUS' AND X4.FIELDVALUE = RH.RECV_STATUS)
          LEFT OUTER JOIN PSXLATITEM X5 ON X5.FIELDNAME = 'MATCH_STATUS_RECV' AND X5.FIELDVALUE = RH.MATCH_STATUS_RECV)
          LEFT OUTER JOIN PSXLATITEM X6 ON X6.FIELDNAME = 'RECV_SHIP_STATUS' AND X6.FIELDVALUE = RLS.RECV_SHIP_STATUS)
          LEFT OUTER JOIN PSXLATITEM X7 ON X7.FIELDNAME = 'MOVE_STAT_AM' AND X7.FIELDVALUE = RLS.MOVE_STAT_AM)
          LEFT OUTER JOIN PSXLATITEM X8 ON X8.FIELDNAME = 'RECV_AM_STATUS' AND X8.FIELDVALUE = RLA.RECV_AM_STATUS)
          LEFT OUTER JOIN PSXLATITEM X9 ON X9.FIELDNAME = 'MATCH_STATUS_VCHR' AND X9.FIELDVALUE = VC.MATCH_STATUS_VCHR)
          LEFT OUTER JOIN PSXLATITEM X11 ON X11.FIELDNAME = 'PYMNT_SELCT_STATUS' AND X11.FIELDVALUE = XREF.PYMNT_SELCT_STATUS)
          LEFT OUTER JOIN PSXLATITEM X12 ON X12.FIELDNAME = 'PYMNT_STATUS' AND X12.FIELDVALUE = PYMNT.PYMNT_STATUS)
          LEFT OUTER JOIN PSXLATITEM X13 ON X13.FIELDNAME = 'POST_STATUS_AP' AND X13.FIELDVALUE = PYMNT.POST_STATUS_AP)
          LEFT OUTER JOIN PSXLATITEM X14 ON X14.FIELDNAME = 'CANCEL_POST_STATUS' AND X14.FIELDVALUE = PYMNT.CANCEL_POST_STATUS)
          LEFT OUTER JOIN PSXLATITEM X15 ON X15.FIELDNAME = 'ENTRY_STATUS' AND X15.FIELDVALUE = VC.ENTRY_STATUS)
          LEFT OUTER JOIN PSXLATITEM X16 ON X16.FIELDNAME = 'APPR_STATUS' AND X16.FIELDVALUE = VC.APPR_STATUS)
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND A.PO_ID = B.PO_ID
  AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
  AND B.PO_ID = C.PO_ID
  AND B.LINE_NBR = C.LINE_NBR
  AND C.BUSINESS_UNIT = D.BUSINESS_UNIT
  AND C.PO_ID = D.PO_ID
  AND C.LINE_NBR = D.LINE_NBR
  AND C.SCHED_NBR = D.SCHED_NBR
  AND A.VENDOR_SETID = E.SETID
  AND A.VENDOR_ID = E.VENDOR_ID
  AND (CAT.EFFDT = (SELECT MAX(E_ED.EFFDT) FROM PS_ITM_CAT_TBL E_ED WHERE CAT.SETID = E_ED.SETID AND CAT.CATEGORY_TYPE = E_ED.CATEGORY_TYPE 
                                                                      AND CAT.CATEGORY_CD = E_ED.CATEGORY_CD AND CAT.CATEGORY_ID = E_ED.CATEGORY_ID AND E_ED.EFFDT <= SYSDATE)
     OR CAT.EFFDT IS NULL)
  --XLAT X1
  AND X1.FIELDNAME = 'PO_STATUS'
  AND X1.FIELDVALUE = A.PO_STATUS
  --XLAT X2
  AND X2.FIELDNAME = 'RECV_REQ'
  AND X2.FIELDVALUE = B.RECV_REQ
  --XLAT X3
  AND X3.FIELDNAME = 'MATCH_STATUS_PO'
  AND X3.FIELDVALUE = A.MATCH_STATUS_PO
  --XLAT X10
  AND X10.FIELDNAME = 'VENDOR_CLASS'
  AND X10.FIELDVALUE = E.VENDOR_CLASS
  AND A.BUSINESS_UNIT LIKE '6%'
  AND D.BUSINESS_UNIT_GL = 'UNUNI'
  --AND TO_CHAR(A.ACCOUNTING_DT, 'YYYY') IN ('2012')
  AND D.BUDGET_DT BETWEEN TO_DATE('2014-01-01','YYYY-MM-DD') AND TO_DATE('2014-12-31','YYYY-MM-DD')
  AND G.LEDGER_GROUP = 'DET_UU'
  AND G.MONETARY_AMOUNT <> 0
  AND D.ACCOUNT = '71405' AND D.PROJECT_ID = '00064158'
ORDER BY A.BUSINESS_UNIT, A.PO_ID, B.LINE_NBR, C.SCHED_NBR, D.DISTRIB_LINE_NUM, RLA.PRE_INTFC_ID, RLA.PRE_INTFC_LINE_NUM, PRE.INTFC_ID, PRE.INTFC_LINE_NUM;
