--Experimental Version 10
--PP Added DST_CODE_TBL
--Under Testing
SELECT 'PIT_PENDING_ITEMS_ALL', A.ENTRY_DT "Entered Date", A.GROUP_BU "Group Unit", A.GROUP_ID "Group ID", A.EDIT_STATUS, X1.XLATLONGNAME "Editing", A.POST_STATUS, X2.XLATLONGNAME "Posting Status", 
       A.CONTROL_CURRENCY "Control Currency", A.FORMAT_CURRENCY "Format Currency", A.PAYMENT_AMT "Payment Amount", A.ORIGIN_ID "Origin ID", A.GROUP_TYPE "Group Type", 
       A.OPRID "User ID", A.ASSN_OPRID "Assigned User ID", A.OPRID_APPROVED_BY "Approved User ID", A.DST_BAL_STATUS "Balanced I-Yes/O-No",
       A.CONTROL_AMT "Control Amount", A.CONTROL_CNT "Control Count", A.ENTERED_AMT "Entered Amount", A.ENTERED_CNT "Entered Count", A.POSTED_TOTAL "Posted Total", A.POSTED_COUNT "Payments Set To Post", A.GROUP_SEQ_NUM,
       A.ACCOUNTING_DT "Accounting Date", A.RECEIVED_DT "Received Date", A.POST_DT "Posted Date", A.BUSINESS_UNIT "Business Unit",
       B.CUST_ID "Customer ID", C.NAME1 "Customer Name", C.NAMESHORT, B.ASOF_DT "As Of Date", B.DUE_DT "Due Date", B.POST_DT "Peng Item Posted Date", B.ITEM "Item ID", B.ITEM_LINE "Item Line", B.GROUP_SEQ_NUM "Sequence", 
       B.ENTRY_TYPE, E.DESCRSHORT "Entry Type", B.ENTRY_REASON, ERT.DESCR "Entry Reason", B.POSTED_FLAG, B.DST_ID_AR "AR Distribution Code", DST.DESCR "AR Dist Code Descr", B.ENTRY_USE_ID "System Function ID", B.PAYMENT_METHOD,
       B.ENTRY_AMT "Entry Amount", B.ENTRY_CURRENCY "Entry Currency", B.RATE_MULT "Pndg Item Rate Multiplier", B.RATE_DIV "Pndg Item Rate Divisor", B.PAYMENT_AMT "Pndg Item Payment Amount", 
       B.PAYMENT_CURRENCY "Pndg Item Payment Currency", B.ENTRY_AMT_BASE "Pndg Item Base Amount", B.CURRENCY_CD "Currency Code", B.REAL_GAIN_LOSS "Realized Gain/Loss Amount", B.DST_ID_REAL "Realized Gain/Loss Code",
       B.ITM_PAY_AMT_BASE, B.CONTROL_CURRENCY, B.CONTROL_CURR_BASE, B.CONTROL_RATE_MULT, B.CONTROL_RATE_DIV, 
       B.AR_ERROR_CD "AR Update Error Code", ERR.AR_MSG_NUM, CAT.MESSAGE_TEXT, B.ITEM_ACCTG_DT "Original Item Accounting Date",
       B.PC_DISTRIB_STATUS "PC Distribution Status", B.AR_SEQ_NUM, B.SHIP_TO_CUST_ID "Ship To Customer", B.SOLD_TO_CUST_ID "Sold To Customer", 
       B.CONTRACT_NUM "Contract", B.GL_LVL "GL Level",--B.BUSINESS_UNIT_CA "Contracts Business Unit", B.CONTRACT_LINE_NUM "Contract Line Num",
       ITM.ITEM_STATUS, X3.XLATLONGNAME "Item Status Description", B.DST_BAL_ITEM, ITM.PO_REF "Item PO Reference", ITM.BANK_CD "Item Bank Code", ITM.BANK_ACCT_KEY "Item Bank Account", 
       ITM.DT_INVOICED "Item Date Invoiced", ITM.INVOICE "Item Invoice", ITM.SHIP_TO_CUST_ID, ITM.SOLD_TO_CUST_ID,
       ITA.ITEM_SEQ_NUM "Item Sequence Number", ITA.ENTRY_TYPE AS ITA_ENTRY_TYPE, ITA.ENTRY_CURRENCY "Item ACT Entry Currency", ITA.RATE_MULT "Item ACT Rate MULT", ITA.RATE_DIV "Item ACT Rate DIV", 
       ITA.PAYMENT_AMT "Item ACT Payment Amount", ITA.PAYMENT_CURRENCY "Item ACT Payment Currency", ITA.PYMT_RATE_MULT "Payment Rate Multiplier", ITA.PYMT_RATE_DIV "Payment Rate Divisor", 
       ITA.POSTED_PI "Last Post Process Instance", ITA.DEPOSIT_BU "Deposit Bus Unit", ITA.DEPOSIT_ID "Deposit ID", ITA.GROUP_BU "Item ACT Group Unit", ITA.GROUP_ID "Item ACT Group ID", ITA.GROUP_SEQ_NUM AS ITA_GROUP_SEQ_NUM, 
       ITA.PAYMENT_SEQ_NUM "Payment Seq", ITA.PAYMENT_ID "Payment ID", ITA.BANK_CD "Item ACT Bank Code", ITA.BANK_ACCT_KEY "Item ACT Bank Account", 
       ITA.ARRE_STATUS "Revenue Estimate Status", ARC.BUDGET_HDR_STATUS "Budget Checking Header", ARC.AR_SOURCE_TRAN "Transaction Type", ARC.KK_AMOUNT_TYPE "KK Amount Type",
       ARC.CC_AMT_MULTIPLIER "CC Amt Multiplier", ARC.CC_REV_BUCKET "Rev Estimate", ARC.FOREIGN_AMOUNT "AR KK HDR Foreign Amount", ARC.FOREIGN_CURRENCY "AR KK HDR Foreign Currency", 
       PD.ACCOUNT "Pndg Item Account", PD.DEPTID "Pndg Item DeptID", PD.OPERATING_UNIT "Pndg Item Op Unit", PD.FUND_CODE "Pndg Item Fund", PD.CHARTFIELD2 "Pndg Item Donor", PD.PROJECT_ID "Pndg Item Project ID", 
       PD.ACTIVITY_ID "Pndg Item Activity ID", PD.BUDGET_DT "Pndg Item Bud DT",
       ITMDST.DST_SEQ_NUM "Distribution Sequence", 
       ITMDST.ACCOUNT "Item Account", ITMDST.DEPTID "Item DeptID", ITMDST.OPERATING_UNIT "Item Op Unit", ITMDST.FUND_CODE "Item Fund", ITMDST.CHARTFIELD2 "Item Donor", ITMDST.PROJECT_ID "Item Project ID", 
       ITMDST.ACTIVITY_ID "Item Activity ID", ITMDST.JOURNAL_ID "Journal ID", ITMDST.APPL_JRNL_ID "Journal Template", ITMDST.MONETARY_AMOUNT "Item DST Monetary Amount",       
       DEPC.OPRID "Deposit OPRID", DEPC.ASSN_OPRID "Deposit Assigned OPRID", DEPC.DEP_POST_STATUS, X5.XLATLONGNAME "Deposit Post Status", DEPC.PAY_WS_TYPE "Payment Worksheet Type", 
       DEPC.DEPOSIT_STATUS, X6.XLATLONGNAME "Deposit Status", DEPC.BANK_CD "Deposit Bank Code", DEPC.BNK_ID_NBR "Deposit Bank ID NBR", DEPC.BANK_ACCT_KEY "Deposit Bank Account", DEPC.BANK_ACCOUNT_NUM "Deposit Bank Account NBR", 
       DEPC.DEPOSIT_TYPE "Deposit Type", DEPC.PYMT_RATE_MULT "Deposit Payment Rate MULT", DEPC.PYMT_RATE_DIV "Deposit Payment Rate DIV",
       PYMT.PAYMENT_SEQ_NUM "Pymnt Sequence NBR", PYMT.PAYMENT_ID "Pymnt ID", PYMT.PAYMENT_STATUS, X4.XLATLONGNAME "Payment Status", PYMT.PAYMENT_AMT "Pymnt Amount", PYMT.PAYMENT_CURRENCY "Pymnt Currency", 
       PYMT.UNPOST_REASON "Unpost Reason", PYMT.MISC_PAYMENT "Journal Directly Y/N", PYMT.MISC_DST_BAL "Dist Balanced Status", PYMT.CASH_CNTRL_DONE "Cash Control Complete", PYMT.CC_AFFECTED "Rev Estimate Affected", 
       PYMT.BUDGET_HDR_STATUS "Pymnt Budget Header Status",
       BIH.INVOICE, BIH.INVOICE_DT, BIH.ACCOUNTING_DT, BIH.RATE_DATE, BIH.RATE_MULT, BIH.RATE_DIV, BIH.AR_LVl, BIH.AR_DST_OPT, BIH.AR_ENTRY_CREATED, BIH.BUSINESS_UNIT_GL, BIH.GL_LVL, BIH.GL_ENTRY_CREATED, 
       BIH.ADD_DTTM, BIH.LAST_UPDATE_DTTM, BIH.LAST_MAINT_OPRID, BIH.BILL_STATUS, BIH.BANK_CD, BIH.BANK_ACCT_KEY, 
       BIL.BUSINESS_UNIT_CA, BIL.CONTRACT_NUM, BIL.CONTRACT_DT, BIL.CONTRACT_LINE_NUM, BIL.LINE_SEQ_NUM, BIL.INVOICE_LINE, BIL.LINE_TYPE, BIL.PRODUCT_ID, BIL.IDENTIFIER, BIL.DESCR, BIL.ERROR_STATUS_BI,
       BIL.BILL_PLAN_ID,
       BIL.BPLAN_LN_NBR, BIL.EVENT_OCCURRENCE, BIL.XREF_SEQ_NUM, BIL.GROSS_EXTENDED_AMT, BIL.NET_EXTENDED_AMT, BIL.GROSS_EXTENDED_BSE, BIL.NET_EXTENDED_BSE,
       CAH.CONTRACT_TYPE "Contract Type", CAH.CA_STATUS "Contract Status", CAH.CONTRACT_SIGN_DT "Contract Signed", CAH.CONTR_NET_AMT "Net Amount", CAH.CURRENCY_CD "Contract Currency", 
       TO_CHAR(CAST((CAH.LASTUPDDTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') "Last Update Date/Time HEADER", CAH.LASTUPDOPRID "Last Update User HEADER", 
       CAH.DESCR "Contract Description", CAH.AMENDMENT_DT "Amendment Date", CAH.REVISED_NET "Revised Net Amount", CAH.LEGAL_REVIEW_FLG "Legal Review Y/N",
       CAD.CONTRACT_LINE_NUM "Contract Line Nbr", CAD.DESCR "Contract Line Descr", CAD.PRICING_STRUCTURE "Pricing Structure", CAD.START_DT "Start Date DETAIL", CAD.END_DT "End Date DETAIL", CAD.GROSS_AMT "Gross Amount", 
       CAD.LASTUPDDTTM "Last Update Date/Time DETAIL", CAD.LASTUPDOPRID "Last Update User DETAIL", CAD.PRODUCT_ID "Product DETAIL", CAD.PRODUCT_GROUP "Product Group",
       CAAE.EVENT_NUM "Event Nbr", CAAE.AP_EVENT_TYPE, X10.FIELDVALUE || ' - ' || X12.XLATLONGNAME AS "Event Type", CAAE.AP_EVENT_STATUS, X11.FIELDVALUE || ' - ' || X11.XLATLONGNAME AS "Event Status",
       CAAE.ACCOUNTING_DT "Acctg Date", CAA.ACCT_PLAN_ID "Revenue Plan", CAA.REV_RECOG_METHOD, X9.FIELDVALUE || ' - ' || X9.XLATLONGNAME AS "Revenue Method", 
       CAA.AP_STATUS, X7.FIELDVALUE || ' - ' || X7.XLATLONGNAME AS "Revenue Plan Status", 
       CAAE.MILESTONE_ORIGIN, X12.FIELDVALUE || ' - ' || X12.XLATLONGNAME AS "M/S Origin", CAAE.MS_SEQNUM "M/S Nbr", CAM.DESCR "M/S Descr",
       CAM.MILESTONE_STATUS, X13.FIELDVALUE || ' - ' || X13.XLATLONGNAME AS "M/S Status", CAM.COMPLETION_DATE "M/S Compl Date", CAM.ESTIMATED_COMP_DT "M/S Estd Compl Date",
       CAAE.AMOUNT "Revenue Amount", CAAE.CURRENCY_CD "Rev Transaction Curr", CAA.CA_ALLOC_METHOD, X8.FIELDVALUE || ' - ' || X8.XLATLONGNAME AS " REV Allocation Method",
       BP.BP_STATUS, X15.FIELDVALUE || ' - ' || X15.XLATLONGNAME AS "Bill Plan Status",
       BP.BILL_PLAN_TYPE, X16.FIELDVALUE || ' - ' || X16.XLATLONGNAME AS "Bill Plan Type", BPE.EVENT_OCCURRENCE "Bill Plan Evt Occur", 
       BPE.BILL_EVENT_TYPE, X17.FIELDVALUE || ' - ' || X17.XLATLONGNAME AS "Bill Plan Event Type", BPE.BP_EVENT_STATUS, X14.FIELDVALUE || ' - ' || X14.XLATLONGNAME AS "Bill Plan Event Status",
       BPE.AMOUNT "Billing Amount", BPE.CURRENCY_CD "Bill Transaction Curr",
       CADD.ACCOUNT "Cntrct Acct", CADD.OPERATING_UNIT "Cntrct Op Unit", CADD.FUND_CODE "Cntrct Fund", CADD.DEPTID "Cntrct Dtl DeptID", CADD.PROJECT_ID "Cntrct Prj ID", CADD.CHARTFIELD2 "Cntrct Donor", CADD.COMBO_VALID_FLG,
       CADP.BUSINESS_UNIT_PC "Cntrct Trms PC BU", CADP.PROJECT_ID "Cntrct Trms Prj ID", CADP.ACTIVITY_ID "Cntrct Trms Act ID"
FROM ((((((((((((((((((((((((((((((((((((((((((PS_GROUP_CONTROL A 
         LEFT OUTER JOIN PS_PENDING_ITEM B ON A.GROUP_BU = B.GROUP_BU AND A.GROUP_ID = B.GROUP_ID)
         LEFT OUTER JOIN PS_AR_ERROR_TBL ERR ON B.AR_ERROR_CD = ERR.AR_ERROR_CD)
         LEFT OUTER JOIN PSMSGCATDEFN CAT ON CAT.MESSAGE_SET_NBR = 6035 AND MESSAGE_NBR = ERR.AR_MSG_NUM)
         LEFT OUTER JOIN PS_PENDING_DST PD ON B.GROUP_BU = PD.GROUP_BU AND B.GROUP_ID = PD.GROUP_ID AND B.BUSINESS_UNIT = PD.BUSINESS_UNIT AND B.CUST_ID = PD.CUST_ID AND B.ITEM = PD.ITEM AND B.ITEM_LINE = PD.ITEM_LINE 
                                          AND B.GROUP_SEQ_NUM = PD.GROUP_SEQ_NUM AND PD.SYSTEM_DEFINED = 'A')
         LEFT OUTER JOIN PS_ITEM ITM ON ITM.BUSINESS_UNIT = B.BUSINESS_UNIT AND ITM.CUST_ID =  B.CUST_ID AND ITM.ITEM = B.ITEM AND ITM.ITEM_LINE = B.ITEM_LINE)
         LEFT OUTER JOIN PS_ITEM_ACTIVITY ITA ON ITA.BUSINESS_UNIT = ITM.BUSINESS_UNIT AND ITA.CUST_ID =  ITM.CUST_ID AND ITA.ITEM = ITM.ITEM AND ITA.ITEM_LINE = ITM.ITEM_LINE 
                                             AND A.GROUP_BU = ITA.GROUP_BU AND A.GROUP_ID = ITA.GROUP_ID AND B.GROUP_SEQ_NUM = ITA.GROUP_SEQ_NUM)
         LEFT OUTER JOIN PS_AR_CC_TRAN_HDR ARC ON ITA.BUSINESS_UNIT =  ARC.BUSINESS_UNIT AND ITA.CUST_ID =  ARC.CUST_ID AND ITA.ITEM =  ARC.ITEM AND ITA.ITEM_LINE =  ARC.ITEM_LINE AND ITA.ITEM_SEQ_NUM =  ARC.ITEM_SEQ_NUM)
         LEFT OUTER JOIN PS_BI_HDR BIH ON BIH.BUSINESS_UNIT = ITM.BUSINESS_UNIT_BI AND BIH.INVOICE = ITM.INVOICE)
         LEFT OUTER JOIN PS_BI_LINE BIL ON BIH.BUSINESS_UNIT = BIL.BUSINESS_UNIT AND BIH.INVOICE = BIL.INVOICE)
         LEFT OUTER JOIN PS_CA_CONTR_HDR CAH ON BIL.CONTRACT_NUM = CAH.CONTRACT_NUM AND BIL.BUSINESS_UNIT = CAH.BUSINESS_UNIT_BI AND BIL.BUSINESS_UNIT_CA = CAH.BUSINESS_UNIT)
         LEFT OUTER JOIN PS_CA_DETAIL CAD ON CAH.CONTRACT_NUM = CAD.CONTRACT_NUM)
         LEFT OUTER JOIN PS_CA_ACCTPLAN CAA ON CAH.CONTRACT_NUM = CAA.CONTRACT_NUM)
         LEFT OUTER JOIN PS_CA_AP_EVENT CAAE ON CAH.CONTRACT_NUM = CAAE.CONTRACT_NUM AND CAA.ACCT_PLAN_ID = CAAE.ACCT_PLAN_ID AND CAAE.EVENT_NUM = BIL.EVENT_OCCURRENCE)
         LEFT OUTER JOIN PS_CA_MILESTONE CAM ON CAH.CONTRACT_NUM = CAM.CONTRACT_NUM AND CAAE.MS_SEQNUM = CAM.MS_SEQNUM)
         LEFT OUTER JOIN PS_CA_DETAIL_DST CADD ON CAH.CONTRACT_NUM = CADD.CONTRACT_NUM AND CAD.CONTRACT_LINE_NUM = CADD.CONTRACT_LINE_NUM)
         LEFT OUTER JOIN PS_CA_DETAIL_PROJ CADP ON CAH.CONTRACT_NUM = CADP.CONTRACT_NUM AND CAD.CONTRACT_LINE_NUM = CADP.CONTRACT_LINE_NUM)
         LEFT OUTER JOIN PS_CA_BILL_PLAN BP ON CAH.CONTRACT_NUM = BP.CONTRACT_NUM)
         LEFT OUTER JOIN PS_CA_BP_EVENTS BPE ON BP.CONTRACT_NUM = BPE.CONTRACT_NUM AND BP.BILL_PLAN_ID = BPE.BILL_PLAN_ID AND BPE.EVENT_OCCURRENCE = BIL.EVENT_OCCURRENCE)
         LEFT OUTER JOIN PSXLATITEM X7 ON X7.FIELDNAME = 'AP_STATUS' AND X7.FIELDVALUE = CAA.AP_STATUS AND X7.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X8 ON X8.FIELDNAME = 'CA_ALLOC_METHOD' AND X8.FIELDVALUE = CAA.CA_ALLOC_METHOD AND X8.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X9 ON X9.FIELDNAME = 'REV_RECOG_METHOD' AND X9.FIELDVALUE = CAA.REV_RECOG_METHOD AND X9.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X10 ON X10.FIELDNAME = 'AP_EVENT_TYPE' AND X10.FIELDVALUE = CAAE.AP_EVENT_TYPE AND X10.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X11 ON X11.FIELDNAME = 'AP_EVENT_STATUS' AND X11.FIELDVALUE = CAAE.AP_EVENT_STATUS AND X11.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X12 ON X12.FIELDNAME = 'MILESTONE_ORIGIN' AND X12.FIELDVALUE = CAAE.MILESTONE_ORIGIN AND X12.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X13 ON X13.FIELDNAME = 'MILESTONE_STATUS' AND X13.FIELDVALUE = CAM.MILESTONE_STATUS AND X13.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X14 ON X14.FIELDNAME = 'BP_EVENT_STATUS' AND X14.FIELDVALUE = BPE.BP_EVENT_STATUS AND X14.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X15 ON X15.FIELDNAME = 'BP_STATUS' AND X15.FIELDVALUE = BP.BP_STATUS AND X15.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X16 ON X16.FIELDNAME = 'BILL_PLAN_TYPE' AND X16.FIELDVALUE = BP.BILL_PLAN_TYPE AND X16.EFF_STATUS = 'A')
         LEFT OUTER JOIN PSXLATITEM X17 ON X17.FIELDNAME = 'BILL_EVENT_TYPE' AND X17.FIELDVALUE = BPE.BILL_EVENT_TYPE AND X17.EFF_STATUS = 'A')
         --LEFT OUTER JOIN PS_ITEM_ACTIVITY ITA ON A.GROUP_BU = ITA.GROUP_BU AND A.GROUP_ID = ITA.GROUP_ID AND A.BUSINESS_UNIT = ITA.BUSINESS_UNIT)
         --LEFT OUTER JOIN PS_ITEM ITM ON ITM.BUSINESS_UNIT = ITA.BUSINESS_UNIT AND ITM.CUST_ID =  ITA.CUST_ID AND ITM.ITEM = ITA.ITEM AND ITM.ITEM_LINE = ITA.ITEM_LINE)
         LEFT OUTER JOIN PS_ITEM_DST ITMDST ON ITA.BUSINESS_UNIT = ITMDST.BUSINESS_UNIT AND ITA.CUST_ID = ITMDST.CUST_ID AND ITA.ITEM = ITMDST.ITEM 
                                           AND ITA.ITEM_LINE = ITMDST.ITEM_LINE AND ITA.ITEM_SEQ_NUM = ITMDST.ITEM_SEQ_NUM AND ITMDST.SYSTEM_DEFINED = 'A')
         LEFT OUTER JOIN PS_DEPOSIT_CONTROL DEPC ON ITA.DEPOSIT_BU = DEPC.DEPOSIT_BU AND ITA.DEPOSIT_ID = DEPC.DEPOSIT_ID)
         LEFT OUTER JOIN PS_PAYMENT PYMT ON DEPC.DEPOSIT_BU = PYMT.DEPOSIT_BU AND DEPC.DEPOSIT_ID = PYMT.DEPOSIT_ID AND ITA.PAYMENT_SEQ_NUM = PYMT.PAYMENT_SEQ_NUM)
         LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'PAYMENT_STATUS' AND X4.FIELDVALUE = PYMT.PAYMENT_STATUS)
         LEFT OUTER JOIN PSXLATITEM X5 ON X5.FIELDNAME = 'DEP_POST_STATUS' AND X5.FIELDVALUE = DEPC.DEP_POST_STATUS)
         LEFT OUTER JOIN PSXLATITEM X6 ON X6.FIELDNAME = 'DEPOSIT_STATUS' AND X6.FIELDVALUE = DEPC.DEPOSIT_STATUS)
         LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'ITEM_STATUS' AND X3.FIELDVALUE = ITM.ITEM_STATUS)
         LEFT OUTER JOIN PS_CUSTOMER C ON C.SETID = 'UNUNI' AND B.CUST_ID = C.CUST_ID)
         LEFT OUTER JOIN PS_ENTRY_TYPE_TBL E ON E.SETID = 'UNUNI' AND E.ENTRY_TYPE = B.ENTRY_TYPE)
         LEFT OUTER JOIN PS_ENTRY_REASN_TBL ERT ON ERT.SETID = E.SETID AND E.ENTRY_TYPE = ERT.ENTRY_TYPE AND B.ENTRY_REASON = ERT.ENTRY_REASON) 
         LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'EDIT_STATUS' AND X1.FIELDVALUE = A.EDIT_STATUS)
         LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'POST_STATUS' AND X2.FIELDVALUE = A.POST_STATUS)
         LEFT OUTER JOIN PS_DST_CODE_TBL DST ON DST.DST_ID = B.DST_ID_AR)
WHERE A.GROUP_BU LIKE '6%'
  --AND A.ACCOUNTING_DT BETWEEN TO_DATE('2013-01-01','YYYY-MM-DD') AND TO_DATE('2013-12-31','YYYY-MM-DD')
  AND (CADD.EFFDT = (SELECT MAX(CADD_ED.EFFDT) FROM PS_CA_DETAIL_DST CADD_ED WHERE CADD.CONTRACT_NUM = CADD_ED.CONTRACT_NUM AND CADD.CONTRACT_LINE_NUM = CADD_ED.CONTRACT_LINE_NUM 
                                                                               AND CADD.DST_SEQ_NUM = CADD_ED.DST_SEQ_NUM AND CADD_ED.EFFDT<= SYSDATE)
       OR CADD.EFFDT IS NULL)
  AND (DST.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC DST_A WHERE DST_A.SETCNTRLVALUE = B.BUSINESS_UNIT AND DST_A.RECNAME = 'DST_CODE_TBL') 
    OR DST.SETID IS NULL)
  AND (DST.EFFDT = (SELECT MAX(EFFDT) FROM PS_DST_CODE_TBL DST_X WHERE DST_X.SETID = DST.SETID AND DST_X.DST_ID = DST.DST_ID AND DST_X.EFFDT <= SYSDATE AND DST_X.EFF_STATUS = 'A')
    OR DST.EFFDT IS NULL)
  AND A.ENTRY_DT BETWEEN TO_DATE('2015-01-01','YYYY-MM-DD') AND TO_DATE('2020-12-31','YYYY-MM-DD')
  --AND B.CUST_ID IN ('10824', '10685')
  --AND B.ITEM = 'NET OCW - OPCONTR APR-2014'
ORDER BY A.ENTRY_DT, A.GROUP_BU, A.GROUP_ID, A.BUSINESS_UNIT, B.CUST_ID, B.ITEM, B.ITEM_LINE, ITA.ITEM_SEQ_NUM, ITA.GROUP_SEQ_NUM, CAH.CONTRACT_NUM, CAD.CONTRACT_LINE_NUM, cAAE.EVENT_NUM, CAAE.MS_SEQNUM, CAA.ACCT_PLAN_ID;
