--Receipt Delivery Report
--Experimental Version 3
SELECT A.BUSINESS_UNIT "Receipt BU", A.RECEIVER_ID "Receipt #", TO_CHAR(A.RECEIPT_DT,'YYYY-MM-DD') "Received Date", A.RECV_STATUS, X1.XLATLONGNAME "Receipt Status", A.MATCH_STATUS_RECV, X2.XLATLONGNAME "Match Status",
       B.RECV_LN_NBR "Receipt Line #", B.RECV_SHIP_SEQ_NBR "Receiver Shipping Seq #", C.DISTRIB_LINE_NUM "Distrib Line #", RLA.DISTRIB_SEQ_NUM "Distrib Seq #", A.OPRID "Receipt HDR User ID",
       C.QTY_DS_ACCPT_VUOM "Distributed Qty in Vendor UOM", TO_CHAR(B.DUE_DT,'YYYY-MM-DD') "Due Date", TO_CHAR(C.DELIVERED_DT,'YYYY-MM-DD') "Delivered Date", 
       B.QTY_SH_REJCT_VUOM "Reject Quantity in Vendor UOM", B.QTY_SH_ACCPT_VUOM "Accept Quantity in Vendor UOM", B.QTY_SH_RECVD_VUOM "Receipt Quantity in Vendor UOM", C.QTY_PO "PO Qty on Recv Ln Distrib", 
       A.BILL_OF_LADING "Bill of Lading", B.BUSINESS_UNIT_PO "PO BU", POH.PO_STATUS, X4.XLATLONGNAME "PO Status", B.PO_ID "Purchase Order", B.LINE_NBR "PO Line #", B.SCHED_NBR "PO Sched #", 
       C.PO_DIST_LINE_NUM "PO Distrib Line #", 
       TO_CHAR(POH.PO_DT,'YYYY-MM-DD') "PO Date", TO_CHAR(POH.ACCOUNTING_DT,'YYYY-MM-DD') "PO Accounting Date", TO_CHAR(POD.BUDGET_DT,'YYYY-MM-DD') "PO Budget Date", TO_CHAR(POH.ACTIVITY_DATE,'YYYY-MM-DD') "PO Last Activity",
       POL.CANCEL_STATUS "PO Line Cancel Status", POD.DISTRIB_LN_STATUS "PO Distrib Line Status", POD.KK_CLOSE_FLAG "PO KK Close Flag", POD.KK_PROCESS_PRIOR "PO Process Prior Document", 
       POD.KK_CLOSE_PRIOR "PO Close Prior Transaction", POD.QTY_PO "PO Qty Distrib", POD.MERCH_AMT_BSE "PO Dist Base Merchandise Amt", POC.DISTRIB_MTHD_FLG "Distribute by", POC.MATCH_STATUS_LN_PO "Match Status PO Line", 
       POC.PRICE_PO "PO Price Line Ship", POC.PRICE_PO_BSE "Price Base Line Ship", POC.QTY_PO "PO Qty Line Ship", POC.MERCHANDISE_AMT "Merchandise Amt Line Ship", POC.CURRENCY_CD "Curr Cd Line Ship", 
       POC.MERCH_AMT_BSE "Base Merchandise Amt Line Ship", POC.FREIGHT_TERMS "Freight Terms Code", POC.MATCH_LINE_OPT "Match Line Option", POD.MERCHANDISE_AMT "Merchandise Amt PO Distrib", POD.CURRENCY_CD "Curr Cd PO Distrib", 
       POH.CURRENCY_CD "PO HDR Currency", POL.RECV_REQ, X5.XLATLONGNAME "Receiving Required PO", B.CATEGORY_ID "Category ID", CAT.CATEGORY_CD "Category Code", CAT.ACCOUNT "Category Account",
       B.INV_ITEM_ID "Item ID", ITM.DESCR "Item Descr", P.ACCOUNT "Item Account", POL.CNTRCT_SETID "Contract SetID", POL.CNTRCT_ID "Contract ID", POL.CNTRCT_LINE_NBR "Contract Line #", 
       POL.RELEASE_NBR "Release #", POL.AMT_ONLY_FLG "Amt Only", A.VENDOR_ID  "Vendor ID", E.NAME1 "Vendor Name", C.REQ_ID "Requisition #", C.LOCATION "Location", D.DESCR "Location Description",
       B.DESCR254_MIXED "More Info", B.RECEIPT_UM "Vndr UOM", B.REJECT_REASON "Reject Reason Code", B.REJECT_ACTION "Action On Rejection", C.DELIVERED_TO "Delivered To", A.SHIPTO_ID "Ship To Location", 
       C.DELIVERED_FLG "Delivered Flag", A.INTFC_ASSET "Process AM", C.BUSINESS_UNIT_AM "BU AM", C.PROFILE_ID "AM Profile ID", B.MOVE_STAT_AM, X3.XLATLONGNAME "AM Move Status", RLA.ACTUAL_COST "Unit Cost", 
       RLA.COST "Total Cost", RLA.CUSTODIAN "Custodian", RLA.DESCR "RLA Description", TO_CHAR(CAST((RLA.DTTM_STAMP) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') "RLA Date/Time Stamp", 
       RLA.FINANCIAL_ASSET_SW "Capitalized Asset", RLA.LOCATION "RLA Location", 
       RLA.MODEL "Model", RLA.SERIAL_ID "Serial ID", RLA.TAG_NUMBER "Tag Number", RLA.PRE_INTFC_ID "Pre-Interface ID", RLA.PRE_INTFC_LINE_NUM "Pre-Interface Line #", RLA.PRICE_PO_BSE "RLA PO Price Base", 
       RLA.RECV_AM_STATUS "RECV AM Intfc Status", PRE.INTFC_ID "Interface ID", PRE.INTFC_LINE_NUM "Interface Line #", PRE.LOAD_STATUS "PRE Load Status", TO_CHAR(PRE.TRANS_DT,'YYYY-MM-DD') "Transaction Date", 
       TO_CHAR(PRE.ACCOUNTING_DT,'YYYY-MM-DD') "AM Intfc Accounting Date", PRE.TXN_COST "Transaction Cost", PRE.TXN_CURRENCY_CD "Transaction Currency", 
       FIN.BUSINESS_UNIT "AM BU FIN", FIN.ASSET_ID "Asset ID FIN", TO_CHAR(CAST((FIN.DTTM_STAMP) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') "FIN Date/Time Stamp", 
       FIN.INTFC_TYPE "Trans Load Type", FIN.INTFC_STATUS "Interface Status", FIN.LOAD_STATUS "Load Status", TO_CHAR(FIN.IN_SERVICE_DT,'YYYY-MM-DD') "In Service Date", FIN.OPEN_TRANS_ID "Open Transaction ID", 
       PHYA.BUSINESS_UNIT "AM BU PHYA", PHYA.ASSET_ID "Asset ID PHYA", TO_CHAR(PHYA.ACQUISITION_DT,'YYYY-MM-DD') "Acquisition Date", PHYA.DESCR "Asset Descr PHYA",
       G.BUSINESS_UNIT "AP BU", G.VOUCHER_ID "Voucher ID", G.VOUCHER_LINE_NUM "Voucher Line #", G.DISTRIB_LINE_NUM "Voucher Distrib #", G.QTY_VCHR "Quantity VCHR", VC.INVOICE_ID "Invoice ID", 
       VC.TXN_CURRENCY_CD "Voucher Transact Curr", VC.GROSS_AMT "Gross Invoice Amount", VC.GROSS_AMT_BSE "Base Gross Amount", 
       VC.APPR_STATUS "Approval Status", VC.APPR_INSTANCE "Approval Instance", VC.OPRID "Voucher User ID", TO_CHAR(VC.ENTERED_DT,'YYYY-MM-DD') "Voucher Entered on", 
       TO_CHAR(VC.LAST_UPDATE_DT,'YYYY-MM-DD') "Voucher Last Updated", VC.OPRID_LAST_UPDT "Voucher Last User to Update", 
       VC.MATCH_STATUS_VCHR "Voucher Match Status", VC.MATCH_OVERRIDE "Match Override", TO_CHAR(VC.MATCHED_DT,'YYYY-MM-DD') "Voucher Matched Date", 
       VC.VOUCHER_STYLE "Voucher Style", VC.CLOSE_STATUS "Close Status", VC.ENTRY_STATUS "Entry Status",
       G.FOREIGN_AMOUNT "Voucher Dist Foreign Amt", G.TXN_CURRENCY_CD "Voucher Dist Foreign Curr Cd", G.MONETARY_AMOUNT "Voucher Dist Base Amt", G.QTY_VCHR "Voucher Dist Qty", 
       VC.RATE_MULT "Voucher HDR Rate Mult", VC.RATE_DIV "Voucher HDR Rate Div", G.RATE_MULT "Voucher Distrib Rate Mult", G.RATE_DIV "Voucher Distrib Rate Div", G.ACCOUNT "VCHR_ACCOUNT",
       FIN.PROCESS_INSTANCE, D.BUILDING, D.FLOOR, D.ATTN_TO, D.ADDRESS1, D.ADDRESS2, D.ADDRESS3, D.ADDRESS4, D.CITY, D.STATE, D.POSTAL, D.PHONE
FROM ((PS_RECV_HDR A LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'RECV_STATUS' AND X1.FIELDVALUE = A.RECV_STATUS)
       LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'MATCH_STATUS_RECV' AND X2.FIELDVALUE = A.MATCH_STATUS_RECV), 
       ((((PS_RECV_LN_SHIP B LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'MOVE_STAT_AM' AND X3.FIELDVALUE = B.MOVE_STAT_AM)
        LEFT OUTER JOIN PS_MASTER_ITEM_TBL ITM ON B.ITM_SETID = ITM.SETID AND B.INV_ITEM_ID = ITM.INV_ITEM_ID)
        LEFT OUTER JOIN PS_PURCH_ITEM_ATTR P ON ITM.SETID = P.SETID AND ITM.INV_ITEM_ID = P.INV_ITEM_ID)
        LEFT OUTER JOIN PS_ITM_CAT_TBL CAT ON CAT.SETID = 'UNUNI' AND CAT.CATEGORY_ID = B.CATEGORY_ID), PS_VENDOR E,
       ((((((((((((PS_RECV_LN_DISTRIB C LEFT OUTER JOIN PS_RECV_LN_ASSET RLA ON C.BUSINESS_UNIT = RLA.BUSINESS_UNIT AND C.RECEIVER_ID = RLA.RECEIVER_ID 
                                                                             AND C.RECV_LN_NBR = RLA.RECV_LN_NBR AND C.RECV_SHIP_SEQ_NBR = RLA.RECV_SHIP_SEQ_NBR
                                                                             AND C.DISTRIB_LINE_NUM = RLA.DISTRIB_LINE_NUM)
          LEFT OUTER JOIN PS_INTFC_PRE_AM PRE ON RLA.PRE_INTFC_ID = PRE.PRE_INTFC_ID AND RLA.PRE_INTFC_LINE_NUM = PRE.PRE_INTFC_LINE_NUM)
          LEFT OUTER JOIN PS_INTFC_FIN FIN ON PRE.INTFC_ID = FIN.INTFC_ID AND PRE.INTFC_LINE_NUM = FIN.INTFC_LINE_NUM)
          LEFT OUTER JOIN PS_INTFC_PHY_A PHYA ON PRE.INTFC_ID = PHYA.INTFC_ID AND PRE.INTFC_LINE_NUM = PHYA.INTFC_LINE_NUM) 
          LEFT OUTER JOIN PS_PO_HDR POH ON C.BUSINESS_UNIT_PO = POH.BUSINESS_UNIT AND C.PO_ID = POH.PO_ID)
          LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'PO_STATUS' AND X4.FIELDVALUE = POH.PO_STATUS)
          LEFT OUTER JOIN PS_PO_LINE POL ON C.BUSINESS_UNIT_PO = POL.BUSINESS_UNIT AND C.PO_ID = POL.PO_ID AND C.LINE_NBR = POL.LINE_NBR)
          LEFT OUTER JOIN PS_PO_LINE_SHIP POC ON C.BUSINESS_UNIT_PO = POC.BUSINESS_UNIT AND C.PO_ID = POC.PO_ID AND C.LINE_NBR = POC.LINE_NBR AND C.SCHED_NBR = POC.SCHED_NBR)
          LEFT OUTER JOIN PS_PO_LINE_DISTRIB POD ON C.BUSINESS_UNIT_PO = POD.BUSINESS_UNIT AND C.PO_ID = POD.PO_ID AND C.LINE_NBR = POD.LINE_NBR AND C.SCHED_NBR = POD.SCHED_NBR
                                                AND C.PO_DIST_LINE_NUM = POD.DISTRIB_LINE_NUM)
          LEFT OUTER JOIN PSXLATITEM X5 ON X5.FIELDNAME = 'RECV_REQ' AND X5.FIELDVALUE = POL.RECV_REQ)
          LEFT OUTER JOIN PS_DISTRIB_LINE G ON (((C.BUSINESS_UNIT IS NOT NULL OR C.BUSINESS_UNIT <> ' ') --Vouchers with receipt
                AND POD.BUSINESS_UNIT = G.BUSINESS_UNIT_PO AND POD.PO_ID = G.PO_ID AND POD.LINE_NBR = G.LINE_NBR AND POD.SCHED_NBR = G.SCHED_NBR 
                AND POD.DISTRIB_LINE_NUM = G.PO_DIST_LINE_NUM
                AND (G.BUSINESS_UNIT_RECV = C.BUSINESS_UNIT AND G.RECEIVER_ID = C.RECEIVER_ID AND G.RECV_LN_NBR = C.RECV_LN_NBR 
                 AND G.RECV_SHIP_SEQ_NBR = C.RECV_SHIP_SEQ_NBR AND G.RECV_DIST_LINE_NUM = C.DISTRIB_LINE_NUM))
                  OR ((C.BUSINESS_UNIT IS NULL OR C.BUSINESS_UNIT = ' ') --Vouchers with no receipt
                AND POD.BUSINESS_UNIT = G.BUSINESS_UNIT_PO AND POD.PO_ID = G.PO_ID AND POD.LINE_NBR = G.LINE_NBR AND POD.SCHED_NBR = G.SCHED_NBR 
                AND POD.DISTRIB_LINE_NUM = G.PO_DIST_LINE_NUM))
          LEFT OUTER JOIN PS_VOUCHER VC ON G.BUSINESS_UNIT = VC.BUSINESS_UNIT AND G.VOUCHER_ID = VC.VOUCHER_ID)
          LEFT OUTER JOIN PS_LOCATION_TBL D ON C.LOCATION = D.LOCATION)
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
    AND A.RECEIVER_ID = B.RECEIVER_ID
    AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
    AND B.RECEIVER_ID = C.RECEIVER_ID
    AND B.RECV_LN_NBR = C.RECV_LN_NBR
    AND B.RECV_SHIP_SEQ_NBR = C.RECV_SHIP_SEQ_NBR
    --AND B.RECV_SHIP_STATUS NOT IN ('X','C')
    AND A.VENDOR_SETID = E.SETID
    AND A.VENDOR_ID = E.VENDOR_ID
    AND (D.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC F WHERE F.SETCNTRLVALUE = A.BUSINESS_UNIT AND F.RECNAME = 'LOCATION_TBL') 
      OR D.SETID IS NULL)
    AND (CAT.EFFDT = (SELECT MAX(E_ED.EFFDT) FROM PS_ITM_CAT_TBL E_ED WHERE CAT.SETID = E_ED.SETID AND CAT.CATEGORY_TYPE = E_ED.CATEGORY_TYPE AND CAT.CATEGORY_CD = E_ED.CATEGORY_CD AND CAT.CATEGORY_ID = E_ED.CATEGORY_ID 
                                                                        AND E_ED.EFFDT <= SYSDATE)
     OR CAT.EFFDT IS NULL)
    --AND C.QTY_DS_ACCPT_VUOM > 0
    AND (D.EFFDT = (SELECT MAX(G_ED.EFFDT) FROM PS_LOCATION_TBL G_ED WHERE D.SETID = G_ED.SETID AND D.LOCATION = G_ED.LOCATION --AND G_ED.EFFDT <= B.DUE_DT
                                                                      AND G_ED.EFFDT <= SYSDATE)
      OR D.EFFDT IS NULL)
    AND A.BUSINESS_UNIT LIKE '6%'
    AND A.RECEIPT_DT BETWEEN TO_DATE('2015-01-01','YYYY-MM-DD') AND TO_DATE('2015-12-31','YYYY-MM-DD')
ORDER BY A.BUSINESS_UNIT, A.RECEIVER_ID, B.RECV_LN_NBR, B.RECV_SHIP_SEQ_NBR, C.DISTRIB_LINE_NUM, RLA.DISTRIB_SEQ_NUM;
