--FSCM PvG
--Version 1
SELECT PGC.PTPG_PGRIDTITLE "Pivod Grid Title", PGM.PTPG_PGRIDNAME "Pivot Grid Name", PGM.PTPG_DSUNIQUEFLD "Unique Heading",
       PGM.PTPG_DSCOLUMN "Data Source Columns", PGM.PTPG_FORMAT "Field Format",
       PGQP.PTPG_VIEWNAME "View Name", PGQP.PTPG_QRYPROMPNAME "Query Prompt Name", PGQP.PTPG_QRYPROMPREC "Prompt Record", PGQP.FIELDNAME "Field Name",
       PGQP.PTPG_QRYPROMPTVAL "Query Prompt Values", PGQP.PTPG_PRMPTXLATVAL "Translate Value", PGS.PTPG_DSNAME "Data Source Name", PGS.PTPG_DSVALUE "Data Source Value",
       PGC.PTPG_DSTYPE, PGC.PTPG_PGRIDTYPE, PGC.OBJECTOWNERID || ' - ' || X1.XLATLONGNAME AS "PvG Object Ident", RECD.OBJECTOWNERID || ' - ' || X2.XLATLONGNAME AS "Record Object Ident",
       QRYD.QRYNAME, QRYF.RECNAME, QRYF.FIELDNAME, QRYF.FLDNUM
--       SUBSTR(PGQP.PTPG_VIEWNAME, 1, LENGTH(PGQP.PTPG_VIEWNAME)-5)
FROM ((((((PSPGMODEL PGM LEFT OUTER JOIN PSPGQRYPROMPT PGQP ON PGM.PTPG_PGRIDNAME = PGQP.PTPG_PGRIDNAME
                                                      AND PGQP.FIELDNAME = SUBSTR(PGM.PTPG_DSUNIQUEFLD, 3, LENGTH(PGM.PTPG_DSUNIQUEFLD))
                                                      AND SUBSTR(PGQP.PTPG_VIEWNAME, 1, LENGTH(PGQP.PTPG_VIEWNAME)-5) = PGQP.PTPG_PGRIDNAME)
      LEFT OUTER JOIN PSPGSETTINGS PGS ON PGS.PTPG_PGRIDNAME = PGM.PTPG_PGRIDNAME)
      LEFT OUTER JOIN PSQRYDEFN QRYD ON QRYD.QRYNAME = PGS.PTPG_DSVALUE)
      LEFT OUTER JOIN PSQRYFIELD QRYF ON QRYF.QRYNAME = QRYD.QRYNAME AND QRYF.QRYFLDNAME = PGM.PTPG_DSUNIQUEFLD)
      LEFT OUTER JOIN PSRECDEFN RECD ON QRYF.RECNAME = RECD.RECNAME)
      LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'OBJECTOWNERID' AND X2.FIELDVALUE = RECD.OBJECTOWNERID AND X2.EFF_STATUS = 'A'),
      (PSPGCORE PGC LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'OBJECTOWNERID' AND X1.FIELDVALUE = PGC.OBJECTOWNERID AND X1.EFF_STATUS = 'A')
WHERE 1 = 1
  AND PGM.PTPG_PGRIDNAME = PGC.PTPG_PGRIDNAME
--  AND PGM.PTPG_PGRIDNAME = 'AP_S360_DB_AMOUNT_BY_STATUS'
--  AND PGQP.FIELDNAME <> ' '
ORDER BY PGM.PTPG_PGRIDNAME, QRYF.FLDNUM;
