select /*insert*/ * from PSXLATITEM WHERE FIELDNAME = 'PMT_STATUS';

REM INSERTING into PSXLATITEM
SET DEFINE OFF;
Insert into PSXLATITEM (FIELDNAME,FIELDVALUE,EFFDT,EFF_STATUS,XLATLONGNAME,XLATSHORTNAME,LASTUPDDTTM,LASTUPDOPRID,SYNCID) values ('PMT_STATUS','C',to_date('01-JAN-00','DD-MON-RR'),'A','Canceled','Canceled',to_timestamp('24-AUG-04 05.16.17.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'PPLSOFT',30568);
Insert into PSXLATITEM (FIELDNAME,FIELDVALUE,EFFDT,EFF_STATUS,XLATLONGNAME,XLATSHORTNAME,LASTUPDDTTM,LASTUPDOPRID,SYNCID) values ('PMT_STATUS','E',to_date('01-JAN-00','DD-MON-RR'),'A','Error','Error',to_timestamp('20-APR-04 05.53.25.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'PPLSOFT',30569);
Insert into PSXLATITEM (FIELDNAME,FIELDVALUE,EFFDT,EFF_STATUS,XLATLONGNAME,XLATSHORTNAME,LASTUPDDTTM,LASTUPDOPRID,SYNCID) values ('PMT_STATUS','H',to_date('01-JAN-00','DD-MON-RR'),'A','Flagged for Hold','Hold',to_timestamp('04-MAY-04 05.04.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'PPLSOFT',30570);
Insert into PSXLATITEM (FIELDNAME,FIELDVALUE,EFFDT,EFF_STATUS,XLATLONGNAME,XLATSHORTNAME,LASTUPDDTTM,LASTUPDOPRID,SYNCID) values ('PMT_STATUS','L',to_date('01-JAN-00','DD-MON-RR'),'A','Awaiting Dispatch','Awaiting',to_timestamp('05-OCT-04 05.38.23.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'PPLSOFT',30572);
Insert into PSXLATITEM (FIELDNAME,FIELDVALUE,EFFDT,EFF_STATUS,XLATLONGNAME,XLATSHORTNAME,LASTUPDDTTM,LASTUPDOPRID,SYNCID) values ('PMT_STATUS','P',to_date('01-JAN-00','DD-MON-RR'),'A','Paid','Paid',to_timestamp('20-APR-04 05.53.25.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'PPLSOFT',30573);
Insert into PSXLATITEM (FIELDNAME,FIELDVALUE,EFFDT,EFF_STATUS,XLATLONGNAME,XLATSHORTNAME,LASTUPDDTTM,LASTUPDOPRID,SYNCID) values ('PMT_STATUS','R',to_date('01-JAN-00','DD-MON-RR'),'A','Received by Bank','Received',to_timestamp('20-APR-04 05.53.25.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'PPLSOFT',30574);
Insert into PSXLATITEM (FIELDNAME,FIELDVALUE,EFFDT,EFF_STATUS,XLATLONGNAME,XLATSHORTNAME,LASTUPDDTTM,LASTUPDOPRID,SYNCID) values ('PMT_STATUS','S',to_date('01-JAN-00','DD-MON-RR'),'A','Dispatched to Bank','Dispatched',to_timestamp('01-FEB-05 05.07.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'PPLSOFT',30575);
Insert into PSXLATITEM (FIELDNAME,FIELDVALUE,EFFDT,EFF_STATUS,XLATLONGNAME,XLATSHORTNAME,LASTUPDDTTM,LASTUPDOPRID,SYNCID) values ('PMT_STATUS','SC',to_date('01-JAN-00','DD-MON-RR'),'A','In Process','In Process',to_timestamp('04-MAY-04 05.04.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'PPLSOFT',31233);

8 rows selected. 

--https://connor-mcdonald.com/2019/05/17/hacking-together-faster-inserts/
--multi-table insert

select s.name, st.value
from v$statname s, v$mystat st
where st.statistic# = s.statistic#
and s.name like '%- undo records applied';
