--Trial Balance CSV 2013
SELECT X.FISCAL_YEAR, X.ACCOUNT_TYPE, ACCT.DESCR AS ACCT_TYPE_DESCR, X.ACCOUNT, X.DESCR AS ACCT_DESCR, X.CURRENCY_CD,
            SUM(X.PERIOD_0) AS "Bal Fwd-BASE", SUM(X.PERIOD_0_TRAN) AS "Bal Fwd-TRAN",
            SUM(X.JAN) AS "JAN-Base Curr", SUM(X.JAN_TRAN) AS "JAN-Trans Curr", 
            SUM(X.FEB) AS "FEB-Base Curr", SUM(X.FEB_TRAN) AS "FEB-Trans Curr", 
            SUM(X.MAR) AS "MAR-Base Curr", SUM(X.MAR_TRAN) AS "MAR-Trans Curr", 
            SUM(X.APR) AS "APR-Base Curr", SUM(X.APR_TRAN) AS "APR-Trans Curr", 
            SUM(X.MAY) AS "MAY-Base Curr", SUM(X.MAY_TRAN) AS "MAY-Trans Curr", 
            SUM(X.JUN) AS "JUN-Base Curr", SUM(X.JUN_TRAN) AS "JUN-Trans Curr", 
            SUM(X.JUL) AS "JUL-Base Curr", SUM(X.JUL_TRAN) AS "JUL-Trans Curr", 
            SUM(X.AUG) AS "AUG-Base Curr", SUM(X.AUG_TRAN) AS "AUG-Trans Curr", 
            SUM(X.SEP) AS "SEP-Base Curr", SUM(X.SEP_TRAN) AS "SEP-Trans Curr", 
            SUM(X.OCT) AS "OCT-Base Curr", SUM(X.OCT_TRAN) AS "OCT-Trans Curr", 
            SUM(X.NOV) AS "NOV-Base Curr", SUM(X.NOV_TRAN) AS "NOV-Trans Curr", 
            SUM(X.DEC) AS "DEC-Base Curr", SUM(X.DEC_TRAN) AS "DEC-Trans Curr", 
            SUM(X.POSTED_BASE_AMT) AS "Period Close-BASE", SUM(X.POSTED_TRAN_AMT) AS "Period Close-TRAN"
FROM (SELECT ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD, SUM(ST.POSTED_BASE_AMT) AS POSTED_BASE_AMT, SUM(ST.POSTED_TRAN_AMT) AS POSTED_TRAN_AMT
   , CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_0
   , CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS PERIOD_0_TRAN   
   , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JAN_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS FEB
   , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS FEB_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAR
   , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS MAR_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS APR
   , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS APR_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAY
   , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS MAY_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUN
   , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JUN_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUL
   , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JUL_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS AUG
   , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS AUG_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS SEP
   , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS SEP_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS OCT
   , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS OCT_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS NOV
   , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS NOV_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEC
   , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS DEC_TRAN
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ET.ACCOUNT = ST.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)
    AND ST.BUSINESS_UNIT = 'UNUNI'
    AND ST.LEDGER = 'USD'
    AND ST.FISCAL_YEAR = '2013'
    AND ((ST.ACCOUNTING_PERIOD BETWEEN 1 and 12 AND ET.ACCOUNT_TYPE IN ('E', 'R')) OR (ST.ACCOUNTING_PERIOD BETWEEN 0 and 12 AND ET.ACCOUNT_TYPE NOT IN ('E', 'R')))    
    AND ST.STATISTICS_CODE = ' '
GROUP BY ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ST.ACCOUNTING_PERIOD, ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD) X, PS_ACCT_TYPE_TBL ACCT
WHERE ACCT.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'ACCT_TYPE_TBL')
    AND ACCT.ACCOUNT_TYPE = X.ACCOUNT_TYPE
    --AND X.ACCOUNT = '11004'
GROUP BY X.FISCAL_YEAR, X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR, X.CURRENCY_CD
ORDER BY X.ACCOUNT, X.DESCR;
