select vchr_bld_error_flg, vchr_bld_status, A.* 
from PS_VCHR_HDR_QV A 
where 1 = 1
  AND A.VCHR_SRC = 'XML' 
  and exists (select 'x' from ps_tse_vchr X where X.BUSINESS_UNIT = A.BUSINESS_UNIT and X.VOUCHER_ID = A.VOUCHER_ID)
order by process_instance desc;

--Payables Voucher Error Logging
--AP TSE Records
SELECT 'TSE_VCHR', A.* FROM PS_TSE_VCHR A WHERE BUSINESS_UNIT IN (select business_unit from ps_bus_unit_tbl_ap where business_unit_gl = 'UNDP1') 
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID;
SELECT 'TSE_VCHR_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_VCHR_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR) 
WHERE BUSINESS_UNIT IN (select business_unit from ps_bus_unit_tbl_ap where business_unit_gl = 'UNDP1')
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID;
SELECT 'TSE_VCHRLN_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_VCHRLN_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR)
WHERE BUSINESS_UNIT IN (select business_unit from ps_bus_unit_tbl_ap where business_unit_gl = 'UNDP1') 
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID, VOUCHER_LINE_NUM;
SELECT 'TSE_ACCTLN_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_ACCTLN_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR) 
WHERE BUSINESS_UNIT IN (select business_unit from ps_bus_unit_tbl_ap where business_unit_gl = 'UNDP1') 
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID, VOUCHER_LINE_NUM;
SELECT 'TSE_PYMNT_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_PYMNT_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR)
WHERE BUSINESS_UNIT IN (select business_unit from ps_bus_unit_tbl_ap where business_unit_gl = 'UNDP1') 
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID;
SELECT 'TSE_MISC_FLD', A.*, CAT.MESSAGE_TEXT--, CAT.DESCRLONG 
FROM (PS_TSE_MISC_FLD A LEFT OUTER JOIN PSMSGCATDEFN CAT ON A.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND A.MESSAGE_NBR = CAT.MESSAGE_NBR) 
WHERE BUSINESS_UNIT IN (select business_unit from ps_bus_unit_tbl_ap where business_unit_gl = 'UNDP1') 
ORDER BY TSE_PROC_INSTANCE DESC, BUSINESS_UNIT, VOUCHER_ID;

--Version 4
select A.BUSINESS_UNIT, A.VOUCHER_ID, A.TSE_JOBID, A.TSE_PROC_INSTANCE, A.ORIGIN, A.GRP_AP_ID, A.VENDOR_ID, A.CNTRCT_ID, A.INVOICE_ID, A.INVOICE_DT, A.GROSS_AMT, A.TXN_CURRENCY_CD, A.VCHR_SRC,
       (SELECT RTRIM(XMLAGG(XMLELEMENT(E, B.TSE_SET_NBR || ' - '|| B.TSE_EDIT_TYPE || ' - '|| X1.XLATLONGNAME || ' - '|| B.TSE_FIELDNAME || ' - '|| B.BUSINESS_UNIT || ' - '|| B.VOUCHER_ID 
                                          || ' - '|| B.MESSAGE_SET_NBR || ' - '|| B.MESSAGE_NBR || ' - '|| B.MESSAGE_PARM || ' - '|| B.MESSAGE_PARM2 || ' - '|| B.MESSAGE_PARM3 || ' - '|| 
                                          CAT.MESSAGE_TEXT, ' ; ' || chr(13)).EXTRACT('//text()')ORDER BY B.TSE_SET_NBR)
                                      .getclobval(),',') AS "A0"
        FROM ((PS_TSE_VCHR_FLD B LEFT OUTER JOIN PSMSGCATDEFN CAT ON B.MESSAGE_SET_NBR = CAT.MESSAGE_SET_NBR AND B.MESSAGE_NBR = CAT.MESSAGE_NBR)
               LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'TSE_EDIT_TYPE' AND X1.FIELDVALUE = B.TSE_EDIT_TYPE AND X1.EFF_STATUS = 'A')
        WHERE A.BUSINESS_UNIT = A.BUSINESS_UNIT AND A.VOUCHER_ID = B.VOUCHER_ID AND A.TSE_JOBID = B.TSE_JOBID AND A.TSE_PROC_INSTANCE = B.TSE_PROC_INSTANCE) AS "Exceptions - VCHR_FLD",
       (SELECT RTRIM(XMLAGG(XMLELEMENT(E, C.TSE_SET_NBR || ' - '|| C.TSE_EDIT_TYPE || ' - '|| X2.XLATLONGNAME || ' - '|| C.TSE_FIELDNAME || ' - '|| C.VOUCHER_LINE_NUM || ' - '|| 
                                          C.MESSAGE_SET_NBR || ' - '|| C.MESSAGE_NBR || ' - '|| C.MESSAGE_PARM || ' - '|| C.MESSAGE_PARM2 || ' - '|| C.MESSAGE_PARM3 || ' - '|| 
                                          CAT1.MESSAGE_TEXT, ' ; ' || chr(13)).EXTRACT('//text()')ORDER BY C.VOUCHER_LINE_NUM)
                                      .getclobval(),',') AS "A1"
        FROM ((PS_TSE_VCHRLN_FLD C LEFT OUTER JOIN PSMSGCATDEFN CAT1 ON C.MESSAGE_SET_NBR = CAT1.MESSAGE_SET_NBR AND C.MESSAGE_NBR = CAT1.MESSAGE_NBR)
              LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'TSE_EDIT_TYPE' AND X2.FIELDVALUE = C.TSE_EDIT_TYPE AND X2.EFF_STATUS = 'A')
        WHERE A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.VOUCHER_ID = C.VOUCHER_ID AND A.TSE_JOBID = C.TSE_JOBID AND A.TSE_PROC_INSTANCE = C.TSE_PROC_INSTANCE) AS "Exceptions - VCHRLN_FLD",
        (SELECT RTRIM(XMLAGG(XMLELEMENT(E, D.TSE_SET_NBR || ' - '|| D.TSE_EDIT_TYPE || ' - '|| X3.XLATLONGNAME || ' - '|| D.TSE_FIELDNAME || ' - '|| D.PYMNT_CNT || ' - '|| D.MESSAGE_SET_NBR 
                                           || ' - '|| D.MESSAGE_NBR || ' - '|| D.MESSAGE_PARM || ' - '|| D.MESSAGE_PARM2 || ' - '|| D.MESSAGE_PARM3 || ' - '|| CAT2.MESSAGE_TEXT, ' ; ' 
                                           || chr(13)).EXTRACT('//text()')ORDER BY D.PYMNT_CNT)
                                      .getclobval(),',') AS "A2"
        FROM ((PS_TSE_PYMNT_FLD D LEFT OUTER JOIN PSMSGCATDEFN CAT2 ON D.MESSAGE_SET_NBR = CAT2.MESSAGE_SET_NBR AND D.MESSAGE_NBR = CAT2.MESSAGE_NBR)
               LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'TSE_EDIT_TYPE' AND X3.FIELDVALUE = D.TSE_EDIT_TYPE AND X3.EFF_STATUS = 'A')
        WHERE A.BUSINESS_UNIT = D.BUSINESS_UNIT AND A.VOUCHER_ID = D.VOUCHER_ID AND A.TSE_JOBID = D.TSE_JOBID AND A.TSE_PROC_INSTANCE = D.TSE_PROC_INSTANCE) AS "Exceptions - PYMNT_FLD",
        (SELECT RTRIM(XMLAGG(XMLELEMENT(E, E.TSE_SET_NBR || ' - '|| E.TSE_EDIT_TYPE || ' - '|| X4.XLATLONGNAME || ' - '|| E.TSE_FIELDNAME || ' - '|| E.VOUCHER_LINE_NUM || ' - '|| 
                                           E.DISTRIB_LINE_NUM || ' - '|| E.MESSAGE_SET_NBR || ' - '|| E.MESSAGE_NBR || ' - '|| E.MESSAGE_PARM || ' - '|| E.MESSAGE_PARM2 || ' - '|| 
                                           E.MESSAGE_PARM3 || ' - '|| CAT3.MESSAGE_TEXT, ' ; ' || chr(13)).EXTRACT('//text()')ORDER BY E.VOUCHER_LINE_NUM, E.DISTRIB_LINE_NUM)
                                      .getclobval(),',') AS "A3"
        FROM ((PS_TSE_ACCTLN_FLD E LEFT OUTER JOIN PSMSGCATDEFN CAT3 ON E.MESSAGE_SET_NBR = CAT3.MESSAGE_SET_NBR AND E.MESSAGE_NBR = CAT3.MESSAGE_NBR)
              LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'TSE_EDIT_TYPE' AND X4.FIELDVALUE = E.TSE_EDIT_TYPE AND X4.EFF_STATUS = 'A')
        WHERE A.BUSINESS_UNIT = E.BUSINESS_UNIT AND A.VOUCHER_ID = E.VOUCHER_ID AND A.TSE_JOBID = E.TSE_JOBID AND A.TSE_PROC_INSTANCE = E.TSE_PROC_INSTANCE) AS "Exceptions - ACCTLN_FLD"
FROM PS_TSE_VCHR A
WHERE 1 = 1
  AND (A.BUSINESS_UNIT IN (select business_unit from ps_bus_unit_tbl_ap where business_unit_gl = 'UNDP1')
  AND A.BUSINESS_UNIT IN ('ZMB10', 'ZWE10', 'NGA10', 'TZA10', 'KEN10'))
--  AND A.VOUCHER_ID = '00075110'
ORDER BY A.TSE_PROC_INSTANCE DESC, A.BUSINESS_UNIT, A.VOUCHER_ID DESC;
