--UN Secretariat format UNU TB 2013 CSV
SELECT X.FISCAL_YEAR, X.ACCOUNT_TYPE, ACCT.DESCR AS ACCT_TYPE_DESCR, X.ACCOUNT, X.DESCR AS ACCT_DESCR,
            SUM(X.PERIOD_0) AS "Opening Balance", SUM(X.DEBIT) AS "Debits", SUM(X.CREDIT) AS "Credits",
            SUM(X.PERIOD_YTD) AS "Movement", SUM(X.POSTED_BASE_AMT) AS "Closing Balance"           
FROM (SELECT ST.FISCAL_YEAR, ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, SUM(ST.POSTED_BASE_AMT) AS POSTED_BASE_AMT,
     CASE WHEN ST.ACCOUNTING_PERIOD = 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_0
   , CASE WHEN ST.ACCOUNTING_PERIOD > 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_YTD
   , CASE WHEN (SUM(ST.POSTED_BASE_AMT) > 0.00 AND ST.ACCOUNTING_PERIOD > 0) THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEBIT
   , CASE WHEN (SUM(ST.POSTED_BASE_AMT) < 0.00 AND ST.ACCOUNTING_PERIOD > 0) THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS CREDIT
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ET.ACCOUNT = ST.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)
    AND ST.BUSINESS_UNIT = 'UNUNI'
    AND ST.LEDGER = 'USD'
    AND ST.FISCAL_YEAR = '2013'
    AND ((ST.ACCOUNTING_PERIOD BETWEEN 1 and 12 AND ET.ACCOUNT_TYPE IN ('E', 'R')) OR (ST.ACCOUNTING_PERIOD BETWEEN 0 and 12 AND ET.ACCOUNT_TYPE NOT IN ('E', 'R')))        
    AND ST.STATISTICS_CODE = ' '
    --AND (ST.ACCOUNTING_PERIOD BETWEEN 0 AND 12)
    --AND ET.ACCOUNT_TYPE NOT IN ('E', 'R')    
GROUP BY ST.FISCAL_YEAR, ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.BASE_CURRENCY, ST.ACCOUNTING_PERIOD) X, PS_ACCT_TYPE_TBL ACCT
WHERE ACCT.SETID = 'SHARE'
    AND ACCT.ACCOUNT_TYPE = X.ACCOUNT_TYPE
GROUP BY X.FISCAL_YEAR, X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR
ORDER BY X.ACCOUNT, X.DESCR;
