SELECT X.BUSINESS_UNIT 
 , X.PO_ID 
 , X.LINE_NBR 
 , X.SCHED_NBR 
 , X.DISTRIB_LINE_NUM 
 , HDR.PO_DT 
 , HDR.ACCOUNTING_DT 
 , DIST.BUDGET_DT 
 , HDR.CURRENCY_CD AS HDR_CURR_CD 
 , %Coalesce(%ROUND((HDR.RATE_MULT/HDR.RATE_DIV) , 7) , 0.00) AS PO_HDR_RATE 
 , %Coalesce(%ROUND((DIST.RATE_MULT/DIST.RATE_DIV) , 7) , 0.00) AS PO_DIST_RATE 
 , %Coalesce(%ROUND(E.CUR_EXCHNG_RT , 7) , 0.00) AS CURRENT_RATE 
 , X.INV_ITEM_ID 
 , X.DESCR254_MIXED 
 , X.UNIT_OF_MEASURE 
 , X.RECV_REQ 
 , X.AMT_ONLY_FLG 
 , X.ACCOUNT 
 , X.DEPTID 
 , %subrec(CF14_AN_SBR, X) 
 , %subrec(PC_CF1_N_SBR, X) 
 , X.QTY_ORDERED 
 , X.AMT_ORDERED_BASE 
 , SUM(X.QTY_RECEIVED) AS QTY_RECEIVED 
 , SUM(X.AMT_RECEIVED_BASE) AS AMT_RECEIVED_BASE 
 , SUM(X.QTY_INVOICED) AS QTY_INVOICED 
 , SUM(X.AMT_INVOICED_BASE) AS AMT_INVOICED_BASE 
  FROM ( 
 SELECT L.BUSINESS_UNIT 
 , L.PO_ID 
 , L.LINE_NBR 
 , DIST.SCHED_NBR 
 , DIST.DISTRIB_LINE_NUM 
 , L.INV_ITEM_ID 
 , L.DESCR254_MIXED 
 , L.UNIT_OF_MEASURE 
 , L.RECV_REQ 
 , L.AMT_ONLY_FLG 
 , DIST.ACCOUNT 
 , DIST.DEPTID 
 , %subrec(CF14_AN_SBR, DIST) 
 , %subrec(PC_CF1_N_SBR, DIST) 
 , DIST.QTY_PO AS QTY_ORDERED 
 , DIST.MERCH_AMT_BSE AS AMT_ORDERED_BASE 
 , 0.00 AS QTY_RECEIVED 
 , 0.00 AS AMT_RECEIVED_BASE 
 , 0.00 AS QTY_INVOICED 
 , 0.00 AS AMT_INVOICED_BASE 
  FROM PS_PO_LINE L 
  , PS_PO_LINE_DISTRIB DIST 
 WHERE L.BUSINESS_UNIT = DIST.BUSINESS_UNIT 
   AND L.PO_ID = DIST.PO_ID 
   AND L.LINE_NBR = DIST.LINE_NBR 
   AND L.CANCEL_STATUS NOT IN ('C', 'X') 
   AND DIST.DISTRIB_LN_STATUS NOT IN ('X', 'C') 
   AND L.BUSINESS_UNIT LIKE '6%' 
  GROUP BY L.BUSINESS_UNIT, L.PO_ID, L.LINE_NBR, DIST.SCHED_NBR, DIST.DISTRIB_LINE_NUM, L.INV_ITEM_ID, L.DESCR254_MIXED, L.UNIT_OF_MEASURE, L.RECV_REQ, L.AMT_ONLY_FLG, DIST.ACCOUNT, DIST.DEPTID, %subrec(CF14_AN_SBR, DIST), %subrec(PC_CF1_N_SBR, DIST), DIST.QTY_PO, DIST.MERCH_AMT_BSE 
  UNION ALL 
 SELECT DIST.BUSINESS_UNIT 
 , DIST.PO_ID 
 , DIST.LINE_NBR 
 , DIST.SCHED_NBR 
 , DIST.DISTRIB_LINE_NUM 
 , L.INV_ITEM_ID 
 , L.DESCR254_MIXED 
 , L.UNIT_OF_MEASURE 
 , L.RECV_REQ 
 , L.AMT_ONLY_FLG 
 , DIST.ACCOUNT 
 , DIST.DEPTID 
 , %subrec(CF14_AN_SBR, DIST) 
 , %subrec(PC_CF1_N_SBR, DIST) 
 , DIST.QTY_PO AS QTY_ORDERED 
 , DIST.MERCH_AMT_BSE AS AMT_ORDERED_BASE 
 , %Coalesce(%ROUND(SUM(QTY_DS_ACCPT_VUOM) , 3) , 0.00) AS QTY_RECEIVED 
 , %Coalesce(%ROUND(SUM(RCVD.MERCH_AMT_BSE) , 3) , 0.00) AMT_RECEIVED_BASE 
 , 0.00 AS QTY_INVOICED 
 , 0.00 AS AMT_INVOICED_BASE 
  FROM PS_PO_LINE_DISTRIB DIST 
  , PS_RECV_LN_DISTRIB RCVD 
  , PS_PO_LINE L 
 WHERE RCVD.BUSINESS_UNIT_PO = DIST.BUSINESS_UNIT 
   AND RCVD.PO_ID = DIST.PO_ID 
   AND RCVD.LINE_NBR = DIST.LINE_NBR 
   AND RCVD.SCHED_NBR = DIST.SCHED_NBR 
   AND RCVD.PO_DIST_LINE_NUM = DIST.DISTRIB_LINE_NUM 
   AND L.BUSINESS_UNIT = DIST.BUSINESS_UNIT 
   AND L.PO_ID = DIST.PO_ID 
   AND L.LINE_NBR = DIST.LINE_NBR 
   AND DIST.BUSINESS_UNIT LIKE '6%' 
   AND RCVD.RECV_DS_STATUS <> 'X' 
   AND L.CANCEL_STATUS NOT IN ('C', 'X') 
   AND DIST.DISTRIB_LN_STATUS NOT IN ('X', 'C') 
  GROUP BY DIST.BUSINESS_UNIT, DIST.PO_ID, DIST.LINE_NBR, DIST.SCHED_NBR, DIST.DISTRIB_LINE_NUM, L.INV_ITEM_ID, L.DESCR254_MIXED, L.UNIT_OF_MEASURE, L.RECV_REQ, L.AMT_ONLY_FLG, DIST.ACCOUNT, DIST.DEPTID, %subrec(CF14_AN_SBR, DIST), %subrec(PC_CF1_N_SBR, DIST), DIST.QTY_PO, DIST.MERCH_AMT_BSE 
  UNION ALL 
 SELECT DIST.BUSINESS_UNIT 
 , DIST.PO_ID 
 , DIST.LINE_NBR 
 , DIST.SCHED_NBR 
 , DIST.DISTRIB_LINE_NUM 
 , POL.INV_ITEM_ID 
 , POL.DESCR254_MIXED 
 , POL.UNIT_OF_MEASURE 
 , POL.RECV_REQ 
 , POL.AMT_ONLY_FLG 
 , DIST.ACCOUNT 
 , DIST.DEPTID 
 , %subrec(CF14_AN_SBR, DIST) 
 , %subrec(PC_CF1_N_SBR, DIST) 
 , DIST.QTY_PO AS QTY_ORDERED 
 , DIST.MERCH_AMT_BSE AS AMT_ORDERED_BASE 
 , 0.00 AS QTY_RECEIVED 
 , 0.00 AS AMT_RECEIVED_BASE 
 , %Coalesce(%ROUND(SUM(DLV.QTY_VCHR) , 3) , 0.00) QTY_INVOICED 
 , %Coalesce(%ROUND(SUM(DLV.MERCH_AMT_BSE) , 3) , 0.00) AMT_INVOICED_BASE 
  FROM PS_VOUCHER_LINE L 
  , PS_VOUCHER V 
  , PS_DISTRIB_LINE DLV 
  , PS_PO_LINE_DISTRIB DIST 
  , PS_PO_LINE POL 
 WHERE V.BUSINESS_UNIT = L.BUSINESS_UNIT 
   AND V.VOUCHER_ID = L.VOUCHER_ID 
   AND V.BUSINESS_UNIT = DLV.BUSINESS_UNIT 
   AND V.VOUCHER_ID = DLV.VOUCHER_ID 
   AND L.VOUCHER_LINE_NUM = DLV.VOUCHER_LINE_NUM 
   AND L.BUSINESS_UNIT_PO = DIST.BUSINESS_UNIT 
   AND L.PO_ID = DIST.PO_ID 
   AND L.LINE_NBR = DIST.LINE_NBR 
   AND DLV.SCHED_NBR = DIST.SCHED_NBR 
   AND DLV.PO_DIST_LINE_NUM = DIST.DISTRIB_LINE_NUM 
   AND POL.BUSINESS_UNIT = DIST.BUSINESS_UNIT 
   AND POL.PO_ID = DIST.PO_ID 
   AND POL.LINE_NBR = DIST.LINE_NBR 
   AND L.BUSINESS_UNIT_PO <> ' ' 
   AND L.PO_ID <> ' ' 
   AND V.ENTRY_STATUS <> 'X' 
   AND V.VOUCHER_STYLE <> 'THRD' 
   AND (V.MANUAL_CLOSE_DT IS NULL 
    OR EXISTS ( 
 SELECT 'X' 
  FROM PS_PYMNT_VCHR_XREF X 
 WHERE X.BUSINESS_UNIT = V.BUSINESS_UNIT 
   AND X.VOUCHER_ID = V.VOUCHER_ID 
   AND X.PYMNT_SELCT_STATUS <> 'X')) 
   AND POL.CANCEL_STATUS NOT IN ('C', 'X') 
   AND DIST.DISTRIB_LN_STATUS NOT IN ('X', 'C') 
   AND DIST.BUSINESS_UNIT LIKE '6%' 
  GROUP BY DIST.BUSINESS_UNIT, DIST.PO_ID, DIST.LINE_NBR, DIST.SCHED_NBR, DIST.DISTRIB_LINE_NUM, POL.INV_ITEM_ID, POL.DESCR254_MIXED, POL.UNIT_OF_MEASURE, POL.RECV_REQ, POL.AMT_ONLY_FLG, DIST.ACCOUNT, DIST.DEPTID, %subrec(CF14_AN_SBR, DIST), %subrec(PC_CF1_N_SBR, DIST), DIST.QTY_PO, DIST.MERCH_AMT_BSE ) X, PS_PO_HDR HDR, PS_PO_LINE_DISTRIB DIST, PS_CUR_RT_TBL E, PS_BUS_UNIT_TBL_GL F 
 WHERE X.BUSINESS_UNIT = HDR.BUSINESS_UNIT 
   AND X.PO_ID = HDR.PO_ID 
   AND X.BUSINESS_UNIT = DIST.BUSINESS_UNIT 
   AND X.PO_ID = DIST.PO_ID 
   AND X.LINE_NBR = DIST.LINE_NBR 
   AND X.SCHED_NBR = DIST.SCHED_NBR 
   AND X.DISTRIB_LINE_NUM = DIST.DISTRIB_LINE_NUM 
   AND DIST.BUSINESS_UNIT_GL = F.BUSINESS_UNIT 
   AND E.FROM_CUR = HDR.CURRENCY_CD 
   AND E.TO_CUR = F.BASE_CURRENCY 
   AND E.CUR_RT_TYPE = 'UNORE' 
   AND %EffdtCheck(CUR_RT_TBL E1, E, %CurrentDateIn) 
   AND E.EFF_STATUS = 'A' 
   AND X.BUSINESS_UNIT LIKE '6%' 
   AND HDR.PO_STATUS NOT IN ('C', 'X', 'PX') 
   AND DIST.DISTRIB_LN_STATUS NOT IN ('X', 'C') 
   AND DIST.KK_CLOSE_FLAG <> 'Y' 
   AND X.BUSINESS_UNIT <> ' ' 
   AND X.PO_ID <> ' ' 
  GROUP BY X.BUSINESS_UNIT, X.PO_ID, X.LINE_NBR, X.SCHED_NBR, X.DISTRIB_LINE_NUM, HDR.PO_DT, HDR.ACCOUNTING_DT, DIST.BUDGET_DT, HDR.CURRENCY_CD, %Coalesce(%ROUND((HDR.RATE_MULT/HDR.RATE_DIV), 7), 0), %Coalesce(%ROUND((DIST.RATE_MULT/DIST.RATE_DIV), 7), 0), %Coalesce(%ROUND(E.CUR_EXCHNG_RT, 7), 0), X.INV_ITEM_ID, X.DESCR254_MIXED, X.UNIT_OF_MEASURE, X.RECV_REQ, X.AMT_ONLY_FLG, X.ACCOUNT, X.DEPTID, %subrec(CF14_AN_SBR, X), %subrec(PC_CF1_N_SBR, X), X.QTY_ORDERED, X.AMT_ORDERED_BASE
