-----------------SETUP Data
--Open Period Data for modules where GL BU = 'UNUNI'
--All Modules for UNUNI
--Need to ensure that GL is also listed
SELECT OPN.PSFT_PRODUCT, OPN.BUSINESS_UNIT, OPN.LEDGER_GROUP, OPN.TRANSACTION_TYPE, TRAN.DESCR, OPN.LEDGER_CODE, OPN.GL_ADJUST_TYPE, OPN.CALENDAR_ID, 
            OPN.OPEN_YEAR_FROM, OPN.OPEN_PERIOD_FROM, OPN.BEGIN_LAG_DAYS, OPN.OPEN_FROM_DATE, OPN.OPEN_YEAR_TO, OPN.OPEN_PERIOD_TO, OPN.END_LAG_DAYS, OPN.OPEN_TO_DATE 
FROM PS_TRANS_TYPE_TBL TRAN, (PS_FIN_OPEN_PERIOD OPN LEFT OUTER JOIN PS_FIN_BU_MAPPING MAP ON OPN.PSFT_PRODUCT = MAP.PSFT_PRODUCT 
                                                                                             AND OPN.BUSINESS_UNIT = MAP.BUSINESS_UNIT
                                                                                             AND MAP.BUSINESS_UNIT_GL = 'UNUNI')
WHERE OPN.PSFT_PRODUCT = TRAN.PSFT_PRODUCT
    AND OPN.TRANSACTION_TYPE = TRAN.TRANSACTION_TYPE
    AND OPN.LEDGER_GROUP = 'ACTUALS'
    AND (OPN.BUSINESS_UNIT LIKE '6%' OR OPN.BUSINESS_UNIT = 'UNUNI')
ORDER BY OPN.PSFT_PRODUCT, OPN.BUSINESS_UNIT, OPN.LEDGER_GROUP, OPN.TRANSACTION_TYPE;
--Check Control, Budgetary and Open Item Accounts
SELECT to_char(sysdate, 'Dy DD-Mon-YYYY HH24:MI:SS') as "Now", A.* FROM PS_GL_ACCOUNT_TBL A WHERE SETID = 'SHARE' AND CONTROL_FLAG = 'Y';
SELECT to_char(sysdate, 'Dy DD-Mon-YYYY HH24:MI:SS') as "Now", A.* FROM PS_GL_ACCOUNT_TBL A WHERE SETID = 'SHARE' AND BUDGETARY_ONLY = 'Y';
SELECT to_char(sysdate, 'Dy DD-Mon-YYYY HH24:MI:SS') as "Now", A.* FROM PS_GL_ACCOUNT_TBL A WHERE SETID = 'SHARE' AND OPEN_ITEM = 'Y';
--UNU_CUST_DONOR_XREF
SELECT A.CUST_ID, A.NAME1, A.CUST_STATUS, A.NAMESHORT, B.CHARTFIELD2 AS DONOR, B.EFF_STATUS, B.DESCR, B.DESCRSHORT
FROM PS_CUSTOMER A, PS_CHARTFIELD2_TBL B
WHERE A.SETID = 'UNUNI'
     AND A.CUST_STATUS = 'A'
     AND A.SETID = B.SETID
     AND B.EFFDT = (SELECT MAX(B_ED.EFFDT) FROM PS_CHARTFIELD2_TBL B_ED WHERE B.SETID = B_ED.SETID AND B.CHARTFIELD2 = B_ED.CHARTFIELD2)
     AND A.CUST_ID = B.CHARTFIELD2
ORDER BY 1;
--FIN0010_GL_ACCOUNTS
SELECT A.SETID, A.ACCOUNT, A.DESCR, A.DESCRSHORT, A.ACCOUNT_TYPE, A.STATISTICS_ACCOUNT, A.UNIT_OF_MEASURE, A.CONTROL_FLAG,  A.BUDGETARY_ONLY,
            A.OPEN_ITEM, A.OPEN_ITEM_DESCR, A.OPEN_ITEM_EDIT_REC, A.OPEN_ITEM_EDIT_FLD, A.ACCOUNTING_OWNER, A.BALANCE_FWD_SW, A.VAT_ACCOUNT_FLG, 
            H.CF_ATTRIBUTE, H.CF_ATTRIB_VALUE, I.DESCR60
FROM PS_GL_ACCOUNT_TBL A, PS_ACCT_TYPE_TBL B, PS_CF_ATTRIB_TBL H, PS_CF_ATTRIB_VALUE I
WHERE (A.EFFDT = (SELECT MAX(A_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL A_ED WHERE A.SETID = A_ED.SETID AND A.ACCOUNT = A_ED.ACCOUNT 
                                                                                                                              AND A_ED.EFFDT <= SYSDATE)
     AND B.ACCOUNT_TYPE = A.ACCOUNT_TYPE
     AND B.SETID = (SELECT D.SETID FROM PS_SET_CNTRL_REC D WHERE D.SETCNTRLVALUE = A.SETID AND D.RECNAME = 'ACCT_TYPE_TBL')
     AND A.SETID = 'SHARE'
     AND A.EFF_STATUS = 'A'
     AND A.STATISTICS_ACCOUNT = 'Y'
     AND A.SETID = H.SETID
     AND H.EFFDT = (SELECT MAX(H_ED.EFFDT) FROM PS_CF_ATTRIB_TBL H_ED WHERE H.SETID = H_ED.SETID AND H.CHARTFIELD_VALUE = H_ED.CHARTFIELD_VALUE 
                                                                                                                          AND H_ED.EFFDT <= A.EFFDT)
     AND H.SETID = I.SETID
     AND H.FIELDNAME = I.FIELDNAME
     AND H.CF_ATTRIBUTE = I.CF_ATTRIBUTE
     AND H.CF_ATTRIB_VALUE = I.CF_ATTRIB_VALUE
     AND H.FIELDNAME = 'ACCOUNT'
     AND H.CHARTFIELD_VALUE = A.ACCOUNT)
UNION
SELECT C.SETID, C.ACCOUNT, C.DESCR, C.DESCRSHORT, C.ACCOUNT_TYPE, C.STATISTICS_ACCOUNT, C.UNIT_OF_MEASURE, C.CONTROL_FLAG,  C.BUDGETARY_ONLY, 
            C.OPEN_ITEM, C.OPEN_ITEM_DESCR, C.OPEN_ITEM_EDIT_REC, C.OPEN_ITEM_EDIT_FLD, C.ACCOUNTING_OWNER, C.BALANCE_FWD_SW, C.VAT_ACCOUNT_FLG, 
            J.CF_ATTRIBUTE, J.CF_ATTRIB_VALUE, K.DESCR60
FROM PS_GL_ACCOUNT_TBL C, PS_CF_ATTRIB_TBL J, PS_CF_ATTRIB_VALUE K
WHERE (C.ACCOUNT_TYPE = ' '
     AND C.EFF_STATUS = 'A'
     AND C.SETID = 'SHARE'
     AND C.EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL C_ED WHERE C.SETID = C_ED.SETID AND C.ACCOUNT = C_ED.ACCOUNT 
                                                                                                                             AND C_ED.EFFDT <= SYSDATE)
     AND J.EFFDT = (SELECT MAX(J_ED.EFFDT) FROM PS_CF_ATTRIB_TBL J_ED WHERE J.SETID = J_ED.SETID AND J.CHARTFIELD_VALUE = J_ED.CHARTFIELD_VALUE
                                                                                                                        AND J_ED.EFFDT <= SYSDATE)
     AND J.SETID = K.SETID
     AND J.FIELDNAME = K.FIELDNAME
     AND J.CF_ATTRIBUTE = K.CF_ATTRIBUTE
     AND J.CF_ATTRIB_VALUE = K.CF_ATTRIB_VALUE
     AND J.SETID = C.SETID
     AND K.FIELDNAME = 'ACCOUNT'
     AND J.CHARTFIELD_VALUE = C.ACCOUNT)
UNION
SELECT E.SETID, E.ACCOUNT, E.DESCR, E.DESCRSHORT, E.ACCOUNT_TYPE, E.STATISTICS_ACCOUNT, E.UNIT_OF_MEASURE, E.CONTROL_FLAG,  E.BUDGETARY_ONLY, 
            E.OPEN_ITEM, E.OPEN_ITEM_DESCR, E.OPEN_ITEM_EDIT_REC, E.OPEN_ITEM_EDIT_FLD,  E.ACCOUNTING_OWNER, F.BALANCE_FWD_SW, E.VAT_ACCOUNT_FLG, 
            M.CF_ATTRIBUTE, M.CF_ATTRIB_VALUE, M.DESCR60
FROM PS_GL_ACCOUNT_TBL E, PS_ACCT_TYPE_TBL F, PS_CF_ATTRIB_TBL L, PS_CF_ATTRIB_VALUE M
WHERE ( E.EFFDT = (SELECT MAX(E_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL E_ED WHERE E.SETID = E_ED.SETID AND E.ACCOUNT = E_ED.ACCOUNT
                                                                                                                              AND E_ED.EFFDT <= SYSDATE)
     AND F.ACCOUNT_TYPE = E.ACCOUNT_TYPE
     AND F.SETID = (SELECT G.SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = E.SETID AND G.RECNAME = 'ACCT_TYPE_TBL')
     AND E.SETID = 'SHARE'
     AND E.EFF_STATUS = 'A'
     AND E.STATISTICS_ACCOUNT = 'N'
     AND L.EFFDT = (SELECT MAX(L_ED.EFFDT) FROM PS_CF_ATTRIB_TBL L_ED WHERE L.SETID = L_ED.SETID AND L.CHARTFIELD_VALUE = L_ED.CHARTFIELD_VALUE
                                                                                                                         AND L_ED.EFFDT <= SYSDATE)
     AND L.SETID = M.SETID
     AND L.FIELDNAME = M.FIELDNAME
     AND L.CF_ATTRIBUTE = M.CF_ATTRIBUTE
     AND L.CF_ATTRIB_VALUE = M.CF_ATTRIB_VALUE
     AND L.SETID = E.SETID
     AND L.FIELDNAME = 'ACCOUNT'
     AND L.CHARTFIELD_VALUE = E.ACCOUNT)
UNION
SELECT N.SETID, N.ACCOUNT, N.DESCR, N.DESCRSHORT, N.ACCOUNT_TYPE, N.STATISTICS_ACCOUNT, N.UNIT_OF_MEASURE, N.CONTROL_FLAG,  N.BUDGETARY_ONLY, 
            N.OPEN_ITEM, N.OPEN_ITEM_DESCR, 
            N.OPEN_ITEM_EDIT_REC, N.OPEN_ITEM_EDIT_FLD, N.ACCOUNTING_OWNER, N.BALANCE_FWD_SW, N.VAT_ACCOUNT_FLG, ' ', ' ', ' '
FROM PS_GL_ACCOUNT_TBL N, PS_ACCT_TYPE_TBL O
WHERE (N.EFFDT = (SELECT MAX(N_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL N_ED WHERE N.SETID = N_ED.SETID AND N.ACCOUNT = N_ED.ACCOUNT 
                                                                                                                              AND N_ED.EFFDT <= SYSDATE)
     AND N.ACCOUNT_TYPE = O.ACCOUNT_TYPE
     AND N.SETID = 'SHARE'
     AND O.SETID = (SELECT P.SETID FROM PS_SET_CNTRL_REC P WHERE P.RECNAME = 'ACCT_TYPE_TBL' AND P.SETCNTRLVALUE = N.SETID)
     AND N.EFF_STATUS = 'A'
     AND N.STATISTICS_ACCOUNT = 'Y')
UNION
SELECT Q.SETID, Q.ACCOUNT, Q.DESCR, Q.DESCRSHORT, Q.ACCOUNT_TYPE, Q.STATISTICS_ACCOUNT, Q.UNIT_OF_MEASURE, Q.CONTROL_FLAG,  Q.BUDGETARY_ONLY, 
            Q.OPEN_ITEM, Q.OPEN_ITEM_DESCR, 
            Q.OPEN_ITEM_EDIT_REC, Q.OPEN_ITEM_EDIT_FLD, Q.ACCOUNTING_OWNER, Q.BALANCE_FWD_SW, Q.VAT_ACCOUNT_FLG, ' ', ' ', ' '
FROM PS_GL_ACCOUNT_TBL Q
WHERE (Q.EFFDT = (SELECT MAX(Q_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL Q_ED WHERE Q.SETID = Q_ED.SETID AND Q.ACCOUNT = Q_ED.ACCOUNT
                                                                                                                               AND Q_ED.EFFDT <= SYSDATE)
     AND Q.ACCOUNT_TYPE = ' '
     AND Q.EFF_STATUS = 'A'
     AND Q.SETID = 'SHARE')
UNION
SELECT R.SETID, R.ACCOUNT, R.DESCR, R.DESCRSHORT, R.ACCOUNT_TYPE, R.STATISTICS_ACCOUNT, R.UNIT_OF_MEASURE, R.CONTROL_FLAG,  R.BUDGETARY_ONLY, 
            R.OPEN_ITEM, R.OPEN_ITEM_DESCR, 
            R.OPEN_ITEM_EDIT_REC, R.OPEN_ITEM_EDIT_FLD, R.ACCOUNTING_OWNER, S.BALANCE_FWD_SW, R.VAT_ACCOUNT_FLG, ' ', ' ', ' '
FROM PS_GL_ACCOUNT_TBL R, PS_ACCT_TYPE_TBL S
WHERE (R.EFFDT = (SELECT MAX(R_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL R_ED WHERE R.SETID = R_ED.SETID AND R.ACCOUNT = R_ED.ACCOUNT 
                                                                                                                              AND R_ED.EFFDT <= SYSDATE)
     AND R.SETID = S.SETID
     AND R.SETID = 'SHARE'
     AND S.SETID = (SELECT T.SETID FROM PS_SET_CNTRL_REC T WHERE T.SETCNTRLVALUE = R.SETID AND T.RECNAME = 'ACCT_TYPE_TBL')
     AND S.ACCOUNT_TYPE = R.ACCOUNT_TYPE
     AND R.STATISTICS_ACCOUNT = 'N'
     AND R.EFF_STATUS = 'A')
UNION
SELECT U.SETID, U.ACCOUNT, U.DESCR, U.DESCRSHORT, U.ACCOUNT_TYPE, U.STATISTICS_ACCOUNT, U.UNIT_OF_MEASURE, U.CONTROL_FLAG,  U.BUDGETARY_ONLY, 
            U.OPEN_ITEM, U.OPEN_ITEM_DESCR, 
            U.OPEN_ITEM_EDIT_REC, U.OPEN_ITEM_EDIT_FLD, U.ACCOUNTING_OWNER, U.BALANCE_FWD_SW, U.VAT_ACCOUNT_FLG, ' ', ' ', ' '
FROM PS_GL_ACCOUNT_TBL U
WHERE (U.EFFDT = (SELECT MAX(U_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL U_ED WHERE U.SETID = U_ED.SETID AND U.ACCOUNT = U_ED.ACCOUNT 
                                                                                                                              AND U_ED.EFFDT <= SYSDATE)
     AND U.SETID = 'SHARE'
     AND U.EFF_STATUS = 'A')
ORDER BY 1, 2;
