--UNU User Preferences
SELECT A.OPRID, A.BUSINESS_UNIT, A.LC_CNTRY, A.AS_OF_DATE, A.SETID, A.NAME1, B.ORIGIN, B.DEPTID, B.CHK_INV_AMT_FLG, B.INVOICE_AMT_MAX, B.AUTH_APPROVE_VCHR, 
       B.VCHR_APPRVL_AMT, B.AUTH_POST_VOUCHER, B.AUTH_VCHR_GRP, B.AUTH_SCHED_PYMNT, B.AUTH_OVRRD_MATCH, B.AUTH_PREPAY_VCHR, B.PREPAY_LIMIT_AMT, 
       B.AUTH_PAY_UNMTCHED, B.UNMATCH_PAY_AMT, B.AUTH_CPY_MTCH_PO, B.PYMNT_RCRD_FLG, B.AUTH_3RDPARTY_VCHR, B.AUTH_ADJUST_VCHR, B.AUTH_JORUNAL_VCHR, B.AUTH_REGISTER_VCHR,
       B.AUTH_REGULAR_VCHR, B.AUTH_TEMPLATE_VCHR, B.AUTH_CORRECT_VCHR, B.AUTH_CLBK_VCHR, B.AUTH_SGL_PYMNT_VCH,
       C.AUTH_VNDR_UNCERTFY, C.AUTH_VNDR_CERTFY, C.AUTH_VNDR_INACT_ST, D.ORIGIN, D.DEPTID, D.LOCATION, 
       D.CNTRCT_ENTRY, D.CNTRCT_APPROVE, D.CNTRCT_HOLD, D.CNTRCT_CLOSE, D.CNTRCT_PO_RLS, D.CNTRCT_AP_RLS, D.SHIPTO_ID, D.LOCATION, D.CNTRCT_STATUS, 
       D.RFQ_ENTRY, D.RFQ_HOLD, D.RFQ_APPROVE, D.RFQ_CLOSE, D.RFQ_STATUS, D.BUSINESS_UNIT_RECV, D.EDIT_CHARTFIELDS, D.PO_ONLY_RECEIVE, D.ALL_BUYERS_FLG, D.ALL_REQUESTORS_FLG, 
       D.PO_APPROVAL_AUTH, D.PO_WRK_APPR_AUTH, D.PO_CLOSE_AUTH, D.REQ_APPROVAL_AUTH, D.REQ_WRK_APPR_AUTH, D.REQ_CLOSE_AUTH, D.OVERRIDE_SUGG_VNDR, D.INV_RECEIVER, 
       D.INTFC_RECEIPT, D.DUE_DT_DAYS, D.PREPAID_AUTH_STAT, D.DELETE_PO_ALLOWED, D.DELETE_REQ_ALLOWED, D.PO_CLOSE_ALL , D.REQ_CLOSE_ALL, D.CNTRCT_CANCEL, D.PO_VRBT_SECURITY, 
       D.PO_REOPEN_AUTH, D.OVRD_PO_FOR_CLOSE,  D.REQ_REOPEN_AUTH, D.OVRD_REQ_FOR_CLOSE
FROM PS_OPR_DEF_TBL_FS A , PS_OPR_DEF_TBL_AP B , PS_OPR_DEF_TBL_VND C , PS_OPR_DEF_TBL_PM D
WHERE A.OPRID = B.OPRID 
    AND A.OPRID = C.OPRID 
    AND A.OPRID = D.OPRID
    AND (A.BUSINESS_UNIT LIKE '6%' OR A.BUSINESS_UNIT = 'UNUNI');
--LISTAGG Funtion for security information ONLY ACTIVE USERS
SELECT ROLEUSER, LISTAGG(ROLENAME, '|') WITHIN GROUP (ORDER BY ROLEUSER) ROLENAME
FROM PSROLEUSER 
WHERE ROLEUSER IN (SELECT DISTINCT B.OPRID FROM PSUSEREMAIL A, PSOPRDEFN B WHERE A.OPRID = B.OPRID AND A.EMAILID LIKE '%unu.edu' AND B.ACCTLOCK = 0)
GROUP BY ROLEUSER
ORDER BY 1;
--LISTAGG Function for OPRALIASTYPE
--ARGUS has custom OPRALIASTYPE
SELECT A.OPRID, A.OPRDEFNDESC, A.EMAILID, LISTAGG(B.OPRALIASVALUE, '|') WITHIN GROUP (ORDER BY B.OPRALIASTYPE) OPRALIAS 
--B.OPRALIASVALUE
FROM PSOPRDEFN A, PSOPRALIAS B
WHERE A.OPRID = B.OPRID
    --AND B.OPRALIASTYPE = 'A02'
    --AND B.OPRALIASVALUE = 'UNUNI'
    --AND A.OPRID = 'prakash.prashant'
    AND A.OPRID IN (SELECT DISTINCT B.OPRID FROM PSUSEREMAIL A, PSOPRDEFN B WHERE A.OPRID = B.OPRID AND A.EMAILID LIKE '%unu.edu' AND B.ACCTLOCK = 0)
GROUP BY A.OPRID, A.OPRDEFNDESC, A.EMAILID
ORDER BY 1;
--UNU_USER_APPROVAL
--What can a person approve?
SELECT A.ROLEUSER, A.ROLENAME, B.DESCR, A.RTE_CNTL_PROFILE, H.RTE_CNTL_TYPE, L.RTE_FROM_VALUE, L.RTE_TO_VALUE
FROM PS_RTE_CNTL_RUSER A, PSROLEDEFN B, PS_RTE_CNTL_HDR H, PS_RTE_CNTL_LN L 
WHERE A.ROLENAME = B.ROLENAME
    AND A.RTE_CNTL_PROFILE = H.RTE_CNTL_PROFILE
    AND H.RTE_CNTL_PROFILE = L.RTE_CNTL_PROFILE
    AND H.RTE_CNTL_TYPE = L.RTE_CNTL_TYPE
    AND A.ROLEUSER IN (SELECT DISTINCT B.OPRID FROM PSUSEREMAIL A, PSOPRDEFN B WHERE A.OPRID = B.OPRID AND A.EMAILID LIKE '%unu.edu' AND B.ACCTLOCK = 0)
    --AND A.ROLENAME NOT LIKE '%LEVEL0%'
    AND A.RTE_CNTL_PROFILE NOT IN ('ADMIN_PO','ADMIN_AP')
ORDER BY 1, 2, 3;
--UNU Requestors
--Accounts which are unlocked ONLY
SELECT A.REQUESTOR_ID, A.ACTIVE_FLG, A.REQ_STATUS, A.SHIPTO_SETID, A.LOCATION_SETID, A.LOCATION, A.ORIGIN_PO_SETID, A.ORIGIN, A.DEPTID_SETID, A.CATALOG_SETID, 
            A.CATALOG_ID, A.USE_ASSGN_CAT_ONLY, A.CONSOLIDATE_FLG, A.PRICE_CAN_CHANGE, A.BUSINESS_UNIT_GL, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.FUND_CODE, 
            A.CHARTFIELD2, A.PROJECT_ID, A.BUSINESS_UNIT_PC, A.ACTIVITY_ID, B.CATALOG_ID
FROM PS_REQUESTOR_TBL A, PS_REQUESTOR_CAT B 
WHERE A.REQUESTOR_ID = B.REQUESTOR_ID (+)
    AND B.SETID (+) = 'UNUNI'
    AND A.REQUESTOR_ID IN (SELECT DISTINCT B.OPRID FROM PSUSEREMAIL A, PSOPRDEFN B WHERE B.OPRID = A.REQUESTOR_ID AND A.OPRID = B.OPRID AND A.EMAILID LIKE '%unu.edu' AND B.ACCTLOCK = 0)
ORDER BY 1;
--UNU Users Process Group Information
--Version 2
SELECT A.OPRID, A.RTM_PRCS_ALLOW AS "Allow Processing", A.RTM_CONSOLE_FLG "Use Event Notification", 
       (SELECT LISTAGG(B.RTM_SOURCE_TXN || ' - ' || RTS.DESCR || ' - ' || B.RTM_PROCESS_GROUP || ' - ' || RTG.RTM_SHORT_DESCR, ' > ') WITHIN GROUP (ORDER BY B.RTM_SOURCE_TXN) AS "Process Groups"
        FROM PS_RTM_OPR_GROUP B, PS_RTM_PROCESS_GRP RTG, PS_RTM_SOURCE RTS WHERE A.OPRID = B.OPRID AND B.RTM_PROCESS_GROUP = RTG.RTM_PROCESS_GROUP AND B.RTM_SOURCE_TXN = RTS.RTM_SOURCE_TXN) AS "Process Groups"
FROM PS_OPR_DEF_TBL_RTM A
WHERE A.OPRID IN (SELECT DISTINCT B.OPRID FROM PSUSEREMAIL A, PSOPRDEFN B WHERE A.OPRID = B.OPRID AND A.EMAILID LIKE '%unu.edu' AND B.ACCTLOCK = 0)
GROUP BY A.OPRID, A.RTM_PRCS_ALLOW, A.RTM_CONSOLE_FLG
ORDER BY A.OPRID;
--Use DB LINK for bringing in user information from Portal for UNUNI
SELECT A.UN_T_LNAME, A.UN_T_FNAME, A.UN_USER_ID, A.UN_EMAIL_ADDR, A.UN_CONTRACT_TYPE, A.UN_EMP_VND_ID, A.UN_BUS_UNIT, A.UN_LOCATION, A.UN_DEPTID,
       SUBSTR(A.UN_EMAIL_ADDR, instr(A.UN_EMAIL_ADDR, '@')+1) AS ORG
FROM PS_UN_ACS_USR_VW1@UNDPPALINK A
WHERE A.UN_AGENCY_NAME = 'UNUNI'
    AND A.UN_USER_ID <> 'kenta.fujimara'
ORDER BY UN_LOCATION;
