--AR20005
--Experimental Version 5
--Included Sponsor Type and its description column
--Make note that not all donors have a Sponsor Type
SELECT X.CUST_ID, X.NAME1, X.NAME2, X.NAMESHORT, X.SPNSR_TYPE, X.DESCR, X.BUSINESS_UNIT, X.ITEM,
            X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2, X.CHARTFIELD2, X.PROJECT_ID, 
            SUM(X.ITEM_AMT_BASE) ITEM_AMT_BASE, SUM(X.OVERDUE_AMT_BASE) OVERDUE_AMT_BASE, SUM(X.ITEM_AMT_BASE) + SUM(X.OVERDUE_AMT_BASE) NET_RCV_AMT_BASE, 
            SUM(X.COLLECTED_AMT_BASE) COLLECTED_AMT_BASE, SUM(X.WRITE_OFF_AMT_BASE) WRITE_OFF_AMT_BASE,
            (SUM(X.ITEM_AMT_BASE) + SUM(X.OVERDUE_AMT_BASE) + (SUM(X.COLLECTED_AMT_BASE) + SUM(X.WRITE_OFF_AMT_BASE))) REMAINING_AMT_BASE
FROM
(
SELECT DISTINCT ITA.CUST_ID, CUST.NAME1, CUST.NAME2, CUST.NAMESHORT, CUST.SPNSR_TYPE, SPNSR.DESCR, ITA.BUSINESS_UNIT, ITA.ITEM, 
            DST.ACCOUNT, DST.DEPTID, DST.OPERATING_UNIT, DST.FUND_CODE, DST.AFFILIATE, DST.AFFILIATE_INTRA1, DST.AFFILIATE_INTRA2, DST.CHARTFIELD2, DST.PROJECT_ID,
            CASE WHEN ITA.ENTRY_USE_ID NOT IN ('FC-01', 'WS-01', 'MT-01', 'DM-01', 'WS-09', 'WS-10', 'WS-11', 'WS-12', 'MT-02', 'MT-03', 'MT-06', 'MT-07', 'DM-07', 'DM-08', 'DM-09', 'DM-10') 
                     THEN SUM(ITA.ENTRY_AMT_BASE) ELSE 0 END AS "ITEM_AMT_BASE",
            CASE WHEN ITA.ENTRY_USE_ID IN ('WS-01', 'MT-01', 'DM-01') THEN SUM(ITA.ENTRY_AMT_BASE) ELSE 0 END AS "COLLECTED_AMT_BASE",
            CASE WHEN ITA.ENTRY_USE_ID IN ('WS-09', 'WS-10', 'WS-11', 'WS-12', 'MT-02', 'MT-03', 'MT-06', 'MT-07', 'DM-07', 'DM-08', 'DM-09', 'DM-10') 
                     THEN SUM(ITA.ENTRY_AMT_BASE) ELSE 0 END AS "WRITE_OFF_AMT_BASE",
            CASE WHEN ITA.ENTRY_USE_ID = 'FC-01' THEN SUM(ITA.ENTRY_AMT_BASE) ELSE 0 END AS "OVERDUE_AMT_BASE"
FROM PS_ITEM_ACTIVITY ITA, PS_ITEM_DST DST, PS_CUSTOMER CUST, PS_GM_SPNSR_TYPE SPNSR
WHERE ITA.BUSINESS_UNIT = DST.BUSINESS_UNIT
    AND ITA.CUST_ID = DST.CUST_ID
    AND ITA.ITEM = DST.ITEM
    AND ITA.ITEM_LINE = DST.ITEM_LINE
    AND ITA.ITEM_SEQ_NUM = DST.ITEM_SEQ_NUM
    --AND ITA.ENTRY_USE_ID NOT IN ('WS-01', 'MT-01', 'DM-01', 'WS-09', 'WS-10', 'WS-11', 'WS-12', 'MT-02', 'MT-03', 'MT-06', 'MT-07', 'DM-07', 'DM-08', 'DM-09', 'DM-10')
    AND CUST.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = DST.BUSINESS_UNIT AND G.RECNAME = 'CUSTOMER')
    AND CUST.CUST_ID = DST.CUST_ID
    AND (SPNSR.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC D WHERE D.SETCNTRLVALUE = DST.BUSINESS_UNIT AND D.RECNAME = 'GM_SPNSR_TYPE') OR SPNSR.SETID IS NULL)
    AND CUST.SPNSR_TYPE = SPNSR.SPNSR_TYPE (+)
    AND ITA.BUSINESS_UNIT LIKE '6%'
    --AND DST.CUST_ID IN ('10627')
    --[$whereclause]
    AND DST.SYSTEM_DEFINED = 'A'
    --[$Where_Write_Off]
GROUP BY ITA.CUST_ID, CUST.NAME1, CUST.NAME2, CUST.NAMESHORT, CUST.SPNSR_TYPE, SPNSR.DESCR, ITA.ITEM, ITA.BUSINESS_UNIT, ITA.ENTRY_USE_ID,
         DST.ACCOUNT, DST.DEPTID, DST.OPERATING_UNIT, DST.FUND_CODE, DST.AFFILIATE, DST.AFFILIATE_INTRA1, DST.AFFILIATE_INTRA2, DST.CHARTFIELD2, DST.PROJECT_ID
) X
WHERE X.BUSINESS_UNIT LIKE '6%'
    --AND X.CUST_ID IN ('10627', '10685', '10433', '10824', '10007', '10044', '10006')
    --AND X.CUST_ID IN ('10433')
GROUP BY X.CUST_ID, X.NAME1, X.NAME2, X.NAMESHORT, X.SPNSR_TYPE, X.DESCR, X.BUSINESS_UNIT, X.ITEM, X.ACCOUNT, X.DEPTID, X.OPERATING_UNIT, X.FUND_CODE, 
               X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2, X.CHARTFIELD2, X.PROJECT_ID
ORDER BY X.CUST_ID, X.BUSINESS_UNIT, X.ITEM;

--PIT_PENDING_ITEMS_ALL
--Experimental Version 5
--Added PS_ITEM and PS_ITEM_ACTIVITY
--Date criteria has been changed to limit the number of rows
SELECT 'PIT_PENDING_ITEMS_ALL', A.ENTRY_DT, A.GROUP_BU, A.GROUP_ID, A.EDIT_STATUS, X1.XLATLONGNAME AS EDIT_STS_DESCR, A.POST_STATUS, X2.XLATLONGNAME AS POST_STS_DESCR, 
       A.CONTROL_CURRENCY, A.FORMAT_CURRENCY, A.ORIGIN_ID, A.GROUP_TYPE, B.CONTRACT_NUM,
       A.OPRID, A.ACCOUNTING_DT, A.BUSINESS_UNIT, B.CUST_ID, C.NAME1, C.NAMESHORT, B.ASOF_DT, B.DUE_DT, B.POST_DT, B.ITEM, B.ITEM_LINE, B.ENTRY_TYPE, E.DESCRSHORT, 
       B.ENTRY_REASON, ERT.DESCR AS ENTRY_REASON_DESCR, B.POSTED_FLAG, B.DST_ID_AR, B.ENTRY_USE_ID, B.PAYMENT_METHOD,
       B.ENTRY_AMT, B.ENTRY_CURRENCY, B.ENTRY_AMT_BASE, B.CURRENCY_CD, B.AR_ERROR_CD, ITM.ITEM_STATUS, X3.XLATLONGNAME AS ITEM_STATUS_DESCR, 
       ITM.PO_REF AS ITEM_PO_REF, ITM.BANK_CD AS ITEM_BANK_CD, ITM.BANK_ACCT_KEY AS ITEM_BANK_ACCT_KEY, ITM.DT_INVOICED AS ITEM_DT_INVOICED, ITM.INVOICE AS ITEM_INVOICE,
       ITM.SHIP_TO_CUST_ID, ITM.SOLD_TO_CUST_ID,
       ITA.ITEM_SEQ_NUM, ITA.ENTRY_TYPE AS ITA_ENTRY_TYPE, ITA.DEPOSIT_BU, ITA.DEPOSIT_ID, ITA.GROUP_BU AS ITA_GROUP_BU, ITA.GROUP_ID AS ITA_GROUP_ID, ITA.GROUP_SEQ_NUM AS ITA_GROUP_SEQ_NUM, ITA.PAYMENT_ID, ITA.PAYMENT_SEQ_NUM,
       ITA.BANK_CD AS ITA_BANK_CD, ITA.BANK_ACCT_KEY AS ITA_BANK_ACCT_KEY, 
       PD.ACCOUNT AS PEND_ACCT, PD.DEPTID AS PEND_DEPTID, PD.OPERATING_UNIT AS PEND_OP_UNIT, PD.FUND_CODE AS PEND_FUND_CD, PD.CHARTFIELD2 AS PEND_DONOR, PD.PROJECT_ID AS PEND_PROJECT_ID, PD.ACTIVITY_ID, PD.BUDGET_DT,
       ITMDST.ACCOUNT AS ITEM_ACCT, ITMDST.DEPTID AS ITEM_DEPTID, ITMDST.OPERATING_UNIT AS ITEM_OP_UNIT, ITMDST.FUND_CODE AS ITEM_FUND_CD, ITMDST.CHARTFIELD2 AS ITEM_DONOR, ITMDST.PROJECT_ID AS ITEM_PROJECT_ID, 
       ITMDST.ACTIVITY_ID AS ITEM_ACTIVITY_ID,
       DEPC.OPRID, DEPC.ASSN_OPRID,DEPC.DEP_POST_STATUS, X5.XLATLONGNAME AS DEP_POST_STS_DESCR, DEPC.PAY_WS_TYPE, DEPC.DEPOSIT_STATUS, X6.XLATLONGNAME AS DEPOSIT_STS_DESCR,
       DEPC.BANK_SETID, DEPC.BANK_CD, DEPC.BNK_ID_NBR, DEPC.BANK_ACCT_KEY, DEPC.BANK_ACCOUNT_NUM, DEPC.DEPOSIT_TYPE, DEPC.PYMT_RATE_MULT, DEPC.PYMT_RATE_DIV,
       PYMT.PAYMENT_SEQ_NUM, PYMT.PAYMENT_ID, PYMT.PAYMENT_STATUS, X4.XLATLONGNAME AS PYMNT_STS_DESCR, PYMT.PAYMENT_AMT, PYMT.PAYMENT_CURRENCY, PYMT.UNPOST_REASON
FROM ((((((((((((((((PS_GROUP_CONTROL A 
         LEFT OUTER JOIN PS_PENDING_ITEM B ON A.GROUP_BU = B.GROUP_BU AND A.GROUP_ID = B.GROUP_ID)
         LEFT OUTER JOIN PS_PENDING_DST PD ON B.GROUP_BU = PD.GROUP_BU AND B.GROUP_ID = PD.GROUP_ID AND B.BUSINESS_UNIT = PD.BUSINESS_UNIT AND B.CUST_ID = PD.CUST_ID AND B.ITEM = PD.ITEM AND B.ITEM_LINE = PD.ITEM_LINE 
                                          AND B.GROUP_SEQ_NUM = PD.GROUP_SEQ_NUM AND PD.SYSTEM_DEFINED = 'A')
         LEFT OUTER JOIN PS_ITEM ITM ON ITM.BUSINESS_UNIT = B.BUSINESS_UNIT AND ITM.CUST_ID =  B.CUST_ID AND ITM.ITEM = B.ITEM AND ITM.ITEM_LINE = B.ITEM_LINE)
         LEFT OUTER JOIN PS_ITEM_ACTIVITY ITA ON ITA.BUSINESS_UNIT = ITM.BUSINESS_UNIT AND ITA.CUST_ID =  ITM.CUST_ID AND ITA.ITEM = ITM.ITEM AND ITA.ITEM_LINE = ITM.ITEM_LINE 
                                             AND A.GROUP_BU = ITA.GROUP_BU AND A.GROUP_ID = ITA.GROUP_ID AND B.GROUP_SEQ_NUM = ITA.GROUP_SEQ_NUM)
         --LEFT OUTER JOIN PS_ITEM_ACTIVITY ITA ON A.GROUP_BU = ITA.GROUP_BU AND A.GROUP_ID = ITA.GROUP_ID AND A.BUSINESS_UNIT = ITA.BUSINESS_UNIT)
         --LEFT OUTER JOIN PS_ITEM ITM ON ITM.BUSINESS_UNIT = ITA.BUSINESS_UNIT AND ITM.CUST_ID =  ITA.CUST_ID AND ITM.ITEM = ITA.ITEM AND ITM.ITEM_LINE = ITA.ITEM_LINE)
         LEFT OUTER JOIN PS_ITEM_DST ITMDST ON ITA.BUSINESS_UNIT = ITMDST.BUSINESS_UNIT AND ITA.CUST_ID = ITMDST.CUST_ID AND ITA.ITEM = ITMDST.ITEM 
                                           AND ITA.ITEM_LINE = ITMDST.ITEM_LINE AND ITA.ITEM_SEQ_NUM = ITMDST.ITEM_SEQ_NUM AND ITMDST.SYSTEM_DEFINED = 'A')
         LEFT OUTER JOIN PS_DEPOSIT_CONTROL DEPC ON ITA.DEPOSIT_BU = DEPC.DEPOSIT_BU AND ITA.DEPOSIT_ID = DEPC.DEPOSIT_ID)
         LEFT OUTER JOIN PS_PAYMENT PYMT ON DEPC.DEPOSIT_BU = PYMT.DEPOSIT_BU AND DEPC.DEPOSIT_ID = PYMT.DEPOSIT_ID AND ITA.PAYMENT_SEQ_NUM = PYMT.PAYMENT_SEQ_NUM)
         LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'PAYMENT_STATUS' AND X4.FIELDVALUE = PYMT.PAYMENT_STATUS)
         LEFT OUTER JOIN PSXLATITEM X5 ON X5.FIELDNAME = 'DEP_POST_STATUS' AND X5.FIELDVALUE = DEPC.DEP_POST_STATUS)
         LEFT OUTER JOIN PSXLATITEM X6 ON X6.FIELDNAME = 'DEPOSIT_STATUS' AND X6.FIELDVALUE = DEPC.DEPOSIT_STATUS)
         LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'ITEM_STATUS' AND X3.FIELDVALUE = ITM.ITEM_STATUS)
         LEFT OUTER JOIN PS_CUSTOMER C ON C.SETID = 'UNUNI' AND B.CUST_ID = C.CUST_ID)
         LEFT OUTER JOIN PS_ENTRY_TYPE_TBL E ON E.SETID = 'UNUNI' AND E.ENTRY_TYPE = B.ENTRY_TYPE)
         LEFT OUTER JOIN PS_ENTRY_REASN_TBL ERT ON ERT.SETID = E.SETID AND E.ENTRY_TYPE = ERT.ENTRY_TYPE AND B.ENTRY_REASON = ERT.ENTRY_REASON) 
         LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'EDIT_STATUS' AND X1.FIELDVALUE = A.EDIT_STATUS)
         LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'POST_STATUS' AND X2.FIELDVALUE = A.POST_STATUS)
WHERE A.GROUP_BU LIKE '6%'
  --AND A.ACCOUNTING_DT BETWEEN TO_DATE('2013-01-01','YYYY-MM-DD') AND TO_DATE('2013-12-31','YYYY-MM-DD')
  AND A.ENTRY_DT BETWEEN TO_DATE('2014-01-01','YYYY-MM-DD') AND TO_DATE('2020-12-31','YYYY-MM-DD')
  --AND B.CUST_ID IN ('10083', '10044')
ORDER BY A.ENTRY_DT, A.GROUP_BU, A.GROUP_ID, A.BUSINESS_UNIT, B.CUST_ID, B.ITEM, B.ITEM_LINE, ITA.ITEM_SEQ_NUM, ITA.GROUP_SEQ_NUM;
