--Actual Receipt Accrual Version 2
--15SEPT2014
SELECT H.BUSINESS_UNIT AS BU_RECV, H.RECEIVER_ID, H.RECEIPT_DT, S.OPRID, H.MATCH_STATUS_RECV, S.RECV_LN_NBR, S.RECV_SHIP_SEQ_NBR, LD.DISTRIB_LINE_NUM, S.CURRENCY_CD, 
            S.MERCHANDISE_AMT, S.MERCH_AMT_BSE, S.MERCH_AMT_PO_BSE, S.BUSINESS_UNIT_PO AS BU_PO, S.PO_ID, L.LINE_NBR, D.SCHED_NBR, S.DISTRIB_MTHD_FLG,
            L.AMT_ONLY_FLG, D.DISTRIB_LINE_NUM AS PO_DISTRIB_LINE_NUM, G.CATEGORY_CD, G.DESCR, G.ACCOUNT AS CAT_ACCOUNT, L.INV_ITEM_ID, ITM.DESCR AS ITM_DESCR, L.DESCR254_MIXED, 
            D.QTY_PO AS POD_QTY_PO, D.MERCH_AMT_BSE AS PO_USD_AMT, D.MERCHANDISE_AMT AS PO_FOREIGN_AMT, D.CURRENCY_CD AS PO_DIST_CURR_CD,
            D.ACCOUNT AS PO_ACCT, D.OPERATING_UNIT AS PO_OP_UNIT, D.FUND_CODE AS PO_FUND, D.DEPTID AS PO_DEPT, D.PROJECT_ID AS PO_PRJ, D.ACTIVITY_ID AS PO_ACT, 
            D.CHARTFIELD2 AS PO_DONOR, 
            G.RECV_REQ, P.VENDOR_SETID, P.VENDOR_ID, V.NAME1, S.CONVERSION_RATE,
            LD.BUSINESS_UNIT_AM, LD.BUSINESS_UNIT_GL, LD.PROFILE_ID, LD.FINANCIAL_ASSET_SW, LD.RECV_DS_STATUS, LD.MERCHANDISE_AMT_PO, LD.LOCATION, LD.REQ_ID,
            D.QTY_PO "PO Quantity", S.QTY_LN_ASSET_SUOM "Quantity to be Asset Tracked", S.QTY_LN_INV_SUOM "Line Inv Qty", S.QTY_SH_ACCPT "Qty Accepted in Receipt UOM", 
            S.QTY_SH_ACCPT_SUOM "Accepted Quantity", S.QTY_SH_ACCPT_VUOM "Accept Quantity in Vendor UOM", S.QTY_SH_NETRCV_VUOM "Net Receipt Quantity", 
            S.QTY_SH_RECVD "Qty Received in Receipt UOM", S.QTY_SH_RECVD_SUOM "Receipt Quantity", S.QTY_SH_RECVD_VUOM "Receipt Quantity in Vendor UOM", 
            S.REJECT_ACTION, S.REJECT_REASON, S.RECEIPT_ALLOC_TYPE, S.RECEIPT_DTTM, S.RECEIPT_UM, S.RECEIVE_UOM, S.RECV_LN_MATCH_OPT, S.RECV_SHIP_STATUS, S.RECV_STOCK_UOM, 
            S.SERIAL_CONTROL, S.SERIAL_STATUS, S.SHIP_DATE_STATUS, S.SHIP_QTY_STATUS, S.UNIT_MEASURE_STD
FROM PS_RECV_HDR H, PS_PO_HDR P, PS_PO_LINE L, PS_RECV_LN_SHIP S, PS_PO_LINE_DISTRIB D, PS_SET_CNTRL_REC F, PS_ITM_CAT_TBL G, PS_RECV_LN_DISTRIB LD,
          PS_MASTER_ITEM_TBL ITM, PS_VENDOR V
WHERE H.BUSINESS_UNIT LIKE '6%'
   AND S.BUSINESS_UNIT = H.BUSINESS_UNIT
   AND S.RECEIVER_ID = H.RECEIVER_ID
   AND S.MATCH_LINE_FLG = 'Y' 
   AND S.RECV_LN_MATCH_OPT <> 'F' 
   AND S.PRODUCTION_ID = ' ' 
   AND S.BUSINESS_UNIT_PO = P.BUSINESS_UNIT 
   AND S.PO_ID = P.PO_ID 
   AND S.PO_ID <> ' ' 
   AND S.BUSINESS_UNIT_PO = L.BUSINESS_UNIT 
   AND S.PO_ID = L.PO_ID 
   AND S.LINE_NBR = L.LINE_NBR    
   AND S.BUSINESS_UNIT_PO = D.BUSINESS_UNIT 
   AND S.PO_ID = D.PO_ID 
   AND S.LINE_NBR = D.LINE_NBR
   AND S.SCHED_NBR = D.SCHED_NBR
   AND S.BUSINESS_UNIT = LD.BUSINESS_UNIT 
   AND S.RECEIVER_ID = LD.RECEIVER_ID 
   AND S.RECV_LN_NBR = LD.RECV_LN_NBR 
   AND S.RECV_SHIP_SEQ_NBR = LD.RECV_SHIP_SEQ_NBR
   AND LD.PO_DIST_LINE_NUM = D.DISTRIB_LINE_NUM
   AND F.SETCNTRLVALUE = S.BUSINESS_UNIT
   AND G.SETID = F.SETID
   AND G.CATEGORY_ID = S.CATEGORY_ID
   AND F.RECNAME = 'ITM_CAT_TBL'   
   AND G.EFFDT = (SELECT MAX(G_ED.EFFDT) FROM PS_ITM_CAT_TBL G_ED WHERE G.SETID = G_ED.SETID AND G.CATEGORY_TYPE = G_ED.CATEGORY_TYPE AND G.CATEGORY_CD = G_ED.CATEGORY_CD 
          AND G.CATEGORY_ID = G_ED.CATEGORY_ID AND G_ED.EFFDT <= SYSDATE)   
   AND L.ITM_SETID = ITM.SETID (+)
   AND L.INV_ITEM_ID = ITM.INV_ITEM_ID (+)
   AND P.VENDOR_SETID = V.SETID
   AND P.VENDOR_ID = V.VENDOR_ID     
   AND L.RECV_REQ = 'Y'
   AND S.MERCHANDISE_AMT <> 0 
   AND S.RECV_SHIP_STATUS IN ('O', 'R') 
   AND H.RECV_STATUS IN ('N', 'O', 'P','R','M') 
   AND P.MATCH_STATUS_PO NOT IN ('N')
   AND H.MATCH_STATUS_RECV <> 'M' 
   AND D.DST_ACCT_TYPE = 'DST'
   AND D.KK_CLOSE_FLAG <> 'Y'
   --AND NOT EXISTS (SELECT 'X' FROM PS_RECV_LN_ACCTG LN WHERE LN.BUSINESS_UNIT = LD.BUSINESS_UNIT AND LN.RECEIVER_ID = LD.RECEIVER_ID AND LN.RECV_LN_NBR = LD.RECV_LN_NBR AND LN.RECV_SHIP_SEQ_NBR = LD.RECV_SHIP_SEQ_NBR AND LN.DISTRIB_LINE_NUM = LD.DISTRIB_LINE_NUM)
   AND EXISTS (SELECT 'X' FROM PS_RECV_LN_SHP_MTH M WHERE S.BUSINESS_UNIT = M.BUSINESS_UNIT AND S.RECEIVER_ID  = M.RECEIVER_ID AND S.RECV_LN_NBR = M.RECV_LN_NBR AND S.RECV_SHIP_SEQ_NBR = M.RECV_SHIP_SEQ_NBR)
   AND NOT EXISTS (SELECT 'X' FROM PS_PO_LINE_SHIP LS WHERE LS.BUSINESS_UNIT = S.BUSINESS_UNIT_PO AND LS.PO_ID = S.PO_ID AND LS.LINE_NBR = S.LINE_NBR AND LS.SCHED_NBR = S.SCHED_NBR AND LS.MATCH_LINE_OPT = 'N')    
ORDER BY 1,2,3,4,5,D.LINE_NBR, D.SCHED_NBR, D.DISTRIB_LINE_NUM;
