--Check KK Exceptions for UNU since inception
SELECT TO_CHAR(KK_TRAN_DT, 'YYYY') AS KK_YEAR, BUSINESS_UNIT, KK_SOURCE_TRAN, KK_PROCESS_STATUS, COUNT(1) "Count of Rows"
FROM PS_KK_SOURCE_HDR
WHERE (BUSINESS_UNIT LIKE '6%' OR BUSINESS_UNIT = 'UNUNI' OR BUSINESS_UNIT_PC = 'UNUNI')
     AND KK_PROCESS_STATUS NOT IN ('V', 'W')
GROUP BY TO_CHAR(KK_TRAN_DT, 'YYYY'), BUSINESS_UNIT, KK_SOURCE_TRAN, KK_PROCESS_STATUS
ORDER BY TO_CHAR(KK_TRAN_DT, 'YYYY') DESC, BUSINESS_UNIT, KK_SOURCE_TRAN, KK_PROCESS_STATUS;
--Requisition Budget Status
--Also added PO information. Change KK transaction date to filter
SELECT A.BUSINESS_UNIT, A.REQ_ID, A.LINE_NBR, A.SCHED_NBR, A.DISTRIB_LINE_NUM, B.REQ_DT, B.REQ_STATUS, B.BUDGET_HDR_STATUS, A.BUDGET_LINE_STATUS,  
            PO.BUSINESS_UNIT AS PO_BU, PO.PO_ID, PO.DISTRIB_LN_STATUS, E.EXCPTN_TYPE, X1.XLATLONGNAME, E.LEDGER_GROUP,
            A.ACCOUNT, A.OPERATING_UNIT, E.DEPTID AS BUD_DEPT, A.DEPTID, A.FUND_CODE, A.CHARTFIELD2, A.PROJECT_ID, A.ACTIVITY_ID,  
            A.CURRENCY_CD, A.MONETARY_AMOUNT, A.MONETARY_AMT_BSE, A.CURRENCY_CD_BASE,
            B.REQUESTOR_ID, B.OPRID_ENTERED_BY, B.OPRID_MODIFIED_BY, B.OPRID_APPROVED_BY,
            E.ACCOUNT, E.DEPTID, E.OPERATING_UNIT, E.FUND_CODE, E.CHARTFIELD2, E.PROJECT_ID, E.ACTIVITY_ID, E.BUDGET_PERIOD, E.PROCESS_INSTANCE,
            A.QTY_OPEN, A.AMT_OPEN, A.AMT_OPEN_BSE, A.QTY_OPEN_STD, A.KK_CLOSE_FLAG
FROM PS_REQ_HDR B, (((((PS_REQ_LN_DISTRIB A LEFT OUTER JOIN PS_KK_SOURCE_HDR C ON A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.REQ_ID = C.REQ_ID) 
                                   LEFT OUTER JOIN PS_KK_SOURCE_LN D ON C.KK_TRAN_DT = D.KK_TRAN_DT AND C.KK_TRAN_ID = D.KK_TRAN_ID AND A.LINE_NBR = D.LINE_NBR 
                                                                                           AND A.SCHED_NBR = D.SCHED_NBR AND A.DISTRIB_LINE_NUM = D.DISTRIB_LINE_NUM)
                                   LEFT OUTER JOIN PS_KK_EXCPTN_TBL E ON D.KK_TRAN_ID = E.KK_TRAN_ID AND D.KK_TRAN_DT = E.KK_TRAN_DT AND D.KK_TRAN_LN = E.KK_TRAN_LN)
                                   LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'EXCPTN_TYPE' AND X1.FIELDVALUE = E.EXCPTN_TYPE)
                                   LEFT OUTER JOIN PS_PO_LINE_DISTRIB PO ON PO.BUSINESS_UNIT_REQ = A.BUSINESS_UNIT AND PO.REQ_ID = A.REQ_ID AND PO.REQ_LINE_NBR = A.LINE_NBR
                                                                              AND PO.REQ_SCHED_NBR = A.SCHED_NBR AND PO.REQ_DISTRIB_NBR = A.DISTRIB_LINE_NUM)
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
     AND A.REQ_ID = B.REQ_ID
     AND A.BUSINESS_UNIT LIKE '6%'     
     AND A.BUDGET_LINE_STATUS IN ('E','N')
     --AND B.REQ_STATUS NOT IN ('C', 'X')
     AND TO_CHAR(C.KK_TRAN_DT, 'YYYY') >= '2014'
ORDER BY 1,2,3,4,5,6;
--PO Budget Status
--Check the PO Status to eliminate POs which are closed/cancelled
--Apparently PS is maintaining a row in KK Exception Table
SELECT A.BUSINESS_UNIT, A.PO_ID, A.LINE_NBR, A.SCHED_NBR, A.DISTRIB_LINE_NUM, B.PO_STATUS, B.RECV_STATUS, B.PO_DT, A.DST_ACCT_TYPE, B.BUDGET_HDR_STATUS,
            B.MATCH_STATUS_PO, A.BUDGET_LINE_STATUS, E.EXCPTN_TYPE, X1.XLATLONGNAME, E.LEDGER_GROUP, B.VENDOR_ID, B.PO_REF, 
            B.OPRID_ENTERED_BY, B.OPRID_APPROVED_BY, B.OPRID_MODIFIED_BY, 
            A.QTY_PO_STD_EXP, A.CURRENCY_CD, A.MONETARY_AMOUNT, A.MONETARY_AMT_BSE, A.CURRENCY_CD_BASE,
            A.ACCOUNT, A.OPERATING_UNIT, E.DEPTID AS BUD_DEPT, A.DEPTID, A.FUND_CODE, A.CHARTFIELD2, A.PROJECT_ID, A.ACTIVITY_ID,
            C.KK_TRAN_ID, C.KK_TRAN_DT, C.KK_SOURCE_TRAN, C.KK_PROCESS_STATUS,
            E.ACCOUNT, E.DEPTID, E.OPERATING_UNIT, E.FUND_CODE, E.CHARTFIELD2, E.PROJECT_ID, E.ACTIVITY_ID, E.BUDGET_PERIOD, E.PROCESS_INSTANCE,
            A.BUSINESS_UNIT_REQ AS BU_REQ, A.REQ_ID, A.REQ_LINE_NBR, A.REQ_SCHED_NBR, A.REQ_DISTRIB_NBR, 
            A.KK_CLOSE_FLAG, A.KK_PROCESS_PRIOR, A.KK_CLOSE_PRIOR           
FROM PS_PO_HDR B, ((((PS_PO_LINE_DISTRIB A LEFT OUTER JOIN PS_KK_SOURCE_HDR C ON A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.PO_ID = C.PO_ID)
                                LEFT OUTER JOIN PS_KK_SOURCE_LN D ON C.KK_TRAN_ID = D.KK_TRAN_ID AND C.KK_TRAN_DT = D.KK_TRAN_DT AND A.LINE_NBR = D.LINE_NBR 
                                                                                         AND A.SCHED_NBR = D.SCHED_NBR AND A.DST_ACCT_TYPE = D.DST_ACCT_TYPE 
                                                                                         AND A.DISTRIB_LINE_NUM = D.DISTRIB_LINE_NUM)
                                LEFT OUTER JOIN PS_KK_EXCPTN_TBL E ON D.KK_TRAN_ID = E.KK_TRAN_ID AND D.KK_TRAN_DT = E.KK_TRAN_DT AND D.KK_TRAN_LN = E.KK_TRAN_LN) 
                                LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'EXCPTN_TYPE' AND X1.FIELDVALUE = E.EXCPTN_TYPE)
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
     AND A.PO_ID = B.PO_ID
     AND A.BUSINESS_UNIT LIKE '6%'
     AND A.BUDGET_LINE_STATUS IN ('E','N')
     --AND B.PO_STATUS NOT IN ('C', 'X')
     --AND A.DST_ACCT_TYPE <> 'RAC'
     --AND E.LEDGER_GROUP <> 'CHD_UU'
     AND TO_CHAR(C.KK_TRAN_DT, 'YYYY') >= '2014'
ORDER BY A.BUSINESS_UNIT, A.PO_ID, A.LINE_NBR, A.SCHED_NBR, A.DISTRIB_LINE_NUM, B.PO_DT;
--Vouchers with KK Exceptions
--Based on PS_DISTRIB_LINE - AP_VOUCHER
--Modified it based on PS delivered view KK_XCP_AP1_VW2
SELECT A.BUSINESS_UNIT, A.VOUCHER_ID, B.VENDOR_ID, A.VOUCHER_LINE_NUM, A.DISTRIB_LINE_NUM, B.BUDGET_HDR_STATUS, A.BUDGET_LINE_STATUS, 
            E.EXCPTN_TYPE, X1.XLATLONGNAME, E.LEDGER_GROUP, A.FOREIGN_AMOUNT, A.TXN_CURRENCY_CD, A.MERCHANDISE_AMT, A.MERCH_AMT_BSE, A.ACCOUNTING_DT, 
            B.CLOSE_STATUS, B.ENTRY_STATUS, A.BUDGET_DT, A.QTY_VCHR, A.MONETARY_AMOUNT, A.CURRENCY_CD, A.MONETARY_AMT_BSE, A.BASE_CURRENCY, 
            B.MATCH_STATUS_VCHR, A.LEDGER, B.APPR_STATUS, B.APPR_INSTANCE, B.OPRID, B.OPRID_LAST_UPDT, APPR.ROLEUSER AS OPRID_APPROVED_BY,
            A.ACCOUNT, A.OPERATING_UNIT, A.DEPTID, A.FUND_CODE, A.CHARTFIELD2, A.BUSINESS_UNIT_PC, A.PROJECT_ID, A.ACTIVITY_ID, 
            C.KK_TRAN_ID, C.KK_TRAN_DT, C.KK_SOURCE_TRAN, C.KK_PROCESS_STATUS, 
            E.ACCOUNT, E.DEPTID, E.OPERATING_UNIT, E.FUND_CODE, E.CHARTFIELD2, E.PROJECT_ID, E.ACTIVITY_ID, E.BUDGET_PERIOD, E.PROCESS_INSTANCE,
            A.BUSINESS_UNIT_PO, A.PO_ID, A.LINE_NBR, A.SCHED_NBR, A.PO_DIST_LINE_NUM, 
            A.BUSINESS_UNIT_RECV, A.RECEIVER_ID, A.RECV_LN_NBR, A.RECV_SHIP_SEQ_NBR, A.RECV_DIST_LINE_NUM, B.INVOICE_ID, B.INVOICE_DT,
            A.KK_PROCESS_PRIOR, A.KK_CLOSE_PRIOR
FROM PS_VOUCHER B, ((((PS_DISTRIB_LINE A LEFT OUTER JOIN PS_KK_SOURCE_HDR C ON A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.VOUCHER_ID = C.VOUCHER_ID)
                                   LEFT OUTER JOIN PS_KK_SOURCE_LN D ON C.KK_TRAN_ID = D.KK_TRAN_ID AND C.KK_TRAN_DT = D.KK_TRAN_DT 
                                                                                            AND A.VOUCHER_LINE_NUM = D.VOUCHER_LINE_NUM AND A.DISTRIB_LINE_NUM = D.DISTRIB_LINE_NUM)
                                   LEFT OUTER JOIN PS_KK_EXCPTN_TBL E ON D.KK_TRAN_ID = E.KK_TRAN_ID AND D.KK_TRAN_DT = E.KK_TRAN_DT AND D.KK_TRAN_LN = E.KK_TRAN_LN)
                                   LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'EXCPTN_TYPE' AND X1.FIELDVALUE = E.EXCPTN_TYPE), PS_APPR_INST_LOG APPR
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
     AND A.VOUCHER_ID = B.VOUCHER_ID
     AND (A.BUSINESS_UNIT LIKE '6%' OR A.BUSINESS_UNIT_GL = 'UNUNI')
     AND A.BUDGET_LINE_STATUS IN ('E', 'N')
     AND B.APPR_INSTANCE = APPR.APPR_INSTANCE 
     AND APPR.APPR_INST_STATUS = 'A'
     --AND B.ENTRY_STATUS NOT IN ('X','T')
     --AND B.CLOSE_STATUS <> 'C'
     AND TO_CHAR(C.KK_TRAN_DT, 'YYYY') >= '2014'
ORDER BY A.BUSINESS_UNIT, A.VOUCHER_ID, A.VOUCHER_LINE_NUM, A.DISTRIB_LINE_NUM, A.BUDGET_LINE_STATUS, E.EXCPTN_TYPE;
--Vouchers with KK Exceptions RXL and RXG
--Based on PS_VCHR_ACCTG_LINE - AP_ACCT_LN
--Modified it based on PS delivered view KK_XCP_AP2_VW2
SELECT A.BUSINESS_UNIT, A.VOUCHER_ID, A.VOUCHER_LINE_NUM, A.DISTRIB_LINE_NUM, A.BUDGET_HDR_STATUS, A.BUDGET_LINE_STATUS, E.EXCPTN_TYPE, X1.XLATLONGNAME, 
       E.LEDGER_GROUP, A.FOREIGN_AMOUNT, A.FOREIGN_CURRENCY, A.MONETARY_AMOUNT, A.MERCHANDISE_AMT, A.MERCH_AMT_BSE, A.ACCOUNTING_DT, 
       B.MATCH_STATUS_VCHR, A.APPL_JRNL_ID, A.PYMNT_CNT, A.UNPOST_SEQ, A.DST_ACCT_TYPE, A.LEDGER, A.CF_BAL_LINE_NUM,        
       A.ACCOUNT, A.OPERATING_UNIT, A.DEPTID, A.FUND_CODE, A.CHARTFIELD2, A.BUSINESS_UNIT_PC, A.PROJECT_ID, A.ACTIVITY_ID, 
       C.KK_TRAN_ID, C.KK_TRAN_DT, C.KK_SOURCE_TRAN, C.KK_PROCESS_STATUS, 
       E.ACCOUNT, E.DEPTID, E.OPERATING_UNIT, E.FUND_CODE, E.CHARTFIELD2, E.PROJECT_ID, E.ACTIVITY_ID, E.BUDGET_PERIOD, E.PROCESS_INSTANCE
FROM PS_VOUCHER B, ((((PS_VCHR_ACCTG_LINE A LEFT OUTER JOIN PS_KK_SOURCE_HDR C ON A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.VOUCHER_ID = C.VOUCHER_ID
                    AND A.APPL_JRNL_ID = C.APPL_JRNL_ID AND A.PYMNT_CNT = C.PYMNT_CNT)
                    LEFT OUTER JOIN PS_KK_SOURCE_LN D ON C.KK_TRAN_ID = D.KK_TRAN_ID AND C.KK_TRAN_DT = D.KK_TRAN_DT 
                    AND A.VOUCHER_LINE_NUM = D.VOUCHER_LINE_NUM AND A.DISTRIB_LINE_NUM = D.DISTRIB_LINE_NUM
                    AND A.UNPOST_SEQ = D.UNPOST_SEQ AND A.DST_ACCT_TYPE = D.DST_ACCT_TYPE 
                    AND A.CF_BAL_LINE_NUM = D.CF_BAL_LINE_NUM AND A.LEDGER = D.LEDGER)
                    LEFT OUTER JOIN PS_KK_EXCPTN_TBL E ON D.KK_TRAN_ID = E.KK_TRAN_ID AND D.KK_TRAN_DT = E.KK_TRAN_DT AND D.KK_TRAN_LN = E.KK_TRAN_LN)
                    LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'EXCPTN_TYPE' AND X1.FIELDVALUE = E.EXCPTN_TYPE)
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND A.VOUCHER_ID = B.VOUCHER_ID
  AND (A.BUSINESS_UNIT LIKE '6%' OR A.BUSINESS_UNIT_GL = 'UNUNI')
  AND A.BUDGET_LINE_STATUS IN ('E', 'N')
  --AND B.ENTRY_STATUS NOT IN ('X','T')
  --AND B.CLOSE_STATUS <> 'C'
  --AND TO_CHAR(C.KK_TRAN_DT, 'YYYY') >= '2014'
ORDER BY 1,2,3,4,7;
--Review Commitment Control - PC Exceptions
--Not from KK
SELECT A.BUSINESS_UNIT, A.PROJECT_ID, A.RESOURCE_ID, A.BUDGET_PERIOD, A.BUDGET_LN, A.KK_SOURCE_TRAN, A.TRANS_DT, A.ACCOUNTING_DT, A.CALENDAR_ID,
       A.PC_BUDGET_ID, B.PC_BUD_TYPE, B.DESCR AS PROJ_DESCR, B.START_DT, B.CALENDAR_ID, B.NUM_PERIODS, A.DESCR AS BUD_ITEM_DESCR, 
       A.PC_INTFC_STATUS, A.PC_LOAD_STATUS, B.PC_BUDGET_STATUS, B.ANALYSIS_TYPE, B.PC_FUND_FINALIZED, B.FINALIZE_SW, B.PROJECT_ID_TO, B.POST_OPTION, 
       B.PC_SEND_TO_KK, B.LAST_DTTIME, B.FMS_DTTM_STAMP, B.FMS_OPRID, B.FMS_LASTUPDDTTM, B.FMS_LASTUPDOPRID, B.BUDGET_ADJUST,
       A.ANALYSIS_TYPE, A.INTFC_ID, A.PROCESS_INSTANCE, A.KK_DISTRIB_STATUS, A.PC_BUDGET_ITEM, KK_BUDG_LN_TYPE, BD_HDR_STATUS, GM_DISTRIB_STATUS, LOAD_STATUS,
       A.JOURNAL_ID, A.ACCOUNT, A.OPERATING_UNIT, A.FUND_CODE, A.DEPTID, A.CHARTFIELD2, A.ACTIVITY_ID, A.MESSAGE_SET_NBR, A.MESSAGE_NBR, C.MESSAGE_TEXT
FROM PS_INTFC_PROJ_RES A, PS_PC_BUD_PLAN B, PSMSGCATDEFN C
WHERE A.KK_DISTRIB_STATUS IN ('E', 'S', 'B', 'C', 'N', ' ') 
    AND A.BUSINESS_UNIT = B.BUSINESS_UNIT 
    AND A.PROJECT_ID = B.PROJECT_ID 
    AND (A.PC_BUDGET_ID = B.PC_BUDGET_ID OR A.PC_BUDGET_ID = 0)
    AND A.MESSAGE_SET_NBR = C.MESSAGE_SET_NBR (+)
    AND A.MESSAGE_NBR = C.MESSAGE_NBR (+)
    AND A.BUSINESS_UNIT = 'UNUNI'
ORDER BY BUDGET_PERIOD DESC, B.FMS_LASTUPDDTTM DESC;
--Project Budget Exceptions
--From KK
--Includes KK Header, Line and Exception Table(s)
SELECT A.BUSINESS_UNIT, A.PROJECT_ID, A.RESOURCE_ID, A.BUDGET_PERIOD, A.BUDGET_LN, A.KK_SOURCE_TRAN, KKH.KK_SOURCE_TRAN, KKH.KK_TRAN_DT, KKH.KK_TRAN_ID,
       A.TRANS_DT, A.ACCOUNTING_DT, A.CALENDAR_ID,
       A.PC_BUDGET_ID, B.PC_BUD_TYPE, B.DESCR AS PROJ_DESCR, B.START_DT, B.CALENDAR_ID, B.NUM_PERIODS, A.DESCR AS BUD_ITEM_DESCR, 
       A.PC_INTFC_STATUS, A.PC_LOAD_STATUS, B.PC_BUDGET_STATUS, B.ANALYSIS_TYPE, B.PC_FUND_FINALIZED, B.FINALIZE_SW, B.PROJECT_ID_TO, B.POST_OPTION, 
       B.PC_SEND_TO_KK, B.LAST_DTTIME, B.FMS_DTTM_STAMP, B.FMS_OPRID, B.FMS_LASTUPDDTTM, B.FMS_LASTUPDOPRID, B.BUDGET_ADJUST,
       A.ANALYSIS_TYPE, A.INTFC_ID, A.PROCESS_INSTANCE, A.KK_DISTRIB_STATUS, A.PC_BUDGET_ITEM, KK_BUDG_LN_TYPE, BD_HDR_STATUS, GM_DISTRIB_STATUS, LOAD_STATUS,
       A.JOURNAL_ID, A.ACCOUNT, A.OPERATING_UNIT, A.FUND_CODE, A.DEPTID, A.CHARTFIELD2, A.ACTIVITY_ID, A.MESSAGE_SET_NBR, A.MESSAGE_NBR, C.MESSAGE_TEXT, 
       KKL.KK_TRAN_LN, KKE.EXCPTN_TYPE, X1.XLATLONGNAME
FROM PS_INTFC_PROJ_RES A, PS_PC_BUD_PLAN B, PSMSGCATDEFN C, PS_KK_SOURCE_HDR KKH, PS_KK_SOURCE_LN KKL, PS_KK_EXCPTN_TBL KKE, PSXLATITEM X1
WHERE A.KK_DISTRIB_STATUS IN ('E', 'S', 'B', 'C', 'N', ' ') 
    AND A.BUSINESS_UNIT = B.BUSINESS_UNIT 
    AND A.PROJECT_ID = B.PROJECT_ID 
    AND (A.PC_BUDGET_ID = B.PC_BUDGET_ID OR A.PC_BUDGET_ID = 0)
    AND A.MESSAGE_SET_NBR = C.MESSAGE_SET_NBR (+)
    AND A.MESSAGE_NBR = C.MESSAGE_NBR (+)
    AND A.BUSINESS_UNIT = KKH.BUSINESS_UNIT_PC
    AND A.PROJECT_ID = KKH.PROJECT_ID
    AND A.JOURNAL_ID = KKH.JOURNAL_ID
    AND A.PROCESS_INSTANCE = KKH.PROCESS_INSTANCE 
    --AND KKH.KK_SOURCE_TRAN = 'PC_BUDGET' 
    AND KKH.KK_PROCESS_STATUS NOT IN ('V', 'N')
    AND KKH.KK_TRAN_ID = KKL.KK_TRAN_ID
    AND KKH.KK_TRAN_DT = KKL.KK_TRAN_DT
    AND KKL.KK_TRAN_ID = KKE.KK_TRAN_ID
    AND KKL.KK_TRAN_DT = KKE.KK_TRAN_DT
    AND KKL.KK_TRAN_LN = KKE.KK_TRAN_LN
    AND A.RESOURCE_ID = KKL.RESOURCE_ID
    AND A.BUSINESS_UNIT = 'UNUNI'
    --AND A.PROJECT_ID = '00064324'
    AND X1.FIELDNAME = 'EXCPTN_TYPE'
    AND X1.FIELDVALUE = KKE.EXCPTN_TYPE
ORDER BY A.TRANS_DT DESC;
--GL Journals with Budget Exceptions
--Based on PS_JRNL_LN - GL_JOURNAL
--Modified it based on PS delivered view KK_XCP_GL1_VW2
SELECT A.BUSINESS_UNIT, A.JOURNAL_ID, A.JOURNAL_DATE, A.UNPOST_SEQ, B.JRNL_HDR_STATUS, B.JRNL_EDIT_ERR_STAT, B.JRNL_PROCESS_REQST, 
            BUSINESS_UNIT_IU, B.FISCAL_YEAR, B.ACCOUNTING_PERIOD, B.LEDGER_GROUP, B.LEDGER, A.LEDGER, B.OPRID, B.SOURCE,
            B.BUDGET_HDR_STATUS, A.JOURNAL_LINE, A.BUDGET_LINE_STATUS, E.EXCPTN_TYPE, X1.XLATLONGNAME, E.LEDGER_GROUP, LINE_DESCR, 
            A.BUDGET_DT, A.FOREIGN_AMOUNT, A.FOREIGN_CURRENCY, A.MONETARY_AMOUNT, A.CURRENCY_CD, 
            A.ACCOUNT, A.OPERATING_UNIT, A.DEPTID, A.FUND_CODE, A.CHARTFIELD2, A.BUSINESS_UNIT_PC, A.PROJECT_ID, A.ACTIVITY_ID, 
            A.AFFILIATE, A.AFFILIATE_INTRA2, A.AFFILIATE_INTRA1, A.ANALYSIS_TYPE, A.JRNL_LN_REF,
            C.KK_TRAN_ID, C.KK_TRAN_DT, C.KK_SOURCE_TRAN, C.KK_PROCESS_STATUS, 
            E.ACCOUNT, E.DEPTID, E.OPERATING_UNIT, E.FUND_CODE, E.CHARTFIELD2, E.PROJECT_ID, E.ACTIVITY_ID, E.BUDGET_PERIOD, 
            E.AFFILIATE, E.AFFILIATE_INTRA2, E.AFFILIATE_INTRA1, E.PROCESS_INSTANCE, DESCR254
FROM PS_JRNL_HEADER B, ((((PS_JRNL_LN A LEFT OUTER JOIN PS_KK_SOURCE_HDR C ON A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.JOURNAL_ID = C.JOURNAL_ID 
                        AND A.JOURNAL_DATE = C.JOURNAL_DATE AND A.UNPOST_SEQ = C.UNPOST_SEQ)
                        LEFT OUTER JOIN PS_KK_SOURCE_LN D ON C.KK_TRAN_ID = D.KK_TRAN_ID AND C.KK_TRAN_DT = D.KK_TRAN_DT
                        AND A.JOURNAL_LINE = D.JOURNAL_LINE AND A.LEDGER = D.LEDGER)
                        LEFT OUTER JOIN PS_KK_EXCPTN_TBL E ON D.KK_TRAN_ID = E.KK_TRAN_ID AND D.KK_TRAN_DT = E.KK_TRAN_DT AND D.KK_TRAN_LN = E.KK_TRAN_LN)
                        LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'EXCPTN_TYPE' AND X1.FIELDVALUE = E.EXCPTN_TYPE)
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
     AND A.JOURNAL_ID = B.JOURNAL_ID
     AND A.JOURNAL_DATE = B.JOURNAL_DATE 
     AND A.UNPOST_SEQ = B.UNPOST_SEQ
     AND A.BUSINESS_UNIT = 'UNUNI'
     AND A.BUDGET_LINE_STATUS IN ('E', 'N')
     AND TO_CHAR(C.KK_TRAN_DT, 'YYYY') >= '2014'
     AND B.FISCAL_YEAR >= '2013'
     --AND A.JOURNAL_ID = '0005320912'
ORDER BY A.BUSINESS_UNIT, A.JOURNAL_ID, A.JOURNAL_DATE, A.UNPOST_SEQ, A.JOURNAL_LINE;
--KK Override Details
--Version 2 - Enhancements
--Added Budget Period and included KK_SOURCE_LN
SELECT B.KK_TRAN_ID, TO_CHAR(B.KK_TRAN_DT,'YYYY-MM-DD') As KK_TRAN_DT, B.KK_SOURCE_TRAN, B.KK_PROCESS_STATUS, D.EXCPTN_TYPE, E.XLATLONGNAME,
       B.KK_PROC_INSTANCE, B.BUSINESS_UNIT, TO_CHAR(B.JOURNAL_DATE,'YYYY-MM-DD') AS JRNL_DATE, B.JOURNAL_ID, B.UNPOST_SEQ, LN.JOURNAL_LINE, LN.LEDGER,
       B.CUST_ID, B.ITEM, B.ITEM_LINE, B.DEPOSIT_ID, B.PAYMENT_SEQ_NUM,
       B.PO_ID, B.REQ_ID, B.VOUCHER_ID, LN.VOUCHER_LINE_NUM, LN.LINE_NBR, LN.SCHED_NBR, LN.DISTRIB_LINE_NUM, LN.ACCTG_LINE_NO, B.INVOICE, LN.LINE_SEQ_NUM, B.KEYLIST,
       C.BUDGET_PERIOD, C.LEDGER_GROUP, C.BUSINESS_UNIT, C.ACCOUNT, C.DEPTID, C.OPERATING_UNIT, C.FUND_CODE, C.CHARTFIELD2, C.PROJECT_ID, 
       C.KK_BD_OVER_FLAG, C.KK_TRAN_OVER_FLAG, C.KK_BD_OVER_OPRID, C.KK_TRAN_OVER_OPRID
FROM PS_KK_ACTIVITY_LOG A, PS_KK_SOURCE_HDR B, PS_KK_OVERRIDE_TBL C, PS_KK_EXCPTN_TBL D, PSXLATITEM E, PS_KK_SOURCE_LN LN
WHERE A.KK_TRAN_ID = B.KK_TRAN_ID
    AND A.KK_TRAN_DT = B.KK_TRAN_DT
    AND B.KK_TRAN_ID = C.KK_TRAN_ID
    AND B.KK_TRAN_DT = C.KK_TRAN_DT
    AND B.KK_TRAN_ID = D.KK_TRAN_ID
    AND B.KK_TRAN_DT = D.KK_TRAN_DT
    AND B.KK_TRAN_ID = LN.KK_TRAN_ID
    AND B.KK_TRAN_DT = LN.KK_TRAN_DT
    AND A.KK_TRAN_LN = LN.KK_TRAN_LN
    AND A.KK_TRAN_LN = D.KK_TRAN_LN 
    AND A.BUSINESS_UNIT = C.BUSINESS_UNIT
    AND A.LEDGER_GROUP = D.LEDGER_GROUP
    AND C.LEDGER_GROUP = D.LEDGER_GROUP
    AND A.BALANCING_LINE <> 'Y'
    AND (C.KK_BD_OVER_FLAG = 'Y' OR C.KK_TRAN_OVER_FLAG = 'Y')
    AND (A.BUSINESS_UNIT = 'UNUNI' OR A.BUSINESS_UNIT LIKE '6%')
    --AND A.LEDGER_GROUP = 'ALT_UU'
    AND (C.BUDGET_PERIOD IN ('2014', '2015') OR C.BUDGET_PERIOD = ' ')
	AND TO_CHAR(B.KK_TRAN_DT, 'YYYY') >= '2014'
    AND C.ACCOUNT = A.ACCOUNT
    AND C.DEPTID = A.DEPTID
    AND D.ACCOUNT = A.ACCOUNT
    AND D.DEPTID = A.DEPTID
    --AND B.KK_TRAN_ID = '0060380860'
    AND E.FIELDNAME = 'EXCPTN_TYPE'
    AND E.FIELDVALUE = D.EXCPTN_TYPE
ORDER BY 2 DESC;
--KK Exceptions with more details
SELECT A.KK_TRAN_ID, TO_CHAR(A.KK_TRAN_DT,'YYYY-MM-DD') As KK_TRAN_DT, A.KK_SOURCE_TRAN, A.KK_PROCESS_STATUS, C.EXCPTN_TYPE, D.XLATLONGNAME, 
       A.KK_PROC_INSTANCE, A.BUSINESS_UNIT, A.CUST_ID, A.DEPOSIT_BU, A.DEPOSIT_ID, A.PAYMENT_SEQ_NUM, 
       A.INVOICE, A.ITEM, A.ITEM_LINE, A.ITEM_SEQ_NUM, A.JOURNAL_DATE, A.JOURNAL_ID, B.JOURNAL_LINE, B.LEDGER, B.UNPOST_SEQ,
       A.REQ_ID, G.REQ_STATUS, G.REQUESTOR_ID, G.OPRID_APPROVED_BY, G.IN_PROCESS_FLG, G.BUDGET_HDR_STATUS, G.BUDGET_CHECK,
       A.PO_ID, B.LINE_NBR, B.SCHED_NBR, F.PO_STATUS, F.VENDOR_ID, F.BUYER_ID, F.OPRID_ENTERED_BY, F.OPRID_APPROVED_BY, F.IN_PROCESS_FLG, F.BUDGET_HDR_STATUS,        
       A.RECEIVER_ID, A.RECV_LN_NBR, A.RECV_SHIP_SEQ_NBR, A.DISTRIB_LINE_NUM, A.VOUCHER_ID, B.VOUCHER_LINE_NUM, B.DISTRIB_LINE_NUM,
       A.KEYLIST, B.KK_TRAN_LN, C.LEDGER_GROUP, C.BUSINESS_UNIT, 
       C.ACCOUNT, C.DEPTID, C.OPERATING_UNIT, C.FUND_CODE, C.CHARTFIELD2, C.BUSINESS_UNIT_PC, C.PROJECT_ID, C.ACTIVITY_ID, 
       C.BUDGET_PERIOD, C.MESSAGE_NBR, C.MESSAGE_PARM1, C.MESSAGE_PARM2, C.MESSAGE_PARM3, C.MESSAGE_PARM4, MSG.MESSAGE_TEXT, MSG.DESCRLONG, 
       C.PROCESS_INSTANCE, E.PRCSTYPE, E.PRCSNAME, E.OPRID, E.RUNSTATUS, TO_CHAR(CAST((E.BEGINDTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') AS BEGINDTTM, 
       TO_CHAR(CAST((E.ENDDTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') AS ENDDTTM, E.RUNCNTLID      
FROM PS_KK_SOURCE_HDR A, PS_KK_SOURCE_LN B, PS_KK_EXCPTN_TBL C, PSXLATITEM D, PSPRCSRQST E, PS_PO_HDR F, PS_REQ_HDR G, PSMSGCATDEFN MSG
WHERE A.KK_TRAN_ID = B.KK_TRAN_ID
  AND A.KK_TRAN_DT = B.KK_TRAN_DT
  AND B.KK_TRAN_ID = C.KK_TRAN_ID
  AND B.KK_TRAN_DT = C.KK_TRAN_DT
  AND B.KK_TRAN_LN = C.KK_TRAN_LN
  --AND (A.BUSINESS_UNIT = 'UNUNI' OR A.BUSINESS_UNIT LIKE '6%')
  AND (A.BUSINESS_UNIT = 'UNUNI' OR A.BUSINESS_UNIT LIKE '6%' OR A.BUSINESS_UNIT_PC = 'UNUNI')
  AND A.KK_PROCESS_STATUS NOT IN ('V', 'W')
  AND TO_CHAR(A.KK_TRAN_DT, 'YYYY') >= '2014'
  AND D.FIELDNAME = 'EXCPTN_TYPE'
  AND D.FIELDVALUE = C.EXCPTN_TYPE
  AND 18021 = MSG.MESSAGE_SET_NBR (+)
  AND C.MESSAGE_NBR = MSG.MESSAGE_NBR (+)
  AND C.PROCESS_INSTANCE =  E.PRCSINSTANCE (+)
  AND A.BUSINESS_UNIT =  F.BUSINESS_UNIT (+)
  AND A.PO_ID =  F.PO_ID (+)
  AND A.BUSINESS_UNIT =  G.BUSINESS_UNIT (+)
  AND A.REQ_ID =  G.REQ_ID (+)  
ORDER BY 2 DESC, KK_SOURCE_TRAN, KK_TRAN_LN;
--Query to report all those exceptions in KK which cannot be overridden
SELECT A.KK_TRAN_ID, TO_CHAR(A.KK_TRAN_DT,'YYYY-MM-DD') As KK_TRAN_DT, A.KK_SOURCE_TRAN, A.KK_PROCESS_STATUS, C.EXCPTN_TYPE, D.XLATLONGNAME, 
       A.KK_PROC_INSTANCE, A.BUSINESS_UNIT, A.CUST_ID, A.DEPOSIT_BU, A.DEPOSIT_ID, A.PAYMENT_SEQ_NUM, 
       A.INVOICE, A.ITEM, A.ITEM_LINE, A.ITEM_SEQ_NUM, A.JOURNAL_DATE, A.JOURNAL_ID, B.JOURNAL_LINE, B.LEDGER, B.UNPOST_SEQ,
       A.REQ_ID, G.REQ_STATUS, G.REQUESTOR_ID, G.OPRID_APPROVED_BY, G.IN_PROCESS_FLG, G.BUDGET_HDR_STATUS, G.BUDGET_CHECK,
       A.PO_ID, B.LINE_NBR, B.SCHED_NBR, F.PO_STATUS, F.VENDOR_ID, F.BUYER_ID, F.OPRID_ENTERED_BY, F.OPRID_APPROVED_BY, F.IN_PROCESS_FLG, F.BUDGET_HDR_STATUS,        
       A.RECEIVER_ID, A.RECV_LN_NBR, A.RECV_SHIP_SEQ_NBR, A.DISTRIB_LINE_NUM, A.VOUCHER_ID, B.VOUCHER_LINE_NUM, B.DISTRIB_LINE_NUM,
       A.KEYLIST, B.KK_TRAN_LN, C.LEDGER_GROUP, C.BUSINESS_UNIT, 
       C.ACCOUNT, C.DEPTID, C.OPERATING_UNIT, C.FUND_CODE, C.CHARTFIELD2, C.BUSINESS_UNIT_PC, C.PROJECT_ID, C.ACTIVITY_ID, 
       C.BUDGET_PERIOD, C.MESSAGE_NBR, C.MESSAGE_PARM1, C.MESSAGE_PARM2, C.MESSAGE_PARM3, C.MESSAGE_PARM4, MSG.MESSAGE_TEXT, MSG.DESCRLONG, 
       C.PROCESS_INSTANCE, E.PRCSTYPE, E.PRCSNAME, E.OPRID, E.RUNSTATUS, TO_CHAR(CAST((E.BEGINDTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') AS BEGINDTTM, 
       TO_CHAR(CAST((E.ENDDTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') AS ENDDTTM, E.RUNCNTLID      
FROM PS_KK_SOURCE_HDR A, PS_KK_SOURCE_LN B, PS_KK_EXCPTN_TBL C, PSXLATITEM D, PSPRCSRQST E, PS_PO_HDR F, PS_REQ_HDR G, PSMSGCATDEFN MSG
WHERE A.KK_TRAN_ID = B.KK_TRAN_ID
  AND A.KK_TRAN_DT = B.KK_TRAN_DT
  AND B.KK_TRAN_ID = C.KK_TRAN_ID
  AND B.KK_TRAN_DT = C.KK_TRAN_DT
  AND B.KK_TRAN_LN = C.KK_TRAN_LN
  AND (A.BUSINESS_UNIT = 'UNUNI' OR A.BUSINESS_UNIT LIKE '6%')
  AND A.KK_PROCESS_STATUS NOT IN ('V', 'W')
  AND TO_CHAR(A.KK_TRAN_DT, 'YYYY') >= '2014'
  AND D.FIELDNAME = 'EXCPTN_TYPE'
  AND D.FIELDVALUE = C.EXCPTN_TYPE
  AND 18021 = MSG.MESSAGE_SET_NBR (+)
  AND C.MESSAGE_NBR = MSG.MESSAGE_NBR (+)
  AND C.PROCESS_INSTANCE =  E.PRCSINSTANCE (+)
  AND A.BUSINESS_UNIT =  F.BUSINESS_UNIT (+)
  AND A.PO_ID =  F.PO_ID (+)
  AND A.BUSINESS_UNIT =  G.BUSINESS_UNIT (+)
  AND A.REQ_ID =  G.REQ_ID (+)
  AND C.EXCPTN_TYPE IN ('E2', 'E3', 'E5', 'E8', 'E9', 'E10', 'E12', 'E13', 'E15', 'E18', 'E19', 'E20', 'E22', 'E24', 'E26', 'E28', 'E29', 'E30', 'E31', 'E32', 'E35', 'E36', 'E40', 'E42', 'E43', 'E44', 'E45', 
                        'E46', 'E47', 'E48', 'E49', 'E50', 'E51', 'E52', 'E57', 'E58', 'E59', 'E60', 'E62', 'E63', 'E64', 'E65', 'E66', 'E67', 'E90', 'E91', 'E92', 'E96', 'E97', 'E98', 'E99')
ORDER BY 2 DESC, KK_SOURCE_TRAN, KK_TRAN_LN;
