--SELECT * FROM PS_ACCT_TYPE_TBL WHERE SETID = 'SHARE'

--PPs Latest GL Fund Status - 2012
--Trimmed Version
SELECT X.OPERATING_UNIT, DECODE( X.DEPTID,' ',' ','B0' || SUBSTR(X.DEPTID, 1, 3)) AS BUDG_DEPT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, F.DESCR AS Project_Description, 
            X.CHARTFIELD2 AS Donor, G.DESCR AS Donor_Description, X.ACCOUNT_TYPE, ACCT.DESCR AS Accnt_Type_Descr, X.ACCOUNT, X.DESCR Account_Description, 
            SUM(A_OPN_BAL) "A - Opening Balance", 
            SUM(B_FUND_BAL_ADJ) "B - Fund Balance Adjustment", SUM(C_INC) "C - Income", SUM(D_INC_TRF_ADJ) "D - Income Trnsfrs/Adjustments", SUM(E_EXP) "E - Expenditure"
FROM
(SELECT A.OPERATING_UNIT, DECODE(A.DEPTID,' ',' ','B0' || SUBSTR(A.DEPTID, 1, 3)) AS BUDG_DEPT, A.FUND_CODE, A.DEPTID, B.ACCOUNT_TYPE, A.ACCOUNT, B.DESCR, A.PROJECT_ID, A.CHARTFIELD2
          , CASE WHEN (B.ACCOUNT_TYPE = 'Q' AND A.ACCOUNTING_PERIOD = 0) THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS A_OPN_BAL
          , CASE WHEN (B.ACCOUNT_TYPE = 'Q' AND A.ACCOUNTING_PERIOD > 0) THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS B_FUND_BAL_ADJ
          , CASE WHEN (B.ACCOUNT_TYPE = 'R' AND A.ACCOUNT <> '51035') THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS C_INC
          , CASE WHEN (B.ACCOUNT_TYPE = 'R' AND A.ACCOUNT = '51035') THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS D_INC_TRF_ADJ          
          , CASE WHEN B.ACCOUNT_TYPE = 'E' THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS E_EXP            
FROM PS_LEDGER A, PS_GL_ACCOUNT_TBL B, PS_SET_CNTRL_REC B2
WHERE B.ACCOUNT = A.ACCOUNT
    AND B2.SETCNTRLVALUE = A.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = B.SETID
    AND (A.BUSINESS_UNIT = 'UNUNI'
    AND A.LEDGER = 'USD'
    AND A.BUSINESS_UNIT = 'UNUNI'
    --AND A.OPERATING_UNIT LIKE :2
    --AND A.DEPTID IN ('11001')
    --AND A.FUND_CODE = '11000'
    --AND A.CHARTFIELD2 LIKE :5
    --AND A.PROJECT_ID LIKE :6
    AND A.FISCAL_YEAR = '2012'
    AND A.ACCOUNTING_PERIOD >= 0
    AND A.ACCOUNTING_PERIOD <= 12
    AND B.SETID = 'SHARE'
    AND B.EFFDT = (SELECT MAX(B_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL B_ED WHERE B.SETID = B_ED.SETID AND B.ACCOUNT = B_ED.ACCOUNT AND B_ED.EFFDT <= SYSDATE)
    AND B.ACCOUNT = A.ACCOUNT    
    AND B.ACCOUNT_TYPE IN ('R','E','Q'))
GROUP BY A.OPERATING_UNIT, DECODE( A.DEPTID,' ',' ','B0' || SUBSTR( A.DEPTID, 1, 3)), A.DEPTID, B.ACCOUNT_TYPE, A.ACCOUNT, B.DESCR, A.PROJECT_ID, A.FUND_CODE, A.CHARTFIELD2, B.ACCOUNT_TYPE, 
           A.ACCOUNTING_PERIOD) X, PS_PROJECT_ID_VW F, PS_CHARTFIELD2_TBL G, PS_ACCT_TYPE_TBL ACCT
WHERE ACCT.SETID = 'SHARE'
    AND ACCT.ACCOUNT_TYPE = X.ACCOUNT_TYPE 
    AND 'UNUNI' = F.SETID (+)
    AND X.PROJECT_ID = F.PROJECT_ID (+)    
    AND 'UNUNI' =  G.SETID (+)
    AND X.CHARTFIELD2 =  G.CHARTFIELD2 (+)
    AND (G.EFFDT IS NULL
      OR (G.EFFDT = (SELECT MAX(G_ED.EFFDT) FROM PS_CHARTFIELD2_TBL G_ED WHERE G.SETID = G_ED.SETID AND G.CHARTFIELD2 = G_ED.CHARTFIELD2 AND G_ED.EFFDT <= SYSDATE)))
GROUP BY X.OPERATING_UNIT, DECODE(X.DEPTID,' ',' ','B0' || SUBSTR(X.DEPTID, 1, 3)), X.FUND_CODE, X.DEPTID, X.PROJECT_ID, F.DESCR, X.CHARTFIELD2, G.DESCR, 
               X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR 
ORDER BY X.OPERATING_UNIT, DECODE(X.DEPTID,' ',' ','B0' || SUBSTR(X.DEPTID, 1, 3)), X.FUND_CODE, X.DEPTID, X.PROJECT_ID, F.DESCR, X.CHARTFIELD2, G.DESCR, 
               X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR;


--PPs Latest GL Fund Status
--Expanded Version
SELECT X.OPERATING_UNIT, C.DESCR AS Op_Description, DECODE( X.DEPTID,' ',' ','B0' || SUBSTR(X.DEPTID, 1, 3)) AS BUDG_DEPT, X.FUND_CODE, --D.DESCR AS FundCode_Description, 
            X.DEPTID, --E.DESCR AS Dept_Description, 
            X.PROJECT_ID, F.DESCR AS Project_Description, 
            X.CHARTFIELD2 AS Donor, --G.DESCR AS Donor_Description, 
            X.ACCOUNT, X.DESCR Account_Description, 
            SUM(A_OPN_BAL) "A - Opening Balance", 
            SUM(B_FUND_BAL_ADJ) "B - Fund Balance Adjustment", SUM(C_INC) "C - Income", SUM(D_INC_TRF_ADJ) "D - Income Trnsfrs/Adjustments", SUM(E_EXP) "E - Expenditure"
FROM
(SELECT A.OPERATING_UNIT, DECODE(A.DEPTID,' ',' ','B0' || SUBSTR(A.DEPTID, 1, 3)) AS BUDG_DEPT, A.FUND_CODE, A.DEPTID, A.ACCOUNT, B.DESCR, A.PROJECT_ID, A.CHARTFIELD2
          , CASE WHEN (B.ACCOUNT_TYPE = 'Q' AND A.ACCOUNTING_PERIOD = 0) THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS A_OPN_BAL
          , CASE WHEN (B.ACCOUNT_TYPE = 'Q' AND A.ACCOUNTING_PERIOD > 0) THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS B_FUND_BAL_ADJ
          , CASE WHEN (B.ACCOUNT_TYPE = 'R' AND A.ACCOUNT <> '51035') THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS C_INC
          , CASE WHEN (B.ACCOUNT_TYPE = 'R' AND A.ACCOUNT = '51035') THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS D_INC_TRF_ADJ          
          , CASE WHEN B.ACCOUNT_TYPE = 'E' THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS E_EXP            
FROM PS_LEDGER A, PS_GL_ACCOUNT_TBL B, PS_SET_CNTRL_REC B2
WHERE B.ACCOUNT = A.ACCOUNT
    AND B2.SETCNTRLVALUE = A.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = B.SETID
    AND (A.BUSINESS_UNIT = 'UNUNI'
    AND A.LEDGER = 'USD'
    AND A.BUSINESS_UNIT = 'UNUNI'
    --AND A.OPERATING_UNIT LIKE :2
    --AND A.DEPTID IN ('11001')
    --AND A.FUND_CODE = '11000'
    --AND A.CHARTFIELD2 LIKE :5
    --AND A.PROJECT_ID LIKE :6
    AND A.FISCAL_YEAR = '2012'
    AND A.ACCOUNTING_PERIOD >= 0
    AND A.ACCOUNTING_PERIOD <= 12
    AND B.SETID = 'SHARE'
    AND B.EFFDT = (SELECT MAX(B_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL B_ED WHERE B.SETID = B_ED.SETID AND B.ACCOUNT = B_ED.ACCOUNT AND B_ED.EFFDT <= SYSDATE)
    AND B.ACCOUNT = A.ACCOUNT    
    AND B.ACCOUNT_TYPE IN ('R','E','Q'))
GROUP BY A.OPERATING_UNIT, DECODE( A.DEPTID,' ',' ','B0' || SUBSTR( A.DEPTID, 1, 3)), A.DEPTID, A.ACCOUNT, B.DESCR, A.PROJECT_ID, A.FUND_CODE, A.CHARTFIELD2, B.ACCOUNT_TYPE, 
           A.ACCOUNTING_PERIOD) 
           X, PS_OPER_UNIT_TBL C, --PS_FUND_TBL D, 
           --PS_DEPT_TBL E, 
           PS_PROJECT_ID_VW F--, PS_CHARTFIELD2_TBL G
WHERE C.SETID = 'SHARE'
     AND X.OPERATING_UNIT = C.OPERATING_UNIT
     AND C.EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_OPER_UNIT_TBL C_ED WHERE C.SETID = C_ED.SETID AND C.OPERATING_UNIT = C_ED.OPERATING_UNIT AND C_ED.EFFDT <= SYSDATE)
     --AND D.SETID = 'UNUNI'
     --AND X.FUND_CODE = D.FUND_CODE
     --AND D.EFFDT = (SELECT MAX(D_ED.EFFDT) FROM PS_FUND_TBL D_ED WHERE D.SETID = D_ED.SETID AND D.FUND_CODE = D_ED.FUND_CODE AND D_ED.EFFDT <= SYSDATE)
     --AND 'UNUNI' =  E.SETID (+)
     --AND X.DEPTID =  E.DEPTID (+)
     --AND (E.EFFDT IS NULL
       --OR (E.EFFDT = (SELECT MAX(E_ED.EFFDT) FROM PS_DEPT_TBL E_ED WHERE E.SETID = E_ED.SETID AND E.DEPTID = E_ED.DEPTID AND E_ED.EFFDT <= SYSDATE)))  
    AND 'UNUNI' = F.SETID (+)
    AND X.PROJECT_ID = F.PROJECT_ID (+)
    --AND 'UNUNI' =  G.SETID (+)
    --AND X.CHARTFIELD2 =  G.CHARTFIELD2 (+)
    --AND (G.EFFDT IS NULL
     --OR (G.EFFDT = (SELECT MAX(G_ED.EFFDT) FROM PS_CHARTFIELD2_TBL G_ED WHERE G.SETID = G_ED.SETID AND G.CHARTFIELD2 = G_ED.CHARTFIELD2 AND G_ED.EFFDT <= SYSDATE)))
GROUP BY X.OPERATING_UNIT, C.DESCR, DECODE(X.DEPTID,' ',' ','B0' || SUBSTR(X.DEPTID, 1, 3)), X.FUND_CODE, --D.DESCR, 
               X.DEPTID, --E.DESCR, 
               X.PROJECT_ID, F.DESCR, X.CHARTFIELD2, --G.DESCR, 
               X.ACCOUNT, X.DESCR 
ORDER BY X.OPERATING_UNIT, C.DESCR, DECODE(X.DEPTID,' ',' ','B0' || SUBSTR(X.DEPTID, 1, 3)), X.FUND_CODE, --D.DESCR, 
               X.DEPTID, --E.DESCR, 
               X.PROJECT_ID, F.DESCR, X.CHARTFIELD2, --G.DESCR, 
               X.ACCOUNT, X.DESCR;
               

--Actuals for Expense & Revenue ACCOUNTS ONLY from Ledger for all UNU Departments - 2012
--Included Account Type
SELECT X.FISCAL_YEAR, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X1.ACCOUNT_TYPE, ACCT.DESCR AS ACCT_TYPE_DESCR, X.PROJECT_ID, X.CHARTFIELD2, 
            (SUBSTR(X1.ACCOUNT,1,LENGTH(X1.ACCOUNT)-2) || '00') AS ACCOUNT, X1.DESCR, SUM(X.POSTED_BASE_AMT) AS TOTAL,
            SUM(X.PERIOD_0) PERIOD_0, SUM(X.JAN) JAN, SUM(X.FEB) FEB, SUM(X.MAR) MAR, SUM(X.APR) APR, SUM(X.MAY) MAY, SUM(X.JUN) JUN, 
            SUM(X.JUL) JUL, SUM(X.AUG) AUG, SUM(X.SEP) SEP, SUM(X.OCT) OCT, SUM(X.NOV) NOV, SUM(X.DEC) DEC
FROM (
SELECT ST.FISCAL_YEAR, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ET.ACCOUNT_TYPE, ST.PROJECT_ID, ST.CHARTFIELD2, ST.ACCOUNT, ET.DESCR, 
            SUM(ST.POSTED_BASE_AMT) AS POSTED_BASE_AMT,
   CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_0 
 , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JAN
 , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS FEB 
 , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAR 
 , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS APR 
 , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAY 
 , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUN 
 , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUL 
 , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS AUG 
 , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS SEP 
 , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS OCT 
 , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS NOV 
 , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEC 
FROM PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET
WHERE ET.SETID = 'SHARE'
    AND ET.ACCOUNT = ST.ACCOUNT
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate) 
    AND ST.BUSINESS_UNIT = 'UNUNI'
    AND ST.LEDGER = 'USD'
    AND (ST.ACCOUNTING_PERIOD BETWEEN 1 AND 12)
    AND ST.FISCAL_YEAR = 2012
    --AND ST.STATISTICS_CODE = ' '
    --AND ST.CURRENCY_CD = 'USD'
    AND ET.ACCOUNT_TYPE IN ('E', 'R')     
    --AND ST.DEPTID IN (SELECT D.DEPTID FROM PS_DEPT_TBL D WHERE SETID = 'UNUNI' AND EFF_STATUS = 'A' AND EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_DEPT_TBL C_ED WHERE D.SETID = C_ED.SETID AND D.DEPTID = C_ED.DEPTID AND C_ED.EFFDT <= sysdate))
    --AND ST.DEPTID = '11901'
GROUP BY ST.FISCAL_YEAR, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ET.ACCOUNT_TYPE, ST.ACCOUNT, ST.PROJECT_ID, ST.CHARTFIELD2, ET.DESCR, ST.ACCOUNTING_PERIOD) 
                X, PS_GL_ACCOUNT_TBL X1, PS_ACCT_TYPE_TBL ACCT
WHERE X1.SETID = 'SHARE'
    AND X1.ACCOUNT = (SUBSTR(X.ACCOUNT,1,LENGTH(X.ACCOUNT)-2) || '00')
    AND ACCT.SETID = 'SHARE'
    AND ACCT.ACCOUNT_TYPE = X1.ACCOUNT_TYPE
GROUP BY X.FISCAL_YEAR, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X1.ACCOUNT_TYPE, ACCT.DESCR, X1.ACCOUNT, X.PROJECT_ID, X.CHARTFIELD2, X1.DESCR
ORDER BY X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X1.ACCOUNT;

--Reporting Query
--GL Fund Status
SELECT 'UNU_GL_FUND_STATUS', X.FISCAL_YEAR, X.OPERATING_UNIT, DECODE( X.DEPTID,' ',' ','B0' || SUBSTR(X.DEPTID, 1, 3)) AS BUDG_DEPT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, F.DESCR AS Project_Description, 
            X.CHARTFIELD2 AS Donor, G.DESCR AS Donor_Description, X.ACCOUNT_TYPE, ACCT.DESCR AS Accnt_Type_Descr, X.ACCOUNT, X.DESCR Account_Description, 
            SUM(A_OPN_BAL) "A - Opening Balance", 
            SUM(B_FUND_BAL_ADJ) "B - Fund Balance Adjustment", SUM(C_INC) "C - Income", SUM(D_INC_TRF_ADJ) "D - Income Trnsfrs/Adjustments", SUM(E_EXP) "E - Expenditure"
FROM
(SELECT A.FISCAL_YEAR, A.OPERATING_UNIT, DECODE(A.DEPTID,' ',' ','B0' || SUBSTR(A.DEPTID, 1, 3)) AS BUDG_DEPT, A.FUND_CODE, A.DEPTID, B.ACCOUNT_TYPE, A.ACCOUNT, B.DESCR, A.PROJECT_ID, A.CHARTFIELD2
          , CASE WHEN (B.ACCOUNT_TYPE = 'Q' AND A.ACCOUNTING_PERIOD = 0) THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS A_OPN_BAL
          , CASE WHEN (B.ACCOUNT_TYPE = 'Q' AND A.ACCOUNTING_PERIOD > 0) THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS B_FUND_BAL_ADJ
          , CASE WHEN (B.ACCOUNT_TYPE = 'R' AND A.ACCOUNT <> '51035') THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS C_INC
          , CASE WHEN (B.ACCOUNT_TYPE = 'R' AND A.ACCOUNT = '51035') THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS D_INC_TRF_ADJ          
          , CASE WHEN B.ACCOUNT_TYPE = 'E' THEN SUM(A.POSTED_BASE_AMT) ELSE 0 END AS E_EXP            
FROM PS_LEDGER A, PS_GL_ACCOUNT_TBL B, PS_SET_CNTRL_REC B2
WHERE B.ACCOUNT = A.ACCOUNT
    AND B2.SETCNTRLVALUE = A.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = B.SETID
    AND (A.BUSINESS_UNIT = 'UNUNI'
    AND A.LEDGER = 'USD'
    AND A.BUSINESS_UNIT = 'UNUNI'
    --AND A.OPERATING_UNIT LIKE :2
    --AND A.DEPTID IN ('11001')
    --AND A.FUND_CODE = '11000'
    --AND A.CHARTFIELD2 LIKE :5
    --AND A.PROJECT_ID LIKE :6
    AND A.FISCAL_YEAR = '2013'
    AND A.ACCOUNTING_PERIOD >= 0
    AND A.ACCOUNTING_PERIOD <= 12
    AND B.SETID = 'SHARE'
    AND B.EFFDT = (SELECT MAX(B_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL B_ED WHERE B.SETID = B_ED.SETID AND B.ACCOUNT = B_ED.ACCOUNT AND B_ED.EFFDT <= SYSDATE)
    AND B.ACCOUNT = A.ACCOUNT    
    AND B.ACCOUNT_TYPE IN ('R','E','Q'))
GROUP BY A.FISCAL_YEAR, A.OPERATING_UNIT, DECODE( A.DEPTID,' ',' ','B0' || SUBSTR( A.DEPTID, 1, 3)), A.DEPTID, B.ACCOUNT_TYPE, A.ACCOUNT, B.DESCR, A.PROJECT_ID, A.FUND_CODE, A.CHARTFIELD2, B.ACCOUNT_TYPE, 
           A.ACCOUNTING_PERIOD) X, PS_PROJECT_ID_VW F, PS_CHARTFIELD2_TBL G, PS_ACCT_TYPE_TBL ACCT
WHERE ACCT.SETID = 'SHARE'
    AND ACCT.ACCOUNT_TYPE = X.ACCOUNT_TYPE 
    AND 'UNUNI' = F.SETID (+)
    AND X.PROJECT_ID = F.PROJECT_ID (+)    
    AND 'UNUNI' =  G.SETID (+)
    AND X.CHARTFIELD2 =  G.CHARTFIELD2 (+)
    AND (G.EFFDT IS NULL
      OR (G.EFFDT = (SELECT MAX(G_ED.EFFDT) FROM PS_CHARTFIELD2_TBL G_ED WHERE G.SETID = G_ED.SETID AND G.CHARTFIELD2 = G_ED.CHARTFIELD2 AND G_ED.EFFDT <= SYSDATE)))
GROUP BY X.FISCAL_YEAR, X.OPERATING_UNIT, DECODE(X.DEPTID,' ',' ','B0' || SUBSTR(X.DEPTID, 1, 3)), X.FUND_CODE, X.DEPTID, X.PROJECT_ID, F.DESCR, X.CHARTFIELD2, G.DESCR, 
               X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR 
ORDER BY X.FISCAL_YEAR, X.OPERATING_UNIT, DECODE(X.DEPTID,' ',' ','B0' || SUBSTR(X.DEPTID, 1, 3)), X.FUND_CODE, X.DEPTID, X.PROJECT_ID, F.DESCR, X.CHARTFIELD2, G.DESCR, 
               X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR;
               
--New Trial Balance for UN Sec
SELECT X.FISCAL_YEAR, X.ACCOUNT_TYPE, ACCT.DESCR AS ACCT_TYPE_DESCR, X.ACCOUNT, X.DESCR AS ACCT_DESCR,
            SUM(X.PERIOD_0) AS "Opening Balance", SUM(X.DEBIT) AS "Debits", SUM(X.CREDIT) AS "Credits",
            SUM(X.PERIOD_YTD) AS "Movement", SUM(X.POSTED_BASE_AMT) AS "Closing Balance"           
FROM (SELECT ST.FISCAL_YEAR, ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, SUM(ST.POSTED_BASE_AMT) AS POSTED_BASE_AMT,
     CASE WHEN ST.ACCOUNTING_PERIOD = 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_0
   , CASE WHEN ST.ACCOUNTING_PERIOD > 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_YTD
   , CASE WHEN (SUM(ST.POSTED_BASE_AMT) > 0.00 AND ST.ACCOUNTING_PERIOD > 0) THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEBIT
   , CASE WHEN (SUM(ST.POSTED_BASE_AMT) < 0.00 AND ST.ACCOUNTING_PERIOD > 0) THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS CREDIT
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ET.ACCOUNT = ST.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)
    AND ST.BUSINESS_UNIT = 'UNUNI'
    AND ST.LEDGER = 'USD'
    AND ST.FISCAL_YEAR = 2012
    AND ((ST.ACCOUNTING_PERIOD BETWEEN 1 and 12 AND ET.ACCOUNT_TYPE IN ('E', 'R')) OR (ST.ACCOUNTING_PERIOD BETWEEN 0 and 12 AND ET.ACCOUNT_TYPE NOT IN ('E', 'R')))        
    AND ST.STATISTICS_CODE = ' '
    --AND (ST.ACCOUNTING_PERIOD BETWEEN 0 AND 12)
    --AND ET.ACCOUNT_TYPE NOT IN ('E', 'R')    
GROUP BY ST.FISCAL_YEAR, ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.BASE_CURRENCY, ST.ACCOUNTING_PERIOD) X, PS_ACCT_TYPE_TBL ACCT
WHERE ACCT.SETID = 'SHARE'
    AND ACCT.ACCOUNT_TYPE = X.ACCOUNT_TYPE
GROUP BY X.FISCAL_YEAR, X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR
ORDER BY X.ACCOUNT, X.DESCR;

--GLVsKK - 2012
SELECT T.BUSINESS_UNIT, T.OPERATING_UNIT, T.DEPTID, T.PROJECT_ID, T.CHARTFIELD2, T.FUND_CODE, T.ACCOUNT, T.DESCR,
            SUM(T.EXP_AMT_GL) AS EXP_AMT_GL, SUM(T.EXP_AMT_KK) AS EXP_AMT_KK, (SUM(T.EXP_AMT_GL) - SUM(T.EXP_AMT_KK)) AS VARIANCE, 
            SUM(T.JAN_GL) AS JAN_GL, SUM(T.JAN_KK) AS JAN_KK, SUM(T.FEB_GL) AS FEB_GL, SUM(T.FEB_KK) AS FEB_KK, SUM(T.MAR_GL) AS MAR_GL, SUM(T.MAR_KK) AS MAR_KK, 
            SUM(T.APR_GL) AS APR_GL, SUM(T.APR_KK) AS APR_KK, SUM(T.MAY_GL) AS MAY_GL, SUM(T.MAY_KK) AS MAY_KK, 
            SUM(T.JUN_GL) AS JUN_GL, SUM(T.JUN_KK) AS JUN_KK, SUM(T.JUL_GL) AS JUL_GL, SUM(T.JUL_KK) AS JUL_KK, SUM(T.AUG_GL) AS AUG_GL, SUM(T.AUG_KK) AS AUG_KK, 
            SUM(T.SEP_GL) AS SEP_GL, SUM(T.SEP_KK) AS SEP_KK, SUM(T.OCT_GL) AS OCT_GL, SUM(T.OCT_KK) AS OCT_KK, 
            SUM(T.NOV_GL) AS NOV_GL, SUM(T.NOV_KK) AS NOV_KK, SUM(T.DEC_GL) AS DEC_GL, SUM(T.DEC_KK) AS DEC_KK
FROM
(SELECT X.BUSINESS_UNIT, X.OPERATING_UNIT, X.DEPTID, C.DESCR AS DEPT_DESCR, X.PROJECT_ID, B.DESCR AS PRJ_DESCR, X.CHARTFIELD2, X.FUND_CODE,
            (SUBSTR(X1.ACCOUNT,1,LENGTH(X1.ACCOUNT)-2) || '00') AS ACCOUNT, X1.DESCR,
            SUM(X.EXP_AMT) AS EXP_AMT_GL, 0.0 AS EXP_AMT_KK,
            SUM(X.JAN) JAN_GL, 0.0 AS JAN_KK, SUM(X.FEB) FEB_GL, 0.0 AS FEB_KK, SUM(X.MAR) MAR_GL, 0.0 AS MAR_KK, SUM(X.APR) APR_GL, 0.0 AS APR_KK, SUM(X.MAY) MAY_GL, 0.0 AS MAY_KK, 
            SUM(X.JUN) JUN_GL, 0.0 AS JUN_KK, SUM(X.JUL) JUL_GL, 0.0 AS JUL_KK, SUM(X.AUG) AUG_GL, 0.0 AS AUG_KK, SUM(X.SEP) SEP_GL, 0.0 AS SEP_KK, SUM(X.OCT) OCT_GL, 0.0 AS OCT_KK, 
            SUM(X.NOV) NOV_GL, 0.0 AS NOV_KK, SUM(X.DEC) DEC_GL, 0.0 AS DEC_KK
FROM (
SELECT ST.BUSINESS_UNIT, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.ACCOUNT, ST.PROJECT_ID, ST.CHARTFIELD2, ET.DESCR, SUM(ST.POSTED_BASE_AMT) AS EXP_AMT   
 , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JAN
 , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS FEB 
 , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAR 
 , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS APR 
 , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAY 
 , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUN 
 , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUL 
 , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS AUG 
 , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS SEP 
 , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS OCT 
 , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS NOV 
 , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEC 
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ST.BUSINESS_UNIT = 'UNUNI'
    --AND ET.SETID = 'SHARE'
    AND ST.ACCOUNT = ET.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)      
    AND ST.LEDGER = 'USD'
    AND (ST.ACCOUNTING_PERIOD BETWEEN 1 AND 12) 
    AND ST.FISCAL_YEAR IN ('2012')
    --AND ST.STATISTICS_CODE = ' ' 
    --AND ST.CURRENCY_CD = 'USD'
    AND ET.ACCOUNT_TYPE IN ('E', 'R')
    --AND ST.PROJECT_ID = '00079888'
    AND ST.PROJECT_ID = '00073654'    
GROUP BY ST.BUSINESS_UNIT, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.ACCOUNT, ST.PROJECT_ID, ST.CHARTFIELD2, ET.DESCR, ST.ACCOUNTING_PERIOD) X, 
               PS_GL_ACCOUNT_TBL X1, PS_PROJECT B, PS_DEPTID_BUGL_VW C, PS_SET_CNTRL_REC B3
WHERE X.BUSINESS_UNIT = B.BUSINESS_UNIT
    AND X.PROJECT_ID = B.PROJECT_ID
    AND B3.SETCNTRLVALUE = X.BUSINESS_UNIT
    AND B3.RECNAME = 'GL_ACCOUNT_TBL'
    AND B3.SETID = X1.SETID
    AND X1.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = X1.SETID AND CJ.ACCOUNT = X1.ACCOUNT AND CJ.EFFDT <= sysdate)
    AND X1.ACCOUNT = (SUBSTR(X.ACCOUNT,1,LENGTH(X.ACCOUNT)-2) || '00')    
    AND C.SETID=(SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'DEPT_TBL')
    AND X.DEPTID = C.DEPTID
    AND C.EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_DEPTID_BUGL_VW C_ED WHERE C.SETID = C_ED.SETID AND C.DEPTID = C_ED.DEPTID AND C_ED.EFFDT <= SYSDATE)
    AND X1.ACCOUNT = (SUBSTR(X.ACCOUNT,1,LENGTH(X.ACCOUNT)-2) || '00')
    AND X1.ACCOUNT_TYPE IN ('E', 'R')
GROUP BY X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, C.DESCR, X1.ACCOUNT, X1.DESCR, X.PROJECT_ID, B.DESCR, X.CHARTFIELD2
--ORDER BY X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X1.ACCOUNT, X.PROJECT_ID, X.CHARTFIELD2
UNION
SELECT X.BUSINESS_UNIT, X.OPERATING_UNIT, X.DEPTID, C.DESCR AS DEPT_DESCR, X.PROJECT_ID, B.DESCR AS PRJ_DESCR, X.CHARTFIELD2, X.FUND_CODE,
            (SUBSTR(X1.ACCOUNT,1,LENGTH(X1.ACCOUNT)-2) || '00') AS ACCOUNT, X1.DESCR, 
            0.0 AS EXP_AMT_GL, SUM(X.EXP_AMT) AS EXP_AMT_KK, 
            0.0 AS JAN_GL, SUM(X.JAN) JAN_KK, 0.0 AS FEB_GL, SUM(X.FEB) FEB_KK, 0.0 AS MAR_GL, SUM(X.MAR) MAR_KK, 0.0 AS APR_GL, SUM(X.APR) APR_KK, 0.0 AS MAY_GL, SUM(X.MAY) MAY_KK, 
            0.0 AS JUN_GL, SUM(X.JUN) JUN_KK, 0.0 AS JUL_GL, SUM(X.JUL) JUL_KK, 0.0 AS AUG_GL, SUM(X.AUG) AUG_KK, 0.0 AS SEP_GL, SUM(X.SEP) SEP_KK, 0.0 AS OCT_GL, SUM(X.OCT) OCT_KK, 
            0.0 AS NOV_GL, SUM(X.NOV) NOV_KK, 0.0 AS DEC_GL, SUM(X.DEC) DEC_KK
FROM
(SELECT A.BUSINESS_UNIT, A.OPERATING_UNIT, A.DEPTID, A.PROJECT_ID, A.CHARTFIELD2, A.FUND_CODE, A.ACCOUNT, D.DESCR, A.ACCOUNTING_PERIOD, 
            DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) AS EXP_AMT,
            CASE A.ACCOUNTING_PERIOD WHEN 1 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS JAN
          , CASE A.ACCOUNTING_PERIOD WHEN 2 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS FEB 
          , CASE A.ACCOUNTING_PERIOD WHEN 3 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS MAR 
          , CASE A.ACCOUNTING_PERIOD WHEN 4 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS APR 
          , CASE A.ACCOUNTING_PERIOD WHEN 5 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS MAY 
          , CASE A.ACCOUNTING_PERIOD WHEN 6 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS JUN 
          , CASE A.ACCOUNTING_PERIOD WHEN 7 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS JUL 
          , CASE A.ACCOUNTING_PERIOD WHEN 8 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS AUG 
          , CASE A.ACCOUNTING_PERIOD WHEN 9 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS SEP 
          , CASE A.ACCOUNTING_PERIOD WHEN 10 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS OCT 
          , CASE A.ACCOUNTING_PERIOD WHEN 11 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS NOV 
          , CASE A.ACCOUNTING_PERIOD WHEN 12 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS DEC            
FROM PS_LEDGER_KK A, PS_GL_ACCOUNT_TBL D, PS_SET_CNTRL_REC B4
WHERE A.BUSINESS_UNIT = 'UNUNI'
     AND B4.SETCNTRLVALUE = A.BUSINESS_UNIT
     AND B4.RECNAME = 'GL_ACCOUNT_TBL'
     AND B4.SETID = D.SETID
     AND A.ACCOUNT = D.ACCOUNT
     AND D.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = D.SETID AND CJ.ACCOUNT = D.ACCOUNT AND CJ.EFFDT <= sysdate)
     AND A.BUDGET_PERIOD IN ('2012')
     AND (A.ACCOUNTING_PERIOD BETWEEN 1 AND 12)
     AND A.LEDGER LIKE 'DET_UU%'
     AND A.PROJECT_ID = '00073654'     
     --AND A.POSTED_BASE_AMT <> 0
     AND D.ACCOUNT_TYPE IN ('E', 'R')     
GROUP BY A.BUSINESS_UNIT, A.OPERATING_UNIT, A.DEPTID, A.PROJECT_ID, A.CHARTFIELD2, A.FUND_CODE, A.ACCOUNT, D.DESCR, 
                A.ACCOUNTING_PERIOD, LEDGER) X, PS_GL_ACCOUNT_TBL X1, PS_PROJECT B, PS_DEPTID_BUGL_VW C, PS_SET_CNTRL_REC B5
WHERE X.BUSINESS_UNIT = B.BUSINESS_UNIT
     AND X.PROJECT_ID = B.PROJECT_ID
     AND B5.SETCNTRLVALUE = X.BUSINESS_UNIT
     AND B5.RECNAME = 'GL_ACCOUNT_TBL'
     AND B5.SETID = X1.SETID
     AND X1.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = X1.SETID AND CJ.ACCOUNT = X1.ACCOUNT AND CJ.EFFDT <= sysdate)
     AND X1.ACCOUNT = (SUBSTR(X.ACCOUNT,1,LENGTH(X.ACCOUNT)-2) || '00')
     AND X1.ACCOUNT_TYPE IN ('E', 'R')
     AND C.SETID=(SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'DEPT_TBL')
     AND X.DEPTID = C.DEPTID
     AND C.EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_DEPTID_BUGL_VW C_ED WHERE C.SETID = C_ED.SETID AND C.DEPTID = C_ED.DEPTID AND C_ED.EFFDT <= SYSDATE)    
GROUP BY X.BUSINESS_UNIT, X.OPERATING_UNIT, X.DEPTID, C.DESCR, X.PROJECT_ID, B.DESCR, X.CHARTFIELD2, X.FUND_CODE, X1.ACCOUNT, X1.DESCR) T
GROUP BY T.BUSINESS_UNIT, T.OPERATING_UNIT, T.DEPTID, T.PROJECT_ID, T.CHARTFIELD2, T.FUND_CODE, T.ACCOUNT, T.DESCR
ORDER BY 2,3,4,6,7;

--With the Account Rollup
--Trying to match with Budgets Overview page output
SELECT T.BUSINESS_UNIT, T.OPERATING_UNIT, T.FUND_CODE, T.DEPTID, T.PROJECT_ID, T.PRJ_DESCR, T.CHARTFIELD2, T.ACCT_ROLLUP, T.ACCOUNT, T.ACCT_DESCR,
            SUM(T.EXP_AMT_GL) AS EXP_AMT_GL, SUM(T.EXP_AMT_KK) AS EXP_AMT_KK, (SUM(T.EXP_AMT_GL) - SUM(T.EXP_AMT_KK)) AS VARIANCE, 
            SUM(T.JAN_GL) AS JAN_GL, SUM(T.JAN_KK) AS JAN_KK, SUM(T.FEB_GL) AS FEB_GL, SUM(T.FEB_KK) AS FEB_KK, SUM(T.MAR_GL) AS MAR_GL, SUM(T.MAR_KK) AS MAR_KK, 
            SUM(T.APR_GL) AS APR_GL, SUM(T.APR_KK) AS APR_KK, SUM(T.MAY_GL) AS MAY_GL, SUM(T.MAY_KK) AS MAY_KK, 
            SUM(T.JUN_GL) AS JUN_GL, SUM(T.JUN_KK) AS JUN_KK, SUM(T.JUL_GL) AS JUL_GL, SUM(T.JUL_KK) AS JUL_KK, SUM(T.AUG_GL) AS AUG_GL, SUM(T.AUG_KK) AS AUG_KK, 
            SUM(T.SEP_GL) AS SEP_GL, SUM(T.SEP_KK) AS SEP_KK, SUM(T.OCT_GL) AS OCT_GL, SUM(T.OCT_KK) AS OCT_KK, 
            SUM(T.NOV_GL) AS NOV_GL, SUM(T.NOV_KK) AS NOV_KK, SUM(T.DEC_GL) AS DEC_GL, SUM(T.DEC_KK) AS DEC_KK
FROM
(SELECT X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, C.DESCR AS DEPT_DESCR, X.PROJECT_ID, B.DESCR AS PRJ_DESCR, X.CHARTFIELD2,
             (SUBSTR(X.ACCOUNT,1,LENGTH(X.ACCOUNT)-2) || '00') AS ACCT_ROLLUP, X.ACCOUNT, X.DESCR AS ACCT_DESCR,
            SUM(X.EXP_AMT) AS EXP_AMT_GL, 0.0 AS EXP_AMT_KK,
            SUM(X.JAN) JAN_GL, 0.0 AS JAN_KK, SUM(X.FEB) FEB_GL, 0.0 AS FEB_KK, SUM(X.MAR) MAR_GL, 0.0 AS MAR_KK, SUM(X.APR) APR_GL, 0.0 AS APR_KK, SUM(X.MAY) MAY_GL, 0.0 AS MAY_KK, 
            SUM(X.JUN) JUN_GL, 0.0 AS JUN_KK, SUM(X.JUL) JUL_GL, 0.0 AS JUL_KK, SUM(X.AUG) AUG_GL, 0.0 AS AUG_KK, SUM(X.SEP) SEP_GL, 0.0 AS SEP_KK, SUM(X.OCT) OCT_GL, 0.0 AS OCT_KK, 
            SUM(X.NOV) NOV_GL, 0.0 AS NOV_KK, SUM(X.DEC) DEC_GL, 0.0 AS DEC_KK
FROM (
SELECT ST.BUSINESS_UNIT, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.ACCOUNT, ET.DESCR, ST.PROJECT_ID, ST.CHARTFIELD2, SUM(ST.POSTED_BASE_AMT) AS EXP_AMT   
 , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JAN
 , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS FEB 
 , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAR 
 , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS APR 
 , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAY 
 , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUN 
 , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUL 
 , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS AUG 
 , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS SEP 
 , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS OCT 
 , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS NOV 
 , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEC 
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ST.BUSINESS_UNIT = 'UNUNI'
    --AND ET.SETID = 'SHARE'
    AND ST.ACCOUNT = ET.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)      
    AND ST.LEDGER = 'USD'
    AND (ST.ACCOUNTING_PERIOD BETWEEN 1 AND 12) 
    AND ST.FISCAL_YEAR IN ('2012')
    --AND ST.STATISTICS_CODE = ' ' 
    --AND ST.CURRENCY_CD = 'USD'
    AND ET.ACCOUNT_TYPE IN ('E', 'R')
    --AND ST.PROJECT_ID = '00079888'
    AND ST.PROJECT_ID = '00064159'
    --AND ST.DEPTID = '11901'
GROUP BY ST.BUSINESS_UNIT, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.ACCOUNT, ET.DESCR, ST.PROJECT_ID, ST.CHARTFIELD2, ST.ACCOUNTING_PERIOD) X, 
               PS_PROJECT B, PS_DEPTID_BUGL_VW C
WHERE X.BUSINESS_UNIT = B.BUSINESS_UNIT (+)
    AND X.PROJECT_ID = B.PROJECT_ID (+)
    AND C.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'DEPT_TBL')
    AND X.DEPTID = C.DEPTID
    AND C.EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_DEPTID_BUGL_VW C_ED WHERE C.SETID = C_ED.SETID AND C.DEPTID = C_ED.DEPTID AND C_ED.EFFDT <= SYSDATE)    
GROUP BY X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, C.DESCR, X.ACCOUNT, X.DESCR, X.PROJECT_ID, B.DESCR, X.CHARTFIELD2
--ORDER BY X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X1.ACCOUNT, X.PROJECT_ID, X.CHARTFIELD2
UNION ALL
SELECT X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, C.DESCR AS DEPT_DESCR, X.PROJECT_ID, B.DESCR AS PRJ_DESCR, X.CHARTFIELD2, 
            (SUBSTR(X.ACCOUNT,1,LENGTH(X.ACCOUNT)-2) || '00') AS ACCT_ROLLUP, X.ACCOUNT, X.DESCR AS ACCT_DESCR,
            0.0 AS EXP_AMT_GL, SUM(X.EXP_AMT) AS EXP_AMT_KK, 
            0.0 AS JAN_GL, SUM(X.JAN) JAN_KK, 0.0 AS FEB_GL, SUM(X.FEB) FEB_KK, 0.0 AS MAR_GL, SUM(X.MAR) MAR_KK, 0.0 AS APR_GL, SUM(X.APR) APR_KK, 0.0 AS MAY_GL, SUM(X.MAY) MAY_KK, 
            0.0 AS JUN_GL, SUM(X.JUN) JUN_KK, 0.0 AS JUL_GL, SUM(X.JUL) JUL_KK, 0.0 AS AUG_GL, SUM(X.AUG) AUG_KK, 0.0 AS SEP_GL, SUM(X.SEP) SEP_KK, 0.0 AS OCT_GL, SUM(X.OCT) OCT_KK, 
            0.0 AS NOV_GL, SUM(X.NOV) NOV_KK, 0.0 AS DEC_GL, SUM(X.DEC) DEC_KK
FROM
(SELECT A.BUSINESS_UNIT, A.OPERATING_UNIT, A.FUND_CODE, A.DEPTID, A.ACCOUNT, D.DESCR, A.PROJECT_ID, A.CHARTFIELD2, 
             DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) AS EXP_AMT,
            CASE A.ACCOUNTING_PERIOD WHEN 1 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS JAN
          , CASE A.ACCOUNTING_PERIOD WHEN 2 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS FEB 
          , CASE A.ACCOUNTING_PERIOD WHEN 3 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS MAR 
          , CASE A.ACCOUNTING_PERIOD WHEN 4 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS APR 
          , CASE A.ACCOUNTING_PERIOD WHEN 5 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS MAY 
          , CASE A.ACCOUNTING_PERIOD WHEN 6 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS JUN 
          , CASE A.ACCOUNTING_PERIOD WHEN 7 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS JUL 
          , CASE A.ACCOUNTING_PERIOD WHEN 8 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS AUG 
          , CASE A.ACCOUNTING_PERIOD WHEN 9 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS SEP 
          , CASE A.ACCOUNTING_PERIOD WHEN 10 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS OCT 
          , CASE A.ACCOUNTING_PERIOD WHEN 11 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS NOV 
          , CASE A.ACCOUNTING_PERIOD WHEN 12 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS DEC            
FROM PS_LEDGER_KK A, PS_GL_ACCOUNT_TBL D, PS_SET_CNTRL_REC B4
WHERE A.BUSINESS_UNIT = 'UNUNI'
     AND B4.SETCNTRLVALUE = A.BUSINESS_UNIT
     AND B4.RECNAME = 'GL_ACCOUNT_TBL'
     AND B4.SETID = D.SETID
     AND A.ACCOUNT = D.ACCOUNT
     AND D.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = D.SETID AND CJ.ACCOUNT = D.ACCOUNT AND CJ.EFFDT <= sysdate)
     AND (A.FISCAL_YEAR IN ('2012') AND (A.ACCOUNTING_PERIOD BETWEEN 1 AND 12) OR BUDGET_PERIOD IN ('2012'))
     AND A.LEDGER LIKE 'DET_UU%'
     AND A.PROJECT_ID = '00064159'
     --AND A.DEPTID = '11901'
     --AND A.POSTED_BASE_AMT <> 0
     AND D.ACCOUNT_TYPE IN ('E', 'R')     
GROUP BY A.BUSINESS_UNIT, A.OPERATING_UNIT, A.FUND_CODE, A.DEPTID, A.ACCOUNT, D.DESCR, A.PROJECT_ID, A.CHARTFIELD2, A.ACCOUNTING_PERIOD, LEDGER) X, 
               PS_PROJECT B, PS_DEPTID_BUGL_VW C
WHERE X.BUSINESS_UNIT = B.BUSINESS_UNIT (+)
     AND X.PROJECT_ID = B.PROJECT_ID (+)     
     AND C.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'DEPT_TBL')
     AND X.DEPTID = C.DEPTID
     AND C.EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_DEPTID_BUGL_VW C_ED WHERE C.SETID = C_ED.SETID AND C.DEPTID = C_ED.DEPTID AND C_ED.EFFDT <= SYSDATE)    
GROUP BY X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, C.DESCR, X.PROJECT_ID, B.DESCR, X.CHARTFIELD2, X.ACCOUNT, X.DESCR) T
GROUP BY T.BUSINESS_UNIT, T.OPERATING_UNIT, T.FUND_CODE, T.DEPTID, T.PROJECT_ID, T.PRJ_DESCR, T.CHARTFIELD2, T.ACCT_ROLLUP, T.ACCOUNT, T.ACCT_DESCR
ORDER BY 2,3,4,5,6,7,8;

--Testing GLvsKK
--Matches Budgets Overview Page
SELECT T.BUSINESS_UNIT, T.OPERATING_UNIT, T.FUND_CODE, T.DEPTID, T.PROJECT_ID, T.PRJ_DESCR, T.CHARTFIELD2, T.ACCT_ROLLUP, T.ACCOUNT, T.ACCT_DESCR,
            SUM(T.EXP_AMT_GL) AS EXP_AMT_GL, SUM(T.EXP_AMT_KK) AS EXP_AMT_KK, (SUM(T.EXP_AMT_GL) - SUM(T.EXP_AMT_KK)) AS VARIANCE, 
            SUM(T.JAN_GL) AS JAN_GL, SUM(T.JAN_KK) AS JAN_KK, SUM(T.FEB_GL) AS FEB_GL, SUM(T.FEB_KK) AS FEB_KK, SUM(T.MAR_GL) AS MAR_GL, SUM(T.MAR_KK) AS MAR_KK, 
            SUM(T.APR_GL) AS APR_GL, SUM(T.APR_KK) AS APR_KK, SUM(T.MAY_GL) AS MAY_GL, SUM(T.MAY_KK) AS MAY_KK, 
            SUM(T.JUN_GL) AS JUN_GL, SUM(T.JUN_KK) AS JUN_KK, SUM(T.JUL_GL) AS JUL_GL, SUM(T.JUL_KK) AS JUL_KK, SUM(T.AUG_GL) AS AUG_GL, SUM(T.AUG_KK) AS AUG_KK, 
            SUM(T.SEP_GL) AS SEP_GL, SUM(T.SEP_KK) AS SEP_KK, SUM(T.OCT_GL) AS OCT_GL, SUM(T.OCT_KK) AS OCT_KK, 
            SUM(T.NOV_GL) AS NOV_GL, SUM(T.NOV_KK) AS NOV_KK, SUM(T.DEC_GL) AS DEC_GL, SUM(T.DEC_KK) AS DEC_KK
FROM
(SELECT X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, C.DESCR AS DEPT_DESCR, X.PROJECT_ID, B.DESCR AS PRJ_DESCR, X.CHARTFIELD2,
             (SUBSTR(X.ACCOUNT,1,LENGTH(X.ACCOUNT)-2) || '00') AS ACCT_ROLLUP, X.ACCOUNT, X.DESCR AS ACCT_DESCR,
            SUM(X.EXP_AMT) AS EXP_AMT_GL, 0.0 AS EXP_AMT_KK,
            SUM(X.JAN) JAN_GL, 0.0 AS JAN_KK, SUM(X.FEB) FEB_GL, 0.0 AS FEB_KK, SUM(X.MAR) MAR_GL, 0.0 AS MAR_KK, SUM(X.APR) APR_GL, 0.0 AS APR_KK, SUM(X.MAY) MAY_GL, 0.0 AS MAY_KK, 
            SUM(X.JUN) JUN_GL, 0.0 AS JUN_KK, SUM(X.JUL) JUL_GL, 0.0 AS JUL_KK, SUM(X.AUG) AUG_GL, 0.0 AS AUG_KK, SUM(X.SEP) SEP_GL, 0.0 AS SEP_KK, SUM(X.OCT) OCT_GL, 0.0 AS OCT_KK, 
            SUM(X.NOV) NOV_GL, 0.0 AS NOV_KK, SUM(X.DEC) DEC_GL, 0.0 AS DEC_KK
FROM (
SELECT ST.BUSINESS_UNIT, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.ACCOUNT, ET.DESCR, ST.PROJECT_ID, ST.CHARTFIELD2, SUM(ST.POSTED_BASE_AMT) AS EXP_AMT   
 , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JAN
 , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS FEB 
 , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAR 
 , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS APR 
 , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAY 
 , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUN 
 , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUL 
 , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS AUG 
 , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS SEP 
 , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS OCT 
 , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS NOV 
 , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEC 
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ST.BUSINESS_UNIT = 'UNUNI'
    --AND ET.SETID = 'SHARE'
    AND ST.ACCOUNT = ET.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)      
    AND ST.LEDGER = 'USD'
    AND (ST.ACCOUNTING_PERIOD BETWEEN 1 AND 12) 
    AND ST.FISCAL_YEAR IN ('2012')
    --AND ST.STATISTICS_CODE = ' ' 
    --AND ST.CURRENCY_CD = 'USD'
    AND ET.ACCOUNT_TYPE IN ('E', 'R')
    --AND ST.PROJECT_ID = '00079888'
    AND ST.PROJECT_ID = '00064158'
    --AND ST.DEPTID = '11901'
GROUP BY ST.BUSINESS_UNIT, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.ACCOUNT, ET.DESCR, ST.PROJECT_ID, ST.CHARTFIELD2, ST.ACCOUNTING_PERIOD) X, 
               PS_PROJECT B, PS_DEPTID_BUGL_VW C
WHERE X.BUSINESS_UNIT = B.BUSINESS_UNIT (+)
    AND X.PROJECT_ID = B.PROJECT_ID (+)
    AND C.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'DEPT_TBL')
    AND X.DEPTID = C.DEPTID
    AND C.EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_DEPTID_BUGL_VW C_ED WHERE C.SETID = C_ED.SETID AND C.DEPTID = C_ED.DEPTID AND C_ED.EFFDT <= SYSDATE)    
GROUP BY X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, C.DESCR, X.ACCOUNT, X.DESCR, X.PROJECT_ID, B.DESCR, X.CHARTFIELD2
--ORDER BY X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X1.ACCOUNT, X.PROJECT_ID, X.CHARTFIELD2
UNION ALL
SELECT X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, C.DESCR AS DEPT_DESCR, X.PROJECT_ID, B.DESCR AS PRJ_DESCR, X.CHARTFIELD2,
            (SUBSTR(X.ACCOUNT,1,LENGTH(X.ACCOUNT)-2) || '00') AS ACCT_ROLLUP, X.ACCOUNT, X.DESCR AS ACCT_DESCR,
            0.0 AS EXP_AMT_GL, SUM(X.EXP_AMT) AS EXP_AMT_KK, 
            0.0 AS JAN_GL, SUM(X.JAN) JAN_KK, 0.0 AS FEB_GL, SUM(X.FEB) FEB_KK, 0.0 AS MAR_GL, SUM(X.MAR) MAR_KK, 0.0 AS APR_GL, SUM(X.APR) APR_KK, 0.0 AS MAY_GL, SUM(X.MAY) MAY_KK, 
            0.0 AS JUN_GL, SUM(X.JUN) JUN_KK, 0.0 AS JUL_GL, SUM(X.JUL) JUL_KK, 0.0 AS AUG_GL, SUM(X.AUG) AUG_KK, 0.0 AS SEP_GL, SUM(X.SEP) SEP_KK, 0.0 AS OCT_GL, SUM(X.OCT) OCT_KK, 
            0.0 AS NOV_GL, SUM(X.NOV) NOV_KK, 0.0 AS DEC_GL, SUM(X.DEC) DEC_KK
FROM
(SELECT A.BUSINESS_UNIT, A.OPERATING_UNIT, A.FUND_CODE, A.DEPTID, A.ACCOUNT, D.DESCR, A.PROJECT_ID, A.CHARTFIELD2,
             DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) AS EXP_AMT,
            CASE A.ACCOUNTING_PERIOD WHEN 1 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS JAN
          , CASE A.ACCOUNTING_PERIOD WHEN 2 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS FEB 
          , CASE A.ACCOUNTING_PERIOD WHEN 3 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS MAR 
          , CASE A.ACCOUNTING_PERIOD WHEN 4 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS APR 
          , CASE A.ACCOUNTING_PERIOD WHEN 5 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS MAY 
          , CASE A.ACCOUNTING_PERIOD WHEN 6 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS JUN 
          , CASE A.ACCOUNTING_PERIOD WHEN 7 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS JUL 
          , CASE A.ACCOUNTING_PERIOD WHEN 8 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS AUG 
          , CASE A.ACCOUNTING_PERIOD WHEN 9 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS SEP 
          , CASE A.ACCOUNTING_PERIOD WHEN 10 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS OCT 
          , CASE A.ACCOUNTING_PERIOD WHEN 11 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS NOV 
          , CASE A.ACCOUNTING_PERIOD WHEN 12 THEN DECODE(SUBSTR(LEDGER,1,6),'DET_UU',SUM(POSTED_BASE_AMT),0) ELSE 0 END AS DEC            
FROM PS_LEDGER_KK A, PS_GL_ACCOUNT_TBL D, PS_SET_CNTRL_REC B4
WHERE A.BUSINESS_UNIT = 'UNUNI'
     AND B4.SETCNTRLVALUE = A.BUSINESS_UNIT
     AND B4.RECNAME = 'GL_ACCOUNT_TBL'
     AND B4.SETID = D.SETID
     AND A.ACCOUNT = D.ACCOUNT
     AND D.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = D.SETID AND CJ.ACCOUNT = D.ACCOUNT AND CJ.EFFDT <= sysdate)
     --AND (A.FISCAL_YEAR IN ('2012') AND (A.ACCOUNTING_PERIOD BETWEEN 1 AND 12))
     AND A.BUDGET_PERIOD IN ('2012')
     AND A.LEDGER LIKE 'DET_UU%'
     AND A.PROJECT_ID = '00064158'
     --AND A.DEPTID = '11901'
     --AND A.POSTED_BASE_AMT <> 0
     AND D.ACCOUNT_TYPE IN ('E', 'R')     
GROUP BY A.BUSINESS_UNIT, A.OPERATING_UNIT, A.FUND_CODE, A.DEPTID, A.ACCOUNT, D.DESCR, A.PROJECT_ID, A.CHARTFIELD2, A.ACCOUNTING_PERIOD, LEDGER) X, 
               PS_PROJECT B, PS_DEPTID_BUGL_VW C
WHERE X.BUSINESS_UNIT = B.BUSINESS_UNIT (+)
     AND X.PROJECT_ID = B.PROJECT_ID (+)     
     AND C.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'DEPT_TBL')
     AND X.DEPTID = C.DEPTID
     AND C.EFFDT = (SELECT MAX(C_ED.EFFDT) FROM PS_DEPTID_BUGL_VW C_ED WHERE C.SETID = C_ED.SETID AND C.DEPTID = C_ED.DEPTID AND C_ED.EFFDT <= SYSDATE)    
GROUP BY X.BUSINESS_UNIT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, C.DESCR, X.PROJECT_ID, B.DESCR, X.CHARTFIELD2, X.ACCOUNT, X.DESCR) T
GROUP BY T.BUSINESS_UNIT, T.OPERATING_UNIT, T.FUND_CODE, T.DEPTID, T.PROJECT_ID, T.PRJ_DESCR, T.CHARTFIELD2, T.ACCT_ROLLUP, T.ACCOUNT, T.ACCT_DESCR
--HAVING (SUM(T.EXP_AMT_GL) <> 0 AND SUM(T.EXP_AMT_KK) <> 0)
ORDER BY ACCOUNT,2,3,4,5,6,7,8;

--Ledger Inquiry
--Only Account
SELECT X.FISCAL_YEAR, X.ACCOUNT_TYPE, ACCT.DESCR AS ACCT_TYPE_DESCR, X.ACCOUNT, X.DESCR AS ACCT_DESCR, X.CURRENCY_CD,
            SUM(X.PERIOD_0) AS "Bal Fwd-BASE", SUM(X.PERIOD_0_TRAN) AS "Bal Fwd-TRAN",
            SUM(X.JAN) AS "JAN-Base Curr", SUM(X.JAN_TRAN) AS "JAN-Trans Curr", 
            SUM(X.FEB) AS "FEB-Base Curr", SUM(X.FEB_TRAN) AS "FEB-Trans Curr", 
            SUM(X.MAR) AS "MAR-Base Curr", SUM(X.MAR_TRAN) AS "MAR-Trans Curr", 
            SUM(X.APR) AS "APR-Base Curr", SUM(X.APR_TRAN) AS "APR-Trans Curr", 
            SUM(X.MAY) AS "MAY-Base Curr", SUM(X.MAY_TRAN) AS "MAY-Trans Curr", 
            SUM(X.JUN) AS "JUN-Base Curr", SUM(X.JUN_TRAN) AS "JUN-Trans Curr", 
            SUM(X.JUL) AS "JUL-Base Curr", SUM(X.JUL_TRAN) AS "JUL-Trans Curr", 
            SUM(X.AUG) AS "AUG-Base Curr", SUM(X.AUG_TRAN) AS "AUG-Trans Curr", 
            SUM(X.SEP) AS "SEP-Base Curr", SUM(X.SEP_TRAN) AS "SEP-Trans Curr", 
            SUM(X.OCT) AS "OCT-Base Curr", SUM(X.OCT_TRAN) AS "OCT-Trans Curr", 
            SUM(X.NOV) AS "NOV-Base Curr", SUM(X.NOV_TRAN) AS "NOV-Trans Curr", 
            SUM(X.DEC) AS "DEC-Base Curr", SUM(X.DEC_TRAN) AS "DEC-Trans Curr", 
            SUM(X.POSTED_BASE_AMT) AS "Period Close-BASE", SUM(X.POSTED_TRAN_AMT) AS "Period Close-TRAN"
FROM (SELECT ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD, SUM(ST.POSTED_BASE_AMT) AS POSTED_BASE_AMT, SUM(ST.POSTED_TRAN_AMT) AS POSTED_TRAN_AMT
   , CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_0
   , CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS PERIOD_0_TRAN   
   , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JAN_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS FEB
   , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS FEB_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAR
   , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS MAR_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS APR
   , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS APR_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAY
   , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS MAY_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUN
   , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JUN_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUL
   , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JUL_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS AUG
   , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS AUG_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS SEP
   , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS SEP_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS OCT
   , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS OCT_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS NOV
   , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS NOV_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEC
   , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS DEC_TRAN
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ET.ACCOUNT = ST.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)
    AND ST.BUSINESS_UNIT = 'UNUNI'
    AND ST.LEDGER = 'USD'
    AND ST.FISCAL_YEAR = '2012'
    AND ((ST.ACCOUNTING_PERIOD BETWEEN 1 and 12 AND ET.ACCOUNT_TYPE IN ('E', 'R')) OR (ST.ACCOUNTING_PERIOD BETWEEN 0 and 12 AND ET.ACCOUNT_TYPE NOT IN ('E', 'R')))    
    AND ST.STATISTICS_CODE = ' '
GROUP BY ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ST.ACCOUNTING_PERIOD, ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD) X, PS_ACCT_TYPE_TBL ACCT
WHERE ACCT.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'ACCT_TYPE_TBL')
    AND ACCT.ACCOUNT_TYPE = X.ACCOUNT_TYPE
    --AND X.ACCOUNT = '11004'
GROUP BY X.FISCAL_YEAR, X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR, X.CURRENCY_CD
ORDER BY X.ACCOUNT, X.DESCR;

--Ledger Inquiry
--All CFs
SELECT X.FISCAL_YEAR, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2, 
            X.ACCOUNT_TYPE, ACCT.DESCR AS ACCT_TYPE_DESCR, X.ACCOUNT, X.DESCR AS ACCT_DESCR, X.CURRENCY_CD,
            SUM(X.PERIOD_0) AS "Bal Fwd-BASE", SUM(X.PERIOD_0_TRAN) AS "Bal Fwd-TRAN",
            SUM(X.JAN) AS "JAN-Base Curr", SUM(X.JAN_TRAN) AS "JAN-Trans Curr", 
            SUM(X.FEB) AS "FEB-Base Curr", SUM(X.FEB_TRAN) AS "FEB-Trans Curr", 
            SUM(X.MAR) AS "MAR-Base Curr", SUM(X.MAR_TRAN) AS "MAR-Trans Curr", 
            SUM(X.APR) AS "APR-Base Curr", SUM(X.APR_TRAN) AS "APR-Trans Curr", 
            SUM(X.MAY) AS "MAY-Base Curr", SUM(X.MAY_TRAN) AS "MAY-Trans Curr", 
            SUM(X.JUN) AS "JUN-Base Curr", SUM(X.JUN_TRAN) AS "JUN-Trans Curr", 
            SUM(X.JUL) AS "JUL-Base Curr", SUM(X.JUL_TRAN) AS "JUL-Trans Curr", 
            SUM(X.AUG) AS "AUG-Base Curr", SUM(X.AUG_TRAN) AS "AUG-Trans Curr", 
            SUM(X.SEP) AS "SEP-Base Curr", SUM(X.SEP_TRAN) AS "SEP-Trans Curr", 
            SUM(X.OCT) AS "OCT-Base Curr", SUM(X.OCT_TRAN) AS "OCT-Trans Curr", 
            SUM(X.NOV) AS "NOV-Base Curr", SUM(X.NOV_TRAN) AS "NOV-Trans Curr", 
            SUM(X.DEC) AS "DEC-Base Curr", SUM(X.DEC_TRAN) AS "DEC-Trans Curr", 
            SUM(X.POSTED_BASE_AMT) AS "Period Close-BASE", SUM(X.POSTED_TRAN_AMT) AS "Period Close-TRAN"
FROM (SELECT ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.PROJECT_ID, ST.CHARTFIELD2, ST.AFFILIATE, ST.AFFILIATE_INTRA1, ST.AFFILIATE_INTRA2, 
     ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD, SUM(ST.POSTED_BASE_AMT) AS POSTED_BASE_AMT, SUM(ST.POSTED_TRAN_AMT) AS POSTED_TRAN_AMT
   , CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_0
   , CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS PERIOD_0_TRAN   
   , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JAN_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS FEB
   , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS FEB_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAR
   , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS MAR_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS APR
   , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS APR_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAY
   , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS MAY_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUN
   , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JUN_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUL
   , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JUL_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS AUG
   , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS AUG_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS SEP
   , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS SEP_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS OCT
   , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS OCT_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS NOV
   , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS NOV_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEC
   , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS DEC_TRAN
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ET.ACCOUNT = ST.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)
    AND ST.BUSINESS_UNIT = 'UNUNI'
    AND ST.LEDGER = 'USD'
    AND ST.FISCAL_YEAR = '2013'
    AND ((ST.ACCOUNTING_PERIOD BETWEEN 1 and 12 AND ET.ACCOUNT_TYPE IN ('E', 'R')) OR (ST.ACCOUNTING_PERIOD BETWEEN 0 and 12 AND ET.ACCOUNT_TYPE NOT IN ('E', 'R')))    
    AND ST.STATISTICS_CODE = ' '
GROUP BY ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ST.ACCOUNTING_PERIOD, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.PROJECT_ID, ST.CHARTFIELD2, ST.AFFILIATE, ST.AFFILIATE_INTRA1, ST.AFFILIATE_INTRA2, 
               ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD) X, PS_ACCT_TYPE_TBL ACCT
WHERE ACCT.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'ACCT_TYPE_TBL')
    AND ACCT.ACCOUNT_TYPE = X.ACCOUNT_TYPE
    AND X.ACCOUNT = '21015'
    --AND X.CURRENCY_CD = 'USD'
GROUP BY X.FISCAL_YEAR, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2, 
               X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR, X.CURRENCY_CD
ORDER BY X.ACCOUNT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2, X.DESCR;

--PS Ledger Period Comparison
--Works
SELECT X.FISCAL_YEAR, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2, 
            X.ACCOUNT_TYPE, ACCT.DESCR AS ACCT_TYPE_DESCR, X.ACCOUNT, X.DESCR AS ACCT_DESCR, X.CURRENCY_CD,
            SUM(X.PERIOD_0) AS "Period Bal Fwd",
            SUM(X.JAN) JAN, SUM(X.FEB) FEB, SUM(X.MAR) MAR, SUM(X.APR) APR, SUM(X.MAY) MAY, SUM(X.JUN) JUN, SUM(X.JUL) JUL, SUM(X.AUG) AUG, 
            SUM(X.SEP) SEP, SUM(X.OCT) OCT, SUM(X.NOV) NOV, SUM(X.DEC) DEC, 
            SUM(X.POSTED_BASE_AMT) AS "Period Close"
FROM (SELECT ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.PROJECT_ID, ST.CHARTFIELD2, ST.AFFILIATE, ST.AFFILIATE_INTRA1, ST.AFFILIATE_INTRA2, 
     ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD, SUM(ST.POSTED_BASE_AMT) AS POSTED_BASE_AMT
   , CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_0
   , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS FEB
   , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAR
   , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS APR
   , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAY
   , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUN
   , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUL
   , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS AUG
   , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS SEP
   , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS OCT
   , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS NOV
   , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEC
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ET.ACCOUNT = ST.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)
    AND ST.BUSINESS_UNIT = 'UNUNI'
    AND ST.LEDGER = 'USD'
    AND ST.FISCAL_YEAR = '2012'
    AND ((ST.ACCOUNTING_PERIOD BETWEEN 1 and 12 AND ET.ACCOUNT_TYPE IN ('E', 'R')) OR (ST.ACCOUNTING_PERIOD BETWEEN 0 and 12 AND ET.ACCOUNT_TYPE NOT IN ('E', 'R')))    
    AND ST.STATISTICS_CODE = ' '
GROUP BY ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ST.ACCOUNTING_PERIOD, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.PROJECT_ID, ST.CHARTFIELD2, ST.AFFILIATE, ST.AFFILIATE_INTRA1, ST.AFFILIATE_INTRA2, 
                ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD) X, PS_ACCT_TYPE_TBL ACCT
WHERE ACCT.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'ACCT_TYPE_TBL')
    AND ACCT.ACCOUNT_TYPE = X.ACCOUNT_TYPE
    AND X.ACCOUNT = '12050'
    AND X.CURRENCY_CD = 'USD'
GROUP BY X.FISCAL_YEAR, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2,
               X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR, X.CURRENCY_CD
ORDER BY X.ACCOUNT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2, X.DESCR;

--PS Ledger Period Comparison
--Added Transaction Currency
SELECT X.FISCAL_YEAR, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2, 
            X.ACCOUNT_TYPE, ACCT.DESCR AS ACCT_TYPE_DESCR, X.ACCOUNT, X.DESCR AS ACCT_DESCR, X.CURRENCY_CD,
            SUM(X.PERIOD_0) AS "Bal Fwd-BASE", SUM(X.PERIOD_0_TRAN) AS "Bal Fwd-TRAN",
            SUM(X.JAN) AS "JAN-Base Curr", SUM(X.JAN_TRAN) AS "JAN-Trans Curr", 
            SUM(X.FEB) AS "FEB-Base Curr", SUM(X.FEB_TRAN) AS "FEB-Trans Curr", 
            SUM(X.MAR) AS "MAR-Base Curr", SUM(X.MAR_TRAN) AS "MAR-Trans Curr", 
            SUM(X.APR) AS "APR-Base Curr", SUM(X.APR_TRAN) AS "APR-Trans Curr", 
            SUM(X.MAY) AS "MAY-Base Curr", SUM(X.MAY_TRAN) AS "MAY-Trans Curr", 
            SUM(X.JUN) AS "JUN-Base Curr", SUM(X.JUN_TRAN) AS "JUN-Trans Curr", 
            SUM(X.JUL) AS "JUL-Base Curr", SUM(X.JUL_TRAN) AS "JUL-Trans Curr", 
            SUM(X.AUG) AS "AUG-Base Curr", SUM(X.AUG_TRAN) AS "AUG-Trans Curr", 
            SUM(X.SEP) AS "SEP-Base Curr", SUM(X.SEP_TRAN) AS "SEP-Trans Curr", 
            SUM(X.OCT) AS "OCT-Base Curr", SUM(X.OCT_TRAN) AS "OCT-Trans Curr", 
            SUM(X.NOV) AS "NOV-Base Curr", SUM(X.NOV_TRAN) AS "NOV-Trans Curr", 
            SUM(X.DEC) AS "DEC-Base Curr", SUM(X.DEC_TRAN) AS "DEC-Trans Curr", 
            SUM(X.POSTED_BASE_AMT) AS "Period Close-BASE", SUM(X.POSTED_TRAN_AMT) AS "Period Close-TRAN"
FROM (SELECT ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.PROJECT_ID, ST.CHARTFIELD2, ST.AFFILIATE, ST.AFFILIATE_INTRA1, ST.AFFILIATE_INTRA2, 
     ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD, SUM(ST.POSTED_BASE_AMT) AS POSTED_BASE_AMT, SUM(ST.POSTED_TRAN_AMT) AS POSTED_TRAN_AMT
   , CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS PERIOD_0
   , CASE ST.ACCOUNTING_PERIOD WHEN 0 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS PERIOD_0_TRAN   
   , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 1 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JAN_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS FEB
   , CASE ST.ACCOUNTING_PERIOD WHEN 2 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS FEB_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAR
   , CASE ST.ACCOUNTING_PERIOD WHEN 3 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS MAR_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS APR
   , CASE ST.ACCOUNTING_PERIOD WHEN 4 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS APR_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS MAY
   , CASE ST.ACCOUNTING_PERIOD WHEN 5 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS MAY_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUN
   , CASE ST.ACCOUNTING_PERIOD WHEN 6 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JUN_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS JUL
   , CASE ST.ACCOUNTING_PERIOD WHEN 7 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS JUL_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS AUG
   , CASE ST.ACCOUNTING_PERIOD WHEN 8 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS AUG_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS SEP
   , CASE ST.ACCOUNTING_PERIOD WHEN 9 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS SEP_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS OCT
   , CASE ST.ACCOUNTING_PERIOD WHEN 10 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS OCT_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS NOV
   , CASE ST.ACCOUNTING_PERIOD WHEN 11 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS NOV_TRAN
   , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_BASE_AMT) ELSE 0 END AS DEC
   , CASE ST.ACCOUNTING_PERIOD WHEN 12 THEN SUM(ST.POSTED_TRAN_AMT) ELSE 0 END AS DEC_TRAN
FROM  PS_LEDGER ST, PS_GL_ACCOUNT_TBL ET, PS_SET_CNTRL_REC B2
WHERE ET.ACCOUNT = ST.ACCOUNT
    AND B2.SETCNTRLVALUE = ST.BUSINESS_UNIT
    AND B2.RECNAME = 'GL_ACCOUNT_TBL'
    AND B2.SETID = ET.SETID
    AND ET.EFFDT = (SELECT MAX(CJ.EFFDT) FROM PS_GL_ACCOUNT_TBL CJ WHERE CJ.SETID = ET.SETID AND CJ.ACCOUNT = ET.ACCOUNT AND CJ.EFFDT <= sysdate)
    AND ST.BUSINESS_UNIT = 'UNUNI'
    AND ST.LEDGER = 'USD'
    AND ST.FISCAL_YEAR = '2013'
    AND ((ST.ACCOUNTING_PERIOD BETWEEN 1 and 12 AND ET.ACCOUNT_TYPE IN ('E', 'R')) OR (ST.ACCOUNTING_PERIOD BETWEEN 0 and 12 AND ET.ACCOUNT_TYPE NOT IN ('E', 'R')))    
    AND ST.STATISTICS_CODE = ' '
GROUP BY ST.BUSINESS_UNIT, ST.FISCAL_YEAR, ST.ACCOUNTING_PERIOD, ST.OPERATING_UNIT, ST.FUND_CODE, ST.DEPTID, ST.PROJECT_ID, ST.CHARTFIELD2, ST.AFFILIATE, ST.AFFILIATE_INTRA1, ST.AFFILIATE_INTRA2, 
                ET.ACCOUNT_TYPE, ST.ACCOUNT, ET.DESCR, ST.CURRENCY_CD) X, PS_ACCT_TYPE_TBL ACCT
WHERE ACCT.SETID = (SELECT SETID FROM PS_SET_CNTRL_REC G WHERE G.SETCNTRLVALUE = X.BUSINESS_UNIT AND G.RECNAME = 'ACCT_TYPE_TBL')
    AND ACCT.ACCOUNT_TYPE = X.ACCOUNT_TYPE
    AND X.ACCOUNT = '11004'
    --AND X.CURRENCY_CD = 'USD'
GROUP BY X.FISCAL_YEAR, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2,
               X.ACCOUNT_TYPE, ACCT.DESCR, X.ACCOUNT, X.DESCR, X.CURRENCY_CD
ORDER BY X.ACCOUNT, X.OPERATING_UNIT, X.FUND_CODE, X.DEPTID, X.PROJECT_ID, X.CHARTFIELD2, X.AFFILIATE, X.AFFILIATE_INTRA1, X.AFFILIATE_INTRA2, X.DESCR;
