clear screen
set termout off serveroutput on 

set lines 50 echo off verify off feedback off trimspool on head off autotrace off
--spool _PNGVendor.txt
select 'set termout off echo off verify off feedback off' 
from dual
;
--806 Vendors
SELECT NU.VENDOR_ID, NU.VNDR_LOC, NU.EFFDT, NU.BNK_ID_NBR, NU.BANK_ACCOUNT_NUM, NU.DFI_ID_NUM, NU.BENEF_BRANCH, NU.* 
FROM PS_VNDR_BANK_ACCT NU 
WHERE 1 = 1 
AND NU.EFFDT = (SELECT MAX(NU_ED.EFFDT) FROM PS_VNDR_BANK_ACCT NU_ED WHERE NU.SETID = NU_ED.SETID AND NU.VENDOR_ID = NU_ED.VENDOR_ID 
                                                                       AND NU.VNDR_LOC = NU_ED.VNDR_LOC AND NU_ED.EFFDT <= SYSDATE)
AND NU.SETID = 'PNG10'
--AND NU.VENDOR_ID = '0000000022'
--AND NU.DEFAULT_IND = 'Y'
AND NU.DFI_ID_QUAL = '02'
AND NU.DFI_ID_NUM IN ('WPACPGPM', 'WPACPGPMXXX', 'BPNGPGPM', 'BPNGPGPMXXX', 'BOSPPGPM', 'BOSPPGPMXXX', 'KINIPGPG', 'KINIPGPGXXX', 'ANZBPGPX', 'ANZBPGPXXXX')
AND NU.BENEF_BRANCH <> NU.DFI_ID_NUM
AND EXISTS (SELECT 'X' FROM PS_VENDOR VEN WHERE VEN.SETID = NU.SETID AND VEN.VENDOR_ID = NU.VENDOR_ID AND VEN.VENDOR_STATUS = 'A')
AND EXISTS (SELECT 'X' FROM PS_VENDOR VEN1, PS_VENDOR_LOC VL 
            WHERE VL.SETID = NU.SETID 
              AND VL.VENDOR_ID = NU.VENDOR_ID 
              AND VEN1.SETID = VL.SETID AND VEN1.VENDOR_ID = VL.VENDOR_ID AND VL.VNDR_LOC = VEN1.DEFAULT_LOC
              AND VL.VNDR_LOC = NU.VNDR_LOC)
ORDER BY 1,2
/
--Should update 806 vendors
UPDATE PS_VNDR_BANK_ACCT NU 
SET NU.BENEF_BRANCH = 
(
 SELECT OLD.DFI_ID_NUM FROM PS_VNDR_BANK_ACCT OLD 
 WHERE OLD.SETID = NU.SETID AND OLD.VENDOR_ID = NU.VENDOR_ID AND OLD.VNDR_LOC = NU.VNDR_LOC AND OLD.EFFDT = NU.EFFDT 
   AND OLD.BANK_ACCT_SEQ_NBR = NU.BANK_ACCT_SEQ_NBR
)
WHERE 1 = 1 
AND NU.EFFDT = (SELECT MAX(NU_ED.EFFDT) FROM PS_VNDR_BANK_ACCT NU_ED WHERE NU.SETID = NU_ED.SETID AND NU.VENDOR_ID = NU_ED.VENDOR_ID 
                                                                       AND NU.VNDR_LOC = NU_ED.VNDR_LOC AND NU_ED.EFFDT <= SYSDATE)
AND NU.SETID = 'PNG10'
--AND NU.VENDOR_ID = '0000000022'
AND NU.DEFAULT_IND = 'Y'
AND NU.DFI_ID_QUAL = '02'
AND NU.DFI_ID_NUM IN ('WPACPGPM', 'WPACPGPMXXX', 'BPNGPGPM', 'BPNGPGPMXXX', 'BOSPPGPM', 'BOSPPGPMXXX', 'KINIPGPG', 'KINIPGPGXXX', 'ANZBPGPX', 'ANZBPGPXXXX')
AND EXISTS (SELECT 'X' FROM PS_VENDOR VEN WHERE VEN.SETID = NU.SETID AND VEN.VENDOR_ID = NU.VENDOR_ID AND VEN.VENDOR_STATUS = 'A')
AND EXISTS (SELECT 'X' FROM PS_VENDOR VEN1, PS_VENDOR_LOC VL 
            WHERE VL.SETID = NU.SETID 
              AND VL.VENDOR_ID = NU.VENDOR_ID 
              AND VEN1.SETID = VL.SETID AND VEN1.VENDOR_ID = VL.VENDOR_ID AND VL.VNDR_LOC = VEN1.DEFAULT_LOC
              AND VL.VNDR_LOC = NU.VNDR_LOC)
/
SELECT NU.VENDOR_ID, NU.VNDR_LOC, NU.EFFDT, NU.BNK_ID_NBR, NU.BANK_ACCOUNT_NUM, NU.DFI_ID_NUM, NU.BENEF_BRANCH, NU.* 
FROM PS_VNDR_BANK_ACCT NU 
WHERE 1 = 1 
AND NU.EFFDT = (SELECT MAX(NU_ED.EFFDT) FROM PS_VNDR_BANK_ACCT NU_ED WHERE NU.SETID = NU_ED.SETID AND NU.VENDOR_ID = NU_ED.VENDOR_ID 
                                                                       AND NU.VNDR_LOC = NU_ED.VNDR_LOC AND NU_ED.EFFDT <= SYSDATE)
AND NU.SETID = 'PNG10'
--AND NU.VENDOR_ID = '0000000022'
--AND NU.DEFAULT_IND = 'Y'
AND NU.DFI_ID_QUAL = '02'
AND NU.DFI_ID_NUM IN ('WPACPGPM', 'WPACPGPMXXX', 'BPNGPGPM', 'BPNGPGPMXXX', 'BOSPPGPM', 'BOSPPGPMXXX', 'KINIPGPG', 'KINIPGPGXXX', 'ANZBPGPX', 'ANZBPGPXXXX')
AND NU.BENEF_BRANCH <> NU.DFI_ID_NUM
AND EXISTS (SELECT 'X' FROM PS_VENDOR VEN WHERE VEN.SETID = NU.SETID AND VEN.VENDOR_ID = NU.VENDOR_ID AND VEN.VENDOR_STATUS = 'A')
AND EXISTS (SELECT 'X' FROM PS_VENDOR VEN1, PS_VENDOR_LOC VL 
            WHERE VL.SETID = NU.SETID 
              AND VL.VENDOR_ID = NU.VENDOR_ID 
              AND VEN1.SETID = VL.SETID AND VEN1.VENDOR_ID = VL.VENDOR_ID AND VL.VNDR_LOC = VEN1.DEFAULT_LOC
              AND VL.VNDR_LOC = NU.VNDR_LOC)
ORDER BY 1,2
;
--Should select 0 Vendors
select 'spool off' 
from dual
;
select 'set termout on' 
from dual
;
--spool off
set lines 200
set termout on serveroutput on echo on verify on feedback on trimspool on head on
