--XMLCAST
SELECT :1, 
       RTRIM(XMLCAST(XMLAGG(XMLELEMENT(E, :2 || '.' || column_name, ', ' ||chr(13)).Extract('//text()')ORDER BY column_id) AS CLOB), ',') AS "A0",
       RTRIM(XMLCAST(XMLAGG(XMLELEMENT(E, 'COALESCE'||'('||:2 || '.' || column_name ||', '''') <> '' '' OR ', '' ||chr(13)).Extract('//text()')ORDER BY column_id) 
       AS CLOB), ',') AS "A1"
FROM all_tab_columns
WHERE table_name = :1
GROUP BY :1
ORDER BY :1;

--using XMLCAST
SELECT PD.PMT_ID, PD.PMT_SOURCE, PD.BUSINESS_UNIT, PD.SRC_REF_ID, PD.AMOUNT, PD.AMOUNT_CURRENCY_CD, PD.PYMNT_DT, PD.VALUE_DT, PD.ESTIMATED_DUE_DATE, 
       PD.PMT_STATUS || ' - ' || X1.XLATLONGNAME AS PMT_STS_DESCR, PD.PMT_LAST_STATUS || ' - ' || X2.XLATLONGNAME AS PMT_LAST_STS_DESCR, 
       PD.PMT_TYPE || ' - ' || X9.XLATLONGNAME AS PMT_TYPE_DESCR, PD.BANK_SETID, PD.BANK_CD, PD.BANK_ACCT_KEY, PD.ACCT_BUS_UNIT_GL, PD.FROM_BNK_ID_NBR, 
       PD.FROM_BNK_ACCT_NUM, PD.FROM_DFI_ID_NUM, PD.FROM_DFI_ID_QUAL, PD.PYMNT_METHOD, PD.FORMAT_ID, PD.PRENOTE_FLAG || ' - ' || X4.XLATLONGNAME AS PRE_NOTE_DESCR,
       PD.PAY_IMMEDIATELY, PD.COUNTRY, PD.BANK_ID_QUAL, PD.BNK_ID_NBR, PD.BRANCH_ID, PD.BANK_ACCT_TYPE || ' - ' || X5.XLATLONGNAME AS BANK_ACCT_TYPE_DECSR, 
       PD.BANK_ACCOUNT_NUM, PD.CHECK_DIGIT, PD.DFI_ID_QUAL || ' - ' || X3.XLATLONGNAME AS DFI_ID_QUAL_DESCR, PD.DFI_ID_NUM, 
       PD.BANK_NAME, PD.BANK_NAME_AC, PD.BRANCH_DESCR, PD.BRANCH_NAME_AC, PD.IBAN_CHECK_DIGIT, PD.IBAN_ID, PD.PARTY_ID_TYPE, PD.PARTY_SETID, PD.PARTY_ID, PD.NAME1, 
       PD.NAME1_AC, PD.NAME2, PD.STD_ID_NUM, PD.STD_ID_NUM_QUAL, PD.EFT_PYMNT_FMT_CD || ' - ' || X6.XLATLONGNAME AS EFT_PMT_FMT_CD_DESCR, PD.EFT_RTNG_FLG, PD.EFT_RTNG_STATUS, 
       PD.EFT_TRANS_HANDLING || ' - ' || X7.XLATLONGNAME AS EFT_TRANS_HANDLING_DESCR, PD.EFT_DOM_COSTS_CD || ' - ' || X8.XLATLONGNAME AS EFT_DOMESTIC_COSTS, 
       PD.EFT_CORR_COSTS_CD || ' - ' || X13.XLATLONGNAME AS EFT_CORRESPONDENTS_COSTS, PD.EFT_CROSSED_CHECK, PD.EFT_CHECK_FWRD_CD, PD.EFT_CHECK_DRAW_CD, PD.EFT_PAY_INST_CD1, 
       PD.EFT_PAY_INST_CD2, PD.EFT_PAY_INST_CD3, PD.EFT_PAY_INST_CD4, PD.EFT_PAY_INST_REF1, PD.EFT_PAY_INST_REF2, PD.ADDENDA_VALUE, PD.REPETITVE_TRNFR_CD, PD.DRAWDOWN_FLG, 
       PD.CREATED_BY_USER, PD.PMT_FIELD1, PD.PMT_FIELD2, PD.PMT_FIELD3, PD.PAY_CYCLE, PD.PAY_CYCLE_SEQ_NUM, PD.BATCH_NAME, PD.PMT_FILE_ID, PD.BANK_REF_ID, PD.EVENT_TRACKING_ID, 
       PD.PMT_MSG_ID, PD.PMTRUNINSTANCE, PD.IN_PROCESS_FLG, PD.PAYEE_VIOLATION, PI.PMT_ID AS INV_PMT_ID, PI.INVOICE_ID, PI.BUSINESS_UNIT AS INV_BU, PI.INVOICE_DT, 
       PI.GROSS_AMT, PI.TXN_CURRENCY_CD, PI.PAID_AMT, PI.PAID_AMT_CURRENCY, PI.DISCOUNT_TAKEN, PI.DESCR254_MIXED, PI.PAY_DOC_ID, PI.PAY_DOC_SEQ, PI.AR_NUM, PI.EMPLID, 
       PF.PMT_FILE_ID, PF.PMTRUNINSTANCE, PF.FILE_STATUS || ' - ' || X12.XLATLONGNAME AS FILE_STS_DESCR, PF.BANK_SETID, PF.BANK_CD, PF.FORMAT_ID, PF.TOTAL_PMT_COUNT, 
       PF.OUTPUT_TYPE, PF.PMT_FILE_PATH, PF.FILENAME, PF.CREATE_DTTM, PF.CREATED_BY_USER, PF.PMT_CRYPTO_ID, PF.PUBNODE, PF.MSGNAME, PF.APMSGVER, PF.CHNLNAME, PF.PUBID, 
       PF.IBPUBTRANSACTID, PF.EVENT_TRACKING_ID, PF.EXT_FILE_ID, PF.PMT_FIELD1, XREF.VOUCHER_ID, XREF.PYMNT_ID, 
       XREF.PYMNT_SELCT_STATUS || ' - ' || X10.XLATLONGNAME AS PYMNT_SELECT_STS, XREF.PAID_AMT, XREF.PYMNT_GROSS_AMT, XREF.PAID_AMT_GROSS, XREF.PYMNT_MESSAGE, 
       XREF.PYMNT_HOLD, XREF.PYMNT_HOLD_REASON, XREF.POST_STATUS_AP, XREF.PAID_RATE_DIV, XREF.PAID_RATE_MULT,
       PT.PYMNT_ID_REF, PT.PYMNT_STATUS || ' - ' || X11.XLATLONGNAME AS PYMNT_STS_DESCR, 
       PT.COUNTRY, PT.ADDRESS1, PT.ADDRESS2, PT.ADDRESS3, PT.ADDRESS4, PT.CITY, PT.STATE, PT.POSTAL, PT.OPRID, PT.PYMNT_RECONCILE_DT, PT.RECONCILE_OPRID, PT.RECON_STATUS, 
       PT.MICR_LINE, PA.PAY_DOC_SEQ, PA.SOURCE_TXN, PA.BUSINESS_UNIT, PA.PAY_DOC_ID, PA.CURRENCY_PYMNT, PA.VENDOR_ID, PA.EMPLID, PA.INVOICE_ID, 
       PA.PAY_DOC_DT, PA.PAID_AMT, PA.PAID_AMT_GROSS, PT.EFT_LAYOUT_CD, PT.PMT_PYMNT_STATUS,
       PR.KEY_CHAR_40_01, PR.KEY_CHAR_40_02, PR.KEY_CHAR_40_03, PR.KEY_CHAR_40_04, PR.KEY_CHAR_40_05, PR.KEY_CHAR_40_06, PR.KEY_CHAR_40_07, PR.KEY_CHAR_40_08, 
       PR.KEY_CHAR_40_09, PR.KEY_CHAR_40_10, PR.KEY_CHAR_40_11, PR.KEY_CHAR_40_12, PR.KEY_CHAR_40_13, PR.KEY_CHAR_40_14, PR.KEY_CHAR_40_15, PR.KEY_DATE_01, 
       PR.KEY_DATE_02, PR.KEY_DATE_03, PR.KEY_DATE_04, PR.KEY_DATE_05, PR.KEY_DTTM_01, PR.KEY_DTTM_02, PR.KEY_DTTM_03, PR.KEY_DTTM_04, PR.KEY_DTTM_05, 
       PR.KEY_SIGN_01, PR.KEY_SIGN_02, PR.KEY_SIGN_03, PR.KEY_SIGN_04, PR.KEY_SIGN_05, CTR.ERROR_MESSAGE,
       PAD.PMT_ADDRESS_TYPE || ' - ' || X17.XLATLONGNAME AS "PMT Address Type", PAD.COUNTRY, PAD.ADDRESS1, PAD.ADDRESS2, PAD.ADDRESS3, PAD.ADDRESS4,
       PAD.CITY, PAD.STATE, PAD.POSTAL,
       CFTR.TR_SOURCE_CD, CFTR.SOURCE_BUS_UNIT, CFTR.TR_SOURCE_ID, CFTR.BUSINESS_DATE, CFTR.PMT_ID, CFTR.PMT_STATUS AS "PMT STS", CFTR.CASH_FLOW_LINE, 
       CFTR.CASH_FLOW_LEG, CFTR.PAY_DOC_SEQ, CFTR.CASH_TYPE AS "Cash Type", 
       CFTR.AMOUNT AS "CF Amount", CFTR.CURRENCY_CD AS "CF Curr", CFTR.BANK_SETID AS "CF Bank SetID", CFTR.BANK_CD_CUST AS "CF Bank Cust", CFTR.BANK_CD "CF Bank CD", 
       CFTR.BANK_ACCT_KEY AS "CF Bank Acct Key", CFTR.ACCT_BUS_UNIT_GL, CFTR.BNK_ID_NBR, 
       CFTR.BANK_ACCOUNT_NUM AS "CF Bank Acct#", CFTR.TRANSACTION_LINE, CFTR.RECONCILE_DT, CFTR.RECONCILE_OPRID, CFTR.RECON_TYPE, CFTR.RECON_STATUS, CFTR.RECON_CYCLE_NBR, 
       CFTR.STTLMNT_DT_ACTUAL, CFTR.NET_STATUS, CFTR.APPROVAL_OPRID, CFTR.CPTY_REFERENCE, CFTR.NET_REF_ID, CFTR.CF_SOURCE_REF_ID, CFTR.CP_NETTOR, 
       CFTR.PYMNT_METHOD AS "CF Pymnt Mthd", CFTR.SETTLEMENT_ID AS "CF Settlement ID", CFTR.PYMNT_SELCT_STATUS, CFTR.APPROVAL_FLG_TR, CFTR.APPROV_SUBMITTED, CFTR.PYMNT_ID, 
       CFTR.CURRENCY_CD_BASE, CFTR.BASE_AMT, CFTR.BASE_CURRENCY_BNK, 
       CFTR.BNK_RATE_DIV, CFTR.BNK_RATE_MULT, CFTR.CUR_RT_TYPE_BNK, CFTR.CURRENCY_PYMNT, CFTR.PAID_AMT, CFTR.PAID_AMT_BNK_BSE, CFTR.PAID_AMT_BSE, CFTR.PYMNT_RATE_DIV, 
       CFTR.PYMNT_RATE_MULT, CFTR.PAY_CYCLE, CFTR.PAY_CYCLE_SEQ_NUM, CFTR.BANK_STMT_DT, CFTR.RECORD_SEQ_NUMBER, CFTR.SELECTED_OPRID, CFTR.SELECTED_DTTM, CFTR.APPROVAL_DTTM, 
       CFTR.RECON_RUN_ID, CFTR.BANK_ACCT_RVL_AMT, CFTR.STL_THROUGH, CFTR.EVENT_TRACKING_ID, CFTR.REPETITVE_TRNFR_CD AS "CF Repetitive TRF CD", 
       CFTR.DRAWDOWN_FLG AS "CF Drawdown Flag", CFTR.FORMAT_ID AS "CF Foormat ID", CFTR.TRP_BUSINESS_UNIT, CFTR.POOL_ID,
       BAX.BUSINESS_UNIT AS "BAX_BUS_UNIT", BAX.BAX_TRANSFER_ID, BAX.DESCR AS "BAX DESCR", BAX.TRANSFER_TYPE, BAX.SETTLEMENT_ID, BAX.OPRID, BAX.DTTM_ENTERED,
       BAX.PYMNT_METHOD, BAX.FORMAT_ID,
       (SELECT RTRIM(XMLCAST(XMLAGG(XMLELEMENT(E, PACK.PMT_ACK_FILE_ID || ' - '|| PACK.HEADER_ID || ' - '|| PACK.FILE_ACK_STATUS || ' - ' || X14.XLATLONGNAME || ' - '|| 
                                   PHDR.ACK_FILE_STATUS || ' - ' || X15.XLATLONGNAME || ' - '|| PHDR.BANK_FILE_ID || ' - '|| PHDR.BANK_SEND_DTTM || ' - '||
                                   PHDR.FORMAT_ID || ' - '|| PHDR.FILENAME || ' - '|| PHDR.CREATE_DTTM || ' - '|| PHDR.EVENT_TRACKING_ID || ' - '|| 
                                   PHDR.BANK_SETID || ' - '|| PHDR.BANK_CD || ' - '|| PMACK.PMT_ACK_FILE_ID || ' - '|| PMACK.PYMNT_REF_ID || ' - '|| 
                                   PMACK.PMT_STATUS || ' - ' || X16.XLATLONGNAME || ' - '|| PERR.PMT_ACK_FILE_ID  || ' - '|| PERR.PYMNT_REF_ID || ' - '|| 
                                   PERR.SEQ_NUM || ' - '|| PERR.ERROR_CODE || ' - '|| PERR.ERROR_MESSAGE, ' ; ' || chr(13))
                                   .EXTRACT('//text()')ORDER BY PACK.HEADER_ID, PHDR.BANK_SEND_DTTM desc)AS CLOB),',') AS "A3"
        FROM ((((((PS_PMT_FILE_ACK PACK LEFT OUTER JOIN PS_PMT_ACK_HEADER PHDR ON PHDR.PMT_ACK_FILE_ID = PACK.PMT_ACK_FILE_ID)      
        LEFT OUTER JOIN PS_PMT_ACK PMACK ON PMACK.PMT_ACK_FILE_ID = PACK.PMT_ACK_FILE_ID)
        LEFT OUTER JOIN PS_PMT_ACK_ERR PERR ON PERR.PMT_ACK_FILE_ID = PACK.PMT_ACK_FILE_ID AND PMACK.PYMNT_REF_ID = PERR.PYMNT_REF_ID)
        LEFT OUTER JOIN PSXLATITEM X14 ON X14.FIELDNAME = 'FILE_ACK_STATUS' AND X14.FIELDVALUE = PACK.FILE_ACK_STATUS AND X14.EFF_STATUS = 'A')
        LEFT OUTER JOIN PSXLATITEM X15 ON X15.FIELDNAME = 'ACK_FILE_STATUS' AND X15.FIELDVALUE = PHDR.ACK_FILE_STATUS AND X15.EFF_STATUS = 'A')
        LEFT OUTER JOIN PSXLATITEM X16 ON X16.FIELDNAME = 'PMT_STATUS' AND X16.FIELDVALUE = PMACK.PMT_STATUS AND X16.EFF_STATUS = 'A')
        WHERE PACK.HEADER_ID = PD.PMT_FILE_ID AND (PMACK.PYMNT_REF_ID = PD.SRC_REF_ID OR PERR.PYMNT_REF_ID = PD.SRC_REF_ID)) AS "Acknowledgement - PMT_FILE_ACK",
        (SELECT RTRIM(XMLCAST(XMLAGG(XMLELEMENT(E, VC.BUSINESS_UNIT  || ' - '|| VC.VOUCHER_ID || ' - '|| VL.VOUCHER_LINE_NUM || ' - '|| DL.DISTRIB_LINE_NUM || ' - '|| 
                                           VC.ACCOUNTING_DT || ' - '|| VC.TXN_CURRENCY_CD || ' - '|| DL.FOREIGN_AMOUNT || ' - '|| DL.ACCOUNT || ' - '|| 
                                           DL.OPERATING_UNIT || ' - '|| DL.FUND_CODE || ' - '|| DL.DEPTID || ' - '|| DL.BUSINESS_UNIT_PC || ' - '|| 
                                           DL.PROJECT_ID || ' - '|| DL.ACTIVITY_ID || ' - '|| DL.CHARTFIELD1 || ' - '|| DL.CHARTFIELD2 || ' - '|| DL.MONETARY_AMOUNT 
                                           || ' - '|| VC.ENTRY_STATUS || ' - '|| VC.POST_STATUS_AP || ' - '|| VC.BUDGET_HDR_STATUS || ' - '|| VC.VOUCHER_STYLE 
                                           || ' - '|| VC.INVOICE_ID || ' - '|| VC.INVOICE_DT || ' - '|| DL.DESCR || ' - '|| DL.BUDGET_DT || ' - ' || 
                                           VC.VNDR_LOC || ' - '|| ADDRESS_SEQ_NUM || ' - '|| VC.OPRID_LAST_UPDT, ' ; ' || chr(13))
                                           .EXTRACT('//text()')ORDER BY VC.BUSINESS_UNIT, VC.VOUCHER_ID, VL.VOUCHER_LINE_NUM, DL.DISTRIB_LINE_NUM)
                                           AS CLOB), ',') AS "A4"
       FROM PS_VOUCHER VC, PS_DISTRIB_LINE DL, PS_VOUCHER_LINE VL WHERE VC.BUSINESS_UNIT = VL.BUSINESS_UNIT AND VC.VOUCHER_ID = VL.VOUCHER_ID 
       AND VL.BUSINESS_UNIT = DL.BUSINESS_UNIT AND VL.VOUCHER_ID = DL.VOUCHER_ID 
       AND VL.VOUCHER_LINE_NUM = DL.VOUCHER_LINE_NUM AND VC.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND VC.VOUCHER_ID = XREF.VOUCHER_ID) AS "Voucher Information",
       (SELECT RTRIM(XMLCAST(XMLAGG(XMLELEMENT(E, VX.BUSINESS_UNIT || ' - ' || VX.VOUCHER_ID || ' - ' || VX.PYMNT_CNT || ' - ' || VX.PYMNT_ID || ' - ' || VX.PAID_AMT_GROSS
                                          || ' - ' || CURRENCY_PYMNT || ' - ' || VX.PYMNT_SELCT_STATUS || ' - ' || VX.PYMNT_MESSAGE || ' - ' || VX.PYMNT_HOLD 
                                          || ' - '|| VX.PYMNT_HOLD_REASON || ' - ' || VX.PAY_CYCLE || ' - ' || VX.PAY_CYCLE_SEQ_NUM || ' - ' || VX.POST_STATUS_AP 
                                          || ' - ' || VX.GROSS_AMT_BSE, ' ; ' || chr(13)).EXTRACT('//text()') ORDER BY VX.BUSINESS_UNIT, VX.VOUCHER_ID, VX.PYMNT_CNT)
                                          AS CLOB), ',') AS "A5"
       FROM PS_PYMNT_VCHR_XREF VX WHERE VX.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND VX.VOUCHER_ID = XREF.VOUCHER_ID) AS "XREF Information",
       (SELECT RTRIM(XMLCAST(XMLAGG(XMLELEMENT(E, PIT.PMT_ID || ' - ' || PIT.INTRMED_SEQ_NO || ' - ' || PIT.STL_ROUTING_METHOD || ' - ' || PIT.INTRMED_DFI_ID || ' - ' || 
                                          PIT.INTRMED_PYMNT_MSG || ' - ' || PIT.SETID || ' - ' || PIT.BANK_CD || ' - ' || PIT.BANK_ACCT_KEY
                                          || ' - ' || PIT.BANK_ACCOUNT_NUM, ' ; ' || chr(13)).Extract('//text()')
                                          ORDER BY PIT.PMT_ID, PIT.INTRMED_SEQ_NO)AS CLOB), ',') AS "A6"
       FROM PS_PMT_INTRM_TBL PIT WHERE PIT.PMT_ID = PD.PMT_ID) AS "Intermed Info",
       (SELECT RTRIM(XMLCAST(XMLAGG(XMLELEMENT(E, tel1.event_tracking_id || ' - ' || tel1.event_code || ' - ' || tel1.event_date || ' - ' || tel1.event_severity || ' - ' || 
                                          tel1.oprid || ' - ' || mcd1.message_text || ' - ' || tect1.descr150_mixed || ' - ' || tel1.event_msg_bind1 || ' - ' || 
                                          tel1.event_msg_bind2 || ' - ' || tel1.event_msg_bind3, ' ; ' ||chr(13)).Extract('//text()') 
                                          ORDER BY tel1.event_tracking_id, tel1.event_date)AS CLOB), ',') AS "A7"
       FROM ((ps_tr_event_log tel1 LEFT OUTER JOIN psmsgcatdefn mcd1 ON tel1.message_set_nbr = mcd1.message_set_nbr and tel1.message_nbr = mcd1.message_nbr)
             LEFT OUTER JOIN ps_tr_event_cd_tbl tect1 ON tel1.event_code = tect1.event_code)
       WHERE tel1.event_tracking_id = PD.EVENT_TRACKING_ID) AS "Payment Detail Event Logging",
       (SELECT RTRIM(XMLCAST(XMLAGG(XMLELEMENT(E, tel2.event_tracking_id || ' - ' || tel2.event_code || ' - ' || tel2.event_date || ' - ' || tel2.event_severity || ' - ' || 
                                          tel2.oprid || ' - ' || mcd2.message_text || ' - ' || tect2.descr150_mixed || ' - ' || tel2.event_msg_bind1 || ' - ' || 
                                          tel2.event_msg_bind2 || ' - ' || tel2.event_msg_bind3, ' ; ' ||chr(13)).Extract('//text()') 
                                          ORDER BY tel2.event_tracking_id, tel2.event_date)AS CLOB), ',') AS "A8"
       FROM ((ps_tr_event_log tel2 LEFT OUTER JOIN psmsgcatdefn mcd2 ON tel2.message_set_nbr = mcd2.message_set_nbr and tel2.message_nbr = mcd2.message_nbr)
             LEFT OUTER JOIN ps_tr_event_cd_tbl tect2 ON tel2.event_code = tect2.event_code)
       WHERE tel2.event_tracking_id = PF.EVENT_TRACKING_ID) AS "Payment File Event Logging",
       (SELECT RTRIM(XMLCAST(XMLAGG(XMLELEMENT(E, tel.event_tracking_id || ' - ' || tel.event_code || ' - ' || tel.event_date || ' - ' || tel.event_severity || ' - ' || 
                                          tel.oprid || ' - ' || mcd.message_text || ' - ' || tect.descr150_mixed || ' - ' || tel.event_msg_bind1 || ' - ' || 
                                          tel.event_msg_bind2 || ' - ' || tel.event_msg_bind3, ' ; ' ||chr(13)).Extract('//text()') 
                                          ORDER BY tel.event_tracking_id, tel.event_date)AS CLOB), ',') AS "A9"
       FROM ((ps_tr_event_log tel LEFT OUTER JOIN psmsgcatdefn mcd ON tel.message_set_nbr = mcd.message_set_nbr and tel.message_nbr = mcd.message_nbr)
             LEFT OUTER JOIN ps_tr_event_cd_tbl tect ON tel.event_code = tect.event_code)
       WHERE tel.event_tracking_id = CFTR.EVENT_TRACKING_ID) AS "Cash Flow Event Logging"
FROM ((((((((((((((((((((((((PS_PMT_DETAIL_TBL PD LEFT OUTER JOIN PS_PMT_INVOICE_TBL PI ON PD.PMT_ID = PI.PMT_ID)
      LEFT OUTER JOIN PS_PMT_FILE_DEFN PF ON PD.PMT_FILE_ID = PF.PMT_FILE_ID)
      LEFT OUTER JOIN PS_PMT_REF_TBL PR ON PD.PMT_ID = PR.PMT_ID)
      LEFT OUTER JOIN PS_PMT_ADDRESS_TBL PAD ON PD.PMT_ID = PAD.PMT_ID)
      LEFT OUTER JOIN PSXLATITEM X1 ON X1.FIELDNAME = 'PMT_STATUS' AND X1.FIELDVALUE = PD.PMT_STATUS AND X1.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X2 ON X2.FIELDNAME = 'PMT_LAST_STATUS' AND X2.FIELDVALUE = PD.PMT_LAST_STATUS AND X2.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X3 ON X3.FIELDNAME = 'DFI_ID_QUAL' AND X3.FIELDVALUE = PD.DFI_ID_QUAL AND X3.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X4 ON X4.FIELDNAME = 'PRENOTE_FLAG' AND X4.FIELDVALUE = PD.PRENOTE_FLAG AND X4.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X5 ON X5.FIELDNAME = 'BANK_ACCT_TYPE' AND X5.FIELDVALUE = PD.BANK_ACCT_TYPE AND X5.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X6 ON X6.FIELDNAME = 'EFT_PYMNT_FMT_CD' AND X6.FIELDVALUE = PD.EFT_PYMNT_FMT_CD AND X6.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X7 ON X7.FIELDNAME = 'EFT_TRANS_HANDLING' AND X7.FIELDVALUE = PD.EFT_TRANS_HANDLING AND X7.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X8 ON X8.FIELDNAME = 'EFT_DOM_COSTS_CD' AND X8.FIELDVALUE = PD.EFT_DOM_COSTS_CD AND X8.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X13 ON X13.FIELDNAME = 'EFT_CORR_COSTS_CD' AND X13.FIELDVALUE = PD.EFT_CORR_COSTS_CD AND X13.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X17 ON X17.FIELDNAME = 'PMT_ADDRESS_TYPE' AND X17.FIELDVALUE = PAD.PMT_ADDRESS_TYPE AND X17.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X9 ON X9.FIELDNAME = 'PMT_TYPE' AND X9.FIELDVALUE = PD.PMT_TYPE AND X9.EFF_STATUS = 'A')
      --LEFT OUTER JOIN PS_PYMNT_VCHR_XREF XREF ON PD.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND PI.PAY_DOC_ID = XREF.VOUCHER_ID)
      LEFT OUTER JOIN PS_PAYMENT_TBL PT ON PD.BANK_SETID = PT.BANK_SETID AND PD.BANK_CD = PT.BANK_CD AND PD.BANK_ACCT_KEY = PT.BANK_ACCT_KEY AND PD.PMT_ID = PT.PMT_ID) --AND XREF.PYMNT_ID = PT.PYMNT_ID)
      LEFT OUTER JOIN PS_PYMNT_VCHR_XREF XREF ON PI.BUSINESS_UNIT = XREF.BUSINESS_UNIT AND PI.PAY_DOC_ID = XREF.VOUCHER_ID AND XREF.PYMNT_ID = PT.PYMNT_ID)
      LEFT OUTER JOIN PSXLATITEM X10 ON X10.FIELDNAME = 'PYMNT_SELCT_STATUS' AND X10.FIELDVALUE = XREF.PYMNT_SELCT_STATUS AND X10.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X11 ON X11.FIELDNAME = 'PYMNT_STATUS' AND X11.FIELDVALUE = PT.PYMNT_STATUS AND X11.EFF_STATUS = 'A')
      LEFT OUTER JOIN PSXLATITEM X12 ON X12.FIELDNAME = 'FILE_STATUS' AND X12.FIELDVALUE = PF.FILE_STATUS AND X12.EFF_STATUS = 'A')
      LEFT OUTER JOIN PS_PYMNT_ADVICE PA ON PT.PAY_CYCLE = PA.PAY_CYCLE AND PT.PAY_CYCLE_SEQ_NUM = PA.PAY_CYCLE_SEQ_NUM AND PT.BANK_SETID = PA.BANK_SETID 
                                        AND PT.BANK_CD = PA.BANK_CD AND PT.BANK_ACCT_KEY = PA.BANK_ACCT_KEY AND PT.PYMNT_METHOD = PA.PYMNT_METHOD 
                                        AND PA.PAY_DOC_SEQ = PI.PAY_DOC_SEQ AND PA.PAY_DOC_ID = PI.PAY_DOC_ID AND PA.REMIT_LINE_TYPE = 'A' AND PT.PYMNT_ID_REF = PA.PYMNT_ID_REF)
      LEFT OUTER JOIN UNDPFS.PS_UN_TR_FG_IN_ERR CTR ON PD.PMT_ID = CTR.PMT_ID AND PD.SRC_REF_ID = CTR.SRC_REF_ID)
      LEFT OUTER JOIN PS_CASH_FLOW_TR CFTR ON CFTR.PMT_ID = PD.PMT_ID AND PD.BUSINESS_UNIT = CFTR.SOURCE_BUS_UNIT AND PD.SRC_REF_ID = CFTR.TR_SOURCE_ID AND CFTR.AMOUNT < 0)
      LEFT OUTER JOIN PS_BAX_HEADER_TR BAX ON PD.BUSINESS_UNIT = BAX.BUSINESS_UNIT AND PD.SRC_REF_ID = BAX.BAX_TRANSFER_ID)
WHERE PD.BANK_SETID = 'SHARE' 
--  AND PD.BANK_CD LIKE '6%'
--AND PD.PMT_FILE_ID = '00062460'
AND PD.PYMNT_DT BETWEEN TO_DATE('2021-11-19','YYYY-MM-DD') AND TO_DATE('2022-12-31','YYYY-MM-DD')
--AND PD.BANK_CD = '00055'
--AND UPPER(PD.NAME1) LIKE '%ATMAN%'
--AND PD.PMT_STATUS IN ('L', 'H', 'E', 'SC')
--AND PD.COUNTRY = 'PAK'
--AND PD.PMT_TYPE IN ('BAX')
--AND PD.SRC_REF_ID IN ('BT00082334', 'DL00107205', 'BT00085232', 'DL00105210')
--  AND PD.SRC_REF_ID = '0000159044'
--AND PD.PMT_ID = 'EX0000062518'
--  AND PF.FILENAME = 'UNDP_CIT_002871001_pain002_20211028_060019.xml'
--  AND PD.PMT_FILE_ID = '00073540'
--  AND (PD.PARTY_ID = '71001933' OR PA.EMPLID = '71001933')
  AND PAD.PMT_ADDRESS_TYPE = 'DEST'
  AND PD.PMT_STATUS = 'E'
ORDER BY PD.PYMNT_DT DESC, PD.VALUE_DT DESC, PD.PMT_SOURCE, PD.PMT_ID DESC;
